// ---------------------------------------------------------------------------
// Computing pool: how fast programs and networks run (input size, caches,
// threads, bandwidth, compression), and how people use computers (menus,
// buttons, pointing, typing, error messages, learning to program).
// The main pool for computer science; a secondary one for engineering.
// Studies (designs, confounds, cross-sectional and longitudinal) are done on
// human participants. System-performance items are untagged so engineering
// gets them too; items about people are tagged for computer science.
// See pools/README.md for the rules.
// ---------------------------------------------------------------------------

const COMP_CS = ['computer-science'];

const COMP_CONT = 'It can take any value on a scale, including every value in between — ';
const COMP_DISC = 'It only comes in separate values, with nothing in between — ';

const COMP_NOM = 'Categorical: distinct outcomes with no order. ';
const COMP_ORD = 'Ordinal: the outcomes are ranked, but the difference between steps is arbitrary. ';
const COMP_INT = 'Interval: ranked, with a constant difference between steps, but no natural zero — so values aren\'t "twice as much". ';
const COMP_RAT = 'Ratio: ranked, constant steps AND a natural zero, so "twice as much" makes sense. ';

const COMP_TIME = ['time', 'over time', 'week', 'weeks', 'month', 'months', 'year', 'years', 'day', 'days', 'when it was measured', 'time point', 'session', 'before and after'];

const COMP_P = { name: 'the participants', aliases: ['participants', 'people', 'subjects', 'person', 'users'] };
const COMP_MENU = { name: 'menu length (short or long)', aliases: ['menu length', 'menu', 'short or long', 'short menu', 'long menu', 'number of options', 'number of menu items', 'menu size'] };
const COMP_FIND = { name: 'time to find the option', aliases: ['time to find', 'finding time', 'search time', 'how long it takes', 'how quickly they find', 'speed', 'time taken'] };
const COMP_BUTTON = { name: 'button size (small or large)', aliases: ['button size', 'button', 'small or large', 'small buttons', 'large buttons', 'size of the buttons', 'size'] };
const COMP_TAPERR = { name: 'number of tapping errors', aliases: ['tapping errors', 'errors', 'mistakes', 'wrong taps', 'missed taps', 'number of errors', 'accuracy'] };
const COMP_FONT = { name: 'font size (small or large)', aliases: ['font size', 'font', 'text size', 'small or large', 'small text', 'large text', 'size of the text'] };
const COMP_READ = { name: 'reading speed', aliases: ['reading speed', 'words per minute', 'how fast they read', 'reading time', 'speed', 'reading'] };
const COMP_HILITE = { name: 'syntax highlighting (on or off)', aliases: ['syntax highlighting', 'highlighting', 'on or off', 'colours', 'coloured code', 'plain code', 'colour coding'] };
const COMP_BUGTIME = { name: 'time to find the bug', aliases: ['time to find the bug', 'time to find', 'debugging time', 'how long it takes', 'how quickly they find it', 'speed', 'time taken'] };
const COMP_ERRMSG = { name: 'error message (clear or vague)', aliases: ['error message', 'message', 'clear or vague', 'clear message', 'vague message', 'wording', 'message clarity', 'clarity'] };
const COMP_FIXTIME = { name: 'time to fix the error', aliases: ['time to fix', 'fixing time', 'how long it takes', 'how quickly they fix it', 'speed', 'time taken', 'repair time'] };
const COMP_KEYB = { name: 'keyboard (physical or touchscreen)', aliases: ['keyboard', 'type of keyboard', 'physical or touchscreen', 'physical keyboard', 'touchscreen', 'on-screen keyboard', 'keys'] };
const COMP_WPM = { name: 'typing speed', aliases: ['typing speed', 'words per minute', 'wpm', 'how fast they type', 'speed', 'typing'] };
const COMP_DIST = { name: 'distance to the target (near or far)', aliases: ['distance', 'distance to the target', 'near or far', 'near', 'far', 'how far away', 'target distance'] };
const COMP_CLICK = { name: 'time to click the target', aliases: ['time to click', 'clicking time', 'pointing time', 'movement time', 'how long it takes', 'how quickly they click', 'speed', 'time taken'] };
const COMP_STEPS = { name: 'checkout design (3 steps or 6 steps)', aliases: ['checkout design', 'checkout', 'number of steps', 'steps', '3 steps or 6 steps', '3 steps', '6 steps', 'design', 'number of pages'] };
const COMP_BUYTIME = { name: 'time to complete the purchase', aliases: ['time to complete', 'time to buy', 'purchase time', 'checkout time', 'how long it takes', 'speed', 'time taken'] };
const COMP_DEVICE = { name: 'input device (mouse or touchpad)', aliases: ['input device', 'device', 'mouse or touchpad', 'mouse', 'touchpad', 'trackpad', 'pointing device'] };
const COMP_TARGETS = { name: 'time to click the targets', aliases: ['time to click', 'clicking time', 'pointing time', 'how long it takes', 'how quickly they click', 'speed', 'time taken', 'task time'] };
const COMP_PAIR = { name: 'working (alone or in pairs)', aliases: ['pair programming', 'pairs', 'alone', 'solo', 'alone or in pairs', 'working alone', 'working in pairs', 'partner', 'pair or solo'] };
const COMP_BUGS = { name: 'number of bugs found', aliases: ['bugs found', 'bugs', 'number of bugs', 'how many bugs', 'errors found', 'defects', 'problems found'] };

POOLS.computing = {
  // -------------------------------------------------------------------------
  // 1a. Variable or not?
  // -------------------------------------------------------------------------
  sortItems: [
    // --- variables: system performance ---
    { label: 'run time of a program', variable: true,
      why: 'A program can take longer on some inputs or computers than on others, and the time can be measured in milliseconds.' },
    { label: 'input size', variable: true,
      why: 'A program can be given 10 items or 10 million. The number of items can be counted and changed.' },
    { label: 'cache hit rate', variable: true,
      why: 'Some programs find the data they need in the cache more often than others. The percentage of hits can be measured.' },
    { label: 'server response time', variable: true,
      why: 'A server answers some requests faster than others, and the delay is measured in milliseconds.' },
    { label: 'download time', variable: true,
      why: 'A file can take a few seconds or several minutes to download, and the time can be measured.' },
    { label: 'file size', variable: true,
      why: 'Files are different sizes, measured in bytes, kilobytes or megabytes.' },
    { label: 'number of threads', variable: true,
      why: 'A program can be run with 1 thread or 16, and the number can be set and counted.' },
    { label: 'network bandwidth', variable: true,
      why: 'Some connections can carry more data per second than others. Bandwidth is measured in megabits per second.' },
    { label: 'memory used by a program', variable: true,
      why: 'Programs use different amounts of memory, and it changes as they run. It is measured in megabytes.' },
    { label: 'processor clock speed', variable: true,
      why: 'Processors run at different speeds, and some can be set faster or slower. Clock speed is measured in gigahertz.' },
    { label: 'packet loss', variable: true,
      why: 'On some connections more data packets go missing than on others. The percentage lost can be measured.' },
    { label: 'number of users logged in at once', variable: true,
      why: 'A server might have 3 users at night and 3,000 at midday. The number can be counted.' },
    { label: 'compression level', variable: true,
      why: 'A file can be saved with no compression, light compression or heavy compression, so the level takes different values.' },
    { label: 'number of lines of code', variable: true,
      why: 'Programs are different lengths, and their lines can be counted.' },
    { label: 'number of bugs found in testing', variable: true,
      why: 'Some programs have more bugs found in them than others, and bugs can be counted.' },
    { label: 'battery charge', variable: true,
      why: 'A laptop battery runs down as it is used, and the charge left is measured as a percentage.' },
    { label: 'round-trip time (ping)', variable: true,
      why: 'A message takes longer to reach some servers and come back than others. The time is measured in milliseconds.' },

    // --- variables: people using computers ---
    { label: 'task completion time', variable: true, for: COMP_CS,
      why: 'Some users finish a task on a website faster than others, and the time can be measured in seconds.' },
    { label: 'number of clicks to finish a task', variable: true, for: COMP_CS,
      why: 'Some people, and some designs, need more clicks than others to get a job done. Clicks can be counted.' },
    { label: 'typing speed', variable: true, for: COMP_CS,
      why: 'People type at different speeds, measured in words per minute.' },
    { label: 'time to find an option in a menu', variable: true, for: COMP_CS,
      why: 'Finding an option takes longer in some menus than others, and the time is measured in seconds.' },
    { label: 'button size on a phone screen', variable: true, for: COMP_CS,
      why: 'A designer can make buttons small or large, and their size can be measured in millimetres.' },
    { label: 'number of tapping errors', variable: true, for: COMP_CS,
      why: 'Some users hit the wrong button more often than others, and the wrong taps can be counted.' },
    { label: 'font size', variable: true, for: COMP_CS,
      why: 'Text on screen can be set small or large, and font size is measured in points or pixels.' },
    { label: 'page loading time', variable: true, for: COMP_CS,
      why: 'Some web pages appear almost at once and others take several seconds. The time can be measured.' },
    { label: 'satisfaction rating', variable: true, for: COMP_CS,
      why: 'Users rate how happy they are with an app on a scale, and different users give different ratings.' },
    { label: 'number of steps in a checkout', variable: true, for: COMP_CS,
      why: 'One shop\'s checkout might take 2 pages and another\'s 6. The steps can be counted and changed.' },
    { label: 'number of compiler errors', variable: true, for: COMP_CS,
      why: 'Some attempts at a program produce more compiler errors than others, and they can be counted.' },
    { label: 'time to fix a bug', variable: true, for: COMP_CS,
      why: 'Some bugs take a programmer minutes to fix and others take hours. The time can be measured.' },
    { label: 'number of help requests', variable: true, for: COMP_CS,
      why: 'Some users ask for help more often than others while learning a system, and requests can be counted.' },

    // --- not variables: one particular thing ---
    { label: 'the binary search algorithm', variable: false,
      why: 'Binary search is one particular algorithm — a thing, not a measurement. (How long it takes to run on a list would be a variable.)' },
    { label: 'the Python programming language', variable: false,
      why: 'Python is one particular language. (How many lines a program takes in it, or how fast it runs, would be a variable.)' },
    { label: 'Alan Turing', variable: false,
      why: 'Alan Turing is one particular person. (How long a machine takes to solve a problem would be a variable.)' },
    { label: 'the QWERTY keyboard layout', variable: false,
      why: 'QWERTY is one particular layout. (How fast someone types on it would be a variable.)' },
    { label: 'the Escape key', variable: false,
      why: 'It\'s one particular key. (How often a user presses it would be a variable.)' },
    { label: 'the university\'s login page', variable: false,
      why: 'It\'s one particular web page. (How long it takes to load, or to log in, would be a variable.)' },
    { label: 'the server room', variable: false,
      why: 'It\'s one particular room. (Its temperature, or how many servers are running in it, would be a variable.)' },
    { label: 'bubble sort', variable: false,
      why: 'Bubble sort is one particular sorting method. (The number of comparisons it makes on a list would be a variable.)' },
    { label: 'the file "report.pdf"', variable: false,
      why: 'It\'s one particular file. (Its size, or how long it takes to download, would be a variable.)' },
    { label: 'the computing lab', variable: false,
      why: 'It\'s one particular room. (How many students use it, or how noisy it is, would be a variable.)' },
    { label: 'the mouse', variable: false,
      why: 'The mouse is one particular device. (How quickly someone clicks a target with it would be a variable.)' },
    { label: 'the "Save" button', variable: false,
      why: 'It\'s one particular button. (Its size, or how long users take to find it, would be a variable.)' },
    { label: 'Ada Lovelace', variable: false,
      why: 'Ada Lovelace is one particular person. (The number of steps in a program would be a variable.)' },

    // --- not variables: measurable, but only one possible value ---
    { label: 'the number of bits in a byte', variable: false,
      why: 'It\'s always 8. Something that can only ever have one value is a constant, not a variable.' },
    { label: 'the number of values one bit can take', variable: false,
      why: 'It\'s always 2 — 0 or 1. It can be counted, but it doesn\'t vary.' },
    { label: 'the number of digits in the binary number 1011', variable: false,
      why: 'It\'s always 4 — only one possible value, so it\'s a constant, not a variable.' },
  ],

  // -------------------------------------------------------------------------
  // 1b-1d, 2b, 2c. Relations.
  // -------------------------------------------------------------------------
  relations: [
    // --- system performance ---
    { id: 'comp-inputsize-linear', iv: 'input size', dv: 'run time',
      ivNP: 'the size of the input', dvNP: 'the run time of a linear search',
      hyp: ['input size', 'run time'], ivAxis: 'Input size', dvAxis: 'Run time', dir: 'up',
      says: ['The longer the list a linear search has to look through, the longer it takes to run in the worst case.',
             'The worst-case run time of a linear search goes up as the list gets longer.'],
      why: 'The list is given to the program before it runs; the run time is the result. A slow run can\'t make the list longer.' },
    { id: 'comp-sortsize-time', iv: 'number of items to sort', dv: 'sorting time',
      ivNP: 'the number of items to sort', dvNP: 'the time taken to sort them',
      hyp: ['items to sort', 'sorting time'], ivAxis: 'Items', dvAxis: 'Sorting time', dir: 'up',
      says: ['The more items a program has to sort, the longer the sort takes.',
             'Sorting time goes up as the number of items goes up.'],
      why: 'The number of items is fixed before the sort starts, and each item needs work. Sorting slowly can\'t add items to the list.' },
    { id: 'comp-cache-hit', iv: 'cache size', dv: 'cache hit rate',
      ivNP: 'the size of the cache', dvNP: 'the cache hit rate',
      hyp: ['cache size', 'hit rate'], ivAxis: 'Cache size', dvAxis: 'Hit rate', dir: 'up',
      says: ['Running the same program, a bigger cache usually finds the data it needs more often.',
             'The cache hit rate generally goes up as the cache gets bigger.'],
      why: 'The cache size is set by the hardware or settings before the program runs; the hit rate is the result. Getting more hits can\'t make the cache bigger.' },
    { id: 'comp-users-response', iv: 'users at once', dv: 'response time',
      ivNP: 'the number of users at once', dvNP: 'the server\'s response time',
      hyp: ['users at once', 'response time'], ivAxis: 'Users', dvAxis: 'Response time', dir: 'up',
      says: ['The more people use the same server at the same time, the longer it takes to answer each request.',
             'A server\'s response time goes up as more users use it at once.'],
      why: 'The users send requests, and the server has to share its time between them. A slow response can\'t create more users.' },
    { id: 'comp-bandwidth-download', iv: 'bandwidth', dv: 'download time',
      ivNP: 'the bandwidth of the connection', dvNP: 'the download time',
      hyp: ['bandwidth', 'download time'], ivAxis: 'Bandwidth', dvAxis: 'Download time', dir: 'down',
      says: ['The same file downloads more quickly over a connection with more bandwidth.',
             'Download time goes down as the bandwidth goes up.'],
      why: 'The bandwidth is a property of the connection, fixed before the download starts. A quick download can\'t widen the connection.' },
    { id: 'comp-compress-size', iv: 'compression level', dv: 'file size',
      ivNP: 'the compression level', dvNP: 'the size of the file',
      hyp: ['compression', 'file size'], ivAxis: 'Compression', dvAxis: 'File size', dir: 'down',
      says: ['Saving the same photo with heavier compression gives a smaller file.',
             'The file size goes down as the compression level goes up.'],
      why: 'The compression level is chosen before the file is saved; the file size is the result. A small file can\'t choose its own compression.' },
    { id: 'comp-resolution-size', iv: 'image resolution', dv: 'file size',
      ivNP: 'the resolution of the image', dvNP: 'the size of the file',
      hyp: ['resolution', 'file size'], ivAxis: 'Resolution', dvAxis: 'File size', dir: 'up',
      says: ['Saved in the same format, a photo with more pixels makes a bigger file.',
             'File size goes up as the image resolution goes up.'],
      why: 'Every pixel has to be stored, so the resolution sets how much there is to save. A bigger file can\'t add pixels to the photo.' },
    { id: 'comp-filesize-transfer', iv: 'file size', dv: 'transfer time',
      ivNP: 'the size of the file', dvNP: 'the time to transfer it',
      hyp: ['file size', 'transfer time'], ivAxis: 'File size', dvAxis: 'Transfer time', dir: 'up',
      says: ['Over the same connection, bigger files take longer to transfer.',
             'Transfer time goes up as the file size goes up.'],
      why: 'The file exists before it is sent, and every byte has to travel. A slow transfer can\'t make the file bigger.' },
    { id: 'comp-threads-runtime', iv: 'number of threads', dv: 'run time',
      ivNP: 'the number of threads', dvNP: 'the run time of the task',
      hyp: ['threads', 'run time'], ivAxis: 'Threads', dvAxis: 'Run time', dir: 'down',
      says: ['A task that splits into independent parts runs faster with more threads, up to the number of processor cores.',
             'Up to the number of cores, the run time of a task that splits into independent parts goes down as more threads share the work.'],
      why: 'The number of threads is set before the task runs, and each thread takes a share of the work. A fast run can\'t add threads.' },
    { id: 'comp-clock-runtime', iv: 'clock speed', dv: 'run time',
      ivNP: 'the processor\'s clock speed', dvNP: 'the run time of the program',
      hyp: ['clock speed', 'run time'], ivAxis: 'Clock speed', dvAxis: 'Run time', dir: 'down',
      says: ['On the same processor, a calculation-heavy program finishes sooner when the clock speed is set higher.',
             'The run time of a calculation-heavy program goes down as the processor\'s clock speed goes up.'],
      why: 'The clock speed sets how many steps the processor takes each second. A program finishing quickly can\'t speed up the clock.' },
    { id: 'comp-keylen-brute', iv: 'key length', dv: 'time to try every key',
      ivNP: 'the length of the key', dvNP: 'the time needed to try every possible key',
      hyp: ['key length', 'time to try all keys'], ivAxis: 'Key length', dvAxis: 'Time to try all', dir: 'up',
      says: ['Each extra bit in a key doubles the number of possible keys, so trying them all takes longer.',
             'The time needed to try every possible key goes up as the key gets longer.'],
      why: 'The key length fixes how many keys there are to try before anyone starts. Taking a long time can\'t make the key longer.' },
    { id: 'comp-layers-training', iv: 'number of layers', dv: 'training time',
      ivNP: 'the number of layers in the network', dvNP: 'the training time',
      hyp: ['layers', 'training time'], ivAxis: 'Layers', dvAxis: 'Training time', dir: 'up',
      says: ['With the same data and computer, a neural network with more layers takes longer to train for each pass through the data.',
             'Training time per pass through the data goes up as layers are added to the network.'],
      why: 'The designer chooses the number of layers before training, and each layer adds calculations. Training slowly can\'t add layers.' },
    { id: 'comp-load-collisions', iv: 'hash table fullness', dv: 'number of collisions',
      ivNP: 'how full the hash table is', dvNP: 'the number of collisions',
      hyp: ['table fullness', 'collisions'], ivAxis: 'Fullness', dvAxis: 'Collisions', dir: 'up',
      says: ['The fuller a hash table is, the more often a new item lands in a slot that is already taken.',
             'The number of collisions goes up as the hash table fills up.'],
      why: 'The items already stored take up slots, so new items are more likely to clash. A collision can\'t fill the table beforehand.' },
    { id: 'comp-distance-ping', iv: 'distance to the server', dv: 'round-trip time',
      ivNP: 'the distance to the server', dvNP: 'the round-trip time',
      hyp: ['distance', 'round-trip time'], ivAxis: 'Distance', dvAxis: 'Round trip', dir: 'up',
      says: ['Other things being equal, a message takes longer to reach a distant server and come back than a nearby one.',
             'The round-trip time goes up as the distance to the server goes up.'],
      why: 'The signal has to travel the distance, and travel takes time. A slow reply can\'t move the server further away.' },
    { id: 'comp-loss-resend', iv: 'packet loss', dv: 'packets resent',
      ivNP: 'the rate of packet loss', dvNP: 'the number of packets resent',
      hyp: ['packet loss', 'packets resent'], ivAxis: 'Packet loss', dvAxis: 'Packets resent', dir: 'up',
      says: ['When more packets go missing on a connection, more of them have to be sent again.',
             'The number of packets resent goes up with the rate of packet loss.'],
      why: 'A packet is resent because it was lost; the loss comes first. Resending a packet can\'t make earlier ones go missing.' },
    { id: 'comp-router-download', iv: 'distance from the router', dv: 'download speed',
      ivNP: 'the distance from the Wi-Fi router', dvNP: 'the download speed',
      hyp: ['router distance', 'download speed'], ivAxis: 'Distance', dvAxis: 'Download speed', dir: 'down',
      says: ['In the same building, a laptop further from the Wi-Fi router generally downloads more slowly.',
             'Download speed goes down as the laptop moves further from the router.'],
      why: 'The signal weakens with distance, which slows the download. A slow download can\'t move the laptop.' },
    { id: 'comp-buffer-pauses', iv: 'buffer size', dv: 'playback pauses',
      ivNP: 'the size of the playback buffer', dvNP: 'the number of pauses',
      hyp: ['buffer size', 'pauses'], ivAxis: 'Buffer size', dvAxis: 'Pauses', dir: 'down',
      says: ['On an unsteady connection, a video player with a bigger buffer pauses less often.',
             'The number of pauses in playback goes down as the buffer gets bigger.'],
      why: 'The buffer size is set in the player, and a bigger store of video rides out gaps in the connection. Pausing can\'t change the buffer size.' },

    // --- people using computers ---
    { id: 'comp-menu-find', for: COMP_CS, iv: 'number of menu items', dv: 'time to find an option',
      ivNP: 'the number of items in the menu', dvNP: 'the time to find an option',
      hyp: ['menu items', 'time to find'], ivAxis: 'Menu items', dvAxis: 'Time to find', dir: 'up',
      says: ['The more items there are in a menu, the longer people take to find the option they want.',
             'Time to find an option goes up as the menu gets longer.'],
      why: 'The designer sets the menu before anyone uses it; the search time is the result. Searching slowly can\'t add items to the menu.' },
    { id: 'comp-button-errors', for: COMP_CS, iv: 'button size', dv: 'tapping errors',
      ivNP: 'the size of the buttons', dvNP: 'the number of tapping errors',
      hyp: ['button size', 'tapping errors'], ivAxis: 'Button size', dvAxis: 'Tapping errors', dir: 'down',
      says: ['People tapping on a phone hit the wrong button less often when the buttons are bigger.',
             'Tapping errors go down as the buttons get bigger.'],
      why: 'The button size is fixed in the design before anyone taps; the errors are the result. Tapping accurately can\'t make the buttons bigger.' },
    { id: 'comp-fitts-distance', for: COMP_CS, iv: 'distance to the target', dv: 'time to click it',
      ivNP: 'the distance to the target', dvNP: 'the time to click it',
      hyp: ['target distance', 'time to click'], ivAxis: 'Distance', dvAxis: 'Time to click', dir: 'up',
      says: ['For targets of the same size, people take longer to click one that is further from the pointer (Fitts\'s law).',
             'The time to click a target goes up with its distance from the pointer.'],
      why: 'The target is placed on screen before the person moves; the movement time is the result. A slow click can\'t move the target further away.' },
    { id: 'comp-fitts-size', for: COMP_CS, iv: 'target size', dv: 'time to click it',
      ivNP: 'the size of the target', dvNP: 'the time to click it',
      hyp: ['target size', 'time to click'], ivAxis: 'Target size', dvAxis: 'Time to click', dir: 'down',
      says: ['At the same distance, people click a big target more quickly than a small one (Fitts\'s law).',
             'The time to click a target goes down as the target gets bigger.'],
      why: 'The target size is set on screen before the person moves, and a big target needs less careful aiming. Clicking quickly can\'t make the target bigger.' },
    { id: 'comp-font-reading', for: COMP_CS, iv: 'font size', dv: 'reading speed',
      ivNP: 'the font size', dvNP: 'the reading speed',
      hyp: ['font size', 'reading speed'], ivAxis: 'Font size', dvAxis: 'Reading speed', dir: 'up',
      says: ['From very small text up to a comfortable size, people read on screen faster as the font gets bigger.',
             'Up to a comfortable size, reading speed on screen goes up as the font size goes up.'],
      why: 'The font size is set before the person reads; the reading speed is the result. Reading fast can\'t change the size of the text.' },
    { id: 'comp-steps-abandon', for: COMP_CS, iv: 'steps in the checkout', dv: 'abandoned checkouts',
      ivNP: 'the number of steps in the checkout', dvNP: 'the percentage of abandoned checkouts',
      hyp: ['checkout steps', 'abandoned checkouts'], ivAxis: 'Steps', dvAxis: 'Abandoned', dir: 'up',
      says: ['The more pages a shop\'s checkout has, the more shoppers give up before paying.',
             'The percentage of abandoned checkouts goes up with the number of steps in the checkout.'],
      why: 'The checkout is designed before shoppers use it, and each extra step is another point to give up. Shoppers leaving can\'t add steps.' },
    { id: 'comp-typing-practice', for: COMP_CS, iv: 'weeks of typing practice', dv: 'typing speed',
      ivNP: 'the number of weeks of typing practice', dvNP: 'the typing speed',
      hyp: ['typing practice', 'typing speed'], ivAxis: 'Weeks practised', dvAxis: 'Words/minute', dir: 'up',
      says: ['The more weeks people practise touch-typing, the more words per minute they type.',
             'Typing speed goes up with the weeks of practice.'],
      why: 'The practice comes first and builds the skill. Typing fast at the end can\'t go back and add weeks of practice.' },
    { id: 'comp-rules-password', for: COMP_CS, iv: 'number of password rules', dv: 'time to create a password',
      ivNP: 'the number of password rules', dvNP: 'the time to create a password',
      hyp: ['password rules', 'time to create'], ivAxis: 'Rules', dvAxis: 'Time to create', dir: 'up',
      says: ['The more rules a new password has to meet, the longer people take to create one that is accepted.',
             'The time taken to create an accepted password goes up with the number of rules.'],
      why: 'The site sets its rules before the person starts; the time is the result. Taking a long time can\'t add rules.' },
    { id: 'comp-loading-leave', for: COMP_CS, iv: 'page loading time', dv: 'visitors who leave',
      ivNP: 'the page loading time', dvNP: 'the percentage of visitors who leave before it loads',
      hyp: ['loading time', 'visitors leaving'], ivAxis: 'Loading time', dvAxis: '% who leave', dir: 'up',
      says: ['The longer a web page takes to load, the more visitors give up and leave before it appears.',
             'The percentage of visitors who leave before the page loads goes up with the loading time.'],
      why: 'The loading time comes from the page and the server, and visitors react to the wait. Visitors leaving can\'t make the page slower.' },
    { id: 'comp-errmsg-fix', for: COMP_CS, iv: 'error-message clarity', dv: 'time to fix the error',
      ivNP: 'how clear the error message is', dvNP: 'the time to fix the error',
      hyp: ['message clarity', 'time to fix'], ivAxis: 'Clarity', dvAxis: 'Time to fix', dir: 'down',
      says: ['The clearer the error message, the more quickly programmers fix the mistake.',
             'Time to fix an error goes down as the error message gets clearer.'],
      why: 'The message is written before the programmer reads it; the fixing time is the result. A quick fix can\'t rewrite the message.' },
    { id: 'comp-practice-errors', for: COMP_CS, iv: 'weeks of programming practice', dv: 'compiler errors',
      ivNP: 'the number of weeks of programming practice', dvNP: 'the number of compiler errors',
      hyp: ['weeks of practice', 'compiler errors'], ivAxis: 'Weeks', dvAxis: 'Compiler errors', dir: 'down',
      says: ['Students learning to program make fewer compiler errors per exercise the more weeks they have practised.',
             'The number of compiler errors per exercise goes down with weeks of practice.'],
      why: 'The practice builds up first and the errors are counted later. Making fewer errors can\'t add weeks of practice.' },
    { id: 'comp-uses-tasktime', for: COMP_CS, iv: 'times the app has been used', dv: 'task completion time',
      ivNP: 'the number of times the app has been used', dvNP: 'the task completion time',
      hyp: ['times used', 'task time'], ivAxis: 'Times used', dvAxis: 'Task time', dir: 'down',
      says: ['The more times people have used an app, the more quickly they complete a routine task in it.',
             'Task completion time goes down with the number of times the app has been used.'],
      why: 'The earlier uses come first and build familiarity. Finishing quickly today can\'t add earlier uses.' },
    { id: 'comp-codelen-review', for: COMP_CS, iv: 'length of code', dv: 'review time',
      ivNP: 'the length of the code', dvNP: 'the time to review it',
      hyp: ['code length', 'review time'], ivAxis: 'Lines of code', dvAxis: 'Review time', dir: 'up',
      says: ['The more lines of code a programmer is given to check, the longer the review takes.',
             'Review time goes up with the number of lines of code.'],
      why: 'The code is written before the review, and every line has to be read. A long review can\'t add lines to the code.' },
  ],

  // -------------------------------------------------------------------------
  // 2a. Validity and reliability.
  // -------------------------------------------------------------------------
  validity: [
    // valid and reliable
    { valid: true, reliable: true,
      text: 'To measure how fast a sorting program is, researchers time it with the computer\'s clock on the same 1,000 lists, with nothing else running. Running the timings again gives almost the same result.',
      whyValid: 'the time the program takes to sort is exactly what "how fast it is" means.',
      whyReliable: 'repeating the timings on the same lists gives almost the same result.' },
    { valid: true, reliable: true,
      text: 'To measure how big a set of image files is, a script reads the number of bytes in each file. Running the script again gives exactly the same numbers.',
      whyValid: 'the number of bytes is the size of the file.',
      whyReliable: 'the same files give exactly the same numbers every time.' },
    { valid: true, reliable: true, for: COMP_CS,
      text: 'To measure how long users take to find an option, software records the seconds from when the menu opens to when the right option is clicked, averaged over 20 searches. Testing the same people again gives very similar averages.',
      whyValid: 'the time from opening the menu to clicking the option is exactly the time taken to find it.',
      whyReliable: 'averaging many searches gives very similar results when the same people are tested again.' },
    { valid: true, reliable: true, for: COMP_CS,
      text: 'To measure tapping errors, a phone app logs every tap that lands outside the intended button during a set task. Two researchers who check the logs separately get the same counts.',
      whyValid: 'a tap outside the intended button is exactly what a tapping error is.',
      whyReliable: 'two people checking the logs separately get the same counts.' },

    // reliable, not valid
    { valid: false, reliable: true,
      text: 'To measure how fast a server responds, researchers count the number of cables plugged into it. The count is the same every time.',
      whyValid: 'the number of cables says nothing about how quickly the server answers requests.',
      whyReliable: 'counting the cables again gives the same number. Consistent, but consistently measuring the wrong thing.' },
    { valid: false, reliable: true,
      text: 'To measure how quickly a program runs, researchers count the number of lines in its source code. The count comes out the same whoever does it.',
      whyValid: 'a short program can run slowly and a long one quickly — line count measures the code\'s length, not its speed.',
      whyReliable: 'anyone who counts the lines gets the same number.' },
    { valid: false, reliable: true, for: COMP_CS,
      text: 'To measure how easy a website is to use, researchers count the number of pages on the site. Counting again gives the same number.',
      whyValid: 'how many pages a site has isn\'t how easy it is to use — the count measures the site\'s size.',
      whyReliable: 'counting the pages again gives the same number.' },
    { valid: false, reliable: true, for: COMP_CS,
      text: 'To measure how well students can program, a tutor records the date each student enrolled on the course. Checking the records again gives the same dates.',
      whyValid: 'the enrolment date has nothing to do with programming skill.',
      whyReliable: 'the records give the same dates every time they are checked.' },

    // valid, not reliable
    { valid: true, reliable: false,
      text: 'To compare two search programs, researchers time each one on a single run, while other programs are starting and stopping on the same computer. Timing them again gives quite different results.',
      whyValid: 'timing the programs is the right way to measure how fast they are.',
      whyReliable: 'one run on a busy computer swings from try to try — many runs, with nothing else running, would be needed.' },
    { valid: true, reliable: false,
      text: 'Researchers measure download times over a sensible test connection, but their report doesn\'t say how big the files were or what else was using the network. Others who try to repeat the study get different results.',
      whyValid: 'timing downloads is the right way to measure download time.',
      whyReliable: 'without a full "recipe" — file sizes, network conditions, equipment — nobody can repeat the study and get the same result.' },
    { valid: true, reliable: false, for: COMP_CS,
      text: 'To find out whether a new menu layout helps people find options faster, researchers time 4 users on each layout. When they test another 4 users, the result comes out the other way.',
      whyValid: 'timing how long people take to find options is the right thing to measure.',
      whyReliable: 'repeating it with another 4 users gives a different result. For a small difference, 4 users per layout is far too few.' },
    { valid: true, reliable: false, for: COMP_CS,
      text: 'To measure how often users hesitate, one observer watches over each user\'s shoulder and counts the pauses. When the same session is counted again from a screen recording, the numbers are quite different.',
      whyValid: 'pauses while using a system are a sensible sign of hesitation.',
      whyReliable: 'one observer counting live misses pauses, so counting the same session again gives a different number.' },

    // neither
    { valid: false, reliable: false,
      text: 'To measure a network\'s bandwidth, researchers note how many people walk past the server room in an hour. The count is different every hour.',
      whyValid: 'people walking past have nothing to do with how much data the network can carry.',
      whyReliable: 'the count changes every time it is taken.' },
    { valid: false, reliable: false,
      text: 'To measure how much memory a program uses, researchers roll a die before each run and record the number. The number is different each time.',
      whyValid: 'a die roll has nothing to do with the program\'s memory use.',
      whyReliable: 'the die gives a different number each time.' },
    { valid: false, reliable: false, for: COMP_CS,
      text: 'To measure how quickly people type, researchers note what colour top each participant is wearing. The same person wears a different colour each visit.',
      whyValid: 'the colour of someone\'s top isn\'t a measure of typing speed.',
      whyReliable: 'the same person gives a different answer each visit.' },
    { valid: false, reliable: false, for: COMP_CS,
      text: 'To measure how well a student debugs code, a tutor counts the unread emails in the tutor\'s own inbox at the start of each session. The number changes every day.',
      whyValid: 'the tutor\'s emails have nothing to do with the student\'s debugging.',
      whyReliable: 'the count is different every time.' },
  ],

  // -------------------------------------------------------------------------
  // 2d. Continuous or discrete.
  // -------------------------------------------------------------------------
  continuity: [
    { cat: 'cont', label: 'run time of a program', why: COMP_CONT + '2.5 s, 2.51 s, 2.513 s... time can always be divided further.' },
    { cat: 'cont', label: 'server response time', why: COMP_CONT + '120 ms, 120.4 ms... the delay can be any length.' },
    { cat: 'cont', label: 'download time', why: COMP_CONT + '8 seconds, 8.3 seconds, 8.31 seconds...' },
    { cat: 'cont', label: 'processor temperature', why: COMP_CONT + '65°C, 65.2°C, 65.27°C...' },
    { cat: 'cont', label: 'round-trip time (ping)', why: COMP_CONT + '30 ms, 30.6 ms... it can be measured as finely as the clock allows.' },
    { cat: 'cont', label: 'cache hit rate as a percentage', why: COMP_CONT + '92%, 92.5%, 92.51%... a rate worked out from thousands of accesses can take any value.' },
    { cat: 'cont', label: 'power drawn by a laptop', why: COMP_CONT + '15 W, 15.4 W, 15.43 W...' },
    { cat: 'cont', label: 'distance from the Wi-Fi router', why: COMP_CONT + '3 m, 3.5 m, 3.52 m...' },
    { cat: 'cont', label: 'task completion time', why: COMP_CONT + '45 seconds, 45.7 seconds... time can always be measured more finely.', for: COMP_CS },
    { cat: 'cont', label: 'time to click a target', why: COMP_CONT + '800 ms, 800.5 ms...', for: COMP_CS },
    { cat: 'cont', label: 'button width on screen in millimetres', why: COMP_CONT + '7 mm, 7.5 mm, 7.52 mm... a button can be drawn at any width.', for: COMP_CS },
    { cat: 'cont', label: 'page loading time', why: COMP_CONT + '1.2 s, 1.25 s, 1.253 s...', for: COMP_CS },
    { cat: 'cont', label: 'average number of clicks per task across users', why: COMP_CONT + 'one user can\'t make 6.4 clicks, but an average across users can be 6.4.', for: COMP_CS },

    { cat: 'disc', label: 'number of threads', why: COMP_DISC + 'a program runs 4 threads or 5, never 4.5.' },
    { cat: 'disc', label: 'number of processor cores', why: COMP_DISC + 'a chip has 8 cores or 10, nothing in between.' },
    { cat: 'disc', label: 'number of items in the input', why: COMP_DISC + 'items are counted: 1,000 or 1,001, never 1,000.5.' },
    { cat: 'disc', label: 'number of lines of code', why: COMP_DISC + 'a program has 200 lines or 201, not 200.3.' },
    { cat: 'disc', label: 'number of users logged in', why: COMP_DISC + 'users are counted in whole numbers.' },
    { cat: 'disc', label: 'number of packets resent', why: COMP_DISC + 'each packet is resent or not, so the total is a whole number.' },
    { cat: 'disc', label: 'number of hash collisions', why: COMP_DISC + 'each collision is counted once.' },
    { cat: 'disc', label: 'number of bugs found', why: COMP_DISC + 'a tester finds 3 bugs or 4, never 3.5.' },
    { cat: 'disc', label: 'number of clicks to finish a task', why: COMP_DISC + 'each click is counted once.', for: COMP_CS },
    { cat: 'disc', label: 'number of tapping errors', why: COMP_DISC + 'each wrong tap is counted, so the total is a whole number.', for: COMP_CS },
    { cat: 'disc', label: 'number of items in a menu', why: COMP_DISC + 'a menu has 8 options or 9, nothing in between.', for: COMP_CS },
    { cat: 'disc', label: 'number of steps in a checkout', why: COMP_DISC + 'a checkout has 3 pages or 4, not 3.5.', for: COMP_CS },
    { cat: 'disc', label: 'satisfaction rating on a 1–7 scale', why: COMP_DISC + 'users choose 1, 2, 3... 7, and there\'s no 5.5 on the scale.', for: COMP_CS },
  ],

  // -------------------------------------------------------------------------
  // 2e. Levels of measurement.
  // -------------------------------------------------------------------------
  measurement: [
    { cat: 'categorical', label: 'programming language used (Python, Java or C)', why: COMP_NOM + 'Python isn\'t more or less than Java — they\'re different languages.' },
    { cat: 'categorical', label: 'operating system (Windows, macOS or Linux)', why: COMP_NOM + 'The systems are different, not ranked.' },
    { cat: 'categorical', label: 'sorting algorithm (merge sort, quicksort or insertion sort)', why: COMP_NOM + 'These are kinds of algorithm, not amounts of one.' },
    { cat: 'categorical', label: 'file format (PNG, JPEG or GIF)', why: COMP_NOM + 'A PNG isn\'t more than a JPEG, just different.' },
    { cat: 'categorical', label: 'input device (mouse, touchpad or touchscreen)', why: COMP_NOM + 'The devices are different kinds of thing, with no order.', for: COMP_CS },
    { cat: 'categorical', label: 'which version of a web page a user sees (A or B)', why: COMP_NOM + 'Version A and version B are labels, not amounts.', for: COMP_CS },

    { cat: 'ordinal', label: 'bug severity (minor, major, critical)', why: COMP_ORD + 'Critical is above major, but nothing says the steps are the same size.' },
    { cat: 'ordinal', label: 'league-table position of algorithms by speed (1st, 2nd, 3rd)', why: COMP_ORD + 'The gap between 1st and 2nd could be a millisecond; between 2nd and 3rd, a minute.' },
    { cat: 'ordinal', label: 'compression setting (low, medium, high)', why: COMP_ORD + 'In order, but the jump from low to medium needn\'t match the jump from medium to high.' },
    { cat: 'ordinal', label: 'ease of use from "very difficult" to "very easy"', why: COMP_ORD + 'The labelled answers are in order, but not equally spaced.', for: COMP_CS },
    { cat: 'ordinal', label: 'programming experience (beginner, intermediate, expert)', why: COMP_ORD + 'The labels are ranked, but the steps between them aren\'t equal-sized.', for: COMP_CS },
    { cat: 'ordinal', label: 'ranking three app designs from most to least liked', why: COMP_ORD + 'A ranking gives the order, not how far apart the designs are.', for: COMP_CS },

    { cat: 'interval', label: 'server room temperature in °C', why: COMP_INT + '0°C isn\'t "no temperature", so 24°C isn\'t twice as warm as 12°C.' },
    { cat: 'interval', label: 'date a software update was released', why: COMP_INT + 'Days are equal steps, but the calendar\'s starting point is arbitrary.' },
    { cat: 'interval', label: 'time of day a backup starts', why: COMP_INT + 'The minutes are equal, but midnight isn\'t "no time", so 4 o\'clock isn\'t twice 2 o\'clock.' },
    { cat: 'interval', label: 'ease of use rated on a scale of 1–7', why: COMP_INT + 'The numbered steps are treated as equal, but there\'s no zero, so a 6 isn\'t "twice as easy" as a 3.', for: COMP_CS },
    { cat: 'interval', label: 'satisfaction with an app rated 1–9', why: COMP_INT + 'A numbered scale has constant steps, but no natural zero.', for: COMP_CS },

    { cat: 'ratio', label: 'run time in milliseconds', why: COMP_RAT + '0 ms is no time at all, and 400 ms is twice 200 ms.' },
    { cat: 'ratio', label: 'file size in megabytes', why: COMP_RAT + '0 MB is no data at all, and 10 MB is twice 5 MB.' },
    { cat: 'ratio', label: 'number of threads', why: COMP_RAT + '0 threads is none, and 8 threads is twice 4.' },
    { cat: 'ratio', label: 'bandwidth in megabits per second', why: COMP_RAT + '0 Mbit/s carries nothing, and 100 Mbit/s is twice 50.' },
    { cat: 'ratio', label: 'task completion time in seconds', why: COMP_RAT + '0 seconds is no time, and 60 seconds is twice 30.', for: COMP_CS },
    { cat: 'ratio', label: 'number of tapping errors', why: COMP_RAT + 'Zero errors means none, and 6 errors is twice 3.', for: COMP_CS },
  ],

  // -------------------------------------------------------------------------
  // 2g. Confounds. Paired: the same study done badly, then done properly.
  // All with human participants.
  // -------------------------------------------------------------------------
  confounds: [
    { iv: 'menu length', dv: 'time to find an option', confound: 'experience with the app',
      vars: ['menu length', 'time to find an option', 'experience with the app', 'the options to find'],
      text: 'Researchers test whether shorter menus make options quicker to find. The short-menu version is tried by people who use the app every day; the long-menu version by people who have never used it. Both groups look for the same options.',
      why: 'The short-menu group also knew the app well, so they might find options faster because of experience, not the menu.' },
    { iv: 'button size', dv: 'tapping errors', confound: 'walking or sitting',
      vars: ['button size', 'tapping errors', 'walking or sitting', 'the phone'],
      text: 'Researchers test whether bigger buttons reduce tapping errors. Everyone uses the same phone, but the big-button group sits at a desk while the small-button group taps while walking along a corridor.',
      why: 'The small-button group was also walking, which makes accurate tapping harder. The difference could come from walking, not button size.' },
    { iv: 'font size', dv: 'reading speed', confound: 'text difficulty',
      vars: ['font size', 'reading speed', 'text difficulty', 'the screen'],
      text: 'Researchers test whether a larger font makes on-screen reading faster. Both groups read on the same screen, but the large-font group reads a simple story and the small-font group reads a technical manual.',
      why: 'The small-font group also had a much harder text, which is slower to read anyway. The difference could be the text, not the font.' },
    { iv: 'error-message clarity', dv: 'time to fix the error', confound: 'programming experience',
      vars: ['error-message clarity', 'time to fix the error', 'programming experience', 'the broken program'],
      text: 'Researchers test whether clearer error messages help programmers fix mistakes faster. Everyone fixes the same broken program, but the clear-message group are third-year students and the vague-message group are first-years.',
      why: 'The clear-message group also had two more years of programming, so they might fix errors faster because of experience, not the message.' },
    { iv: 'pair or solo programming', dv: 'number of bugs found', confound: 'time allowed',
      vars: ['pair or solo programming', 'number of bugs found', 'time allowed', 'the code to check'],
      text: 'Researchers test whether checking code in pairs finds more bugs than checking alone. Everyone checks the same code, but the pairs get two hours and the people working alone get one hour.',
      why: 'The pairs also had twice as long, and more time finds more bugs. The difference could come from the time, not the pairing.' },
    { iv: 'shortcut training', dv: 'task completion time', confound: 'the computer',
      vars: ['shortcut training', 'task completion time', 'the computer', 'the editing task'],
      text: 'Researchers test whether training in keyboard shortcuts makes people finish an editing task faster. The trained group uses new, fast computers; the untrained group uses old, slow ones. Both do the same editing task.',
      why: 'The trained group also had faster computers, so they might finish sooner because of the computer, not the training.' },
    { iv: 'syntax highlighting', dv: 'time to find the bug', confound: 'length of the code',
      vars: ['syntax highlighting', 'time to find the bug', 'length of the code', 'the programming language'],
      text: 'Researchers test whether syntax highlighting helps programmers find bugs faster. Everyone reads code in the same language, but the highlighted programs are 20 lines long and the plain ones are 200 lines long.',
      why: 'The highlighted code was also much shorter, and short code is quicker to search. The difference could be length, not the colours.' },
    { iv: 'keyboard type', dv: 'typing speed', confound: 'passage difficulty',
      vars: ['keyboard type', 'typing speed', 'passage difficulty', 'the length of the passage'],
      text: 'Researchers test whether people type faster on a physical keyboard than on a touchscreen. Both groups type a passage of the same length, but the physical-keyboard group copies everyday sentences and the touchscreen group copies code full of symbols.',
      why: 'The touchscreen group also had a harder passage, which is slower to type on any keyboard. The difference could be the passage, not the keyboard.' },
    { iv: 'number of checkout steps', dv: 'time to complete the purchase', confound: 'the product chosen',
      vars: ['number of checkout steps', 'time to complete the purchase', 'the product chosen', 'the test website'],
      text: 'In a lab, researchers test whether a 3-step checkout is quicker to complete than a 6-step one, on the same test website. The 3-step group buys a single book; the 6-step group buys a laptop that needs options choosing.',
      why: 'The 6-step group also had a more complicated product to buy, which takes longer anyway. The difference could be the product, not the steps.' },
    { iv: 'input device', dv: 'time to click the targets', confound: 'size of the targets',
      vars: ['input device', 'time to click the targets', 'size of the targets', 'the number of targets'],
      text: 'Researchers test whether people click targets faster with a mouse than a touchpad. Both groups click 50 targets, but the mouse group\'s targets are large and the touchpad group\'s are small.',
      why: 'The touchpad group also had smaller targets, which take longer to hit with any device. The difference could be target size, not the device.' },

    { iv: 'menu length', dv: 'time to find an option', confound: null,
      text: 'Researchers test whether shorter menus make options quicker to find. People who have never used the app are randomly assigned to the short-menu or long-menu version, and both groups look for the same options.',
      why: 'Random assignment of new users means experience is spread evenly — only the menu length differs.' },
    { iv: 'button size', dv: 'tapping errors', confound: null,
      text: 'Researchers test whether bigger buttons reduce tapping errors. Participants are randomly assigned to big or small buttons, and everyone sits at the same desk using the same phone.',
      why: 'Same phone, same seated position, random groups — only the button size differs.' },
    { iv: 'font size', dv: 'reading speed', confound: null,
      text: 'Researchers test whether a larger font makes on-screen reading faster. Participants are randomly split into two groups who read the same text on the same screen, in a large or a small font.',
      why: 'Same text, same screen, random groups — only the font size differs.' },
    { iv: 'error-message clarity', dv: 'time to fix the error', confound: null,
      text: 'Researchers test whether clearer error messages help programmers fix mistakes faster. Second-year students are randomly assigned to see a clear or a vague message while fixing the same broken program.',
      why: 'Students from the same year, randomly assigned, fixing the same program — only the message differs.' },
    { iv: 'pair or solo programming', dv: 'number of bugs found', confound: null,
      text: 'Researchers test whether checking code in pairs finds more bugs than checking alone. Participants are randomly assigned to work in pairs or alone, and everyone gets the same code and the same hour.',
      why: 'Same code, same time, random assignment — only working in pairs or alone differs.' },
    { iv: 'shortcut training', dv: 'task completion time', confound: null,
      text: 'Researchers test whether training in keyboard shortcuts speeds up an editing task. Participants are randomly split into trained and untrained groups, and everyone uses identical computers for the same task.',
      why: 'Identical computers, the same task, random groups — only the training differs.' },
    { iv: 'syntax highlighting', dv: 'time to find the bug', confound: null,
      text: 'Researchers test whether syntax highlighting helps programmers find bugs faster. Every participant gets the same 50-line programs, shown with or without highlighting in a random order.',
      why: 'Same programs, random order — only the highlighting differs.' },
    { iv: 'keyboard type', dv: 'typing speed', confound: null,
      text: 'Researchers test whether people type faster on a physical keyboard than on a touchscreen. Participants are randomly assigned to one keyboard, and everyone copies the same passage.',
      why: 'Same passage, random groups — only the keyboard differs.' },
    { iv: 'number of checkout steps', dv: 'time to complete the purchase', confound: null,
      text: 'In a lab, researchers test whether a 3-step checkout is quicker than a 6-step one. Participants are randomly assigned to one version of the same test website, and everyone buys the same book.',
      why: 'Same website, same product, random groups — only the number of steps differs.' },
    { iv: 'input device', dv: 'time to click the targets', confound: null,
      text: 'Researchers test whether people click targets faster with a mouse than a touchpad. Every participant uses both devices, in a random order, to click the same 50 targets.',
      why: 'The same targets for both devices, and a random order, so only the device differs.' },
  ],

  // -------------------------------------------------------------------------
  // 2j. Within or between subjects. Pairs: the same study both ways.
  // -------------------------------------------------------------------------
  designs: [
    { cat: 'within',
      label: 'Every participant looks for options in a short menu and in a long menu, and the time each person takes to find an option in the two menus is compared.',
      ivs: [COMP_MENU], dv: COMP_FIND,
      others: [COMP_P] },
    { cat: 'within',
      label: 'Each participant does the same tapping task on a phone app with small buttons and with large buttons, and their tapping errors on the two versions are compared.',
      ivs: [COMP_BUTTON], dv: COMP_TAPERR,
      others: [COMP_P, { name: 'the phone', aliases: ['phone', 'smartphone', 'app'] }] },
    { cat: 'within',
      label: 'Every participant reads one passage on screen in a small font and a similar passage in a large font, and their reading speed for the two is compared.',
      ivs: [COMP_FONT], dv: COMP_READ,
      others: [COMP_P, { name: 'the passages', aliases: ['passage', 'passages', 'screen'] }] },
    { cat: 'within',
      label: 'Each programmer looks for bugs in some programs shown with syntax highlighting and some shown without it, and the time they take to find each bug is compared.',
      ivs: [COMP_HILITE], dv: COMP_BUGTIME,
      others: [{ name: 'the programmers', aliases: ['programmers', 'programmer', 'participants', 'people'] }] },
    { cat: 'within',
      label: 'Every student fixes some errors that come with clear error messages and some that come with vague ones, and the time they take to fix each kind is compared.',
      ivs: [COMP_ERRMSG], dv: COMP_FIXTIME,
      others: [{ name: 'the students', aliases: ['students', 'student', 'participants', 'people'] }] },
    { cat: 'within',
      label: 'Each participant copies a passage on a physical keyboard and a similar passage on a touchscreen keyboard, and their typing speeds on the two are compared.',
      ivs: [COMP_KEYB], dv: COMP_WPM,
      others: [COMP_P, { name: 'the passages', aliases: ['passage', 'passages', 'text'] }] },
    { cat: 'within',
      label: 'Every participant clicks targets that appear near the pointer and targets that appear far from it, and the time they take to click each kind is compared.',
      ivs: [COMP_DIST], dv: COMP_CLICK,
      others: [COMP_P, { name: 'the pointer', aliases: ['pointer', 'cursor'] }] },
    { cat: 'within',
      label: 'In a lab, each participant buys an item using a 3-step checkout and another item using a 6-step checkout, and the time they take to complete each purchase is compared.',
      ivs: [COMP_STEPS], dv: COMP_BUYTIME,
      others: [COMP_P, { name: 'the test website', aliases: ['website', 'test website', 'shop', 'site'] }] },
    { cat: 'within',
      label: 'Every participant clicks a set of targets once with a mouse and once with a touchpad, and the time they take with each device is compared.',
      ivs: [COMP_DEVICE], dv: COMP_TARGETS,
      others: [COMP_P] },
    { cat: 'within',
      label: 'Each programmer checks one piece of code alone and a similar piece with a partner, and the number of bugs they find each time is compared.',
      ivs: [COMP_PAIR], dv: COMP_BUGS,
      others: [{ name: 'the programmers', aliases: ['programmers', 'programmer', 'participants', 'people'] }, { name: 'the code', aliases: ['code', 'piece of code', 'program'] }] },

    { cat: 'between',
      label: 'Participants are randomly assigned to use either a short menu or a long menu, and the two groups\' times to find an option are compared.',
      ivs: [COMP_MENU], dv: COMP_FIND,
      others: [COMP_P] },
    { cat: 'between',
      label: 'One group does a tapping task on a phone app with small buttons, and a different group does it with large buttons. The two groups\' tapping errors are compared.',
      ivs: [COMP_BUTTON], dv: COMP_TAPERR,
      others: [{ name: 'the groups', aliases: ['groups', 'group', 'participants', 'people'] }, { name: 'the phone', aliases: ['phone', 'smartphone', 'app'] }] },
    { cat: 'between',
      label: 'Half the participants read a passage on screen in a small font and the other half read it in a large font. The reading speeds of the two groups are compared.',
      ivs: [COMP_FONT], dv: COMP_READ,
      others: [COMP_P, { name: 'the passage', aliases: ['passage', 'screen'] }] },
    { cat: 'between',
      label: 'One group of programmers looks for bugs in a program with syntax highlighting, and a different group looks at the same program without it. The two groups\' times to find the bugs are compared.',
      ivs: [COMP_HILITE], dv: COMP_BUGTIME,
      others: [{ name: 'the program', aliases: ['program', 'same program', 'source'] }] },
    { cat: 'between',
      label: 'Students are randomly assigned to fix a broken program that gives either a clear error message or a vague one, and the two groups\' times to fix it are compared.',
      ivs: [COMP_ERRMSG], dv: COMP_FIXTIME,
      others: [{ name: 'the broken program', aliases: ['broken program', 'program', 'code'] }] },
    { cat: 'between',
      label: 'One group copies a passage on a physical keyboard and a different group copies it on a touchscreen keyboard. The typing speeds of the two groups are compared.',
      ivs: [COMP_KEYB], dv: COMP_WPM,
      others: [{ name: 'the groups', aliases: ['groups', 'group', 'participants', 'people'] }, { name: 'the passage', aliases: ['passage', 'text'] }] },
    { cat: 'between',
      label: 'Participants are randomly assigned to click targets that appear near the pointer or far from it, and the two groups\' times to click the targets are compared.',
      ivs: [COMP_DIST], dv: COMP_CLICK,
      others: [COMP_P] },
    { cat: 'between',
      label: 'In a lab, one group buys an item using a 3-step checkout and a different group buys it using a 6-step checkout. The two groups\' times to complete the purchase are compared.',
      ivs: [COMP_STEPS], dv: COMP_BUYTIME,
      others: [{ name: 'the item', aliases: ['item', 'product', 'purchase item'] }] },
    { cat: 'between',
      label: 'Half the participants click a set of targets with a mouse and the other half with a touchpad, and the two groups\' times are compared.',
      ivs: [COMP_DEVICE], dv: COMP_TARGETS,
      others: [COMP_P] },
    { cat: 'between',
      label: 'Programmers are randomly assigned to check a piece of code either alone or with a partner, and the number of bugs found in each condition is compared.',
      ivs: [COMP_PAIR], dv: COMP_BUGS,
      others: [{ name: 'the code', aliases: ['code', 'piece of code', 'program'] }] },
  ],

  // -------------------------------------------------------------------------
  // 2f-2h. Cross-sectional, longitudinal, or both. All with people.
  // -------------------------------------------------------------------------
  crosslong: {
    single: [
      { cat: 'cross',
        label: 'In one session each, professional programmers and first-year computing students look for a bug in the same program, and the time each person takes to find it is compared between the two groups.',
        ivs: [{ name: 'experience (professional or first-year)', aliases: ['experience', 'professional', 'first-year', 'professional or first-year', 'expert', 'novice', 'expertise', 'group'] }],
        dv: COMP_BUGTIME,
        others: [{ name: 'the program', aliases: ['program', 'same program', 'code'] }] },
      { cat: 'cross',
        label: 'On one afternoon, people who use a spreadsheet program every day and people who have never used it do the same set task, and the time each group takes is compared.',
        ivs: [{ name: 'spreadsheet experience (daily user or never used)', aliases: ['spreadsheet experience', 'experience', 'daily user', 'never used', 'regular user', 'new user', 'familiarity', 'group'] }],
        dv: { name: 'task completion time', aliases: ['task completion time', 'task time', 'time taken', 'how long it takes', 'speed', 'completion time'] },
        others: [{ name: 'the afternoon', aliases: ['afternoon', 'one afternoon'] }] },
      { cat: 'cross',
        label: 'In the same week, first-, second- and third-year computing students each try out a website, and the number of usability problems each student spots is compared between the year groups.',
        ivs: [{ name: 'year group', aliases: ['year group', 'year of study', 'first second or third year', 'which year', 'group', 'students'] }],
        dv: { name: 'number of usability problems spotted', aliases: ['usability problems', 'problems spotted', 'problems', 'how many problems', 'issues found', 'score'] },
        others: [{ name: 'the website', aliases: ['website', 'site', 'web page'] }] },
      { cat: 'cross',
        label: 'On one testing day, touch-typists and people who type with two fingers copy the same passage, and the number of typing errors in each group is compared.',
        ivs: [{ name: 'typing method (touch-typing or two fingers)', aliases: ['typing method', 'method', 'touch-typing', 'touch typists', 'two fingers', 'two-finger', 'touch-typing or two fingers', 'group'] }],
        dv: { name: 'number of typing errors', aliases: ['typing errors', 'errors', 'mistakes', 'number of errors', 'how many errors', 'accuracy'] },
        others: [{ name: 'the passage', aliases: ['passage', 'text'] }] },

      { cat: 'long',
        label: 'The same students on an introductory programming course have the number of compiler errors in their weekly exercise counted every week for a term.',
        ivs: [{ name: 'time (week of the course)', aliases: ['week of the course', 'term', 'every week', 'course', ...COMP_TIME] }],
        dv: { name: 'number of compiler errors', aliases: ['compiler errors', 'errors', 'mistakes', 'number of errors', 'how many errors', 'bugs'] },
        others: [{ name: 'the students', aliases: ['students', 'learners', 'class'] }] },
      { cat: 'long',
        label: 'A group of new users of a note-taking app are timed doing the same routine task on their first day, after one week and after one month.',
        ivs: [{ name: 'time since starting', aliases: ['time since starting', 'first day', 'one week', 'one month', 'how long they have used it', 'experience', ...COMP_TIME] }],
        dv: { name: 'task completion time', aliases: ['task completion time', 'task time', 'time taken', 'how long it takes', 'speed', 'completion time'] },
        others: [{ name: 'the app', aliases: ['app', 'note-taking app', 'application'] }] },
      { cat: 'long',
        label: 'The same group of people learning a new keyboard layout have their typing speed measured every day for two weeks.',
        ivs: [{ name: 'time (day of learning)', aliases: ['day of learning', 'every day', 'two weeks', 'practice', 'learning', ...COMP_TIME] }],
        dv: COMP_WPM,
        others: [{ name: 'the keyboard layout', aliases: ['keyboard layout', 'layout', 'keyboard'] }] },
      { cat: 'long',
        label: 'The same new staff learning an office booking system have their requests for help counted each week for eight weeks.',
        ivs: [{ name: 'time (week since starting)', aliases: ['week since starting', 'eight weeks', 'each week', 'how long they have used it', ...COMP_TIME] }],
        dv: { name: 'number of help requests', aliases: ['help requests', 'requests for help', 'asking for help', 'how often they ask', 'help', 'questions'] },
        others: [{ name: 'the booking system', aliases: ['booking system', 'system', 'software'] }] },
    ],

    multi: [
      { cat: 'cross',
        label: 'In one session each, professional programmers and first-year students look for bugs in code shown with and without syntax highlighting, and the time each person takes to find the bugs is compared.',
        ivs: [
          { name: 'experience (professional or first-year)', aliases: ['experience', 'professional', 'first-year', 'professional or first-year', 'expert', 'novice', 'expertise'] },
          COMP_HILITE,
        ],
        dv: COMP_BUGTIME,
        others: [{ name: 'the session', aliases: ['session', 'one session'] }] },
      { cat: 'cross',
        label: 'On one afternoon, daily users of a drawing program and people who have never used it click targets with a mouse and with a touchpad, and their times are compared.',
        ivs: [
          { name: 'experience (daily user or never used)', aliases: ['experience', 'daily user', 'never used', 'regular user', 'new user', 'familiarity', 'daily user or never used'] },
          COMP_DEVICE,
        ],
        dv: COMP_TARGETS,
        others: [{ name: 'the afternoon', aliases: ['afternoon', 'one afternoon'] }] },
      { cat: 'cross',
        label: 'On one testing day, touch-typists and two-finger typists copy passages on a physical keyboard and on a touchscreen, and their typing speeds are compared.',
        ivs: [
          { name: 'typing method (touch-typing or two fingers)', aliases: ['typing method', 'method', 'touch-typing', 'touch typists', 'two fingers', 'two-finger', 'touch-typing or two fingers'] },
          COMP_KEYB,
        ],
        dv: COMP_WPM,
        others: [{ name: 'the testing day', aliases: ['testing day', 'one day'] }] },

      { cat: 'long',
        label: 'The same students on an introductory programming course have the compiler errors in a short exercise and a long exercise counted every week for a term.',
        ivs: [
          { name: 'time (week of the course)', aliases: ['week of the course', 'term', 'every week', 'course', ...COMP_TIME] },
          { name: 'exercise length (short or long)', aliases: ['exercise length', 'exercise', 'short or long', 'short exercise', 'long exercise', 'length', 'size of exercise'] },
        ],
        dv: { name: 'number of compiler errors', aliases: ['compiler errors', 'errors', 'mistakes', 'number of errors', 'how many errors', 'bugs'] },
        others: [{ name: 'the students', aliases: ['students', 'learners', 'class'] }] },
      { cat: 'long',
        label: 'A group of new users of a note-taking app are timed doing a simple task and a complex task on their first day, after one week and after one month.',
        ivs: [
          { name: 'time since starting', aliases: ['time since starting', 'first day', 'one week', 'one month', 'how long they have used it', ...COMP_TIME] },
          { name: 'task complexity (simple or complex)', aliases: ['task complexity', 'complexity', 'simple or complex', 'simple', 'complex', 'difficulty', 'type of task'] },
        ],
        dv: { name: 'task completion time', aliases: ['task completion time', 'task time', 'time taken', 'how long it takes', 'speed', 'completion time'] },
        others: [{ name: 'the app', aliases: ['app', 'note-taking app', 'application'] }] },
      { cat: 'long',
        label: 'The same group of people learning a new keyboard layout type real words and random letter strings, and their typing speed for each is measured every day for two weeks.',
        ivs: [
          { name: 'time (day of learning)', aliases: ['day of learning', 'every day', 'two weeks', 'practice', 'learning', ...COMP_TIME] },
          { name: 'type of text (words or random letters)', aliases: ['text', 'type of text', 'real words', 'random letters', 'letter strings', 'words or random letters', 'random'] },
        ],
        dv: COMP_WPM,
        others: [{ name: 'the keyboard layout', aliases: ['keyboard layout', 'layout', 'keyboard'] }] },
    ],

    panel: [
      { cat: 'both',
        label: 'On a programming course, one group of students does its lab exercises in pairs and another group works alone. The number of exercises each group completes is counted every week for six weeks.',
        ivs: [
          { name: 'working (alone or in pairs)', aliases: ['pair programming', 'pairs', 'alone', 'solo', 'alone or in pairs', 'working alone', 'working in pairs', 'partner', 'group'] },
          { name: 'time (week of the course)', aliases: ['week of the course', 'six weeks', 'every week', 'course', ...COMP_TIME] },
        ],
        dv: { name: 'number of exercises completed', aliases: ['exercises completed', 'exercises', 'how many exercises', 'completed', 'progress', 'score'] },
        others: [] },
      { cat: 'both',
        label: 'One group of new users learns an app from a video tutorial and another from a written guide. Both groups are timed doing the same task on their first day, after a week and after a month.',
        ivs: [
          { name: 'guide (video or written)', aliases: ['guide', 'tutorial', 'video or written', 'video', 'written guide', 'instructions', 'training', 'group'] },
          { name: 'time since starting', aliases: ['time since starting', 'first day', 'after a week', 'after a month', 'how long they have used it', ...COMP_TIME] },
        ],
        dv: { name: 'task completion time', aliases: ['task completion time', 'task time', 'time taken', 'how long it takes', 'speed', 'completion time'] },
        others: [] },
      { cat: 'both',
        label: 'One group of people learning to touch-type practises with a typing-tutor program and another group copies printed passages. Both groups\' typing speed is measured every week for eight weeks.',
        ivs: [
          { name: 'practice method (tutor program or printed passages)', aliases: ['practice method', 'method', 'tutor program', 'typing tutor', 'printed passages', 'program or passages', 'how they practise', 'group'] },
          { name: 'time (week of practice)', aliases: ['week of practice', 'eight weeks', 'every week', 'practice', ...COMP_TIME] },
        ],
        dv: COMP_WPM,
        others: [] },
      { cat: 'both',
        label: 'New users of an app are given either a version with short menus or one with long menus. Both groups\' time to find an option is measured on the first, third and tenth day of use.',
        ivs: [
          COMP_MENU,
          { name: 'time (day of use)', aliases: ['day of use', 'first day', 'third day', 'tenth day', 'use', ...COMP_TIME] },
        ],
        dv: COMP_FIND,
        others: [] },
      { cat: 'both',
        label: 'On a programming course, one group of students sees clear error messages and another sees the standard ones. The time both groups take to fix a set error is measured every two weeks for a term.',
        ivs: [
          COMP_ERRMSG,
          { name: 'time (week of the term)', aliases: ['week of the term', 'term', 'every two weeks', 'course', ...COMP_TIME] },
        ],
        dv: COMP_FIXTIME,
        others: [] },
      { cat: 'both',
        label: 'One group of new office staff is trained in keyboard shortcuts and another group is not. Both groups are timed on the same editing task every week for a month.',
        ivs: [
          { name: 'shortcut training (trained or not)', aliases: ['shortcut training', 'shortcuts', 'training', 'trained or not', 'trained', 'untrained', 'keyboard shortcuts', 'group'] },
          { name: 'time (week of the month)', aliases: ['week of the month', 'every week', 'a month', 'how long they have worked', ...COMP_TIME] },
        ],
        dv: { name: 'time to finish the editing task', aliases: ['editing time', 'time to finish', 'task time', 'time taken', 'how long it takes', 'speed', 'completion time'] },
        others: [] },
    ],
  },

  // -------------------------------------------------------------------------
  // Level 3. Factors for box notation.
  // -------------------------------------------------------------------------
  factors: [
    { name: 'Input size', levels: { 2: ['1,000 items', '1 million'], 3: ['100 items', '10,000 items', '1 million'], 4: ['10 items', '100 items', '1,000 items', '10,000 items'] } },
    { name: 'Cache size', levels: { 2: ['2 MB', '8 MB'], 3: ['2 MB', '4 MB', '8 MB'], 4: ['1 MB', '2 MB', '4 MB', '8 MB'] } },
    { name: 'Threads', levels: { 2: ['1 thread', '4 threads'], 3: ['1 thread', '2 threads', '4 threads'], 4: ['1 thread', '2 threads', '4 threads', '8 threads'] } },
    { name: 'Users at once', levels: { 2: ['10 users', '1,000 users'], 3: ['10 users', '100 users', '1,000 users'], 4: ['1 user', '10 users', '100 users', '1,000 users'] } },
    { name: 'Compression', levels: { 2: ['none', 'high'], 3: ['none', 'low', 'high'], 4: ['none', 'low', 'medium', 'high'] } },
    { name: 'Algorithm', levels: { 2: ['linear search', 'binary search'], 3: ['insertion sort', 'merge sort', 'quicksort'] } },
    { name: 'Input order', levels: { 2: ['sorted', 'unsorted'], 3: ['sorted', 'random', 'reversed'] } },
    { name: 'Menu length', for: COMP_CS, levels: { 2: ['5 items', '20 items'], 3: ['5 items', '10 items', '20 items'], 4: ['5 items', '10 items', '15 items', '20 items'] } },
    { name: 'Button size', for: COMP_CS, levels: { 2: ['small', 'large'], 3: ['small', 'medium', 'large'], 4: ['4 mm', '6 mm', '8 mm', '10 mm'] } },
    { name: 'Font size', for: COMP_CS, levels: { 2: ['10 pt', '14 pt'], 3: ['8 pt', '12 pt', '16 pt'], 4: ['8 pt', '10 pt', '12 pt', '14 pt'] } },
    { name: 'Input device', for: COMP_CS, levels: { 2: ['mouse', 'touchpad'], 3: ['mouse', 'touchpad', 'touchscreen'] } },
    { name: 'Keyboard', for: COMP_CS, levels: { 2: ['physical', 'touchscreen'] } },
    { name: 'Error message', for: COMP_CS, levels: { 2: ['vague', 'clear'] } },
    { name: 'Syntax highlighting', for: COMP_CS, levels: { 2: ['off', 'on'] } },
    { name: 'Checkout steps', for: COMP_CS, levels: { 2: ['3 steps', '6 steps'], 3: ['2 steps', '4 steps', '6 steps'], 4: ['2 steps', '3 steps', '4 steps', '5 steps'] } },
    { name: 'Programming', for: COMP_CS, levels: { 2: ['alone', 'in pairs'] } },
  ],
};
