// ---------------------------------------------------------------------------
// The Earth & environment pool: physical geography (its only pool), earth
// sciences and environmental science (main pool), and a neighbour for
// ecology, agriculture and human geography. See pools/README.md.
//
// Studies here are done on samples, sites, rivers, rocks, soils, plots and
// weather stations, never on people. Cross-sectional = many sites measured
// once; longitudinal = the same site monitored over time. Roughly a third of
// the items are shared; the rest carry `for` so that earth sciences gets
// rocks, minerals, crystals and weathering, physical geography gets rivers,
// slopes, coasts, weather and glaciers, and environmental science gets soil,
// water quality, infiltration and noise. Every mechanism is textbook and
// undisputed, and relations are stated only where they hold ("in summer, in
// a stratified lake", "other things being equal").
// ---------------------------------------------------------------------------
const EARTH_ES = ['earth-sciences'];
const EARTH_PG = ['physical-geography'];
const EARTH_ENV = ['environmental'];
const EARTH_PG_ENV = ['physical-geography', 'environmental'];
const EARTH_ES_PG = ['earth-sciences', 'physical-geography'];
const EARTH_SOIL = ['environmental', 'agriculture'];
const EARTH_ECO = ['environmental', 'ecology'];

const EARTH_CONT = 'It can take any value on a scale, including every value in between — ';
const EARTH_DISC = 'It only comes in separate values, with nothing in between — ';

const EARTH_NOM = 'Categorical: distinct outcomes with no order. ';
const EARTH_ORD = 'Ordinal: the outcomes are ranked, but the difference between steps is arbitrary. ';
const EARTH_INT = 'Interval: ranked, with a constant difference between steps, but no natural zero — so values aren\'t "twice as much". ';
const EARTH_RAT = 'Ratio: ranked, constant steps AND a natural zero, so "twice as much" makes sense. ';

const EARTH_TIME = ['time', 'over time', 'week', 'weeks', 'month', 'months', 'year', 'years', 'day', 'days', 'when it was measured', 'time point', 'session', 'before and after'];

POOLS.earth = {
  // -------------------------------------------------------------------------
  // 1a. Variable or not?
  // -------------------------------------------------------------------------
  sortItems: [
    // --- variables: shared ---
    { label: 'rainfall', variable: true,
      why: 'Some days and places get more rain than others, and a rain gauge measures it in millimetres.' },
    { label: 'air temperature', variable: true,
      why: 'The air can be warmer or colder, and a thermometer measures it in degrees.' },
    { label: 'wind speed', variable: true,
      why: 'The wind can blow harder or more gently, and an anemometer measures its speed in metres per second.' },
    { label: 'river discharge', variable: true,
      why: 'A river carries more or less water at different times, and discharge is measured in cubic metres per second.' },
    { label: 'soil moisture content', variable: true,
      why: 'Soil can be wetter or drier, and the water in it can be measured as a percentage of its mass.' },
    { label: 'slope angle', variable: true,
      why: 'Slopes can be steeper or gentler, and a clinometer measures the angle in degrees.' },
    { label: 'altitude', variable: true,
      why: 'Places sit at different heights above sea level, measured in metres.' },
    { label: 'pebble size', variable: true,
      why: 'Pebbles come in different sizes, and each one can be measured along its longest axis in millimetres.' },
    { label: 'soil pH', variable: true,
      why: 'Some soils are more acidic than others, and pH can be measured with a meter or indicator kit.' },
    { label: 'infiltration rate', variable: true,
      why: 'Water soaks into some ground faster than others, and the rate can be measured in millimetres per hour.' },
    { label: 'relative humidity', variable: true,
      why: 'The air can hold more or less water vapour, and a hygrometer measures humidity as a percentage.' },

    // --- variables: earth sciences ---
    { label: 'crystal size in an igneous rock', variable: true, for: EARTH_ES,
      why: 'Some igneous rocks have large crystals and others tiny ones, and crystals can be measured under a microscope.' },
    { label: 'porosity of a rock', variable: true, for: EARTH_ES,
      why: 'Some rocks have more pore space than others, and porosity is measured as a percentage of the rock\'s volume.' },
    { label: 'rate of weathering', variable: true, for: EARTH_ES,
      why: 'Some rocks break down faster than others, and the loss can be measured, for example as millimetres of surface worn away per year.' },
    { label: 'thickness of a rock layer', variable: true, for: EARTH_ES,
      why: 'Rock layers can be thicker or thinner, and a tape measure gives their thickness in metres.' },
    { label: 'dip angle of rock layers', variable: true, for: EARTH_ES,
      why: 'Rock layers can be tilted by different amounts, and a compass-clinometer measures the angle.' },
    { label: 'grain size of a sediment', variable: true, for: EARTH_ES,
      why: 'Sediments range from fine clay to coarse gravel, and grain size can be measured by sieving.' },
    { label: 'permeability of a rock', variable: true, for: EARTH_ES,
      why: 'Water passes through some rocks more easily than others, and the rate it flows through can be measured.' },
    { label: 'mass of a rock sample', variable: true, for: EARTH_ES,
      why: 'Rock samples have different masses, and a balance measures each in grams.' },

    // --- variables: physical geography ---
    { label: 'river velocity', variable: true, for: EARTH_PG,
      why: 'Water flows faster in some stretches than others, and a flow meter measures its speed in metres per second.' },
    { label: 'channel width', variable: true, for: EARTH_PG,
      why: 'Rivers are wider in some places than others, and the width can be measured with a tape from bank to bank.' },
    { label: 'wave height', variable: true, for: EARTH_PG,
      why: 'Waves can be bigger or smaller, and their height is measured in metres from trough to crest.' },
    { label: 'beach gradient', variable: true, for: EARTH_PG,
      why: 'Some beaches slope more steeply than others, and the angle can be measured with a clinometer.' },
    { label: 'glacier flow speed', variable: true, for: EARTH_PG,
      why: 'Glaciers move at different speeds, and the movement of a marker on the ice can be measured in metres per year.' },
    { label: 'snow depth', variable: true, for: EARTH_PG,
      why: 'Snow can lie deeper or shallower, and a ruler pushed into it measures the depth in centimetres.' },
    { label: 'cloud cover', variable: true, for: EARTH_PG,
      why: 'The sky can be clear, partly cloudy or completely covered, and cloud cover is recorded in eighths of the sky (oktas).' },
    { label: 'air pressure', variable: true, for: EARTH_PG,
      why: 'Air pressure rises and falls with the weather, and a barometer measures it in millibars.' },

    // --- variables: environmental science ---
    { label: 'nitrate concentration in river water', variable: true, for: EARTH_ENV,
      why: 'Water samples contain more or less nitrate, and it is measured in milligrams per litre.' },
    { label: 'dissolved oxygen', variable: true, for: EARTH_ENV,
      why: 'Some water holds more oxygen than other water, and a probe measures it in milligrams per litre.' },
    { label: 'turbidity of water', variable: true, for: EARTH_ENV,
      why: 'Water can be clearer or cloudier, and a turbidity meter measures how much the suspended particles scatter light.' },
    { label: 'noise level', variable: true, for: EARTH_ENV,
      why: 'Some places are louder than others, and a sound level meter measures noise in decibels.' },
    { label: 'soil organic matter content', variable: true, for: EARTH_SOIL,
      why: 'Some soils contain more organic matter than others, and it can be measured as the percentage of mass lost when the soil is burnt.' },
    { label: 'soil compaction', variable: true, for: EARTH_SOIL,
      why: 'Soil can be packed more or less tightly, and a penetrometer measures how hard it is to push into.' },
    { label: 'leaf litter depth', variable: true, for: EARTH_ECO,
      why: 'Fallen leaves can lie deeper in some places than others, and the depth can be measured with a ruler.' },

    // --- not variables: one particular thing (shared) ---
    { label: 'the River Severn', variable: false,
      why: 'The Severn is one particular river. (How much water a river carries would be a variable.)' },
    { label: 'Ben Nevis', variable: false,
      why: 'Ben Nevis is one particular mountain. (The height of a mountain would be a variable.)' },
    { label: 'a rain gauge', variable: false,
      why: 'A rain gauge is a piece of equipment, not a measurement. (The rainfall it collects would be a variable.)' },
    { label: 'the Atlantic Ocean', variable: false,
      why: 'The Atlantic is one particular ocean. (The temperature of sea water would be a variable.)' },

    // --- not variables: earth sciences ---
    { label: 'granite', variable: false, for: EARTH_ES,
      why: 'Granite is one particular kind of rock. (The size of the crystals in it would be a variable.)' },
    { label: 'the Giant\'s Causeway', variable: false, for: EARTH_ES,
      why: 'The Giant\'s Causeway is one particular place. (The width of basalt columns would be a variable.)' },
    { label: 'James Hutton', variable: false, for: EARTH_ES,
      why: 'James Hutton is one particular person. (The thickness of a rock layer would be a variable.)' },
    { label: 'a hand lens', variable: false, for: EARTH_ES,
      why: 'A hand lens is a piece of equipment, not a measurement. (The size of the grains you see through it would be a variable.)' },

    // --- not variables: physical geography ---
    { label: 'the Jurassic Coast', variable: false, for: EARTH_PG,
      why: 'The Jurassic Coast is one particular stretch of coast. (How fast a cliff retreats would be a variable.)' },
    { label: 'a clinometer', variable: false, for: EARTH_PG,
      why: 'A clinometer is an instrument, not a measurement. (The slope angle it reads would be a variable.)' },
    { label: 'the Rhône Glacier', variable: false, for: EARTH_PG,
      why: 'The Rhône Glacier is one particular glacier. (How fast a glacier flows would be a variable.)' },
    { label: 'the Gulf Stream', variable: false, for: EARTH_PG,
      why: 'The Gulf Stream is one particular ocean current. (The speed of a current would be a variable.)' },

    // --- not variables: environmental science ---
    { label: 'a sound level meter', variable: false, for: EARTH_ENV,
      why: 'A sound level meter is an instrument, not a measurement. (The noise level it reads would be a variable.)' },
    { label: 'Lough Neagh', variable: false, for: EARTH_ENV,
      why: 'Lough Neagh is one particular lake. (The oxygen content of lake water would be a variable.)' },
    { label: 'a soil auger', variable: false, for: EARTH_ENV,
      why: 'A soil auger is a tool for taking soil samples, not a measurement. (The moisture in a sample would be a variable.)' },

    // --- not variables: measurable, but only one possible value ---
    { label: 'the Mohs hardness of diamond', variable: false,
      why: 'Diamond is 10 on the Mohs scale every time — the scale is defined that way. Only one possible value, so it\'s a constant.' },
    { label: 'the number of hydrogen atoms in a water molecule', variable: false,
      why: 'It\'s always 2 — with a different number it wouldn\'t be water. Only one possible value, so it\'s a constant.' },
    { label: 'the number of degrees in a right angle', variable: false,
      why: 'A right angle is always 90°, so it can\'t vary. (The angle of a slope, which can be anything, would be a variable.)' },
  ],

  // -------------------------------------------------------------------------
  // 1b-1d, 2b, 2c. Relations.
  // -------------------------------------------------------------------------
  relations: [
    // --- shared ---
    { id: 'earth-rain-discharge', iv: 'rainfall intensity', dv: 'river discharge', ivNP: 'the rainfall intensity', dvNP: 'the river discharge',
      hyp: ['rainfall', 'river discharge'], ivAxis: 'Rainfall', dvAxis: 'Discharge', dir: 'up',
      says: ['Heavier rain over a catchment raises the discharge of the river that drains it.',
             'River discharge goes up as the rainfall over its catchment gets heavier.'],
      why: 'The rain falls first and runs into the river, so the rainfall is the changer. A river carrying more water can\'t make it rain harder.' },
    { id: 'earth-altitude-temp', iv: 'altitude', dv: 'air temperature', ivNP: 'the altitude', dvNP: 'the air temperature',
      hyp: ['altitude', 'air temperature'], ivAxis: 'Altitude', dvAxis: 'Air temperature', dir: 'down',
      says: ['On the same mountain, the air is generally colder higher up.',
             'Air temperature generally falls as altitude increases.'],
      why: 'The height of a place is fixed by the landscape, and air that rises up a mountain expands and cools, so higher places are generally colder. Cold air can\'t make a mountain taller.' },
    { id: 'earth-altitude-pressure', iv: 'altitude', dv: 'air pressure', ivNP: 'the altitude', dvNP: 'the air pressure',
      hyp: ['altitude', 'air pressure'], ivAxis: 'Altitude', dvAxis: 'Air pressure', dir: 'down',
      says: ['The higher you go, the lower the air pressure.',
             'Air pressure falls as altitude increases, because there is less air above pressing down.'],
      why: 'The altitude decides how much air is above you, so it is the changer. Changing the pressure on a barometer doesn\'t move it up a hill.' },
    { id: 'earth-veg-erosion', iv: 'vegetation cover', dv: 'soil erosion', ivNP: 'the vegetation cover', dvNP: 'the amount of soil erosion',
      hyp: ['vegetation cover', 'soil erosion'], ivAxis: 'Vegetation cover', dvAxis: 'Soil erosion', dir: 'down',
      says: ['Soil on a slope is eroded less when it has more plant cover.',
             'The amount of soil erosion goes down as vegetation cover goes up.'],
      why: 'Plants shield the soil from raindrops and bind it with their roots, so the cover is the changer. Losing soil can\'t plant more plants.' },
    { id: 'earth-compaction-infil', iv: 'soil compaction', dv: 'infiltration rate', ivNP: 'the soil compaction', dvNP: 'the infiltration rate',
      hyp: ['compaction', 'infiltration rate'], ivAxis: 'Compaction', dvAxis: 'Infiltration', dir: 'down',
      says: ['Water soaks more slowly into soil that has been packed down.',
             'The infiltration rate goes down as the soil becomes more compacted.'],
      why: 'Compaction squeezes out the pore spaces water would soak into, so compaction is the changer. Slow soaking doesn\'t pack the soil down.' },
    { id: 'earth-temp-evap', iv: 'air temperature', dv: 'evaporation rate', ivNP: 'the air temperature', dvNP: 'the evaporation rate',
      hyp: ['temperature', 'evaporation'], ivAxis: 'Temperature', dvAxis: 'Evaporation', dir: 'up',
      says: ['Other things being equal, water evaporates faster from an open pan on warmer days.',
             'The evaporation rate goes up as the air temperature rises.'],
      why: 'Warmth gives water molecules the energy to escape, so the temperature is the changer. Water evaporating from a pan doesn\'t warm the day.' },
    { id: 'earth-slope-runoff', iv: 'slope angle', dv: 'speed of surface runoff', ivNP: 'the slope angle', dvNP: 'the speed of surface runoff',
      hyp: ['slope angle', 'runoff speed'], ivAxis: 'Slope angle', dvAxis: 'Runoff speed', dir: 'up',
      says: ['Rainwater runs off steeper slopes more quickly.',
             'The speed of surface runoff goes up as the slope gets steeper.'],
      why: 'Gravity pulls water downhill harder on a steep slope, so the angle is the changer. Fast-running water can\'t tilt the hillside.' },
    { id: 'earth-cloud-cooling', iv: 'cloud cover', dv: 'night-time cooling', ivNP: 'the cloud cover', dvNP: 'the amount of night-time cooling',
      hyp: ['cloud cover', 'night cooling'], ivAxis: 'Cloud cover', dvAxis: 'Night cooling', dir: 'down',
      says: ['On cloudy nights, the air near the ground cools less than on clear nights.',
             'The amount the air cools overnight goes down as cloud cover goes up.'],
      why: 'Clouds absorb heat rising from the ground and send some back down, so the cloud is the changer. Cool air at ground level can\'t clear the sky.' },
    { id: 'earth-acid-limestone', iv: 'acidity of water', dv: 'rate limestone dissolves', ivNP: 'the acidity of the water', dvNP: 'the rate limestone dissolves',
      hyp: ['acidity', 'limestone dissolving'], ivAxis: 'Acidity', dvAxis: 'Dissolving rate', dir: 'up',
      says: ['Limestone dissolves faster in more acidic water.',
             'The rate limestone dissolves goes up as the water becomes more acidic.'],
      why: 'Acid reacts with the calcium carbonate in limestone, so the acidity is the changer. The rock dissolving doesn\'t make the water more acidic — it does the opposite.' },

    // --- earth sciences ---
    { id: 'earth-magma-crystal', for: EARTH_ES, iv: 'cooling rate of magma', dv: 'crystal size', ivNP: 'the cooling rate of the magma', dvNP: 'the crystal size',
      hyp: ['cooling rate', 'crystal size'], ivAxis: 'Cooling rate', dvAxis: 'Crystal size', dir: 'down',
      says: ['Magma that cools quickly forms rock with smaller crystals.',
             'Crystal size goes down as the cooling rate of the magma goes up.'],
      why: 'Slow cooling gives crystals more time to grow before the melt sets, so the cooling rate is the changer. Crystal size can\'t change how fast the magma lost heat.' },
    { id: 'earth-freezethaw-fragments', for: EARTH_ES, iv: 'number of freeze–thaw cycles', dv: 'mass of rock broken off', ivNP: 'the number of freeze–thaw cycles', dvNP: 'the mass of rock broken off',
      hyp: ['freeze–thaw cycles', 'rock broken off'], ivAxis: 'Freeze–thaw', dvAxis: 'Rock broken off', dir: 'up',
      says: ['A water-soaked porous rock loses more fragments the more freeze–thaw cycles it goes through.',
             'The mass of rock broken off goes up with the number of freeze–thaw cycles.'],
      why: 'Each freeze makes water in the cracks expand and prise the rock apart, so the cycles are the changer. Broken fragments can\'t make the weather freeze.' },
    { id: 'earth-porosity-water', for: EARTH_ES, iv: 'porosity', dv: 'water absorbed', ivNP: 'the porosity of the rock', dvNP: 'the amount of water absorbed',
      hyp: ['porosity', 'water absorbed'], ivAxis: 'Porosity', dvAxis: 'Water absorbed', dir: 'up',
      says: ['A more porous rock soaks up more water.',
             'The amount of water a rock absorbs goes up with its porosity.'],
      why: 'The pore spaces are already in the rock, and water can only fill the space there is. Soaking a rock doesn\'t create the pores.' },
    { id: 'earth-transport-roundness', for: EARTH_ES, iv: 'distance transported', dv: 'pebble roundness', ivNP: 'the distance a pebble has been transported', dvNP: 'the roundness of the pebble',
      hyp: ['distance transported', 'roundness'], ivAxis: 'Distance moved', dvAxis: 'Roundness', dir: 'up',
      says: ['Pebbles become rounder the further they are carried by a river.',
             'Pebble roundness goes up with the distance a pebble has been transported.'],
      why: 'Knocking against other stones grinds off the corners as the pebble travels, so the distance is the changer. Being round doesn\'t send a pebble further.' },
    { id: 'earth-depth-rocktemp', for: EARTH_ES, iv: 'depth below the surface', dv: 'rock temperature', ivNP: 'the depth below the surface', dvNP: 'the temperature of the rock',
      hyp: ['depth', 'rock temperature'], ivAxis: 'Depth', dvAxis: 'Rock temp', dir: 'up',
      says: ['Below the top few metres, rock gets hotter the deeper you go into the crust.',
             'Rock temperature goes up with depth below the surface.'],
      why: 'Heat flows up from the Earth\'s interior, so deeper rock is closer to the source. Heating a rock doesn\'t make it deeper.' },
    { id: 'earth-hardness-abrasion', for: EARTH_ES, iv: 'mineral hardness', dv: 'mass lost by abrasion', ivNP: 'the hardness of the mineral', dvNP: 'the mass lost by abrasion',
      hyp: ['hardness', 'mass lost'], ivAxis: 'Hardness', dvAxis: 'Mass lost', dir: 'down',
      says: ['Harder minerals lose less mass when tumbled with grit for the same time.',
             'The mass lost by abrasion goes down as mineral hardness goes up.'],
      why: 'Hardness is a property the mineral already has, and it resists scratching. Wearing a sample down doesn\'t change how hard it is.' },
    { id: 'earth-grain-settling', for: EARTH_ES, iv: 'grain size', dv: 'settling speed', ivNP: 'the grain size', dvNP: 'the settling speed',
      hyp: ['grain size', 'settling speed'], ivAxis: 'Grain size', dvAxis: 'Settling speed', dir: 'up',
      says: ['In still water, bigger grains of the same mineral sink to the bottom faster.',
             'The settling speed of a grain goes up with its size.'],
      why: 'A bigger grain has more weight for its drag, so the size is the changer. Sinking faster can\'t make a grain bigger.' },

    // --- physical geography ---
    { id: 'earth-gradient-velocity', for: EARTH_PG, iv: 'river gradient', dv: 'river velocity', ivNP: 'the river gradient', dvNP: 'the river velocity',
      hyp: ['gradient', 'velocity'], ivAxis: 'Gradient', dvAxis: 'Velocity', dir: 'up',
      says: ['Other things being equal, water flows faster down a steeper channel.',
             'River velocity goes up as the gradient of the channel increases.'],
      why: 'Gravity pulls the water harder down a steeper bed, so the gradient is the changer. Fast water can\'t tilt the valley floor.' },
    { id: 'earth-downstream-pebble', for: EARTH_PG, iv: 'distance downstream', dv: 'pebble size', ivNP: 'the distance downstream', dvNP: 'the average pebble size',
      hyp: ['distance downstream', 'pebble size'], ivAxis: 'Downstream', dvAxis: 'Pebble size', dir: 'down',
      says: ['Pebbles on a river bed are generally smaller further downstream.',
             'Average pebble size goes down with distance downstream, as the pebbles are worn by abrasion.'],
      why: 'The further a pebble travels, the longer it is knocked and worn, so the distance is the changer. Small pebbles can\'t move a site further down the river.' },
    { id: 'earth-downstream-width', for: EARTH_PG, iv: 'distance downstream', dv: 'channel width', ivNP: 'the distance downstream', dvNP: 'the channel width',
      hyp: ['distance downstream', 'channel width'], ivAxis: 'Downstream', dvAxis: 'Channel width', dir: 'up',
      says: ['Rivers generally get wider further downstream.',
             'Channel width goes up with distance downstream, as tributaries add more water.'],
      why: 'Further downstream more tributaries have joined and more water needs room, so the distance is the changer. Widening a channel doesn\'t move it downstream.' },
    { id: 'earth-wind-wave', for: EARTH_PG, iv: 'wind speed', dv: 'wave height', ivNP: 'the wind speed', dvNP: 'the wave height',
      hyp: ['wind speed', 'wave height'], ivAxis: 'Wind speed', dvAxis: 'Wave height', dir: 'up',
      says: ['Stronger winds blowing over the same stretch of open water make bigger waves.',
             'Wave height goes up as the wind speed increases.'],
      why: 'The wind passes energy to the water surface, so the wind is the changer. Big waves can\'t make the wind blow harder.' },
    { id: 'earth-slope-soildepth', for: EARTH_PG, iv: 'slope angle', dv: 'soil depth', ivNP: 'the slope angle', dvNP: 'the soil depth',
      hyp: ['slope angle', 'soil depth'], ivAxis: 'Slope angle', dvAxis: 'Soil depth', dir: 'down',
      says: ['Soils are generally thinner on steeper slopes.',
             'Soil depth goes down as the slope angle goes up, because soil moves downhill faster than it forms.'],
      why: 'The steepness of the slope controls how fast soil creeps and washes away, so the angle is the changer. Thin soil can\'t steepen a hillside.' },
    { id: 'earth-coast-range', for: EARTH_PG, iv: 'distance from the coast', dv: 'annual temperature range', ivNP: 'the distance from the coast', dvNP: 'the annual temperature range',
      hyp: ['distance inland', 'temperature range'], ivAxis: 'Distance inland', dvAxis: 'Temp range', dir: 'up',
      says: ['Places further from the sea generally have a bigger difference between summer and winter temperatures.',
             'The annual temperature range goes up with distance from the coast.'],
      why: 'The sea warms and cools slowly and evens out the temperature of nearby land, so the distance from it is the changer. A big temperature range can\'t move a town inland.' },
    { id: 'earth-discharge-sediment', for: EARTH_PG, iv: 'river discharge', dv: 'suspended sediment load', ivNP: 'the river discharge', dvNP: 'the suspended sediment load',
      hyp: ['discharge', 'sediment load'], ivAxis: 'Discharge', dvAxis: 'Sediment load', dir: 'up',
      says: ['Rivers generally carry more suspended sediment when their discharge is higher.',
             'The suspended sediment load goes up as discharge increases.'],
      why: 'More, faster water has more energy to pick up and carry sediment, so discharge is the changer. Mud in the water can\'t add water to the river.' },
    { id: 'earth-temp-melt', for: EARTH_PG, iv: 'air temperature', dv: 'glacier melt rate', ivNP: 'the air temperature', dvNP: 'the glacier melt rate',
      hyp: ['air temperature', 'melt rate'], ivAxis: 'Temperature', dvAxis: 'Melt rate', dir: 'up',
      says: ['More ice melts from a glacier\'s surface on warmer days.',
             'The glacier melt rate goes up as the air temperature rises.'],
      why: 'Warm air supplies the heat that melts the ice, so the temperature is the changer. Melting ice cools the air rather than warming it.' },
    { id: 'earth-depth-laketemp', for: EARTH_PG_ENV, iv: 'depth', dv: 'water temperature', ivNP: 'the depth', dvNP: 'the water temperature',
      hyp: ['depth', 'water temperature'], ivAxis: 'Depth', dvAxis: 'Water temp', dir: 'down',
      says: ['In summer, in a stratified lake, the water is colder the deeper you go.',
             'In a stratified lake in summer, water temperature goes down with depth.'],
      why: 'The Sun warms the surface, and the warm, lighter water stays on top, so depth decides how much of that warmth reaches the water. Cooling the water doesn\'t make the lake deeper.' },

    // --- environmental science ---
    { id: 'earth-watertemp-oxygen', for: EARTH_ENV, iv: 'water temperature', dv: 'dissolved oxygen', ivNP: 'the water temperature', dvNP: 'the dissolved oxygen',
      hyp: ['water temperature', 'dissolved oxygen'], ivAxis: 'Water temp', dvAxis: 'Oxygen', dir: 'down',
      says: ['Colder water can hold more dissolved oxygen.',
             'The amount of dissolved oxygen water can hold goes down as its temperature rises.'],
      why: 'Gases are less soluble in warmer water, so the temperature is the changer. Adding oxygen to water doesn\'t cool it.' },
    { id: 'earth-road-noise', for: EARTH_ENV, iv: 'distance from the road', dv: 'noise level', ivNP: 'the distance from the road', dvNP: 'the noise level',
      hyp: ['distance from road', 'noise level'], ivAxis: 'Distance', dvAxis: 'Noise level', dir: 'down',
      says: ['Traffic noise is quieter the further you stand from the road.',
             'The noise level goes down with distance from a busy road.'],
      why: 'Sound spreads out and weakens as it travels, so distance is the changer. A quieter reading can\'t move the meter away from the road.' },
    { id: 'earth-organic-waterhold', for: EARTH_SOIL, iv: 'organic matter content', dv: 'water-holding capacity', ivNP: 'the organic matter content', dvNP: 'the water-holding capacity',
      hyp: ['organic matter', 'water held'], ivAxis: 'Organic matter', dvAxis: 'Water held', dir: 'up',
      says: ['Soil with more organic matter holds more water.',
             'A soil\'s water-holding capacity goes up with its organic matter content.'],
      why: 'Organic matter soaks up water like a sponge, so it is the changer. Wetting a soil doesn\'t add organic matter to it.' },
    { id: 'earth-particle-drainage', for: EARTH_SOIL, iv: 'soil particle size', dv: 'drainage rate', ivNP: 'the soil particle size', dvNP: 'the drainage rate',
      hyp: ['particle size', 'drainage rate'], ivAxis: 'Particle size', dvAxis: 'Drainage rate', dir: 'up',
      says: ['Sandy soil, with bigger particles, drains faster than clay soil.',
             'The drainage rate goes up with the size of the soil particles.'],
      why: 'Bigger particles leave bigger gaps for water to flow through, so particle size is the changer. Water draining through can\'t make the particles bigger.' },
    { id: 'earth-litter-moisture', for: EARTH_ECO, iv: 'leaf litter depth', dv: 'soil moisture', ivNP: 'the depth of leaf litter', dvNP: 'the soil moisture',
      hyp: ['leaf litter', 'soil moisture'], ivAxis: 'Leaf litter', dvAxis: 'Soil moisture', dir: 'up',
      says: ['Other things being equal, soil under a thicker layer of leaf litter stays moister.',
             'Soil moisture goes up with the depth of leaf litter covering it, as the litter slows evaporation.'],
      why: 'The litter blankets the soil and slows water evaporating from it, so the litter is the changer. Damp soil doesn\'t make leaves fall.' },
    { id: 'earth-canopy-temp', for: EARTH_ECO, iv: 'tree canopy cover', dv: 'air temperature', ivNP: 'the tree canopy cover', dvNP: 'the air temperature near the ground',
      hyp: ['canopy cover', 'air temperature'], ivAxis: 'Canopy cover', dvAxis: 'Air temperature', dir: 'down',
      says: ['On a sunny summer afternoon, the air under a denser tree canopy is cooler.',
             'Air temperature near the ground goes down as canopy cover goes up, on a sunny afternoon.'],
      why: 'The leaves block direct sunlight from reaching the ground, so the canopy is the changer. Cooler air can\'t grow more leaves overhead.' },
    { id: 'earth-rain-soilmoisture', for: EARTH_ENV, iv: 'rainfall', dv: 'soil moisture', ivNP: 'the rainfall', dvNP: 'the soil moisture',
      hyp: ['rainfall', 'soil moisture'], ivAxis: 'Rainfall', dvAxis: 'Soil moisture', dir: 'up',
      says: ['The more rain has fallen, the wetter the soil.',
             'Soil moisture goes up with the amount of rain that has fallen.'],
      why: 'Rain soaks into the soil, so the rainfall is the changer. Wet soil can\'t make it rain.' },
  ],

  // -------------------------------------------------------------------------
  // 2a. Validity and reliability.
  // -------------------------------------------------------------------------
  validity: [
    // valid and reliable
    { valid: true, reliable: true,
      text: 'To measure daily rainfall, researchers use a standard rain gauge set in open ground and read it at 9 am every day. Two people reading the same gauge get the same value.',
      whyValid: 'a rain gauge collects the rain that falls and measures it directly.',
      whyReliable: 'two people reading it get the same value.' },
    { valid: true, reliable: true, for: EARTH_PG,
      text: 'To measure river velocity, a researcher holds a calibrated flow meter at the same point and depth in the channel. Three readings taken a minute apart agree closely.',
      whyValid: 'a flow meter measures the speed of the water directly.',
      whyReliable: 'repeated readings agree closely.' },
    { valid: true, reliable: true, for: EARTH_PG,
      text: 'To measure slope angle, researchers sight a clinometer between two ranging poles 5 m apart, marked at the same height. Repeating the reading gives the same angle to within a degree.',
      whyValid: 'a clinometer sighted between two poles measures the angle of the ground between them.',
      whyReliable: 'the repeat gives the same angle to within a degree.' },
    { valid: true, reliable: true, for: EARTH_ES,
      text: 'To measure crystal size, a geologist measures 50 crystals in a thin section with a calibrated microscope scale. Measuring the same 50 crystals again gives almost the same average.',
      whyValid: 'a calibrated scale under the microscope measures crystal length directly.',
      whyReliable: 'measuring again gives almost the same average.' },
    { valid: true, reliable: true, for: EARTH_ENV,
      text: 'To measure dissolved oxygen in a stream, a researcher uses a calibrated oxygen probe held at the same point. Repeated readings agree to 0.1 mg per litre.',
      whyValid: 'an oxygen probe measures the dissolved oxygen directly.',
      whyReliable: 'repeated readings agree closely.' },

    // reliable, not valid
    { valid: false, reliable: true,
      text: 'To measure river discharge, researchers measure only the width of the channel with a tape. The tape gives the same width every time.',
      whyValid: 'discharge depends on depth and velocity as well as width — a wide, shallow, slow river can carry less water than a narrow, deep, fast one.',
      whyReliable: 'measuring the width again gives the same answer. Consistent, but consistently measuring the wrong thing.' },
    { valid: false, reliable: true, for: EARTH_ES,
      text: 'To measure how hard a mineral is, a geologist records its colour. Everyone who looks at it records the same colour.',
      whyValid: 'colour doesn\'t tell you hardness — the same mineral can come in different colours, and different minerals share a colour.',
      whyReliable: 'everyone records the same colour.' },
    { valid: false, reliable: true, for: EARTH_PG,
      text: 'To measure how strongly the wind is blowing, researchers read the direction a wind vane points. The vane points the same way whenever it is read in the same minute.',
      whyValid: 'a wind vane shows direction, not speed — a light breeze and a gale can come from the same direction.',
      whyReliable: 'readings in the same minute agree.' },
    { valid: false, reliable: true, for: EARTH_PG,
      text: 'To measure how fast a glacier flows, researchers measure its width on an aerial photograph. Measuring the photograph again gives the same width.',
      whyValid: 'how wide a glacier is doesn\'t tell you how fast the ice is moving.',
      whyReliable: 'measuring the photograph again gives the same width.' },
    { valid: false, reliable: true, for: EARTH_ENV,
      text: 'To measure noise levels along a street, researchers count the number of trees planted beside it. The count is the same every time.',
      whyValid: 'the number of trees isn\'t how loud the street is — only a sound level meter measures that.',
      whyReliable: 'counting again gives the same number.' },

    // valid, not reliable
    { valid: true, reliable: false,
      text: 'Researchers measure how fast water soaks into soil with an infiltration ring, but their report doesn\'t say the size of the ring, how much water they poured or how long they timed it. Other teams who repeat it get very different rates.',
      whyValid: 'timing water soaking in through a ring is the right way to measure infiltration.',
      whyReliable: 'without a full description of the method, nobody can repeat it and get the same result.' },
    { valid: true, reliable: false, for: EARTH_PG,
      text: 'To measure river velocity, a student times one orange floating 10 m downstream, just once. When other students repeat it, the times differ a lot as the orange catches in eddies.',
      whyValid: 'timing a float over a set distance does measure how fast the surface water moves.',
      whyReliable: 'one float, timed once, gives very different results — several floats, averaged, would be far more consistent.' },
    { valid: true, reliable: false, for: EARTH_PG,
      text: 'To compare pebble size upstream and downstream, a student measures just one pebble at each site. On a second visit the result comes out the other way.',
      whyValid: 'measuring pebbles at each site is the right way to compare pebble size.',
      whyReliable: 'one pebble per site is far too few — pebbles vary so much at each site that a second sample can reverse the result.' },
    { valid: true, reliable: false, for: EARTH_ES,
      text: 'To compare the grain size of two sandstones, a geologist measures three grains from each. Measuring three different grains from the same rocks gives a different answer.',
      whyValid: 'measuring grains is the right way to compare grain size.',
      whyReliable: 'three grains is far too few — dozens are needed before the average settles down.' },
    { valid: true, reliable: false, for: EARTH_ENV,
      text: 'To measure traffic noise at a roadside, a researcher takes one 5-second reading with a sound level meter. Repeating it minutes later gives a very different number, depending on what happens to pass.',
      whyValid: 'a sound level meter does measure noise.',
      whyReliable: 'a single 5-second reading depends on which vehicle happens to pass — an average over a longer period would be more consistent.' },

    // neither
    { valid: false, reliable: false,
      text: 'To measure how acidic a river is, researchers write down how many ducks are on the water when they arrive. The number of ducks changes every visit.',
      whyValid: 'the number of ducks has nothing to do with the pH of the water.',
      whyReliable: 'the same river gets a different "result" every visit.' },
    { valid: false, reliable: false, for: EARTH_ES,
      text: 'To measure the porosity of a rock, a student guesses a number between 1 and 100. The student guesses a different number every time.',
      whyValid: 'a guess has nothing to do with how much pore space the rock has.',
      whyReliable: 'the same rock gets a different number every time.' },
    { valid: false, reliable: false, for: EARTH_PG,
      text: 'To measure wave height, researchers note what colour the sky is. The sky looks different every time they check.',
      whyValid: 'the colour of the sky isn\'t how high the waves are.',
      whyReliable: 'the same waves get a different "result" every time.' },
    { valid: false, reliable: false, for: EARTH_ENV,
      text: 'To measure soil moisture, researchers record which way the wind is blowing. The wind changes direction from hour to hour.',
      whyValid: 'wind direction isn\'t how much water is in the soil.',
      whyReliable: 'the same soil gets a different "result" each hour.' },
  ],

  // -------------------------------------------------------------------------
  // 2d. Continuous or discrete.
  // -------------------------------------------------------------------------
  continuity: [
    // continuous: shared
    { cat: 'cont', label: 'rainfall in a day', why: EARTH_CONT + '4 mm, 4.2 mm, 4.25 mm... rain doesn\'t come in whole-millimetre steps.' },
    { cat: 'cont', label: 'air temperature', why: EARTH_CONT + '12°C, 12.5°C, 12.53°C...' },
    { cat: 'cont', label: 'river discharge', why: EARTH_CONT + '3.2 m³/s, 3.25 m³/s... there\'s always a value in between.' },
    { cat: 'cont', label: 'soil moisture content', why: EARTH_CONT + '23%, 23.4%, 23.45%...' },
    { cat: 'cont', label: 'slope angle', why: EARTH_CONT + '12°, 12.5°, 12.52°... a slope can be at any angle.' },
    // continuous: earth sciences
    { cat: 'cont', label: 'length of a crystal', for: EARTH_ES, why: EARTH_CONT + '2.1 mm, 2.15 mm, 2.153 mm...' },
    { cat: 'cont', label: 'porosity of a rock', for: EARTH_ES, why: EARTH_CONT + '15%, 15.2%, 15.23%...' },
    { cat: 'cont', label: 'dip angle of a rock layer', for: EARTH_ES, why: EARTH_CONT + '30°, 30.5°... layers can be tilted by any amount.' },
    // continuous: physical geography
    { cat: 'cont', label: 'river velocity', for: EARTH_PG, why: EARTH_CONT + '0.4 m/s, 0.45 m/s, 0.452 m/s...' },
    { cat: 'cont', label: 'wave height', for: EARTH_PG, why: EARTH_CONT + '1.2 m, 1.25 m... a wave can be any height.' },
    { cat: 'cont', label: 'channel depth', for: EARTH_PG, why: EARTH_CONT + '34 cm, 34.5 cm... depth can always be measured more finely.' },
    // continuous: environmental science
    { cat: 'cont', label: 'dissolved oxygen', for: EARTH_ENV, why: EARTH_CONT + '8.1 mg/l, 8.15 mg/l, 8.153 mg/l...' },
    { cat: 'cont', label: 'noise level', for: EARTH_ENV, why: EARTH_CONT + '62 dB, 62.5 dB, 62.54 dB...' },
    { cat: 'cont', label: 'nitrate concentration', for: EARTH_ENV, why: EARTH_CONT + '5 mg/l, 5.2 mg/l, 5.23 mg/l...' },

    // discrete: shared
    { cat: 'disc', label: 'number of rain days in a month', why: EARTH_DISC + 'a day either counts as a rain day or not: 12 or 13, never 12.5.' },
    { cat: 'disc', label: 'number of sampling sites', why: EARTH_DISC + 'sites are counted in whole numbers.' },
    { cat: 'disc', label: 'number of pebbles measured at a site', why: EARTH_DISC + 'you measure 30 pebbles or 31, not 30.5.' },
    // discrete: earth sciences
    { cat: 'disc', label: 'number of rock layers in a cliff', for: EARTH_ES, why: EARTH_DISC + 'layers are counted one by one.' },
    { cat: 'disc', label: 'number of fossils in a rock sample', for: EARTH_ES, why: EARTH_DISC + 'a sample holds 4 fossils or 5, nothing in between.' },
    { cat: 'disc', label: 'number of different minerals in a rock', for: EARTH_ES, why: EARTH_DISC + 'a rock contains 3 minerals or 4, never 3.5.' },
    { cat: 'disc', label: 'number of cores drilled', for: EARTH_ES, why: EARTH_DISC + 'each core is counted once.' },
    // discrete: physical geography
    { cat: 'disc', label: 'number of meanders along a stretch of river', for: EARTH_PG, why: EARTH_DISC + 'meanders are counted: 6 or 7, not 6.5.' },
    { cat: 'disc', label: 'number of waves breaking in one minute', for: EARTH_PG, why: EARTH_DISC + 'each wave is counted once: 11 or 12.' },
    { cat: 'disc', label: 'number of frost days in a year', for: EARTH_PG, why: EARTH_DISC + 'a day either had a frost or it didn\'t.' },
    { cat: 'disc', label: 'number of tributaries joining a river', for: EARTH_PG, why: EARTH_DISC + 'tributaries are counted in whole numbers.' },
    // discrete: environmental science
    { cat: 'disc', label: 'number of invertebrates in a kick sample', for: EARTH_ENV, why: EARTH_DISC + 'animals are counted one by one.' },
    { cat: 'disc', label: 'number of earthworms in a soil pit', for: EARTH_ENV, why: EARTH_DISC + 'you find 8 worms or 9, never 8.5.' },
    { cat: 'disc', label: 'number of water samples taken', for: EARTH_ENV, why: EARTH_DISC + 'each bottle is counted once.' },
  ],

  // -------------------------------------------------------------------------
  // 2e. Levels of measurement.
  // -------------------------------------------------------------------------
  measurement: [
    // categorical
    { cat: 'categorical', label: 'wind direction (north, east, south, west)', why: EARTH_NOM + 'North isn\'t more or less than south, just a different direction.' },
    { cat: 'categorical', label: 'which river a sample came from', why: EARTH_NOM + 'The Severn and the Trent are names, not amounts.' },
    { cat: 'categorical', label: 'land use (woodland, grassland, arable)', why: EARTH_NOM + 'Woodland isn\'t more than grassland, just a different use of the land.' },
    { cat: 'categorical', label: 'rock type (granite, basalt, sandstone)', for: EARTH_ES, why: EARTH_NOM + 'These are kinds of rock, with no order between them.' },
    { cat: 'categorical', label: 'colour of a mineral', for: EARTH_ES, why: EARTH_NOM + 'Green isn\'t more than pink, just a different colour.' },
    { cat: 'categorical', label: 'type of fossil found', for: EARTH_ES, why: EARTH_NOM + 'An ammonite isn\'t more than a trilobite, just a different kind.' },
    { cat: 'categorical', label: 'type of cloud (cumulus, stratus, cirrus)', for: EARTH_PG, why: EARTH_NOM + 'These are kinds of cloud, not amounts of cloud.' },
    { cat: 'categorical', label: 'coastal landform (spit, stack, arch)', for: EARTH_PG, why: EARTH_NOM + 'A spit isn\'t more than a stack, just a different landform.' },
    { cat: 'categorical', label: 'source of a water sample (river, lake, borehole)', for: EARTH_ENV, why: EARTH_NOM + 'These are different sources, with no order between them.' },

    // ordinal
    { cat: 'ordinal', label: 'Beaufort wind force (0 to 12)', why: EARTH_ORD + 'Each force covers a different-sized band of wind speeds, so going from force 2 to 3 isn\'t the same increase as going from 10 to 11.' },
    { cat: 'ordinal', label: 'weathering grade (fresh, slightly, moderately, highly weathered)', why: EARTH_ORD + 'The grades are in order, but nothing says each step is the same amount of weathering.' },
    { cat: 'ordinal', label: 'pebble roundness (angular, sub-angular, sub-rounded, rounded)', why: EARTH_ORD + 'The classes are in order of roundness, but the steps aren\'t equal-sized.' },
    { cat: 'ordinal', label: 'sorting of a sediment (poorly, moderately, well sorted)', for: EARTH_ES, why: EARTH_ORD + 'The labels are ranked, but "poorly" to "moderately" needn\'t be the same gap as "moderately" to "well".' },
    { cat: 'ordinal', label: 'bank erosion rated none, slight, moderate or severe', for: EARTH_PG, why: EARTH_ORD + 'The ratings are in order, but the steps aren\'t equal amounts of erosion.' },
    { cat: 'ordinal', label: 'water clarity rated clear, slightly cloudy or very cloudy', for: EARTH_ENV, why: EARTH_ORD + 'The labels are ranked, but the steps between them aren\'t equal-sized.' },
    { cat: 'ordinal', label: 'soil drainage class (poor, moderate, good)', for: EARTH_SOIL, why: EARTH_ORD + 'The classes are in order, but nothing says the steps are the same size.' },

    // interval
    { cat: 'interval', label: 'water temperature in °C', why: EARTH_INT + '0°C isn\'t "no temperature", so 20°C water isn\'t twice as hot as 10°C water.' },
    { cat: 'interval', label: 'date of the first frost of autumn', why: EARTH_INT + 'Days are equal steps, but the calendar\'s starting point is arbitrary.' },
    { cat: 'interval', label: 'year a rock core was drilled', why: EARTH_INT + 'Years are equal steps, but year 0 isn\'t the beginning of time, so 2000 isn\'t "twice" 1000.' },
    { cat: 'interval', label: 'rock face stability rated on a 1–7 scale', for: EARTH_ES, why: EARTH_INT + 'A numbered scale has constant steps, but no natural zero, so a 6 isn\'t "twice as stable" as a 3.' },
    { cat: 'interval', label: 'clock time of high tide', for: EARTH_PG, why: EARTH_INT + 'The minutes are equal, but midnight isn\'t "no time", so 4 o\'clock isn\'t twice 2 o\'clock.' },
    { cat: 'interval', label: 'sand dune stability rated on a 1–5 scale', for: EARTH_PG, why: EARTH_INT + 'A numbered scale has constant steps, but no natural zero, so a 4 isn\'t "twice as stable" as a 2.' },
    { cat: 'interval', label: 'soil temperature in °C', for: EARTH_ENV, why: EARTH_INT + '0°C isn\'t "no heat", so soil at 16°C isn\'t twice as warm as soil at 8°C.' },

    // ratio
    { cat: 'ratio', label: 'rainfall in millimetres', why: EARTH_RAT + '0 mm is no rain at all, and 20 mm is twice 10 mm.' },
    { cat: 'ratio', label: 'river discharge in m³/s', why: EARTH_RAT + '0 m³/s is no flow at all, and 6 m³/s is twice 3 m³/s.' },
    { cat: 'ratio', label: 'wind speed in metres per second', why: EARTH_RAT + '0 m/s is still air, and 10 m/s is twice 5 m/s.' },
    { cat: 'ratio', label: 'depth of a river in centimetres', why: EARTH_RAT + '0 cm is no water, and 60 cm is twice 30 cm.' },
    { cat: 'ratio', label: 'crystal length in millimetres', for: EARTH_ES, why: EARTH_RAT + '0 mm is no crystal at all, and 4 mm is twice 2 mm.' },
    { cat: 'ratio', label: 'thickness of a rock layer in metres', for: EARTH_ES, why: EARTH_RAT + '0 m is no layer, and 3 m is twice 1.5 m.' },
    { cat: 'ratio', label: 'wave height in metres', for: EARTH_PG, why: EARTH_RAT + '0 m is flat water, and 2 m is twice 1 m.' },
    { cat: 'ratio', label: 'snow depth in centimetres', for: EARTH_PG, why: EARTH_RAT + '0 cm is no snow, and 40 cm is twice 20 cm.' },
    { cat: 'ratio', label: 'nitrate concentration in mg per litre', for: EARTH_ENV, why: EARTH_RAT + '0 mg/l is no nitrate, and 10 mg/l is twice 5 mg/l.' },
    { cat: 'ratio', label: 'infiltration rate in mm per hour', for: EARTH_SOIL, why: EARTH_RAT + '0 mm per hour means no water soaks in, and 40 is twice 20.' },
  ],

  // -------------------------------------------------------------------------
  // 2g. Confounds. Pairs: the same study done badly, then properly.
  // -------------------------------------------------------------------------
  confounds: [
    // --- with a confound: shared ---
    { iv: 'vegetation cover', dv: 'soil erosion', confound: 'slope angle',
      vars: ['vegetation cover', 'soil erosion', 'slope angle', 'the collecting trough'],
      text: 'Researchers compare the soil washed off grassy plots and bare plots, catching it in the same kind of collecting trough. The grassy plots are all on gentle slopes; the bare plots are all on steep ones.',
      why: 'The bare plots were also steeper, and soil washes off steep slopes faster anyway. The difference could come from the slope, not the vegetation.' },
    { iv: 'soil compaction', dv: 'infiltration rate', confound: 'soil type',
      vars: ['soil compaction', 'infiltration rate', 'soil type', 'the infiltration ring'],
      text: 'Researchers test whether compacted soil soaks up water more slowly, using the same infiltration ring everywhere. The compacted sites are on footpaths over clay; the loose sites are in a field of sandy soil.',
      why: 'The compacted sites were also clay, which lets water in more slowly than sand whatever its compaction. The difference could come from the soil type, not the compaction.' },
    { iv: 'altitude', dv: 'air temperature', confound: 'time of day',
      vars: ['altitude', 'air temperature', 'time of day', 'the thermometer'],
      text: 'Researchers walk up a hill measuring air temperature with the same thermometer. They read the high sites just after dawn and the low sites in the early afternoon.',
      why: 'The high sites were also read in the cold early morning, and air warms up during the day. The difference could come from the time of day, not the altitude.' },

    // --- with a confound: physical geography ---
    { for: EARTH_PG, iv: 'distance downstream', dv: 'pebble size', confound: 'how pebbles were chosen',
      vars: ['distance downstream', 'pebble size', 'how pebbles were chosen', 'the callipers'],
      text: 'Students measure 30 pebbles with callipers at each site along a river. Upstream they pick pebbles that catch their eye; downstream they pick them at random from points on a grid.',
      why: 'Pebbles picked by eye tend to be the bigger ones, so the upstream samples could look larger because of how they were chosen, not because of where they were.' },
    { for: EARTH_PG, iv: 'wind speed', dv: 'wave height', confound: 'which beach',
      vars: ['wind speed', 'wave height', 'which beach', 'the measuring pole'],
      text: 'Researchers test whether stronger winds give bigger waves, reading wave height against the same measuring pole design. The windy days are all measured at an exposed beach; the calm days at a sheltered bay.',
      why: 'An exposed beach gets bigger waves than a sheltered bay on any day, so the difference could come from the beach, not the wind.' },
    { for: EARTH_PG, iv: 'river gradient', dv: 'river velocity', confound: 'river discharge',
      vars: ['river gradient', 'river velocity', 'river discharge', 'the flow meter'],
      text: 'Researchers compare velocity at steep and gentle stretches of a river with the same flow meter. The steep stretches are measured the day after heavy rain; the gentle stretches during a dry spell.',
      why: 'After heavy rain the river carries much more water and flows faster everywhere. The difference could come from the discharge, not the gradient.' },
    { for: EARTH_PG, iv: 'slope angle', dv: 'soil depth', confound: 'bedrock type',
      vars: ['slope angle', 'soil depth', 'bedrock type', 'the soil auger'],
      text: 'Researchers measure soil depth with a soil auger on steep and gentle slopes. The steep slopes are all on hard granite; the gentle slopes are all on soft shale.',
      why: 'Soil forms more slowly on hard granite than on soft shale, so the thinner soils could come from the rock, not the slope.' },

    // --- with a confound: earth sciences ---
    { for: EARTH_ES, iv: 'acidity', dv: 'mass of limestone dissolved', confound: 'size of the pieces',
      vars: ['acidity', 'mass of limestone dissolved', 'size of the pieces', 'the volume of acid'],
      text: 'A geologist tests whether stronger acid dissolves limestone faster, using 100 cm³ of acid each time. The strong-acid runs use crushed limestone; the weak-acid runs use large chips.',
      why: 'Crushed limestone has far more surface for the acid to attack, so it dissolves faster anyway. The difference could come from the size of the pieces, not the acidity.' },
    { for: EARTH_ES, iv: 'number of freeze–thaw cycles', dv: 'mass of rock broken off', confound: 'rock type',
      vars: ['number of freeze–thaw cycles', 'mass of rock broken off', 'rock type', 'the freezer'],
      text: 'A geologist soaks rock blocks and puts them through freeze–thaw cycles in the same freezer. The blocks given 40 cycles are porous sandstone; the blocks given 10 cycles are granite.',
      why: 'Porous sandstone takes in more water and breaks up more easily than granite, so the difference could come from the rock, not the number of cycles.' },

    // --- with a confound: environmental science ---
    { for: EARTH_ENV, iv: 'water temperature', dv: 'dissolved oxygen', confound: 'how fast the water flows',
      vars: ['water temperature', 'dissolved oxygen', 'how fast the water flows', 'the oxygen probe'],
      text: 'Researchers test whether warmer water holds less oxygen, using the same oxygen probe. The warm samples all come from a still pond; the cool samples all come from a fast, tumbling stream.',
      why: 'Tumbling water mixes in air and gains oxygen, so the cool samples could hold more because of the flow, not the temperature.' },
    { for: EARTH_ECO, iv: 'leaf litter depth', dv: 'soil moisture', confound: 'shade',
      vars: ['leaf litter depth', 'soil moisture', 'shade', 'the moisture probe'],
      text: 'Researchers compare soil moisture under thick and thin leaf litter with the same moisture probe. The thick-litter plots are all in deep shade under trees; the thin-litter plots are all in open sun.',
      why: 'Soil in the shade dries out more slowly than soil in the sun, so the difference could come from the shade, not the litter.' },

    // --- without a confound: shared ---
    { iv: 'vegetation cover', dv: 'soil erosion', confound: null,
      text: 'Researchers mark out plots on the same slope, and strip the grass from half of them, chosen at random. Every plot gets the same simulated rain, and the soil washed off is weighed.',
      why: 'Same slope, same soil, same rain, plots assigned at random — only the vegetation cover differs.' },
    { iv: 'soil compaction', dv: 'infiltration rate', confound: null,
      text: 'Researchers mark out plots in one field of the same soil. Plots chosen at random are rolled flat to compact them, and infiltration is measured in every plot with the same ring and method.',
      why: 'Every plot has the same soil, so compaction is the only thing that differs.' },
    { iv: 'altitude', dv: 'air temperature', confound: null,
      text: 'Researchers place identical data loggers at five heights on one hillside, all in the same kind of shaded screen, and compare readings taken at the same moment.',
      why: 'Readings taken at the same time, with the same equipment, in the same kind of screen — only the altitude differs.' },

    // --- without a confound: physical geography ---
    { for: EARTH_PG, iv: 'distance downstream', dv: 'pebble size', confound: null,
      text: 'Students measure 30 pebbles at each site along a river, and at every site they pick them the same way: the pebble touching the tip of a tape at points chosen by random numbers.',
      why: 'Every site uses the same random method of choosing pebbles, so only the distance downstream differs.' },
    { for: EARTH_PG, iv: 'wind speed', dv: 'wave height', confound: null,
      text: 'Researchers test whether stronger winds give bigger waves by measuring at the same beach on calm and windy days, at the same point in the tide each time.',
      why: 'Same beach, same state of tide — only the wind speed differs.' },
    { for: EARTH_PG, iv: 'river gradient', dv: 'river velocity', confound: null,
      text: 'Researchers compare velocity at steep and gentle stretches of the same river, measuring every site with the same flow meter on the same dry afternoon.',
      why: 'All sites were measured on the same afternoon, so the river carried the same water throughout — only the gradient differs.' },
    { for: EARTH_PG, iv: 'slope angle', dv: 'soil depth', confound: null,
      text: 'Researchers measure soil depth on steep and gentle slopes that are all on the same shale bedrock, under the same grassland, using the same soil auger.',
      why: 'Same rock, same vegetation — only the slope angle differs.' },

    // --- without a confound: earth sciences ---
    { for: EARTH_ES, iv: 'acidity', dv: 'mass of limestone dissolved', confound: null,
      text: 'A geologist cuts identical cubes from one block of limestone and puts them in 100 cm³ of acid of different strengths, at the same temperature, for the same time.',
      why: 'The cubes are identical and come from one block, so only the acidity differs.' },
    { for: EARTH_ES, iv: 'number of freeze–thaw cycles', dv: 'mass of rock broken off', confound: null,
      text: 'A geologist cuts matching blocks from one piece of sandstone, soaks them all the same way, and gives blocks chosen at random 10, 20 or 40 freeze–thaw cycles.',
      why: 'Every block is the same rock, soaked the same way, so only the number of cycles differs.' },

    // --- without a confound: environmental science ---
    { for: EARTH_ENV, iv: 'water temperature', dv: 'dissolved oxygen', confound: null,
      text: 'Researchers fill flasks with water from one source, hold them in water baths at different temperatures, and bubble air through each until it stops changing before measuring its oxygen.',
      why: 'Same water, same treatment — only the temperature differs.' },
    { for: EARTH_ECO, iv: 'leaf litter depth', dv: 'soil moisture', confound: null,
      text: 'Researchers mark out plots in one open field, and cover plots chosen at random with thick or thin layers of leaf litter. Soil moisture is measured in every plot on the same day.',
      why: 'Every plot gets the same sun and the same soil, so only the litter depth differs.' },
  ],

  // -------------------------------------------------------------------------
  // 2j. Within or between. Within: the same site or sample is measured under
  // every condition. Between: different sites or samples in each condition.
  // -------------------------------------------------------------------------
  designs: [
    // --- within ---
    { cat: 'within',
      label: 'One patch of soil is sprinkled with a rainfall simulator at low, medium and high intensity in turn, left to drain between runs, and the runoff is collected and measured each time.',
      ivs: [{ name: 'rainfall intensity', aliases: ['intensity', 'low medium or high', 'rainfall', 'how heavy the rain', 'amount of rain', 'rain intensity', 'simulator setting'] }],
      dv: { name: 'runoff', aliases: ['surface runoff', 'water collected', 'amount of runoff', 'overland flow', 'runoff volume'] },
      others: [{ name: 'the patch of soil', aliases: ['patch', 'soil', 'plot', 'soil patch'] }] },
    { cat: 'within',
      label: 'At one weather station, three different thermometers are placed side by side in the same screen, and the air temperature each one shows is recorded.',
      ivs: [{ name: 'which thermometer', aliases: ['thermometer', 'three thermometers', 'instrument', 'type of thermometer', 'equipment'] }],
      dv: { name: 'temperature reading', aliases: ['temperature', 'reading', 'air temperature', 'degrees', 'how warm'] },
      others: [{ name: 'the weather station', aliases: ['station', 'weather station', 'screen', 'stevenson screen'] }] },
    { cat: 'within',
      label: 'At one point across a river, velocity is measured with a flow meter just below the surface, at mid-depth and just above the bed.',
      ivs: [{ name: 'depth in the water', aliases: ['depth', 'surface mid or bed', 'position', 'how deep', 'height above the bed', 'level'] }],
      dv: { name: 'velocity', aliases: ['speed', 'river velocity', 'flow speed', 'how fast', 'water speed'] },
      others: [{ name: 'the flow meter', aliases: ['flow meter', 'meter', 'instrument', 'equipment'] }] },
    { cat: 'within', for: EARTH_PG,
      label: 'At one river site, the surface velocity is measured three times with a float and three times with a flow meter, and the two methods are compared.',
      ivs: [{ name: 'method (float or flow meter)', aliases: ['method', 'float or flow meter', 'float', 'flow meter', 'technique', 'how it is measured'] }],
      dv: { name: 'surface velocity', aliases: ['velocity', 'speed', 'flow speed', 'how fast', 'water speed'] },
      others: [{ name: 'the river site', aliases: ['site', 'river', 'one site', 'river site'] }] },
    { cat: 'within', for: EARTH_PG,
      label: 'On one hillside, soil depth is measured with an auger at the top, the middle and the bottom of the slope.',
      ivs: [{ name: 'position on the slope', aliases: ['position', 'top middle or bottom', 'where on the slope', 'location', 'slope position', 'top', 'bottom'] }],
      dv: { name: 'soil depth', aliases: ['depth', 'how deep the soil is', 'depth of soil', 'soil thickness', 'thickness'] },
      others: [{ name: 'the hillside', aliases: ['hillside', 'hill', 'one hillside'] }, { name: 'the auger', aliases: ['auger', 'soil auger', 'tool'] }] },
    { cat: 'within', for: EARTH_PG,
      label: 'On one mast at a weather station, anemometers at 2 m, 5 m and 10 m above the ground record wind speed over the same hour.',
      ivs: [{ name: 'height above the ground', aliases: ['height', '2 5 or 10', 'how high', 'metres up', 'elevation'] }],
      dv: { name: 'wind speed', aliases: ['wind', 'speed', 'how windy', 'how fast the wind blows', 'anemometer reading'] },
      others: [{ name: 'the mast', aliases: ['mast', 'one mast', 'pole'] }] },
    { cat: 'within', for: EARTH_ES,
      label: 'One dried sandstone block is soaked in water at 10°C, 20°C and 30°C in turn, dried between soaks, and the mass of water it absorbs is measured each time.',
      ivs: [{ name: 'water temperature', aliases: ['temperature', '10 20 or 30', 'how warm', 'degrees', 'heat'] }],
      dv: { name: 'mass of water absorbed', aliases: ['water absorbed', 'absorption', 'mass gained', 'how much water it takes in', 'uptake'] },
      others: [{ name: 'the sandstone block', aliases: ['block', 'sandstone', 'rock', 'sample'] }] },
    { cat: 'within', for: EARTH_ES,
      label: 'Ten rock samples each have their volume measured twice, once by water displacement and once with callipers, and the two methods are compared.',
      ivs: [{ name: 'method (displacement or callipers)', aliases: ['method', 'displacement', 'callipers', 'displacement or callipers', 'technique', 'how it is measured'] }],
      dv: { name: 'volume', aliases: ['volume of the sample', 'measured volume', 'size', 'cm3', 'how big'] },
      others: [{ name: 'the rock samples', aliases: ['rocks', 'samples', 'ten samples', 'rock'] }] },
    { cat: 'within', for: EARTH_ENV,
      label: 'Water from one sample bottle is tested for nitrate with a test strip and with a laboratory meter, and the two readings are compared.',
      ivs: [{ name: 'method (strip or meter)', aliases: ['method', 'strip or meter', 'test strip', 'lab meter', 'technique', 'how it is tested'] }],
      dv: { name: 'nitrate reading', aliases: ['nitrate', 'nitrate concentration', 'reading', 'concentration', 'how much nitrate'] },
      others: [{ name: 'the sample bottle', aliases: ['bottle', 'sample', 'water', 'one bottle'] }] },
    { cat: 'within', for: EARTH_ENV,
      label: 'In one garden plot, soil temperature is measured with probes at 5 cm, 10 cm and 20 cm below the surface at the same moment.',
      ivs: [{ name: 'depth below the surface', aliases: ['depth', '5 10 or 20', 'how deep', 'probe depth', 'cm down'] }],
      dv: { name: 'soil temperature', aliases: ['temperature', 'how warm', 'degrees', 'heat', 'soil warmth'] },
      others: [{ name: 'the garden plot', aliases: ['plot', 'garden', 'one plot', 'garden plot'] }] },
    { cat: 'within', for: EARTH_ENV,
      label: 'At one spot in a lake, dissolved oxygen is measured with a probe lowered to the surface, 2 m and 5 m.',
      ivs: [{ name: 'depth in the water', aliases: ['depth', 'surface 2 or 5', 'how deep', 'probe depth', 'metres down'] }],
      dv: { name: 'dissolved oxygen', aliases: ['oxygen', 'oxygen level', 'do', 'how much oxygen', 'oxygen content'] },
      others: [{ name: 'the lake', aliases: ['lake', 'one spot', 'spot'] }] },

    // --- between ---
    { cat: 'between',
      label: 'Twelve patches of the same soil are each sprinkled once by a rainfall simulator: four at low, four at medium and four at high intensity. The runoff from each is measured.',
      ivs: [{ name: 'rainfall intensity', aliases: ['intensity', 'low medium or high', 'rainfall', 'how heavy the rain', 'amount of rain', 'rain intensity', 'simulator setting'] }],
      dv: { name: 'runoff', aliases: ['surface runoff', 'water collected', 'amount of runoff', 'overland flow', 'runoff volume'] },
      others: [{ name: 'the soil patches', aliases: ['patches', 'soil', 'plots', 'twelve patches'] }] },
    { cat: 'between',
      label: 'Twenty plots in one field are marked out; ten chosen at random are trampled 200 times and ten are left alone. The infiltration rate of each plot is measured.',
      ivs: [{ name: 'trampling (trampled or not)', aliases: ['trampling', 'trampled or not', 'trampled', 'compaction', 'walked on', 'footfall'] }],
      dv: { name: 'infiltration rate', aliases: ['infiltration', 'how fast water soaks in', 'soaking rate', 'drainage', 'water soaking in'] },
      others: [{ name: 'the field', aliases: ['field', 'one field', 'plots'] }] },
    { cat: 'between',
      label: 'Twelve identical trays of soil are tilted at 5°, 15° or 25°, four at each angle, and the soil washed off by the same sprinkling is weighed.',
      ivs: [{ name: 'slope angle', aliases: ['angle', 'slope', '5 15 or 25', 'tilt', 'steepness', 'how steep'] }],
      dv: { name: 'mass of soil washed off', aliases: ['soil washed off', 'soil loss', 'erosion', 'mass of soil', 'soil lost'] },
      others: [{ name: 'the trays', aliases: ['trays', 'identical trays', 'twelve trays'] }] },
    { cat: 'between', for: EARTH_PG,
      label: 'River velocity is measured once at each of ten steep stretches and ten gentle stretches of different streams.',
      ivs: [{ name: 'gradient (steep or gentle)', aliases: ['gradient', 'steep or gentle', 'steepness', 'slope', 'how steep', 'channel slope'] }],
      dv: { name: 'river velocity', aliases: ['velocity', 'speed', 'flow speed', 'how fast', 'water speed'] },
      others: [{ name: 'the streams', aliases: ['streams', 'stretches', 'rivers'] }] },
    { cat: 'between', for: EARTH_PG,
      label: 'Soil depth is measured with an auger on fifteen steep slopes and fifteen gentle slopes in the same valley.',
      ivs: [{ name: 'slope (steep or gentle)', aliases: ['slope', 'steep or gentle', 'slope angle', 'steepness', 'how steep', 'angle'] }],
      dv: { name: 'soil depth', aliases: ['depth', 'how deep the soil is', 'depth of soil', 'soil thickness', 'thickness'] },
      others: [{ name: 'the valley', aliases: ['valley', 'same valley'] }, { name: 'the auger', aliases: ['auger', 'soil auger', 'tool'] }] },
    { cat: 'between', for: EARTH_PG,
      label: 'Thirty pebbles are measured at each of five sites near the source of a river and five sites near its mouth, with different pebbles at every site.',
      ivs: [{ name: 'position (source or mouth)', aliases: ['position', 'source or mouth', 'upstream or downstream', 'location', 'site', 'distance downstream'] }],
      dv: { name: 'pebble size', aliases: ['size', 'pebble length', 'how big the pebbles are', 'long axis', 'sediment size'] },
      others: [{ name: 'the river', aliases: ['river', 'one river'] }] },
    { cat: 'between', for: EARTH_ES,
      label: 'Fifteen dried sandstone blocks are split into three groups; one group is soaked at 10°C, one at 20°C and one at 30°C. The mass of water each block absorbs is measured.',
      ivs: [{ name: 'water temperature', aliases: ['temperature', '10 20 or 30', 'how warm', 'degrees', 'heat'] }],
      dv: { name: 'mass of water absorbed', aliases: ['water absorbed', 'absorption', 'mass gained', 'how much water it takes in', 'uptake'] },
      others: [{ name: 'the sandstone blocks', aliases: ['blocks', 'sandstone', 'rock', 'samples'] }] },
    { cat: 'between', for: EARTH_ES,
      label: 'Twenty limestone chips of equal mass are split at random; ten go into acid of pH 3 and ten into acid of pH 5. The mass each chip loses in a week is measured.',
      ivs: [{ name: 'acidity (pH 3 or pH 5)', aliases: ['acidity', 'ph', 'ph 3 or 5', 'acid strength', 'how acidic', 'strong or weak acid'] }],
      dv: { name: 'mass lost', aliases: ['mass loss', 'weight lost', 'how much it dissolves', 'dissolving', 'loss of mass'] },
      others: [{ name: 'the limestone chips', aliases: ['chips', 'limestone', 'twenty chips'] }] },
    { cat: 'between', for: EARTH_ENV,
      label: 'Twenty water samples are taken from one river; ten chosen at random are tested for nitrate with test strips and ten with a laboratory meter.',
      ivs: [{ name: 'method (strip or meter)', aliases: ['method', 'strip or meter', 'test strip', 'lab meter', 'technique', 'how it is tested'] }],
      dv: { name: 'nitrate reading', aliases: ['nitrate', 'nitrate concentration', 'reading', 'concentration', 'how much nitrate'] },
      others: [{ name: 'the river', aliases: ['river', 'one river', 'water samples'] }] },
    { cat: 'between', for: EARTH_ENV,
      label: 'In each of fifteen garden plots, one probe is placed at a single depth — 5 cm, 10 cm or 20 cm, five plots each — and the soil temperature is recorded.',
      ivs: [{ name: 'depth below the surface', aliases: ['depth', '5 10 or 20', 'how deep', 'probe depth', 'cm down'] }],
      dv: { name: 'soil temperature', aliases: ['temperature', 'how warm', 'degrees', 'heat', 'soil warmth'] },
      others: [{ name: 'the garden plots', aliases: ['plots', 'garden', 'fifteen plots', 'garden plots'] }] },
    { cat: 'between', for: EARTH_ECO,
      label: 'Twenty pots of the same soil are watered equally; ten chosen at random are covered with leaf litter and ten are left bare. Soil moisture is measured a week later.',
      ivs: [{ name: 'leaf litter (covered or bare)', aliases: ['leaf litter', 'litter', 'covered or bare', 'mulch', 'leaves', 'covering'] }],
      dv: { name: 'soil moisture', aliases: ['moisture', 'water content', 'how wet', 'wetness', 'dampness'] },
      others: [{ name: 'the pots', aliases: ['pots', 'twenty pots', 'containers'] }] },
  ],

  // -------------------------------------------------------------------------
  // 2f-2h. Cross-sectional (many sites, measured once) or longitudinal (the
  // same site, measured over time).
  // -------------------------------------------------------------------------
  crosslong: {
    single: [
      // cross-sectional
      { cat: 'cross',
        label: 'On one dry day, soil moisture is measured at 20 sites under woodland and 20 sites under grassland, and the two land covers are compared.',
        ivs: [{ name: 'land cover (woodland or grassland)', aliases: ['land cover', 'woodland or grassland', 'woodland', 'grassland', 'vegetation', 'land use', 'group'] }],
        dv: { name: 'soil moisture', aliases: ['moisture', 'water content', 'how wet', 'wetness', 'dampness'] },
        others: [{ name: 'the day of sampling', aliases: ['one day', 'same day', 'dry day'] }] },
      { cat: 'cross', for: EARTH_PG,
        label: 'In one week, students measure the pebbles at ten sites spread from the source to the mouth of a river, and compare pebble size along it.',
        ivs: [{ name: 'distance downstream', aliases: ['distance', 'site', 'source to mouth', 'where on the river', 'position', 'location', 'upstream or downstream'] }],
        dv: { name: 'pebble size', aliases: ['size', 'pebble length', 'how big the pebbles are', 'long axis', 'sediment size'] },
        others: [{ name: 'the week of fieldwork', aliases: ['one week', 'same week', 'fieldwork'] }] },
      { cat: 'cross', for: EARTH_PG,
        label: 'At noon on one day, the air temperature is read at twelve weather stations at different altitudes, and the readings are compared.',
        ivs: [{ name: 'altitude', aliases: ['height', 'elevation', 'how high', 'height above sea level', 'station height'] }],
        dv: { name: 'air temperature', aliases: ['temperature', 'how warm', 'degrees', 'heat', 'reading'] },
        others: [{ name: 'noon on one day', aliases: ['noon', 'one day', 'same time', 'midday'] }] },
      { cat: 'cross', for: EARTH_ES,
        label: 'In one field season, a geologist measures crystal size in samples from the edge and from the centre of an igneous intrusion.',
        ivs: [{ name: 'position (edge or centre)', aliases: ['position', 'edge or centre', 'edge', 'centre', 'where in the intrusion', 'location', 'group'] }],
        dv: { name: 'crystal size', aliases: ['crystals', 'size of the crystals', 'how big the crystals are', 'grain size', 'crystal length'] },
        others: [{ name: 'the field season', aliases: ['season', 'one season', 'field season'] }] },
      { cat: 'cross', for: EARTH_ENV,
        label: 'On one morning, dissolved oxygen is measured in 15 fast-flowing streams and 15 slow-flowing streams, and the two groups are compared.',
        ivs: [{ name: 'flow (fast or slow)', aliases: ['flow', 'fast or slow', 'flow speed', 'how fast the stream flows', 'type of stream', 'group'] }],
        dv: { name: 'dissolved oxygen', aliases: ['oxygen', 'oxygen level', 'do', 'how much oxygen', 'oxygen content'] },
        others: [{ name: 'the morning of sampling', aliases: ['one morning', 'same morning', 'morning'] }] },

      // longitudinal
      { cat: 'long',
        label: 'One rain gauge in an open field is read at 9 am every day for a year, to track how much rain falls.',
        ivs: [{ name: 'time (day of the year)', aliases: ['every day', 'date', 'season', 'a year', ...EARTH_TIME] }],
        dv: { name: 'rainfall', aliases: ['rain', 'amount of rain', 'mm of rain', 'precipitation', 'how much rain'] },
        others: [{ name: 'the rain gauge', aliases: ['gauge', 'rain gauge', 'field', 'open field'] }] },
      { cat: 'long', for: EARTH_PG,
        label: 'After a storm, the discharge of one river is measured every hour for three days at the same gauging station.',
        ivs: [{ name: 'time since the storm', aliases: ['hours', 'hour', 'every hour', 'three days', 'hours after the storm', 'time after rain', ...EARTH_TIME] }],
        dv: { name: 'discharge', aliases: ['river discharge', 'flow', 'how much water', 'water flow', 'volume of water'] },
        others: [{ name: 'the gauging station', aliases: ['gauging station', 'station', 'gauge'] }] },
      { cat: 'long', for: EARTH_PG,
        label: 'The profile of one beach is surveyed every month for a year, and the beach gradient is calculated each time.',
        ivs: [{ name: 'time (month of the survey)', aliases: ['every month', 'season', 'a year', 'survey', ...EARTH_TIME] }],
        dv: { name: 'gradient', aliases: ['slope', 'steepness', 'angle', 'profile', 'how steep', 'slope angle'] },
        others: [{ name: 'the beach', aliases: ['beach', 'one beach'] }] },
      { cat: 'long', for: EARTH_ES,
        label: 'A net at the foot of one cliff catches falling rock, and the rock in it is weighed every month for two years.',
        ivs: [{ name: 'time (month)', aliases: ['every month', 'two years', 'season', ...EARTH_TIME] }],
        dv: { name: 'mass of rock fallen', aliases: ['rockfall', 'rock fallen', 'mass', 'weight of rock', 'how much rock'] },
        others: [{ name: 'the net', aliases: ['net', 'cliff', 'the cliff'] }] },
      { cat: 'long', for: EARTH_ENV,
        label: 'At one spot in a lake, the water temperature 1 m below the surface is measured every week for a year.',
        ivs: [{ name: 'time (week of the year)', aliases: ['every week', 'season', 'a year', 'date', ...EARTH_TIME] }],
        dv: { name: 'water temperature', aliases: ['temperature', 'how warm', 'degrees', 'heat', 'temperature of the water'] },
        others: [{ name: 'the lake', aliases: ['lake', 'one spot', 'spot'] }] },
    ],

    multi: [
      // cross-sectional, two factors
      { cat: 'cross',
        label: 'On one dry day, soil moisture is measured at sites under woodland and under grassland, on both north-facing and south-facing slopes, and all four groups are compared.',
        ivs: [
          { name: 'land cover (woodland or grassland)', aliases: ['land cover', 'woodland or grassland', 'woodland', 'grassland', 'vegetation', 'land use'] },
          { name: 'aspect (north or south)', aliases: ['aspect', 'north or south', 'north-facing', 'south-facing', 'direction the slope faces', 'which way it faces'] },
        ],
        dv: { name: 'soil moisture', aliases: ['moisture', 'water content', 'how wet', 'wetness', 'dampness'] },
        others: [{ name: 'the day of sampling', aliases: ['one day', 'same day', 'dry day'] }] },
      { cat: 'cross', for: EARTH_PG,
        label: 'In one week, pebble size is measured at upstream and downstream sites on a river over granite and a river over sandstone.',
        ivs: [
          { name: 'position (upstream or downstream)', aliases: ['position', 'upstream or downstream', 'upstream', 'downstream', 'where on the river', 'distance downstream'] },
          { name: 'river (granite or sandstone)', aliases: ['river', 'granite or sandstone', 'rock type', 'geology', 'which river', 'bedrock'] },
        ],
        dv: { name: 'pebble size', aliases: ['size', 'pebble length', 'how big the pebbles are', 'long axis', 'sediment size'] },
        others: [{ name: 'the week of fieldwork', aliases: ['one week', 'same week', 'fieldwork'] }] },
      { cat: 'cross', for: EARTH_ES,
        label: 'In one field season, crystal size is measured at the edge and the centre of a granite intrusion and of a gabbro intrusion.',
        ivs: [
          { name: 'position (edge or centre)', aliases: ['position', 'edge or centre', 'edge', 'centre', 'where in the intrusion', 'location'] },
          { name: 'intrusion (granite or gabbro)', aliases: ['intrusion', 'granite or gabbro', 'rock type', 'granite', 'gabbro', 'which intrusion'] },
        ],
        dv: { name: 'crystal size', aliases: ['crystals', 'size of the crystals', 'how big the crystals are', 'grain size', 'crystal length'] },
        others: [{ name: 'the field season', aliases: ['season', 'one season', 'field season'] }] },
      { cat: 'cross', for: EARTH_SOIL,
        label: 'On one day, infiltration is measured on footpaths and on the ground beside them, in both a clay area and a sandy area.',
        ivs: [
          { name: 'location (path or off path)', aliases: ['path', 'path or off path', 'footpath', 'on or off the path', 'trampled', 'location'] },
          { name: 'soil type (clay or sand)', aliases: ['soil type', 'clay or sand', 'clay', 'sand', 'sandy', 'type of soil'] },
        ],
        dv: { name: 'infiltration rate', aliases: ['infiltration', 'how fast water soaks in', 'soaking rate', 'drainage', 'water soaking in'] },
        others: [{ name: 'the day of fieldwork', aliases: ['one day', 'same day', 'fieldwork'] }] },

      // longitudinal, two factors
      { cat: 'long',
        label: 'At one weather station, air temperature is recorded every hour for a week, both inside a shaded screen and in direct sun.',
        ivs: [
          { name: 'time (hour)', aliases: ['hours', 'hour', 'every hour', 'a week', 'time of day', ...EARTH_TIME] },
          { name: 'position (shade or sun)', aliases: ['position', 'shade or sun', 'shade', 'sun', 'screen or sun', 'shaded', 'location'] },
        ],
        dv: { name: 'air temperature', aliases: ['temperature', 'how warm', 'degrees', 'heat', 'reading'] },
        others: [{ name: 'the weather station', aliases: ['station', 'weather station', 'one station'] }] },
      { cat: 'long', for: EARTH_PG,
        label: 'At one river site, velocity is measured every hour for three days after a storm, both just below the surface and just above the bed.',
        ivs: [
          { name: 'time since the storm', aliases: ['hours', 'hour', 'every hour', 'three days', 'hours after the storm', ...EARTH_TIME] },
          { name: 'depth (surface or bed)', aliases: ['depth', 'surface or bed', 'surface', 'bed', 'how deep', 'position in the water'] },
        ],
        dv: { name: 'velocity', aliases: ['speed', 'river velocity', 'flow speed', 'how fast', 'water speed'] },
        others: [{ name: 'the river site', aliases: ['site', 'river', 'one site', 'river site'] }] },
      { cat: 'long', for: EARTH_ES,
        label: 'One limestone block is left outdoors, and every year for ten years the surface lowering is measured on both its top face and a side face.',
        ivs: [
          { name: 'time outdoors', aliases: ['every year', 'ten years', 'exposure time', 'age', ...EARTH_TIME] },
          { name: 'face (top or side)', aliases: ['face', 'top or side', 'top face', 'side face', 'which face', 'side'] },
        ],
        dv: { name: 'surface lowering', aliases: ['lowering', 'weathering', 'surface worn away', 'erosion', 'how much has worn away', 'mm lost'] },
        others: [{ name: 'the limestone block', aliases: ['block', 'limestone', 'one block', 'stone'] }] },
      { cat: 'long', for: EARTH_PG_ENV,
        label: 'At one spot in a lake, the water temperature is measured every week for a year, both at the surface and at 10 m depth.',
        ivs: [
          { name: 'time (week of the year)', aliases: ['every week', 'season', 'a year', 'date', ...EARTH_TIME] },
          { name: 'depth (surface or 10 m)', aliases: ['depth', 'surface or 10 m', 'surface', '10 m', 'how deep', 'deep or shallow'] },
        ],
        dv: { name: 'water temperature', aliases: ['temperature', 'how warm', 'degrees', 'heat', 'temperature of the water'] },
        others: [{ name: 'the lake', aliases: ['lake', 'one spot', 'spot'] }] },
    ],

    panel: [
      { cat: 'both',
        label: 'Soil moisture is measured in ten woodland plots and ten grassland plots, and each plot is measured again every week for a year.',
        ivs: [
          { name: 'land cover (woodland or grassland)', aliases: ['land cover', 'woodland or grassland', 'woodland', 'grassland', 'vegetation', 'land use', 'group'] },
          { name: 'time (week)', aliases: ['every week', 'a year', 'season', ...EARTH_TIME] },
        ],
        dv: { name: 'soil moisture', aliases: ['moisture', 'water content', 'how wet', 'wetness', 'dampness'] },
        others: [] },
      { cat: 'both',
        label: 'Rain gauges at a coastal station and an upland station are each read every day for a year.',
        ivs: [
          { name: 'station (coastal or upland)', aliases: ['station', 'coastal or upland', 'coast', 'upland', 'location', 'site', 'group'] },
          { name: 'time (day)', aliases: ['every day', 'a year', 'date', 'season', ...EARTH_TIME] },
        ],
        dv: { name: 'rainfall', aliases: ['rain', 'amount of rain', 'mm of rain', 'precipitation', 'how much rain'] },
        others: [] },
      { cat: 'both', for: EARTH_PG,
        label: 'The profiles of three beaches — one sand, one shingle and one mixed — are each surveyed every month for a year, and the gradient calculated.',
        ivs: [
          { name: 'type of beach', aliases: ['beach', 'sand shingle or mixed', 'sand', 'shingle', 'beach material', 'which beach', 'group'] },
          { name: 'time (month)', aliases: ['every month', 'a year', 'season', 'survey', ...EARTH_TIME] },
        ],
        dv: { name: 'beach gradient', aliases: ['gradient', 'slope', 'steepness', 'beach slope', 'angle', 'profile'] },
        others: [] },
      { cat: 'both', for: EARTH_PG,
        label: 'After the same storm, the discharge of a river draining clay and a river draining chalk is each measured every hour for three days.',
        ivs: [
          { name: 'catchment rock (clay or chalk)', aliases: ['rock', 'clay or chalk', 'clay', 'chalk', 'geology', 'which river', 'catchment', 'group'] },
          { name: 'time since the storm', aliases: ['hours', 'hour', 'every hour', 'three days', 'hours after the storm', ...EARTH_TIME] },
        ],
        dv: { name: 'discharge', aliases: ['river discharge', 'flow', 'how much water', 'water flow', 'volume of water'] },
        others: [] },
      { cat: 'both', for: EARTH_ES,
        label: 'Soaked blocks of limestone and of sandstone are put through freeze–thaw cycles, and each block is weighed after every ten cycles.',
        ivs: [
          { name: 'rock type (limestone or sandstone)', aliases: ['rock', 'limestone or sandstone', 'limestone', 'sandstone', 'type of rock', 'group'] },
          { name: 'number of freeze–thaw cycles', aliases: ['cycles', 'freeze-thaw cycles', 'every ten cycles', 'how many cycles', ...EARTH_TIME] },
        ],
        dv: { name: 'mass of each block', aliases: ['mass', 'weight', 'how heavy', 'mass lost', 'mass loss'] },
        others: [] },
      { cat: 'both', for: EARTH_ENV,
        label: 'Sound level meters 10 m, 50 m and 100 m from a busy road each record the noise level every hour for one day.',
        ivs: [
          { name: 'distance from the road', aliases: ['distance', '10 50 or 100', 'how far from the road', 'metres from the road', 'position', 'group'] },
          { name: 'time (hour of the day)', aliases: ['hours', 'hour', 'every hour', 'time of day', ...EARTH_TIME] },
        ],
        dv: { name: 'noise level', aliases: ['noise', 'decibels', 'db', 'how loud', 'loudness', 'sound level'] },
        others: [] },
      { cat: 'both', for: EARTH_ECO,
        label: 'Dissolved oxygen is measured in five shaded ponds and five unshaded ponds, and each pond is measured every week through the summer.',
        ivs: [
          { name: 'shade (shaded or unshaded)', aliases: ['shade', 'shaded or unshaded', 'shaded', 'unshaded', 'sun', 'type of pond', 'group'] },
          { name: 'time (week)', aliases: ['every week', 'summer', 'season', ...EARTH_TIME] },
        ],
        dv: { name: 'dissolved oxygen', aliases: ['oxygen', 'oxygen level', 'do', 'how much oxygen', 'oxygen content'] },
        others: [] },
    ],
  },

  // -------------------------------------------------------------------------
  // Level 3. Factors for box notation.
  // -------------------------------------------------------------------------
  factors: [
    { name: 'Slope angle', levels: { 2: ['5°', '25°'], 3: ['5°', '15°', '25°'], 4: ['5°', '15°', '25°', '35°'] } },
    { name: 'Land cover', levels: { 2: ['woodland', 'grassland'], 3: ['woodland', 'grassland', 'bare'], 4: ['woodland', 'grassland', 'arable', 'bare'] } },
    { name: 'Rainfall', levels: { 2: ['10 mm/h', '30 mm/h'], 3: ['10 mm/h', '20 mm/h', '30 mm/h'], 4: ['10 mm/h', '20 mm/h', '30 mm/h', '40 mm/h'] } },
    { name: 'Soil type', levels: { 2: ['sand', 'clay'], 3: ['sand', 'silt', 'clay'], 4: ['sand', 'silt', 'clay', 'loam'] } },
    { name: 'Season', levels: { 2: ['summer', 'winter'], 4: ['spring', 'summer', 'autumn', 'winter'] } },
    { name: 'Aspect', for: EARTH_PG, levels: { 2: ['north', 'south'], 4: ['north', 'east', 'south', 'west'] } },
    { name: 'Altitude', for: EARTH_PG, levels: { 2: ['100 m', '500 m'], 3: ['100 m', '300 m', '500 m'], 4: ['100 m', '300 m', '500 m', '700 m'] } },
    { name: 'River site', for: EARTH_PG, levels: { 2: ['upstream', 'downstream'], 3: ['upper', 'middle', 'lower'] } },
    { name: 'Rock type', for: EARTH_ES, levels: { 2: ['granite', 'limestone'], 3: ['granite', 'limestone', 'sandstone'], 4: ['granite', 'limestone', 'sandstone', 'shale'] } },
    { name: 'Acid pH', for: EARTH_ES, levels: { 2: ['pH 3', 'pH 5'], 3: ['pH 3', 'pH 4', 'pH 5'] } },
    { name: 'Freeze–thaw', for: EARTH_ES, levels: { 2: ['10 cycles', '40 cycles'], 3: ['10 cycles', '20 cycles', '40 cycles'], 4: ['10 cycles', '20 cycles', '30 cycles', '40 cycles'] } },
    { name: 'Lake depth', for: EARTH_PG_ENV, levels: { 2: ['1 m', '10 m'], 3: ['1 m', '5 m', '10 m'] } },
    { name: 'Road distance', for: EARTH_ENV, levels: { 2: ['10 m', '100 m'], 3: ['10 m', '50 m', '100 m'], 4: ['10 m', '50 m', '100 m', '200 m'] } },
    { name: 'Probe depth', for: EARTH_ENV, levels: { 2: ['5 cm', '20 cm'], 3: ['5 cm', '10 cm', '20 cm'] } },
    { name: 'Leaf litter', for: EARTH_ECO, levels: { 2: ['none', 'thick'], 3: ['none', 'thin', 'thick'] } },
  ],
};
