// ---------------------------------------------------------------------------
// Economics & business pool: prices, demand and supply, classroom markets and
// auctions, lab savings tasks, shoppers, queues and checkouts, online shops,
// loyalty schemes, shelf space and advertising.
// The only pool for economics and the main pool for business (which also
// draws on mind & behaviour). Studies are done on people — participants,
// customers, shoppers, staff — or on shops and branches followed over time.
// Roughly a third of the items are shared; the rest carry `for` so that
// economics gets markets and auctions and business gets marketing and
// customer service. Every relation is textbook and stated within the range
// where it holds. See pools/README.md for the rules.
// ---------------------------------------------------------------------------
const ECON_E = ['economics'];
const ECON_B = ['business'];

const ECON_CONT = 'It can take any value on a scale, including every value in between — ';
const ECON_DISC = 'It only comes in separate values, with nothing in between — ';

const ECON_NOM = 'Categorical: distinct outcomes with no order. ';
const ECON_ORD = 'Ordinal: the outcomes are ranked, but the difference between steps is arbitrary. ';
const ECON_INT = 'Interval: ranked, with a constant difference between steps, but no natural zero — so values aren\'t "twice as much". ';
const ECON_RAT = 'Ratio: ranked, constant steps AND a natural zero, so "twice as much" makes sense. ';

const ECON_TIME = ['time', 'over time', 'week', 'weeks', 'month', 'months', 'year', 'years', 'day', 'days', 'when it was measured', 'time point', 'session', 'before and after'];

const ECON_P = { name: 'the participants', aliases: ['participants', 'people', 'subjects', 'person'] };
const ECON_SHOPPERS = { name: 'the shoppers', aliases: ['shoppers', 'customers', 'people', 'participants'] };

const ECON_DISCOUNT = { name: 'price (full price or 20% off)', aliases: ['price', 'discount', 'full price', '20% off', 'full price or discount', 'sale', 'offer', 'price cut'] };
const ECON_UNITS = { name: 'number of units bought', aliases: ['units bought', 'units', 'how many they buy', 'quantity', 'amount bought', 'purchases', 'number bought', 'sales'] };
const ECON_DELIVERY = { name: 'delivery charge (free or £4)', aliases: ['delivery charge', 'delivery', 'free delivery', 'charge', 'free or £4', 'postage', 'shipping', 'delivery cost'] };
const ECON_ITEMS = { name: 'number of items ordered', aliases: ['items ordered', 'items', 'order size', 'how many items', 'number of items', 'basket size', 'amount ordered'] };
const ECON_CHECKOUT = { name: 'checkout type (staffed or self-service)', aliases: ['checkout type', 'checkout', 'staffed', 'self-service', 'self checkout', 'till', 'type of till', 'staffed or self-service'] };
const ECON_PAYTIME = { name: 'time taken to pay', aliases: ['time to pay', 'time taken', 'how long it takes', 'paying time', 'speed', 'checkout time', 'how quickly they pay'] };
const ECON_AUCTION = { name: 'auction format (sealed-bid or open)', aliases: ['auction format', 'format', 'sealed bid', 'sealed', 'open', 'open auction', 'sealed-bid or open', 'type of auction'] };
const ECON_PRICEPAID = { name: 'price paid by the winner', aliases: ['price paid', 'winning price', 'winning bid', 'price', 'how much the winner pays', 'amount paid', 'bid'] };
const ECON_RATE = { name: 'interest rate (2% or 10%)', aliases: ['interest rate', 'interest', 'rate', '2% or 10%', 'low or high interest', 'return', 'savings rate'] };
const ECON_SAVED = { name: 'amount saved', aliases: ['amount saved', 'saving', 'savings', 'how much they save', 'money saved', 'amount put aside'] };
const ECON_SELLERS = { name: 'number of sellers (2 or 8)', aliases: ['number of sellers', 'sellers', '2 or 8', 'competition', 'competitors', 'how many sellers', 'market size'] };
const ECON_TRADEPRICE = { name: 'trading price', aliases: ['trading price', 'price', 'prices', 'agreed price', 'market price', 'price of trades', 'selling price'] };
const ECON_LABPRICE = { name: 'price of the snack (£1 or £3)', aliases: ['price', 'snack price', '£1 or £3', 'cheap or dear', 'cost', 'how much it costs', 'price level'] };
const ECON_SNACKS = { name: 'number of snacks bought', aliases: ['snacks bought', 'snacks', 'how many they buy', 'quantity demanded', 'demand', 'number bought', 'quantity'] };
const ECON_ADREP = { name: 'advert showings (once or five times)', aliases: ['advert showings', 'repetition', 'repetitions', 'once or five times', 'how often the advert is shown', 'exposure', 'frequency', 'advertising frequency'] };
const ECON_RECALL = { name: 'brand recall', aliases: ['brand recall', 'recall', 'remembering the brand', 'memory', 'brands remembered', 'whether they remember', 'brand awareness'] };
const ECON_MENU = { name: 'menu size (5 or 20 options)', aliases: ['menu size', 'options', 'number of options', '5 or 20', 'choices', 'number of choices', 'menu length', 'choice'] };
const ECON_DECIDE = { name: 'time to decide', aliases: ['time to decide', 'decision time', 'how long they take', 'deciding', 'time to choose', 'how quickly they choose', 'speed'] };
const ECON_LOAD = { name: 'page loading time (fast or slow)', aliases: ['loading time', 'loading', 'page speed', 'fast or slow', 'load time', 'slow pages', 'fast pages', 'how fast it loads'] };
const ECON_BASKET = { name: 'number of items added to the basket', aliases: ['items added', 'basket', 'items in basket', 'number of items', 'how many items', 'purchases', 'items bought'] };
const ECON_SHELF = { name: 'shelf position (eye level or bottom)', aliases: ['shelf position', 'shelf', 'position', 'eye level', 'bottom shelf', 'eye level or bottom', 'placement', 'height'] };
const ECON_CHOSEN = { name: 'number of times the product is chosen', aliases: ['times chosen', 'chosen', 'choices', 'how often it is picked', 'picked', 'selections', 'sales'] };

POOLS.econ = {
  // -------------------------------------------------------------------------
  // 1a. Variable or not?
  // -------------------------------------------------------------------------
  sortItems: [
    // --- variables: shared ---
    { label: 'price of a product', variable: true,
      why: 'The same product can cost more in one shop than another, or more this month than last. Prices are measured in pounds and pence.' },
    { label: 'number of units sold', variable: true,
      why: 'A shop sells more of a product on some days than others, and the units can be counted from the till records.' },
    { label: 'waiting time at the checkout', variable: true,
      why: 'Some customers wait a few seconds and some wait ten minutes. The wait can be timed.' },
    { label: 'number of customers per hour', variable: true,
      why: 'A shop is busier at some times than others, and the customers coming in each hour can be counted.' },
    { label: 'delivery charge', variable: true,
      why: 'An online shop can charge nothing, £2 or £5 for delivery, so the charge takes different values.' },
    { label: 'size of a discount', variable: true,
      why: 'A discount can be 5%, 20% or 50% off, and the percentage can be set and compared.' },
    { label: 'distance to the nearest shop', variable: true,
      why: 'Some people live next door to a shop and some live miles away. The distance is measured in kilometres.' },
    { label: 'number of items in a basket', variable: true,
      why: 'Some shoppers buy one thing and some buy fifty. The items can be counted at the till.' },
    { label: 'time spent in a shop', variable: true,
      why: 'Some shoppers dash in and out and some browse for an hour. The time can be measured in minutes.' },
    { label: 'a shop\'s daily takings', variable: true,
      why: 'A shop takes more money on some days than others, and the total is measured in pounds.' },
    { label: 'number of staff on a shift', variable: true,
      why: 'A shop can have two staff on one shift and eight on another. They can be counted.' },

    // --- variables: economics ---
    { label: 'quantity demanded', variable: true, for: ECON_E,
      why: 'How much of a good people want to buy changes with its price and with their income, and it can be measured in units.' },
    { label: 'quantity supplied', variable: true, for: ECON_E,
      why: 'Sellers offer more or fewer units for sale depending on the price they can get, and the units can be counted.' },
    { label: 'price of a substitute good', variable: true, for: ECON_E,
      why: 'The price of tea, a substitute for coffee, can go up or down, and it is measured in pounds and pence.' },
    { label: 'weekly household income', variable: true, for: ECON_E,
      why: 'Households receive different amounts each week, and income is measured in pounds.' },
    { label: 'winning bid in an auction', variable: true, for: ECON_E,
      why: 'The same item can sell for more at one auction than another, and the winning bid is recorded in pounds.' },
    { label: 'number of sellers in a market', variable: true, for: ECON_E,
      why: 'A market can have two sellers or twenty. They can be counted, and in a classroom market the lecturer can change the number.' },
    { label: 'interest rate offered on savings', variable: true, for: ECON_E,
      why: 'An account can pay 1% or 5% a year, so the rate takes different values and can be compared.' },
    { label: 'amount saved', variable: true, for: ECON_E,
      why: 'Some people put more money aside than others, and the amount is measured in pounds.' },
    { label: 'cost of making each unit', variable: true, for: ECON_E,
      why: 'Making a product costs more when materials or energy cost more. The cost per unit is measured in pounds.' },
    { label: 'number of trades in a classroom market', variable: true, for: ECON_E,
      why: 'Some rounds of a market have more deals agreed than others, and the trades can be counted.' },
    { label: 'spending on holidays', variable: true, for: ECON_E,
      why: 'Some households spend more on holidays than others, and spending is measured in pounds per year.' },

    // --- variables: business ---
    { label: 'brand recall', variable: true, for: ECON_B,
      why: 'Some people can name a brand after seeing an advert and some can\'t. The percentage who recall it can be measured.' },
    { label: 'email open rate', variable: true, for: ECON_B,
      why: 'Some marketing emails are opened by more of the people who receive them than others. The percentage opened can be worked out.' },
    { label: 'number of repeat visits', variable: true, for: ECON_B,
      why: 'Some customers come back once a month and some every day. Visits can be counted from loyalty-card records.' },
    { label: 'number of reviews on a product page', variable: true, for: ECON_B,
      why: 'One product can have three reviews and another three hundred. They can be counted.' },
    { label: 'customer satisfaction rating', variable: true, for: ECON_B,
      why: 'Customers are more pleased with some visits than others, and can rate their satisfaction on a scale.' },
    { label: 'number of times an advert is shown', variable: true, for: ECON_B,
      why: 'An advert can be shown once or fifty times, and the showings can be counted.' },
    { label: 'website loading time', variable: true, for: ECON_B,
      why: 'Some pages load in half a second and some take several seconds. Loading time is measured in seconds.' },
    { label: 'shelf space given to a product', variable: true, for: ECON_B,
      why: 'A shop can give a product a small gap on the shelf or a whole section. The space can be measured in centimetres.' },
    { label: 'loyalty points per pound spent', variable: true, for: ECON_B,
      why: 'A loyalty scheme can give 1 point or 5 points for each pound, so the rate takes different values.' },
    { label: 'click-through rate of an online advert', variable: true, for: ECON_B,
      why: 'Some adverts are clicked by more of the people who see them than others. The percentage can be worked out.' },

    // --- not variables: one particular thing (shared) ---
    { label: 'the till receipt', variable: false,
      why: 'A till receipt is one particular piece of paper. (The total on it, or the number of items listed, would be a variable.)' },
    { label: 'the corner shop on the high street', variable: false,
      why: 'It\'s one particular shop. (How many customers it serves each day would be a variable.)' },
    { label: 'the customer survey', variable: false,
      why: 'A survey is one particular thing. (The scores customers give on it would be a variable.)' },
    { label: 'the pound coin', variable: false,
      why: 'It\'s one particular coin — a thing, not a measurement. (The number of coins in a till would be a variable.)' },
    { label: 'the self-service checkout', variable: false,
      why: 'It\'s one particular machine. (How long customers take to pay at it would be a variable.)' },

    // --- not variables: one particular thing (economics) ---
    { label: 'Adam Smith', variable: false, for: ECON_E,
      why: 'Adam Smith is one particular person. (The number of workers in a pin factory, or how many pins they make a day, would be a variable.)' },
    { label: 'the supply-and-demand diagram', variable: false, for: ECON_E,
      why: 'It\'s one particular diagram. (The price or the quantity shown on it would be a variable.)' },
    { label: 'the classroom auction', variable: false, for: ECON_E,
      why: 'It\'s one particular event. (The winning bid, or the number of bidders, would be a variable.)' },
    { label: 'the fruit and vegetable stall', variable: false, for: ECON_E,
      why: 'It\'s one particular stall. (The price of its apples, or how many it sells, would be a variable.)' },
    { label: 'the savings account', variable: false, for: ECON_E,
      why: 'An account is one particular thing. (The interest it pays, or the amount in it, would be a variable.)' },

    // --- not variables: one particular thing (business) ---
    { label: 'the company logo', variable: false, for: ECON_B,
      why: 'A logo is one particular design. (How many people recognise it would be a variable.)' },
    { label: 'the brand\'s slogan', variable: false, for: ECON_B,
      why: 'It\'s one particular phrase. (The percentage of people who can remember it would be a variable.)' },
    { label: 'the marketing plan', variable: false, for: ECON_B,
      why: 'A plan is one particular document. (The money spent on advertising, or the sales that follow, would be variables.)' },
    { label: 'the shop\'s loyalty card', variable: false, for: ECON_B,
      why: 'It\'s one particular card. (The number of points collected on it, or how often it is used, would be a variable.)' },
    { label: 'the online checkout page', variable: false, for: ECON_B,
      why: 'It\'s one particular web page. (How long it takes to load, or how many people finish paying on it, would be a variable.)' },

    // --- not variables: measurable, but only one possible value ---
    { label: 'the number of pence in a pound', variable: false,
      why: 'It\'s always 100. Something that can only ever have one value is a constant, not a variable.' },
    { label: 'the number of days in a week', variable: false,
      why: 'It\'s always 7 — only one possible value, so it\'s a constant, not a variable.' },
    { label: 'the number of months in a year', variable: false,
      why: 'It\'s always 12. It can be counted, but it doesn\'t vary.' },
  ],

  // -------------------------------------------------------------------------
  // 1b-1d, 2b, 2c. Relations.
  // -------------------------------------------------------------------------
  relations: [
    // --- shared ---
    { id: 'econ-discount-units', iv: 'size of the discount', dv: 'units sold',
      ivNP: 'the size of the discount', dvNP: 'the number of units sold',
      hyp: ['discount', 'units sold'], ivAxis: 'Discount', dvAxis: 'Units sold', dir: 'up',
      says: ['The bigger the discount a shop puts on a product, the more units of it are sold.',
             'Units sold go up as the discount gets bigger.'],
      why: 'The shop sets the discount before customers arrive; the sales are how customers respond. Selling more can\'t go back and change the discount on the label.' },
    { id: 'econ-delivery-orders', iv: 'delivery charge', dv: 'orders placed',
      ivNP: 'the delivery charge', dvNP: 'the number of orders placed',
      hyp: ['delivery charge', 'orders'], ivAxis: 'Delivery charge', dvAxis: 'Orders', dir: 'down',
      says: ['The higher the delivery charge an online shop sets, the fewer orders it receives.',
             'The number of orders placed goes down as the delivery charge goes up.'],
      why: 'The charge is shown before people decide whether to order, so it is the changer. Getting fewer orders can\'t raise a charge that was already set.' },
    { id: 'econ-distance-visits', iv: 'distance to the shop', dv: 'visits per month',
      ivNP: 'the distance to the shop', dvNP: 'the number of visits per month',
      hyp: ['distance', 'visits'], ivAxis: 'Distance', dvAxis: 'Visits', dir: 'down',
      says: ['The further people live from a shop, the less often they visit it.',
             'Visits per month go down as the distance to the shop goes up.'],
      why: 'Where someone lives is settled before they choose to shop, and a longer trip costs time and money. Visiting less often can\'t move a house further away.' },
    { id: 'econ-checkouts-wait', iv: 'checkouts open', dv: 'waiting time',
      ivNP: 'the number of checkouts open', dvNP: 'the waiting time',
      hyp: ['checkouts open', 'waiting time'], ivAxis: 'Checkouts open', dvAxis: 'Waiting time', dir: 'down',
      says: ['When a busy supermarket opens more checkouts, customers wait less time to pay.',
             'Waiting time goes down as the number of checkouts open goes up.'],
      why: 'The manager decides how many checkouts to open, and more tills share out the same customers. A shorter wait can\'t open another till by itself.' },
    { id: 'econ-steps-complete', iv: 'checkout steps', dv: 'orders completed',
      ivNP: 'the number of steps in an online checkout', dvNP: 'the percentage of orders completed',
      hyp: ['checkout steps', 'completed orders'], ivAxis: 'Checkout steps', dvAxis: '% completed', dir: 'down',
      says: ['The more pages shoppers have to click through to pay online, the fewer of them finish their order.',
             'The percentage of orders completed goes down as the number of checkout steps goes up.'],
      why: 'The website designer sets the number of steps; each extra step is another point where shoppers give up. Finishing an order can\'t change how the website was built.' },
    { id: 'econ-wait-satisfaction', iv: 'waiting time', dv: 'satisfaction rating',
      ivNP: 'the time customers wait', dvNP: 'the satisfaction rating',
      hyp: ['waiting time', 'satisfaction'], ivAxis: 'Waiting time', dvAxis: 'Satisfaction', dir: 'down',
      says: ['The longer customers wait to be served, the less satisfied they say they are.',
             'Satisfaction ratings go down as waiting time goes up.'],
      why: 'The wait happens first and the rating is given afterwards, so the wait is the changer. A low rating given at the end can\'t make the wait longer.' },
    { id: 'econ-temp-icecream', iv: 'temperature', dv: 'ice creams sold',
      ivNP: 'the temperature', dvNP: 'the number of ice creams sold',
      hyp: ['temperature', 'ice creams sold'], ivAxis: 'Temperature', dvAxis: 'Ice creams', dir: 'up',
      says: ['A seaside kiosk sells more ice creams on warmer days.',
             'The number of ice creams sold goes up as the temperature goes up.'],
      why: 'The weather is what it is before anyone buys anything; people want cold food when it is hot. Selling ice creams can\'t warm the day up.' },
    { id: 'econ-rain-umbrellas', iv: 'amount of rain', dv: 'umbrellas sold',
      ivNP: 'the amount of rain', dvNP: 'the number of umbrellas sold',
      hyp: ['rain', 'umbrellas sold'], ivAxis: 'Rainfall', dvAxis: 'Umbrellas sold', dir: 'up',
      says: ['A station shop sells more umbrellas on rainier days.',
             'Umbrella sales go up as the amount of rain goes up.'],
      why: 'The rain falls whatever the shop does, and it is the rain that makes people want umbrellas. Selling umbrellas can\'t make it rain.' },
    { id: 'econ-budget-spend', iv: 'budget given', dv: 'amount spent',
      ivNP: 'the budget each participant is given', dvNP: 'the amount spent in the lab shop',
      hyp: ['budget', 'amount spent'], ivAxis: 'Budget', dvAxis: 'Amount spent', dir: 'up',
      says: ['In a lab shopping task, participants given a bigger budget spend more.',
             'The amount spent in the lab shop goes up with the size of the budget given.'],
      why: 'The researcher hands out the budget before the shopping starts, so it is the changer. Spending more can\'t make the budget you were given bigger.' },
    { id: 'econ-footfall-customers', iv: 'passers-by', dv: 'customers entering',
      ivNP: 'the number of people walking past the shop', dvNP: 'the number of customers who come in',
      hyp: ['passers-by', 'customers entering'], ivAxis: 'Passers-by', dvAxis: 'Customers in', dir: 'up',
      says: ['The more people walk past a shop in an hour, the more customers come into it.',
             'The number of customers entering goes up as the number of people walking past goes up.'],
      why: 'People have to pass the door before they can come in, so the passers-by are the changer. A customer walking in can\'t add people to the street.' },

    // --- economics ---
    { id: 'econ-law-demand', for: ECON_E, iv: 'price', dv: 'quantity demanded',
      ivNP: 'the price of the good', dvNP: 'the quantity demanded',
      hyp: ['price', 'quantity demanded'], ivAxis: 'Price', dvAxis: 'Qty demanded', dir: 'down',
      says: ['For most goods, the higher the price, the fewer units people choose to buy.',
             'The quantity demanded goes down as the price goes up — the law of demand.'],
      why: 'The seller sets the price and buyers decide how much to buy at it. Careful: on the textbook diagram price is on the vertical axis, but price is still the changer here.' },
    { id: 'econ-law-supply', for: ECON_E, iv: 'price offered', dv: 'quantity supplied',
      ivNP: 'the price sellers can get', dvNP: 'the quantity supplied',
      hyp: ['price', 'quantity supplied'], ivAxis: 'Price', dvAxis: 'Qty supplied', dir: 'up',
      says: ['The higher the price sellers can get for a good, the more of it they offer for sale.',
             'The quantity supplied goes up as the price goes up — the law of supply.'],
      why: 'Sellers see the price they can get and then decide how much to produce, because a higher price covers the cost of making more. Offering more for sale doesn\'t raise the price.' },
    { id: 'econ-substitute', for: ECON_E, iv: 'price of tea', dv: 'coffee bought',
      ivNP: 'the price of tea', dvNP: 'the amount of coffee bought',
      hyp: ['price of tea', 'coffee bought'], ivAxis: 'Price of tea', dvAxis: 'Coffee bought', dir: 'up',
      says: ['When tea gets more expensive, people buy more coffee instead.',
             'The amount of coffee bought goes up as the price of tea, a substitute, goes up.'],
      why: 'The tea price changes first, and some tea drinkers switch to its substitute. Buying more coffee can\'t set the price on a box of tea.' },
    { id: 'econ-complement', for: ECON_E, iv: 'price of printers', dv: 'ink cartridges sold',
      ivNP: 'the price of printers', dvNP: 'the number of ink cartridges sold',
      hyp: ['printer price', 'cartridges sold'], ivAxis: 'Printer price', dvAxis: 'Cartridges', dir: 'down',
      says: ['When printers get more expensive, fewer ink cartridges are sold.',
             'Sales of ink cartridges go down as the price of printers, a complement, goes up.'],
      why: 'The two goods are used together, so dearer printers mean fewer printers bought and less need for ink. Selling fewer cartridges can\'t set the price of a printer.' },
    { id: 'econ-income-holidays', for: ECON_E, iv: 'household income', dv: 'holiday spending',
      ivNP: 'household income', dvNP: 'spending on holidays',
      hyp: ['income', 'holiday spending'], ivAxis: 'Income', dvAxis: 'Holiday spend', dir: 'up',
      says: ['When a household\'s income rises, it spends more on holidays — holidays are a normal good.',
             'Spending on holidays goes up as household income goes up.'],
      why: 'The income arrives first and sets how much there is to spend. Spending more on a holiday can\'t raise your income — it uses it up.' },
    { id: 'econ-sellers-price', for: ECON_E, iv: 'number of sellers', dv: 'trading price',
      ivNP: 'the number of competing sellers', dvNP: 'the trading price',
      hyp: ['sellers', 'trading price'], ivAxis: 'Sellers', dvAxis: 'Trading price', dir: 'down',
      says: ['In a classroom market, prices end up lower when there are more competing sellers.',
             'The trading price goes down as the number of sellers goes up.'],
      why: 'The lecturer decides how many sellers there are before trading starts; more sellers compete by undercutting each other. A low price can\'t add sellers to the room.' },
    { id: 'econ-bidders-price', for: ECON_E, iv: 'number of bidders', dv: 'winning bid',
      ivNP: 'the number of bidders', dvNP: 'the winning bid',
      hyp: ['bidders', 'winning bid'], ivAxis: 'Bidders', dvAxis: 'Winning bid', dir: 'up',
      says: ['In classroom auctions for the same voucher, the winning bid tends to be higher when there are more bidders.',
             'The winning bid goes up as the number of bidders goes up.'],
      why: 'The number of bidders is fixed before the bidding; with more people there is more likely to be someone who values the voucher highly. A high winning bid can\'t bring more people into the room.' },
    { id: 'econ-interest-saving', for: ECON_E, iv: 'interest rate', dv: 'amount saved',
      ivNP: 'the interest rate offered', dvNP: 'the amount saved',
      hyp: ['interest rate', 'amount saved'], ivAxis: 'Interest rate', dvAxis: 'Amount saved', dir: 'up',
      says: ['In a lab task where participants choose between money now and more money later, they save more when the interest paid on waiting is higher.',
             'The amount participants save goes up as the interest rate offered goes up.'],
      why: 'The researcher sets the rate before each choice; a higher rate makes waiting pay more. Saving more can\'t change the rate on the screen.' },
    { id: 'econ-queue-join', for: ECON_E, iv: 'queue length', dv: '% who join the queue',
      ivNP: 'the length of the queue', dvNP: 'the percentage of arriving customers who join it',
      hyp: ['queue length', 'joining'], ivAxis: 'Queue length', dvAxis: '% who join', dir: 'down',
      says: ['The longer the queue at a food stall, the smaller the share of arriving customers who join it.',
             'The percentage of customers who join goes down as the queue gets longer.'],
      why: 'Customers see the queue first and then decide whether to join, so the queue is the changer. Walking away doesn\'t make the queue longer.' },
    { id: 'econ-cost-supply', for: ECON_E, iv: 'cost per unit', dv: 'quantity supplied',
      ivNP: 'the cost of making each unit', dvNP: 'the quantity supplied at a given price',
      hyp: ['cost per unit', 'quantity supplied'], ivAxis: 'Cost per unit', dvAxis: 'Qty supplied', dir: 'down',
      says: ['When it costs more to make each unit, firms supply less of the good at any given price.',
             'The quantity supplied at a given price goes down as the cost of making each unit goes up.'],
      why: 'Costs such as materials are set before the firm decides how much to make; dearer inputs make some units no longer worth producing. Making less can\'t raise the price of materials.' },

    // --- business ---
    { id: 'econ-loyalty-visits', for: ECON_B, iv: 'loyalty points per £', dv: 'repeat visits',
      ivNP: 'the loyalty points given per pound', dvNP: 'the number of repeat visits',
      hyp: ['loyalty points', 'repeat visits'], ivAxis: 'Points per £', dvAxis: 'Repeat visits', dir: 'up',
      says: ['The more loyalty points a shop gives for each pound spent, the more often its customers come back.',
             'Repeat visits go up as the points given per pound go up.'],
      why: 'The shop sets the points rate, and the reward gives customers a reason to return. Coming back more often can\'t change the rate the scheme pays.' },
    { id: 'econ-reviews-sales', for: ECON_B, iv: 'positive reviews shown', dv: 'purchases',
      ivNP: 'the number of positive reviews shown', dvNP: 'the number of purchases',
      hyp: ['positive reviews', 'purchases'], ivAxis: 'Good reviews', dvAxis: 'Purchases', dir: 'up',
      says: ['A product page that shows more positive customer reviews leads to more purchases.',
             'Purchases go up as the number of positive reviews shown goes up.'],
      why: 'Shoppers read the reviews before they decide to buy, so the reviews are the changer in this test. The purchases being counted can\'t add reviews already on the page.' },
    { id: 'econ-facings-sales', for: ECON_B, iv: 'shelf space', dv: 'units sold',
      ivNP: 'the shelf space given to a product', dvNP: 'the number of units sold',
      hyp: ['shelf space', 'units sold'], ivAxis: 'Shelf space', dvAxis: 'Units sold', dir: 'up',
      says: ['The more shelf space a shop gives a product, the more of it sells.',
             'Sales of a product go up as its shelf space goes up.'],
      why: 'The shop decides the layout before customers arrive, and a bigger display is easier to notice. In this test the space is fixed first, so selling more can\'t widen the shelf.' },
    { id: 'econ-menu-decide', for: ECON_B, iv: 'options on the menu', dv: 'time to decide',
      ivNP: 'the number of options on the menu', dvNP: 'the time taken to decide',
      hyp: ['menu options', 'time to decide'], ivAxis: 'Menu options', dvAxis: 'Time to decide', dir: 'up',
      says: ['The more options there are on a menu, the longer customers take to decide what to order.',
             'Time to decide goes up as the number of menu options goes up.'],
      why: 'The menu is printed before anyone reads it; more options take longer to look through. Taking longer to decide can\'t add dishes to the menu.' },
    { id: 'econ-loading-purchases', for: ECON_B, iv: 'page loading time', dv: 'purchases completed',
      ivNP: 'the page loading time', dvNP: 'the number of purchases completed',
      hyp: ['loading time', 'purchases'], ivAxis: 'Loading time', dvAxis: 'Purchases', dir: 'down',
      says: ['The longer an online shop\'s pages take to load, the fewer purchases are completed.',
             'Purchases completed go down as page loading time goes up.'],
      why: 'Loading time is set by the website before the shopper acts, and slow pages make shoppers give up. Buying less can\'t slow a page down.' },
    { id: 'econ-staff-served', for: ECON_B, iv: 'staff on shift', dv: 'customers served',
      ivNP: 'the number of staff on shift', dvNP: 'the number of customers served per hour',
      hyp: ['staff on shift', 'customers served'], ivAxis: 'Staff on shift', dvAxis: 'Served per hour', dir: 'up',
      says: ['In a busy café with a long queue, the more staff are on the shift, the more customers are served each hour.',
             'Customers served per hour go up as the number of staff on shift goes up.'],
      why: 'The rota is written before the shift, and more hands can serve more people when there is a queue. Serving more customers can\'t put more staff on the rota.' },
    { id: 'econ-adfreq-recall', for: ECON_B, iv: 'times the advert is seen', dv: 'brand recall',
      ivNP: 'the number of times the advert is seen', dvNP: 'brand recall',
      hyp: ['advert showings', 'brand recall'], ivAxis: 'Showings', dvAxis: 'Brand recall', dir: 'up',
      says: ['The more times people see an advert, the more likely they are to remember the brand afterwards.',
             'Brand recall goes up with the number of times the advert is seen.'],
      why: 'The researcher decides how many times to show the advert, and recall is tested afterwards. Remembering the brand can\'t make the advert play again.' },
    { id: 'econ-fields-signup', for: ECON_B, iv: 'fields on the form', dv: '% who finish signing up',
      ivNP: 'the number of fields on a sign-up form', dvNP: 'the percentage of people who finish signing up',
      hyp: ['form fields', 'sign-ups finished'], ivAxis: 'Form fields', dvAxis: '% signed up', dir: 'down',
      says: ['The more boxes a sign-up form asks people to fill in, the fewer of them finish it.',
             'The percentage who finish signing up goes down as the number of form fields goes up.'],
      why: 'The form is designed before anyone fills it in, and each extra box is more effort. Giving up on the form can\'t add boxes to it.' },
    { id: 'econ-coupon-redeemed', for: ECON_B, iv: 'coupon value', dv: 'coupons redeemed',
      ivNP: 'the value of the coupon', dvNP: 'the number of coupons redeemed',
      hyp: ['coupon value', 'coupons redeemed'], ivAxis: 'Coupon value', dvAxis: 'Redeemed', dir: 'up',
      says: ['The more money a coupon takes off, the more of the coupons are used.',
             'The number of coupons redeemed goes up as their value goes up.'],
      why: 'The value is printed on the coupon before it is handed out, so it is the changer. Using more coupons can\'t change what is printed on them.' },
    { id: 'econ-training-errors', for: ECON_B, iv: 'hours of till training', dv: 'till errors',
      ivNP: 'the hours of till training', dvNP: 'the number of till errors',
      hyp: ['training', 'till errors'], ivAxis: 'Training hours', dvAxis: 'Till errors', dir: 'down',
      says: ['The more hours of training new staff get on the tills, the fewer errors they make.',
             'Till errors go down as the hours of training go up.'],
      why: 'The training comes first and the errors are counted during later shifts. Making fewer errors can\'t go back and add training hours.' },
  ],

  // -------------------------------------------------------------------------
  // 2a. Validity and reliability.
  // -------------------------------------------------------------------------
  validity: [
    // valid and reliable
    { valid: true, reliable: true,
      text: 'To measure how many units of a product sell each week, researchers use the shop\'s till records, which log every item scanned. Two researchers who pull the records separately get the same totals.',
      whyValid: 'every item scanned at the till is a unit sold, so the records count exactly what is wanted.',
      whyReliable: 'two researchers working separately get the same totals.' },
    { valid: true, reliable: true,
      text: 'To measure how long customers wait to pay, a camera system logs the moment each customer joins the queue and the moment they reach the till. Timing the same recordings again gives the same waits.',
      whyValid: 'the time from joining the queue to reaching the till is exactly what waiting time means.',
      whyReliable: 'timing the same recordings again gives the same waits.' },
    { valid: true, reliable: true, for: ECON_E,
      text: 'To measure the trading price in a classroom market, every agreed deal is typed into a computer that records its price. Checking the computer log again gives exactly the same prices.',
      whyValid: 'the price each pair agrees on is the trading price.',
      whyReliable: 'checking the log again gives exactly the same prices.' },
    { valid: true, reliable: true, for: ECON_E,
      text: 'To measure how much participants save in a lab task, the computer records the amount each person moves into the savings account over 20 rounds. Running the task again with the same people gives very similar totals.',
      whyValid: 'the money moved into savings is exactly the amount saved.',
      whyReliable: 'the same people give very similar totals when the task is run again, because each total is built from many rounds.' },
    { valid: true, reliable: true, for: ECON_B,
      text: 'To measure what percentage of website visitors buy something, analysts divide the number of completed orders by the number of visits over a month. Two analysts working from the same records get the same percentage.',
      whyValid: 'completed orders out of visits is exactly the share of visitors who buy.',
      whyReliable: 'two analysts working from the same records get the same answer.' },

    // reliable, not valid
    { valid: false, reliable: true,
      text: 'To measure how satisfied customers are with a café, researchers count the chairs in it. Counting again gives the same number.',
      whyValid: 'the number of chairs says nothing about how pleased the customers are.',
      whyReliable: 'counting the chairs again gives the same number. Consistent, but consistently measuring the wrong thing.' },
    { valid: false, reliable: true,
      text: 'To measure how busy a shop is, researchers copy down the opening hours from the sign on the door. The sign says the same thing every time they look.',
      whyValid: 'opening hours are when the shop could be busy, not how many customers actually come.',
      whyReliable: 'the sign gives the same hours every time it is read.' },
    { valid: false, reliable: true, for: ECON_E,
      text: 'To measure how much people want to buy a product, researchers weigh its packaging. The scales give the same weight every time.',
      whyValid: 'the weight of the packaging isn\'t demand — it measures the box, not the buyers.',
      whyReliable: 'weighing the same packaging gives the same result every time.' },
    { valid: false, reliable: true, for: ECON_B,
      text: 'To measure how well people remember a brand after an advert, researchers count the letters in the brand\'s name. Everyone who counts gets the same number.',
      whyValid: 'the length of the name says nothing about whether anyone remembered it.',
      whyReliable: 'counting the letters always gives the same number.' },

    // valid, not reliable
    { valid: true, reliable: false,
      text: 'To see whether 20% off increases sandwich sales, a café tries the discount for one day and compares its sales with the day before. When it repeats this on two other days, the result comes out the other way.',
      whyValid: 'counting sandwiches sold is the right way to measure sales.',
      whyReliable: 'a single day of sales swings with the weather and passing trade, so one day each is far too little to give the same answer twice.' },
    { valid: true, reliable: false,
      text: 'Researchers time how long customers wait at checkouts, but their report doesn\'t say which branches, days or times of day they used. Other researchers who try to repeat the study get very different waits.',
      whyValid: 'timing customers at the checkout is a sensible way to measure waiting.',
      whyReliable: 'without a full "recipe" — which branches, days and times — nobody can repeat the study and get the same result.' },
    { valid: true, reliable: false, for: ECON_E,
      text: 'To find out whether more sellers lower prices, a lecturer runs one classroom market with 2 sellers and one with 8, each with only 3 buyers and a single round of trading. Repeating it with another class gives the opposite result.',
      whyValid: 'recording the agreed prices is the right way to measure the trading price.',
      whyReliable: 'with so few traders and only one round, a couple of unusual deals decide the result. It needs more traders and more rounds.' },
    { valid: true, reliable: false, for: ECON_B,
      text: 'To measure brand recall after a new advert, researchers show it to 5 people and ask them to name the brand. Asking another 5 people gives a very different percentage.',
      whyValid: 'asking people to name the brand is a direct test of recall.',
      whyReliable: 'with only 5 people, one person more or less changes the percentage by 20 points. Far more people are needed.' },
    { valid: true, reliable: false, for: ECON_B,
      text: 'To count the customers who come into a shop, a member of staff counts by eye while also serving at the till. When the same lunchtime is counted again from the door camera, the number is quite different.',
      whyValid: 'counting people coming through the door is the right way to measure customers entering.',
      whyReliable: 'one busy person counting by eye misses people, so a second count of the same lunchtime gives a different number.' },

    // neither
    { valid: false, reliable: false,
      text: 'To measure how many customers a shop serves each hour, researchers note the colour of the car parked nearest the door. It is a different colour each time they look.',
      whyValid: 'the colour of a parked car has nothing to do with how many customers are served.',
      whyReliable: 'it gives a different answer each time.' },
    { valid: false, reliable: false,
      text: 'To measure how much shoppers like a new shop-window display, researchers write down the weather at the moment each shopper walks past. The weather changes from one shopper to the next.',
      whyValid: 'the weather isn\'t a shopper\'s opinion of the display.',
      whyReliable: 'the same display gets a different "score" every time.' },
    { valid: false, reliable: false, for: ECON_E,
      text: 'To measure how much each participant is willing to pay for a mug, researchers roll a die for each person and record the number. The same person gets a different number every time.',
      whyValid: 'a dice roll has nothing to do with what the person would pay.',
      whyReliable: 'rolling again gives a different number for the same person.' },
    { valid: false, reliable: false, for: ECON_B,
      text: 'To measure how satisfied customers are, a manager counts the emails in their own inbox at the end of each day. The count is different every day.',
      whyValid: 'the manager\'s emails aren\'t the customers\' satisfaction.',
      whyReliable: 'the count changes every day for reasons that have nothing to do with the shop.' },
  ],

  // -------------------------------------------------------------------------
  // 2d. Continuous or discrete.
  // -------------------------------------------------------------------------
  continuity: [
    { cat: 'cont', label: 'time spent queuing', why: ECON_CONT + '3 minutes, 3.5 minutes, 3 minutes and 41 seconds... time can always be divided further.' },
    { cat: 'cont', label: 'time spent in a shop', why: ECON_CONT + '12 minutes, 12.4 minutes, 12.43 minutes...' },
    { cat: 'cont', label: 'weight of loose fruit bought', why: ECON_CONT + '0.5 kg, 0.52 kg, 0.523 kg...' },
    { cat: 'cont', label: 'distance travelled to a shop', why: ECON_CONT + '2 km, 2.3 km, 2.35 km...' },
    { cat: 'cont', label: 'website loading time', why: ECON_CONT + '1.2 seconds, 1.25 seconds... time can be measured as finely as the clock allows.' },
    { cat: 'cont', label: 'litres of fuel bought', why: ECON_CONT + '30 litres, 30.47 litres... the pump can stop at any amount.' },
    { cat: 'cont', label: 'time taken to decide from a menu', why: ECON_CONT + '40 seconds, 40.6 seconds...' },
    { cat: 'cont', label: 'floor area of a shop', why: ECON_CONT + '120 m², 120.5 m², 120.55 m²...' },
    { cat: 'cont', label: 'time taken to serve a customer', why: ECON_CONT + '90 seconds, 90.3 seconds... time can always be divided further.' },
    { cat: 'cont', label: 'average number of items per basket', why: ECON_CONT + 'one basket can\'t hold 8.6 items, but an average across baskets can be 8.6.' },
    { cat: 'cont', label: 'length of shelf given to a product', why: ECON_CONT + '40 cm, 40.5 cm... the gap on the shelf can be any width.' },
    { cat: 'cont', label: 'temperature on the day of a sale', why: ECON_CONT + '21°C, 21.4°C, 21.43°C...' },
    { cat: 'cont', label: 'time a shopper looks at a web page', why: ECON_CONT + '15 seconds, 15.2 seconds...' },

    { cat: 'disc', label: 'number of units sold', why: ECON_DISC + 'a shop sells 40 tins or 41, never 40.5.' },
    { cat: 'disc', label: 'number of customers in a queue', why: ECON_DISC + 'there are 5 people or 6, not 5.5.' },
    { cat: 'disc', label: 'number of checkouts open', why: ECON_DISC + 'a till is open or it isn\'t, so there are 4 or 5 open, nothing in between.' },
    { cat: 'disc', label: 'number of sellers in a market', why: ECON_DISC + 'sellers are counted in whole people.', for: ECON_E },
    { cat: 'disc', label: 'number of bidders in an auction', why: ECON_DISC + 'there are 6 bidders or 7, never 6.5.', for: ECON_E },
    { cat: 'disc', label: 'number of trades in a round', why: ECON_DISC + 'each deal is agreed or not, so the total is a whole number.', for: ECON_E },
    { cat: 'disc', label: 'number of reviews on a product page', why: ECON_DISC + 'a page has 12 reviews or 13, nothing in between.', for: ECON_B },
    { cat: 'disc', label: 'number of repeat visits in a month', why: ECON_DISC + 'a customer comes back 3 times or 4, not 3.2.', for: ECON_B },
    { cat: 'disc', label: 'number of staff on a shift', why: ECON_DISC + 'staff are counted in whole people.' },
    { cat: 'disc', label: 'number of options on a menu', why: ECON_DISC + 'a menu has 10 dishes or 11, never 10.5.' },
    { cat: 'disc', label: 'number of items in a basket', why: ECON_DISC + 'items are counted: 8 or 9, never 8.5.' },
    { cat: 'disc', label: 'number of complaints in a week', why: ECON_DISC + 'each complaint is counted once.' },
    { cat: 'disc', label: 'number of emails opened', why: ECON_DISC + 'each email is opened or not, so the total is a whole number.', for: ECON_B },
    { cat: 'disc', label: 'number of visits to a shop in a month', why: ECON_DISC + 'people visit 2 times or 3, not 2.5.' },
  ],

  // -------------------------------------------------------------------------
  // 2e. Levels of measurement.
  // -------------------------------------------------------------------------
  measurement: [
    { cat: 'categorical', label: 'payment method (cash, card or phone)', why: ECON_NOM + 'Paying by card isn\'t more or less than paying by cash, just different.' },
    { cat: 'categorical', label: 'type of shop (supermarket, corner shop or market stall)', why: ECON_NOM + 'These are kinds of shop, not amounts of one.' },
    { cat: 'categorical', label: 'which brand a shopper chooses', why: ECON_NOM + 'One brand isn\'t "more" than another — they are different labels.' },
    { cat: 'categorical', label: 'product category (food, clothing or electronics)', why: ECON_NOM + 'The categories are different kinds of product, with no order.' },
    { cat: 'categorical', label: 'whether a customer has a loyalty card (yes or no)', why: ECON_NOM + 'Yes and no are two groups, not points on a scale.' },
    { cat: 'categorical', label: 'auction format (sealed-bid or open)', why: ECON_NOM + 'A sealed-bid auction isn\'t more than an open one — they are different ways of selling.', for: ECON_E },
    { cat: 'categorical', label: 'which advert a viewer saw (A, B or C)', why: ECON_NOM + 'Advert A, B and C are labels, not amounts.', for: ECON_B },

    { cat: 'ordinal', label: 'satisfaction from "very dissatisfied" to "very satisfied"', why: ECON_ORD + 'The answers are in order, but nothing says the steps are the same size.' },
    { cat: 'ordinal', label: 'shop size (small, medium or large)', why: ECON_ORD + 'In order, but the jump from small to medium needn\'t match the jump from medium to large.' },
    { cat: 'ordinal', label: 'position in a sales league table (1st, 2nd, 3rd)', why: ECON_ORD + 'The gap between 1st and 2nd could be £10; between 2nd and 3rd, £10,000.' },
    { cat: 'ordinal', label: 'delivery option (standard, express or next-hour)', why: ECON_ORD + 'The options are ranked by speed, but the steps between them aren\'t equal.' },
    { cat: 'ordinal', label: 'how likely to recommend: "unlikely", "possibly", "very likely"', why: ECON_ORD + '"Very likely" is above "possibly", but the steps aren\'t equal-sized.' },
    { cat: 'ordinal', label: 'ranking five products from most to least preferred', why: ECON_ORD + 'A ranking gives the order, not how far apart the products are.' },

    { cat: 'interval', label: 'satisfaction rated on a scale of 1–7', why: ECON_INT + 'The numbered steps are treated as equal, but there\'s no zero, so a 6 isn\'t "twice as satisfied" as a 3.' },
    { cat: 'interval', label: 'likelihood of buying rated 1–10', why: ECON_INT + 'A numbered scale has constant steps, but no natural zero.' },
    { cat: 'interval', label: 'date of a purchase', why: ECON_INT + 'Days are equal steps, but the calendar\'s starting point is arbitrary.' },
    { cat: 'interval', label: 'year a firm was founded', why: ECON_INT + 'Years are equal steps, but year 0 isn\'t "no time", so 2000 isn\'t twice 1000.' },
    { cat: 'interval', label: 'time of day a sale is made', why: ECON_INT + 'The minutes are equal, but midnight isn\'t "no time", so 4 o\'clock isn\'t twice 2 o\'clock.' },
    { cat: 'interval', label: 'temperature in the shop in °C', why: ECON_INT + '0°C isn\'t "no temperature", so 20°C isn\'t twice as warm as 10°C.' },
    { cat: 'interval', label: 'how appealing an advert is, rated 1–9', why: ECON_INT + 'The numbered steps are treated as equal, but there\'s no zero on the scale.', for: ECON_B },

    { cat: 'ratio', label: 'price in pounds', why: ECON_RAT + '£0 is free, and £6 is twice £3.' },
    { cat: 'ratio', label: 'number of units sold', why: ECON_RAT + '0 units is no sales at all, and 200 units is twice 100.' },
    { cat: 'ratio', label: 'minutes spent queuing', why: ECON_RAT + '0 minutes is no wait at all, and 10 minutes is twice 5.' },
    { cat: 'ratio', label: 'weekly takings in pounds', why: ECON_RAT + '£0 is no money taken, and £4,000 is twice £2,000.' },
    { cat: 'ratio', label: 'distance travelled to the shop in km', why: ECON_RAT + '0 km is no distance, and 8 km is twice 4 km.' },
    { cat: 'ratio', label: 'number of staff employed', why: ECON_RAT + 'Zero staff means none, and 20 staff is twice 10.' },
    { cat: 'ratio', label: 'amount saved in a lab task', why: ECON_RAT + '£0 is nothing saved, and £8 is twice £4.', for: ECON_E },
    { cat: 'ratio', label: 'website loading time in seconds', why: ECON_RAT + '0 seconds is no wait, and 4 seconds is twice 2.', for: ECON_B },
  ],

  // -------------------------------------------------------------------------
  // 2g. Confounds. Paired: the same study done badly, then done properly.
  // -------------------------------------------------------------------------
  confounds: [
    // --- shared ---
    { iv: 'a discount', dv: 'units of sun cream sold', confound: 'the weather',
      vars: ['a discount', 'units of sun cream sold', 'the weather', 'the shelf the sun cream is on'],
      text: 'A chemist tests whether 20% off sells more sun cream. It runs the discount during a heatwave week and compares sales with a cool, cloudy week at full price. The sun cream stays on the same shelf throughout.',
      why: 'The discount week was also the hot week, and people buy more sun cream when it is sunny. The extra sales could come from the weather, not the discount.' },
    { iv: 'free delivery', dv: 'number of online orders', confound: 'the time of year',
      vars: ['free delivery', 'number of online orders', 'the time of year', 'the products on sale'],
      text: 'An online shop tests whether free delivery brings in more orders. It offers free delivery in the three weeks before Christmas and charges £4 in three weeks of February, selling the same products throughout.',
      why: 'Free delivery was offered in the busiest shopping weeks of the year. More orders could come from Christmas shopping, not from the delivery charge.' },
    { iv: 'checkout type', dv: 'time taken to pay', confound: 'number of items bought',
      vars: ['checkout type', 'time taken to pay', 'number of items bought', 'the supermarket branch'],
      text: 'Researchers compare how long customers take to pay at staffed and self-service checkouts in the same supermarket. The self-service tills are only for baskets, while customers with full trolleys use the staffed tills.',
      why: 'The staffed-till customers were also buying far more items, and more items take longer to scan. Any difference could come from the shopping, not the type of checkout.' },
    { iv: 'till training course', dv: 'number of till errors', confound: 'experience of the staff',
      vars: ['till training course', 'number of till errors', 'experience of the staff', 'the tills used'],
      text: 'A shop tests whether a training course reduces till errors. The staff who take the course have all worked there for years; the ones who don\'t are all new starters. Everyone uses the same tills.',
      why: 'The trained staff were also the experienced ones, who would make fewer errors anyway. The difference could come from experience, not the course.' },

    // --- economics ---
    { iv: 'number of sellers', dv: 'trading price', confound: 'buyers\' budgets', for: ECON_E,
      vars: ['number of sellers', 'trading price', 'buyers\' budgets', 'the goods traded'],
      text: 'A lecturer tests whether more sellers lower prices in a classroom market. In the 8-seller market, buyers are given budgets of £2; in the 2-seller market, buyers are given £10. Both markets trade the same tokens.',
      why: 'The 8-seller market also had buyers with much less money to spend, which would push prices down anyway. The lower prices could come from the budgets, not the number of sellers.' },
    { iv: 'interest rate', dv: 'amount saved', confound: 'starting amount', for: ECON_E,
      vars: ['interest rate', 'amount saved', 'starting amount', 'the number of rounds'],
      text: 'Researchers test whether a higher interest rate makes participants save more in a lab task. The high-interest group starts with £20 to split between now and later; the low-interest group starts with £5. Both play the same number of rounds.',
      why: 'The high-interest group also had four times as much money, so they could save more pounds whatever the rate. The difference could come from the starting amount, not the interest rate.' },
    { iv: 'number of bidders', dv: 'winning bid', confound: 'value of the voucher', for: ECON_E,
      vars: ['number of bidders', 'winning bid', 'value of the voucher', 'the auction format'],
      text: 'A lecturer tests whether more bidders push up the winning bid in classroom auctions. The auctions with 20 bidders sell a £10 voucher and the auctions with 4 bidders sell a £2 voucher. All use the same open format.',
      why: 'The big auctions were also selling a voucher worth five times as much. Higher winning bids could come from the voucher, not the number of bidders.' },
    { iv: 'price of the snack', dv: 'number of snacks bought', confound: 'the brand', for: ECON_E,
      vars: ['price of the snack', 'number of snacks bought', 'the brand', 'the budget given'],
      text: 'Researchers test the law of demand in a lab shop where participants spend the same budget. The snack priced at £1 is a well-known brand, and the snack priced at £3 is an unknown brand.',
      why: 'The cheaper snack was also the familiar brand, which people may prefer anyway. The difference could come from the brand, not the price.' },

    // --- business ---
    { iv: 'number of advert showings', dv: 'brand recall', confound: 'delay before the test', for: ECON_B,
      vars: ['number of advert showings', 'brand recall', 'delay before the test', 'the advert'],
      text: 'Researchers test whether seeing an advert five times improves brand recall. The five-times group is tested straight away; the once group is tested the next day. Both see the same advert.',
      why: 'The once group also had a day to forget in, and memories fade with time. The difference could come from the delay, not the number of showings.' },
    { iv: 'loyalty scheme', dv: 'number of repeat visits', confound: 'branch location', for: ECON_B,
      vars: ['loyalty scheme', 'number of repeat visits', 'branch location', 'the products on sale'],
      text: 'A chain tests whether a loyalty scheme brings customers back more often. It starts the scheme at its busy town-centre branch and compares with a quiet out-of-town branch without it. Both sell the same products.',
      why: 'The scheme branch is also the town-centre one, where people pass every day on their way to work. More repeat visits could come from the location, not the scheme.' },
    { iv: 'page loading speed', dv: 'number of purchases completed', confound: 'device used', for: ECON_B,
      vars: ['page loading speed', 'number of purchases completed', 'device used', 'the products shown'],
      text: 'An online shop tests whether faster pages lead to more purchases. The fast version is shown to visitors on computers, and the slow version to visitors on phones. Both versions show the same products.',
      why: 'The fast-page visitors were also on computers, where filling in payment details is easier. The difference could come from the device, not the loading speed.' },

    // --- shared, done properly ---
    { iv: 'a discount', dv: 'units of sun cream sold', confound: null,
      text: 'A chemist tests whether 20% off sells more sun cream. Across the summer, a coin toss decides each week whether the discount runs, and the sun cream stays on the same shelf throughout.',
      why: 'Deciding at random spreads hot and cool weeks across both conditions, so the discount is the only systematic difference.' },
    { iv: 'free delivery', dv: 'number of online orders', confound: null,
      text: 'An online shop tests whether free delivery brings in more orders. During the same three weeks, each visitor is randomly shown either free delivery or a £4 charge on the same products.',
      why: 'Same weeks, same products, random visitors — only the delivery charge differs.' },
    { iv: 'checkout type', dv: 'time taken to pay', confound: null,
      text: 'Researchers compare staffed and self-service checkouts. Participants each buy the same basket of 10 items and are randomly assigned to pay at one kind of till.',
      why: 'Same shopping, random assignment — the type of checkout is the only difference.' },
    { iv: 'till training course', dv: 'number of till errors', confound: null,
      text: 'A shop tests whether a training course reduces till errors. New starters are randomly split into two groups, and only one group takes the course. Everyone uses the same tills.',
      why: 'All new starters, split at random, on the same tills — only the course differs.' },

    // --- economics, done properly ---
    { iv: 'number of sellers', dv: 'trading price', confound: null, for: ECON_E,
      text: 'A lecturer tests whether more sellers lower prices. Students are randomly assigned to a 2-seller or an 8-seller market, and buyers in both are given the same £10 budget and trade the same tokens.',
      why: 'Same budgets, same tokens, random traders — the number of sellers is the only difference.' },
    { iv: 'interest rate', dv: 'amount saved', confound: null, for: ECON_E,
      text: 'Researchers test whether a higher interest rate makes participants save more. Everyone starts with £20, and participants are randomly assigned to a 2% or a 10% rate for the same number of rounds.',
      why: 'Same starting money, same rounds, random groups — only the interest rate differs.' },
    { iv: 'number of bidders', dv: 'winning bid', confound: null, for: ECON_E,
      text: 'A lecturer tests whether more bidders push up the winning bid. Every auction sells the same £10 voucher in the same open format, and students are randomly split into auctions of 4 or 20 bidders.',
      why: 'Same voucher, same format, random groups — only the number of bidders differs.' },
    { iv: 'price of the snack', dv: 'number of snacks bought', confound: null, for: ECON_E,
      text: 'Researchers test the law of demand in a lab shop. Every participant gets the same budget and the same snack, and is randomly assigned to see it priced at £1 or £3.',
      why: 'Same snack, same budget, random groups — only the price differs.' },

    // --- business, done properly ---
    { iv: 'number of advert showings', dv: 'brand recall', confound: null, for: ECON_B,
      text: 'Researchers test whether seeing an advert five times improves recall. Participants are randomly assigned to see the same advert once or five times, and everyone is tested the next day.',
      why: 'Same advert, same delay, random groups — only the number of showings differs.' },
    { iv: 'loyalty scheme', dv: 'number of repeat visits', confound: null, for: ECON_B,
      text: 'A chain tests whether a loyalty scheme brings customers back. It picks 20 similar town-centre branches and a coin toss decides which 10 start the scheme. All sell the same products.',
      why: 'Similar branches, chosen at random — the scheme is the only systematic difference.' },
    { iv: 'page loading speed', dv: 'number of purchases completed', confound: null, for: ECON_B,
      text: 'An online shop tests whether faster pages lead to more purchases. Each visitor, whatever device they use, is randomly shown the fast or the slow version of the same pages.',
      why: 'Random assignment spreads phones and computers across both versions, so only the loading speed differs.' },
  ],

  // -------------------------------------------------------------------------
  // 2j. Within or between subjects. Pairs: the same study both ways.
  // -------------------------------------------------------------------------
  designs: [
    // --- within ---
    { cat: 'within',
      label: 'Every participant shops in a mock online store twice: once with a product at full price and once with it at 20% off. The number of units each person buys in the two visits is compared.',
      ivs: [ECON_DISCOUNT], dv: ECON_UNITS,
      others: [ECON_P, { name: 'the mock online store', aliases: ['store', 'online store', 'mock store', 'website', 'shop'] }] },
    { cat: 'within',
      label: 'Each participant places one order in a practice online shop with free delivery and one with a £4 delivery charge. The number of items in each person\'s two orders is compared.',
      ivs: [ECON_DELIVERY], dv: ECON_ITEMS,
      others: [ECON_P, { name: 'the practice online shop', aliases: ['practice shop', 'online shop', 'website'] }] },
    { cat: 'within',
      label: 'Every shopper pays for the same basket once at a staffed checkout and once at a self-service checkout, and the time each person takes to pay at the two is compared.',
      ivs: [ECON_CHECKOUT], dv: ECON_PAYTIME,
      others: [ECON_SHOPPERS, { name: 'the basket', aliases: ['basket', 'same basket', 'shopping'] }] },
    { cat: 'within', for: ECON_E,
      label: 'Every student takes part in both a sealed-bid auction and an open auction for the same kind of voucher, and the price paid by the winner in each is compared.',
      ivs: [ECON_AUCTION], dv: ECON_PRICEPAID,
      others: [{ name: 'the students', aliases: ['students', 'class', 'bidders', 'participants'] }, { name: 'the voucher', aliases: ['voucher', 'prize', 'item'] }] },
    { cat: 'within', for: ECON_E,
      label: 'In a lab task, each participant decides how much to save from an endowment when the interest rate is 2% and again when it is 10%. The amount each person saves at the two rates is compared.',
      ivs: [ECON_RATE], dv: ECON_SAVED,
      others: [ECON_P, { name: 'the endowment', aliases: ['endowment', 'money given', 'starting money'] }] },
    { cat: 'within', for: ECON_E,
      label: 'The same group of students trades in a classroom market with 2 sellers in one round and with 8 sellers in another, and the trading price in the two rounds is compared.',
      ivs: [ECON_SELLERS], dv: ECON_TRADEPRICE,
      others: [{ name: 'the students', aliases: ['students', 'class', 'traders', 'group'] }] },
    { cat: 'within', for: ECON_E,
      label: 'Each participant spends a lab budget once when a snack costs £1 and once when it costs £3, and the number of snacks each person buys at the two prices is compared.',
      ivs: [ECON_LABPRICE], dv: ECON_SNACKS,
      others: [ECON_P, { name: 'the lab budget', aliases: ['budget', 'lab budget', 'money'] }] },
    { cat: 'within', for: ECON_B,
      label: 'Every participant watches a programme in which one brand\'s advert appears once and another brand\'s advert appears five times. The next day, their recall of the two brands is compared.',
      ivs: [ECON_ADREP], dv: ECON_RECALL,
      others: [ECON_P, { name: 'the programme', aliases: ['programme', 'show', 'tv programme'] }] },
    { cat: 'within', for: ECON_B,
      label: 'Each participant orders from a 5-option menu and from a 20-option menu, and the time each person takes to decide is compared across the two menus.',
      ivs: [ECON_MENU], dv: ECON_DECIDE,
      others: [ECON_P] },
    { cat: 'within', for: ECON_B,
      label: 'Every participant shops on a fast-loading and a slow-loading version of the same website, and the number of items each person adds to their basket on the two versions is compared.',
      ivs: [ECON_LOAD], dv: ECON_BASKET,
      others: [ECON_P, { name: 'the website', aliases: ['website', 'same website', 'site', 'version'] }] },
    { cat: 'within', for: ECON_B,
      label: 'In a virtual supermarket, each shopper does several shops in which a cereal is sometimes at eye level and sometimes on the bottom shelf. The number of times each person picks it in the two positions is compared.',
      ivs: [ECON_SHELF], dv: ECON_CHOSEN,
      others: [ECON_SHOPPERS, { name: 'the cereal', aliases: ['cereal', 'product', 'box'] }] },

    // --- between ---
    { cat: 'between',
      label: 'Participants are randomly assigned to shop in a mock online store where a product is either at full price or at 20% off. The number of units each group buys is compared.',
      ivs: [ECON_DISCOUNT], dv: ECON_UNITS,
      others: [ECON_P, { name: 'the mock online store', aliases: ['store', 'online store', 'mock store', 'website', 'shop'] }] },
    { cat: 'between',
      label: 'One group of participants orders from a practice online shop with free delivery, and a different group orders with a £4 delivery charge. The number of items the two groups order is compared.',
      ivs: [ECON_DELIVERY], dv: ECON_ITEMS,
      others: [{ name: 'the groups', aliases: ['groups', 'group', 'participants', 'people'] }] },
    { cat: 'between',
      label: 'Shoppers carrying the same basket are randomly sent to either a staffed or a self-service checkout, and the two groups\' times to pay are compared.',
      ivs: [ECON_CHECKOUT], dv: ECON_PAYTIME,
      others: [ECON_SHOPPERS, { name: 'the basket', aliases: ['basket', 'same basket', 'shopping'] }] },
    { cat: 'between', for: ECON_E,
      label: 'Half the class bids in a sealed-bid auction and the other half in an open auction for the same kind of voucher. The prices paid by the winners in the two groups are compared.',
      ivs: [ECON_AUCTION], dv: ECON_PRICEPAID,
      others: [{ name: 'the class', aliases: ['class', 'students', 'half the class', 'bidders'] }, { name: 'the voucher', aliases: ['voucher', 'prize', 'item'] }] },
    { cat: 'between', for: ECON_E,
      label: 'Participants are randomly assigned to a lab savings task paying 2% or one paying 10%, and the amount each group saves is compared.',
      ivs: [ECON_RATE], dv: ECON_SAVED,
      others: [ECON_P] },
    { cat: 'between', for: ECON_E,
      label: 'Students are randomly split between a classroom market with 2 sellers and one with 8 sellers, and the trading prices in the two markets are compared.',
      ivs: [ECON_SELLERS], dv: ECON_TRADEPRICE,
      others: [{ name: 'the students', aliases: ['students', 'class', 'traders', 'group'] }] },
    { cat: 'between', for: ECON_E,
      label: 'One group of participants spends a lab budget when a snack costs £1, and a different group when it costs £3. The number of snacks bought by the two groups is compared.',
      ivs: [ECON_LABPRICE], dv: ECON_SNACKS,
      others: [{ name: 'the groups', aliases: ['groups', 'group', 'participants', 'people'] }] },
    { cat: 'between', for: ECON_B,
      label: 'One group of participants sees an advert once and a different group sees it five times. The next day, the two groups\' recall of the brand is compared.',
      ivs: [ECON_ADREP], dv: ECON_RECALL,
      others: [{ name: 'the groups', aliases: ['groups', 'group', 'participants', 'people'] }] },
    { cat: 'between', for: ECON_B,
      label: 'Participants are randomly given either a 5-option menu or a 20-option menu, and the time each group takes to decide is compared.',
      ivs: [ECON_MENU], dv: ECON_DECIDE,
      others: [ECON_P] },
    { cat: 'between', for: ECON_B,
      label: 'Visitors to a website are randomly shown a fast-loading or a slow-loading version, and the number of items added to the basket in the two groups is compared.',
      ivs: [ECON_LOAD], dv: ECON_BASKET,
      others: [{ name: 'the visitors', aliases: ['visitors', 'people', 'users', 'participants'] }] },
    { cat: 'between', for: ECON_B,
      label: 'In a virtual supermarket, one group of shoppers finds a cereal at eye level and another group finds it on the bottom shelf. The number of times it is picked in each group is compared.',
      ivs: [ECON_SHELF], dv: ECON_CHOSEN,
      others: [{ name: 'the groups of shoppers', aliases: ['groups', 'group', 'shoppers', 'customers'] }] },
  ],

  // -------------------------------------------------------------------------
  // 2f-2h. Cross-sectional, longitudinal, or both.
  // -------------------------------------------------------------------------
  crosslong: {
    single: [
      { cat: 'cross',
        label: 'On the same day, waiting times at the checkout are recorded at supermarket branches that have self-service tills and at branches that don\'t, and the two kinds of branch are compared.',
        ivs: [{ name: 'self-service tills (has them or not)', aliases: ['self-service', 'self-service tills', 'tills', 'has them or not', 'type of branch', 'branch', 'self checkout'] }],
        dv: { name: 'waiting time', aliases: ['waiting time', 'wait', 'queue time', 'how long they wait', 'queuing'] },
        others: [{ name: 'the day of recording', aliases: ['same day', 'day', 'one day'] }] },
      { cat: 'cross', for: ECON_E,
        label: 'In one week, researchers record the price of the same loaf of bread in supermarkets, corner shops and market stalls, and compare the prices across the three types of shop.',
        ivs: [{ name: 'type of shop', aliases: ['type of shop', 'shop type', 'supermarket', 'corner shop', 'market stall', 'shop', 'outlet'] }],
        dv: { name: 'price of the loaf', aliases: ['price', 'price of bread', 'bread price', 'cost', 'how much it costs'] },
        others: [{ name: 'the week', aliases: ['week', 'one week', 'same week'] }] },
      { cat: 'cross', for: ECON_E,
        label: 'In a single classroom session, students who have taken part in auctions before and students bidding for the first time bid for the same voucher, and the two groups\' bids are compared.',
        ivs: [{ name: 'auction experience (experienced or first time)', aliases: ['experience', 'auction experience', 'experienced', 'first time', 'first-timers', 'novice', 'group'] }],
        dv: { name: 'size of the bid', aliases: ['bid', 'bids', 'size of bid', 'amount bid', 'how much they bid', 'offer'] },
        others: [{ name: 'the voucher', aliases: ['voucher', 'prize', 'same voucher'] }] },
      { cat: 'cross', for: ECON_B,
        label: 'On one Saturday, the spend of customers who have a loyalty card and customers who don\'t is recorded at the same supermarket, and the two groups are compared.',
        ivs: [{ name: 'loyalty card (has one or not)', aliases: ['loyalty card', 'card', 'loyalty', 'card holder', 'has one or not', 'member', 'group'] }],
        dv: { name: 'amount spent', aliases: ['amount spent', 'spend', 'spending', 'basket spend', 'how much they spend', 'money spent'] },
        others: [{ name: 'the supermarket', aliases: ['supermarket', 'shop', 'store'] }] },
      { cat: 'cross', for: ECON_B,
        label: 'In one month, customers of a chain\'s town-centre, retail-park and station branches rate their satisfaction, and the three kinds of branch are compared.',
        ivs: [{ name: 'branch location', aliases: ['branch location', 'location', 'branch', 'town centre', 'retail park', 'station', 'kind of branch', 'where the branch is'] }],
        dv: { name: 'satisfaction rating', aliases: ['satisfaction', 'satisfaction rating', 'rating', 'how satisfied', 'customer satisfaction'] },
        others: [{ name: 'the month', aliases: ['month', 'one month'] }] },

      { cat: 'long',
        label: 'A new café counts its customers every week for its first year of trading.',
        ivs: [{ name: 'time (week of trading)', aliases: ['week of trading', 'first year', 'every week', 'trading', ...ECON_TIME] }],
        dv: { name: 'number of customers', aliases: ['customers', 'number of customers', 'how many customers', 'footfall', 'trade', 'visitors'] },
        others: [{ name: 'the café', aliases: ['café', 'cafe', 'coffee shop', 'shop'] }] },
      { cat: 'long', for: ECON_E,
        label: 'The same 200 households record how much they spend on groceries every month for two years.',
        ivs: [{ name: 'time (month)', aliases: ['every month', 'two years', 'monthly', ...ECON_TIME] }],
        dv: { name: 'grocery spending', aliases: ['grocery spending', 'spending', 'spend', 'how much they spend', 'groceries', 'money spent', 'food spending'] },
        others: [{ name: 'the households', aliases: ['households', 'families', 'homes', '200 households'] }] },
      { cat: 'long', for: ECON_E,
        label: 'The same group of students trades in a classroom market for 10 rounds, and the average trading price is recorded in every round.',
        ivs: [{ name: 'time (round of trading)', aliases: ['round', 'rounds', 'round of trading', '10 rounds', 'each round', 'trading round', ...ECON_TIME] }],
        dv: { name: 'average trading price', aliases: ['trading price', 'price', 'average price', 'prices', 'agreed price', 'market price'] },
        others: [{ name: 'the students', aliases: ['students', 'class', 'traders', 'group'] }] },
      { cat: 'long', for: ECON_B,
        label: 'A new online shop records the number of visitors to its website every day for three months after launch.',
        ivs: [{ name: 'time (days since launch)', aliases: ['days since launch', 'since launch', 'launch', 'every day', 'three months', ...ECON_TIME] }],
        dv: { name: 'number of visitors', aliases: ['visitors', 'number of visitors', 'visits', 'traffic', 'how many people visit', 'web traffic'] },
        others: [{ name: 'the website', aliases: ['website', 'site', 'online shop'] }] },
      { cat: 'long', for: ECON_B,
        label: 'The same customers of a new broadband service rate their satisfaction after 1 month, 6 months and 12 months.',
        ivs: [{ name: 'time since joining', aliases: ['time since joining', 'joining', '1 month', '6 months', '12 months', 'how long they have been customers', ...ECON_TIME] }],
        dv: { name: 'satisfaction rating', aliases: ['satisfaction', 'satisfaction rating', 'rating', 'how satisfied', 'customer satisfaction'] },
        others: [{ name: 'the customers', aliases: ['customers', 'people', 'users', 'subscribers'] }] },
    ],

    multi: [
      { cat: 'cross',
        label: 'On the same day, waiting times are recorded in the morning and the evening at supermarket branches with self-service tills and at branches without, and compared.',
        ivs: [
          { name: 'self-service tills (has them or not)', aliases: ['self-service', 'self-service tills', 'tills', 'has them or not', 'type of branch', 'branch', 'self checkout'] },
          { name: 'time of day (morning or evening)', aliases: ['time of day', 'morning', 'evening', 'morning or evening', 'part of the day'] },
        ],
        dv: { name: 'waiting time', aliases: ['waiting time', 'wait', 'queue time', 'how long they wait', 'queuing'] },
        others: [{ name: 'the day of recording', aliases: ['same day', 'one day'] }] },
      { cat: 'cross', for: ECON_E,
        label: 'In one week, researchers record the prices of a loaf of bread and a pint of milk in supermarkets, corner shops and market stalls, and compare them.',
        ivs: [
          { name: 'type of shop', aliases: ['type of shop', 'shop type', 'supermarket', 'corner shop', 'market stall', 'shop', 'outlet'] },
          { name: 'product (bread or milk)', aliases: ['product', 'bread or milk', 'bread', 'milk', 'item', 'good', 'which product'] },
        ],
        dv: { name: 'price', aliases: ['price', 'prices', 'cost', 'how much it costs'] },
        others: [{ name: 'the week', aliases: ['week', 'one week', 'same week'] }] },
      { cat: 'cross', for: ECON_E,
        label: 'In a single session, experienced and first-time bidders take part in a sealed-bid and an open auction for the same voucher, and their bids are compared.',
        ivs: [
          { name: 'auction experience (experienced or first time)', aliases: ['experience', 'auction experience', 'experienced', 'first time', 'first-timers', 'novice'] },
          ECON_AUCTION,
        ],
        dv: { name: 'size of the bid', aliases: ['size of bid', 'amount bid', 'how much they bid', 'offer', 'bids'] },
        others: [{ name: 'the voucher', aliases: ['voucher', 'prize', 'same voucher'] }] },
      { cat: 'cross', for: ECON_B,
        label: 'At one supermarket, the spend of loyalty-card holders and non-holders is recorded on a weekday and on a Saturday of the same week, and compared.',
        ivs: [
          { name: 'loyalty card (has one or not)', aliases: ['loyalty card', 'card', 'loyalty', 'card holder', 'has one or not', 'member'] },
          { name: 'day (weekday or Saturday)', aliases: ['weekday or saturday', 'weekday', 'saturday', 'weekend', 'day of the week', 'which day'] },
        ],
        dv: { name: 'amount spent', aliases: ['amount spent', 'spend', 'spending', 'basket spend', 'how much they spend', 'money spent'] },
        others: [{ name: 'the supermarket', aliases: ['supermarket', 'shop', 'store'] }] },

      { cat: 'long',
        label: 'A new café counts its morning customers and its afternoon customers separately every week for its first year of trading.',
        ivs: [
          { name: 'time (week of trading)', aliases: ['week of trading', 'first year', 'every week', 'trading', ...ECON_TIME] },
          { name: 'part of the day (morning or afternoon)', aliases: ['part of the day', 'morning', 'afternoon', 'morning or afternoon', 'time of day'] },
        ],
        dv: { name: 'number of customers', aliases: ['customers', 'number of customers', 'how many customers', 'footfall', 'trade', 'visitors'] },
        others: [{ name: 'the café', aliases: ['café', 'cafe', 'coffee shop', 'shop'] }] },
      { cat: 'long', for: ECON_E,
        label: 'The same 200 households record how much they spend on food and how much on clothing every month for two years.',
        ivs: [
          { name: 'time (month)', aliases: ['every month', 'two years', 'monthly', ...ECON_TIME] },
          { name: 'type of spending (food or clothing)', aliases: ['type of spending', 'food or clothing', 'food', 'clothing', 'clothes', 'category', 'what they buy'] },
        ],
        dv: { name: 'amount spent', aliases: ['amount spent', 'spending', 'spend', 'how much they spend', 'money spent', 'expenditure'] },
        others: [{ name: 'the households', aliases: ['households', 'families', 'homes', '200 households'] }] },
      { cat: 'long', for: ECON_E,
        label: 'The same 50 shoppers record their weekly spending in shops and their weekly spending online, every week for twelve weeks.',
        ivs: [
          { name: 'time (week)', aliases: ['every week', 'twelve weeks', 'weekly', ...ECON_TIME] },
          { name: 'where they shop (in shops or online)', aliases: ['where they shop', 'in shops or online', 'online', 'in shops', 'in store', 'channel', 'shopping channel'] },
        ],
        dv: { name: 'amount spent', aliases: ['amount spent', 'spending', 'spend', 'how much they spend', 'money spent', 'expenditure'] },
        others: [{ name: 'the shoppers', aliases: ['shoppers', '50 shoppers', 'customers', 'people', 'participants'] }] },
      { cat: 'long', for: ECON_B,
        label: 'A new online shop records the number of visitors using phones and the number using computers every day for three months after launch.',
        ivs: [
          { name: 'time (days since launch)', aliases: ['days since launch', 'since launch', 'launch', 'every day', 'three months', ...ECON_TIME] },
          { name: 'device (phone or computer)', aliases: ['device', 'phone or computer', 'phone', 'computer', 'mobile', 'laptop', 'desktop'] },
        ],
        dv: { name: 'number of visitors', aliases: ['visitors', 'number of visitors', 'visits', 'traffic', 'how many people visit', 'web traffic'] },
        others: [{ name: 'the website', aliases: ['website', 'site', 'online shop'] }] },
    ],

    panel: [
      { cat: 'both', for: ECON_E,
        label: 'One classroom market has 2 sellers and another has 8 sellers. The average trading price in both markets is recorded in each of 10 rounds.',
        ivs: [
          { name: 'number of sellers (2 or 8)', aliases: ['number of sellers', 'sellers', '2 or 8', 'competition', 'competitors', 'how many sellers', 'market', 'group'] },
          { name: 'time (round of trading)', aliases: ['round', 'rounds', 'round of trading', '10 rounds', 'each round', 'trading round', ...ECON_TIME] },
        ],
        dv: { name: 'average trading price', aliases: ['trading price', 'price', 'average price', 'prices', 'agreed price', 'market price'] },
        others: [] },
      { cat: 'both', for: ECON_E,
        label: 'In a lab savings task, one group of participants is offered 2% interest and another group 10%. Both groups\' savings are recorded in each of six rounds.',
        ivs: [
          { name: 'interest rate (2% or 10%)', aliases: ['interest rate', 'interest', 'rate', '2% or 10%', 'low or high interest', 'return', 'group'] },
          { name: 'time (round)', aliases: ['round', 'rounds', 'six rounds', 'each round', ...ECON_TIME] },
        ],
        dv: ECON_SAVED,
        others: [] },
      { cat: 'both', for: ECON_E,
        label: 'Experienced bidders and first-time bidders each take part in five classroom auctions, one a week, and everyone\'s bids are recorded in every auction.',
        ivs: [
          { name: 'auction experience (experienced or first time)', aliases: ['experience', 'auction experience', 'experienced', 'first time', 'first-timers', 'novice', 'group'] },
          { name: 'time (auction number)', aliases: ['auction number', 'five auctions', 'each auction', 'which auction', 'one a week', ...ECON_TIME] },
        ],
        dv: { name: 'size of the bid', aliases: ['size of bid', 'amount bid', 'how much they bid', 'offer', 'bids'] },
        others: [] },
      { cat: 'both',
        label: 'One group of households is given a price-comparison app and another group is not. Both groups record their grocery spending every month for six months.',
        ivs: [
          { name: 'price-comparison app (given or not)', aliases: ['app', 'price-comparison app', 'price comparison', 'given or not', 'no app', 'group', 'comparison app'] },
          { name: 'time (month)', aliases: ['every month', 'six months', 'monthly', ...ECON_TIME] },
        ],
        dv: { name: 'grocery spending', aliases: ['grocery spending', 'spending', 'spend', 'how much they spend', 'groceries', 'money spent'] },
        others: [] },
      { cat: 'both',
        label: 'New till staff are trained either on a one-day course or on the job. Both groups\' till errors are counted every week for eight weeks.',
        ivs: [
          { name: 'training (course or on the job)', aliases: ['training', 'course', 'on the job', 'course or on the job', 'training method', 'type of training', 'group'] },
          { name: 'time (week)', aliases: ['every week', 'eight weeks', 'weekly', ...ECON_TIME] },
        ],
        dv: { name: 'number of till errors', aliases: ['till errors', 'errors', 'mistakes', 'number of errors', 'how many errors', 'accuracy'] },
        others: [] },
      { cat: 'both', for: ECON_B,
        label: 'A chain starts a loyalty scheme at some of its branches but not others. Customer visits at both kinds of branch are counted every month for a year.',
        ivs: [
          { name: 'loyalty scheme (or not)', aliases: ['loyalty scheme', 'scheme', 'loyalty', 'no scheme', 'scheme or not', 'kind of branch', 'group'] },
          { name: 'time (month)', aliases: ['every month', 'a year', 'monthly', ...ECON_TIME] },
        ],
        dv: { name: 'number of customer visits', aliases: ['visits', 'customer visits', 'number of visits', 'customers', 'footfall', 'how many visit'] },
        others: [] },
      { cat: 'both', for: ECON_B,
        label: 'New customers of an online shop are randomly sent a welcome email or no email. Both groups\' purchases are counted every month for six months.',
        ivs: [
          { name: 'welcome email (or none)', aliases: ['welcome email', 'email', 'no email', 'email or none', 'message', 'group'] },
          { name: 'time (month)', aliases: ['every month', 'six months', 'monthly', ...ECON_TIME] },
        ],
        dv: { name: 'number of purchases', aliases: ['purchases', 'number of purchases', 'orders', 'how many they buy', 'buying', 'sales'] },
        others: [] },
    ],
  },

  // -------------------------------------------------------------------------
  // Level 3. Factors for box notation.
  // -------------------------------------------------------------------------
  factors: [
    { name: 'Price', levels: { 2: ['£1', '£3'], 3: ['£1', '£2', '£3'], 4: ['£1', '£2', '£3', '£4'] } },
    { name: 'Discount', levels: { 2: ['full price', '20% off'], 3: ['none', '10% off', '20% off'], 4: ['none', '10% off', '20% off', '30% off'] } },
    { name: 'Delivery charge', levels: { 2: ['free', '£4'], 3: ['free', '£2', '£4'] } },
    { name: 'Checkout type', levels: { 2: ['staffed', 'self-service'] } },
    { name: 'Type of shop', levels: { 2: ['supermarket', 'corner shop'], 3: ['supermarket', 'corner shop', 'market stall'] } },
    { name: 'Queue length', levels: { 2: ['short', 'long'], 3: ['2 people', '6 people', '10 people'], 4: ['none', '3 people', '6 people', '9 people'] } },
    { name: 'Number of sellers', levels: { 2: ['2 sellers', '8 sellers'], 3: ['2 sellers', '4 sellers', '8 sellers'], 4: ['2 sellers', '4 sellers', '8 sellers', '16 sellers'] }, for: ECON_E },
    { name: 'Interest rate', levels: { 2: ['2%', '10%'], 3: ['2%', '5%', '10%'], 4: ['0%', '2%', '5%', '10%'] }, for: ECON_E },
    { name: 'Auction format', levels: { 2: ['sealed-bid', 'open'] }, for: ECON_E },
    { name: 'Advert showings', levels: { 2: ['once', 'five times'], 3: ['once', '3 times', '5 times'], 4: ['once', '3 times', '5 times', '10 times'] }, for: ECON_B },
    { name: 'Menu size', levels: { 2: ['5 options', '20 options'], 3: ['5 options', '10 options', '20 options'], 4: ['5 options', '10 options', '20 options', '40 options'] }, for: ECON_B },
    { name: 'Loading time', levels: { 2: ['fast', 'slow'], 3: ['1 second', '3 seconds', '6 seconds'] }, for: ECON_B },
    { name: 'Shelf position', levels: { 2: ['eye level', 'bottom shelf'], 3: ['top shelf', 'eye level', 'bottom shelf'] }, for: ECON_B },
    { name: 'Loyalty scheme', levels: { 2: ['no scheme', 'points'], 3: ['none', '1 point/£', '5 points/£'] }, for: ECON_B },
  ],
};
