// ---------------------------------------------------------------------------
// Education pool: practice and revision, reading, classroom conditions,
// questioning, feedback, lectures and slides, and how tests are set and marked.
// The main pool for education (which also draws on the mind & behaviour pool).
// Studies are done on pupils, students and teachers. See pools/README.md for
// the rules.
// ---------------------------------------------------------------------------

const EDU_CONT = 'It can take any value on a scale, including every value in between — ';
const EDU_DISC = 'It only comes in separate values, with nothing in between — ';

const EDU_NOM = 'Categorical: distinct outcomes with no order. ';
const EDU_ORD = 'Ordinal: the outcomes are ranked, but the difference between steps is arbitrary. ';
const EDU_INT = 'Interval: ranked, with a constant difference between steps, but no natural zero — so values aren\'t "twice as much". ';
const EDU_RAT = 'Ratio: ranked, constant steps AND a natural zero, so "twice as much" makes sense. ';

const EDU_TIME = ['time', 'over time', 'week', 'weeks', 'month', 'months', 'year', 'years', 'day', 'days', 'when it was measured', 'time point', 'session', 'before and after', 'when they are tested', 'term'];

const EDU_PUPILS = { name: 'the pupils', aliases: ['pupils', 'children', 'class', 'the class', 'kids'] };
const EDU_STUDENTS = { name: 'the students', aliases: ['students', 'learners', 'undergraduates', 'people'] };

const EDU_WAIT = { name: 'wait time (1 second or 5 seconds)', aliases: ['wait time', 'waiting time', 'pause', 'how long the teacher waits', '1 second or 5 seconds', 'short or long wait', 'wait', 'thinking time'] };
const EDU_HANDS = { name: 'number of pupils who offer an answer', aliases: ['hands up', 'number of hands', 'pupils answering', 'how many answer', 'answers offered', 'volunteers', 'responses', 'participation'] };
const EDU_METHOD = { name: 'study method (self-testing or rereading)', aliases: ['study method', 'method', 'self-testing', 'self testing', 'rereading', 're-reading', 'testing themselves', 'self-testing or rereading', 'how they study', 'revision method'] };
const EDU_FACTS = { name: 'number of facts recalled', aliases: ['facts recalled', 'recall', 'facts', 'memory', 'how many facts', 'remember', 'score', 'final test'] };
const EDU_NOISE = { name: 'classroom noise (quiet or chatter)', aliases: ['noise', 'chatter', 'quiet or chatter', 'quiet', 'noisy', 'background noise', 'sound', 'noise level', 'recording'] };
const EDU_SPELL = { name: 'spelling-test score', aliases: ['spelling', 'spelling score', 'spelling test', 'words spelled correctly', 'correct spellings', 'test score', 'marks'] };
const EDU_FONT = { name: 'font size (12 point or 16 point)', aliases: ['font size', 'font', 'print size', 'text size', 'size of the text', '12 or 16 point', 'point size', 'letter size'] };
const EDU_WPM = { name: 'reading speed (words per minute)', aliases: ['reading speed', 'words per minute', 'wpm', 'how fast they read', 'speed', 'reading rate', 'fluency', 'reading fluency'] };
const EDU_WORKED = { name: 'worked examples (with or without)', aliases: ['worked examples', 'examples', 'with or without examples', 'worked example', 'solutions shown', 'shown how', 'example'] };
const EDU_SOLVED = { name: 'number of problems solved correctly', aliases: ['problems solved', 'problems correct', 'accuracy', 'correct answers', 'how many correct', 'maths score', 'performance'] };
const EDU_SLIDES = { name: 'slide style (few words or full paragraphs)', aliases: ['slide style', 'slides', 'words on slides', 'few words or full paragraphs', 'few words', 'full paragraphs', 'text on slides', 'amount of text', 'slide design'] };
const EDU_TALK = { name: 'number of points recalled from the talk', aliases: ['points recalled', 'recall', 'memory of the talk', 'how much they remember', 'remember', 'points remembered', 'quiz score'] };
const EDU_SPACING = { name: 'practice schedule (spaced or all at once)', aliases: ['practice schedule', 'schedule', 'spaced', 'spacing', 'massed', 'all at once', 'spread out', 'cramming', 'spaced or all at once', 'distributed practice'] };
const EDU_WORDS_WEEK = { name: 'number of words remembered a week later', aliases: ['words remembered', 'vocabulary recalled', 'recall', 'memory', 'how many words', 'retention', 'vocabulary score', 'score'] };
const EDU_LIMIT = { name: 'time limit (20 or 40 minutes)', aliases: ['time limit', 'time allowed', '20 or 40 minutes', 'how long they have', 'time', 'minutes allowed', 'test length in minutes', 'duration'] };
const EDU_ATTEMPTED = { name: 'number of questions attempted', aliases: ['questions attempted', 'attempted', 'how many questions', 'questions answered', 'questions tried', 'number answered', 'completion'] };
const EDU_INTERRUPT = { name: 'announcements (interrupted or not)', aliases: ['announcements', 'interruptions', 'interrupted', 'interrupted or not', 'tannoy', 'disruption', 'distraction', 'being interrupted'] };
const EDU_COMPLETED = { name: 'number of worksheet questions completed', aliases: ['questions completed', 'worksheet questions', 'completed', 'how many questions done', 'work done', 'amount of work', 'progress', 'output'] };

const EDU_FLUENCY = { name: 'reading fluency (words read correctly per minute)', aliases: ['reading fluency', 'fluency', 'words per minute', 'words read correctly', 'wpm', 'reading speed', 'reading', 'how fast they read'] };
const EDU_TABLES = { name: 'times-table answers per minute', aliases: ['times tables', 'times-table speed', 'answers per minute', 'multiplication', 'speed', 'how many answers', 'recall of tables', 'tables score'] };
const EDU_NOTES = { name: 'number of notes written per minute', aliases: ['notes', 'notes per minute', 'note-taking', 'note taking', 'how many notes', 'amount written', 'notes written'] };
const EDU_QUIZ = { name: 'quiz score', aliases: ['quiz score', 'quiz', 'score', 'marks', 'test score', 'how many correct', 'result'] };

POOLS.education = {
  // -------------------------------------------------------------------------
  // 1a. Variable or not?
  // -------------------------------------------------------------------------
  sortItems: [
    // --- variables ---
    { label: 'spelling-test score', variable: true,
      why: 'Pupils spell different numbers of words correctly, and the score can be counted out of the number of words tested.' },
    { label: 'reading fluency', variable: true,
      why: 'Some pupils read aloud faster and more accurately than others, and fluency is measured as words read correctly per minute.' },
    { label: 'teacher wait time', variable: true,
      why: 'A teacher can pause for one second or five after asking a question. The pause can be timed in seconds.' },
    { label: 'classroom noise level', variable: true,
      why: 'Some classrooms are quieter than others, and the noise can be measured in decibels.' },
    { label: 'time allowed for a test', variable: true,
      why: 'A test can last 20 minutes or two hours, and the teacher can choose and measure the time allowed.' },
    { label: 'number of questions attempted', variable: true,
      why: 'Some pupils get further through a test than others, and the questions they tried can be counted.' },
    { label: 'number of practice questions', variable: true,
      why: 'A pupil can practise 5 questions or 50 before a test, and the number can be counted and changed.' },
    { label: 'gap between practice sessions', variable: true,
      why: 'Practice sessions can be an hour apart or a week apart, and the gap can be measured in hours or days.' },
    { label: 'number of worked examples', variable: true,
      why: 'A lesson can show no worked examples or several, and the number can be counted and changed.' },
    { label: 'minutes of reading practice a day', variable: true,
      why: 'Pupils can read for 5 minutes a day or 30, and the time can be measured.' },
    { label: 'number of words on a slide', variable: true,
      why: 'Some slides have a few words and some have whole paragraphs. The words can be counted.' },
    { label: 'length of a lecture', variable: true,
      why: 'Lectures can last 20 minutes or two hours, and the length is measured in minutes.' },
    { label: 'number of notes taken', variable: true,
      why: 'Some students write more notes than others, and the notes can be counted as points or lines written.' },
    { label: 'number of interruptions in a lesson', variable: true,
      why: 'Some lessons are interrupted more often than others, by announcements or visitors, and the interruptions can be counted.' },
    { label: 'height of the writing on the board', variable: true,
      why: 'A teacher can write small or large, and the height of the letters can be measured in centimetres.' },
    { label: 'time spent revising', variable: true,
      why: 'Students revise for different lengths of time, and it can be measured in hours.' },
    { label: 'number of spelling errors in an essay', variable: true,
      why: 'Different essays contain different numbers of spelling mistakes, and they can be counted.' },
    { label: 'confidence rating before a test', variable: true,
      why: 'Students feel more or less sure of themselves before different tests, and can rate it on a scale.' },
    { label: 'number of times a new word is met', variable: true,
      why: 'A pupil might meet a new word once or ten times in their reading, and the meetings can be counted.' },
    { label: 'number of steps in an instruction', variable: true,
      why: 'An instruction can have one step ("open your book") or five, and the steps can be counted.' },
    { label: 'percentage of unfamiliar words in a passage', variable: true,
      why: 'Some passages contain more words a reader doesn\'t know than others, and the percentage can be worked out.' },
    { label: 'time since a topic was taught', variable: true,
      why: 'A quiz can come a day after a topic was taught or three months after. The gap can be measured.' },
    { label: 'mark awarded for an essay', variable: true,
      why: 'Different essays earn different marks, and the same essay can even get different marks from different markers.' },
    { label: 'agreement between two markers', variable: true,
      why: 'Two markers can agree closely on some sets of scripts and less closely on others, and agreement can be measured as a percentage.' },
    { label: 'number of questions on a test', variable: true,
      why: 'A test can have 10 questions or 60. The questions can be counted, and the setter can change the number.' },
    { label: 'number of pupils who put a hand up', variable: true,
      why: 'Some questions get more hands up than others, and the hands can be counted.' },
    { label: 'size of the font on a worksheet', variable: true,
      why: 'A worksheet can be printed in small or large type, and the font size is measured in points.' },

    // --- not variables: one particular thing ---
    { label: 'the classroom whiteboard', variable: false,
      why: 'It\'s one particular board — a thing, not a measurement. (How large the writing on it is, or how many pupils can read it, would be a variable.)' },
    { label: 'Bloom\'s taxonomy', variable: false,
      why: 'It\'s one particular way of sorting learning aims. (How many questions on a test ask pupils to apply an idea would be a variable.)' },
    { label: 'the school library', variable: false,
      why: 'It\'s one particular place. (How many books pupils borrow from it each week would be a variable.)' },
    { label: 'this week\'s spelling test', variable: false,
      why: 'It\'s one particular test. (The score each pupil gets on it would be a variable.)' },
    { label: 'the marking scheme', variable: false,
      why: 'A marking scheme is one particular document. (The mark each script gets using it, or how closely two markers agree, would be a variable.)' },
    { label: 'the school bell', variable: false,
      why: 'It\'s one particular bell. (How loud it is, or how long pupils take to settle after it rings, would be a variable.)' },
    { label: 'Lev Vygotsky', variable: false,
      why: 'Vygotsky is one particular person. (How many problems a pupil can solve with help from a teacher would be a variable.)' },
    { label: 'the class register', variable: false,
      why: 'It\'s one particular record. (The number of lessons each pupil attends would be a variable.)' },
    { label: 'the word "necessary"', variable: false,
      why: 'It\'s one particular word. (How many pupils spell it correctly would be a variable.)' },
    { label: 'the Year 9 maths textbook', variable: false,
      why: 'It\'s one particular book. (The number of worked examples in each chapter would be a variable.)' },
    { label: 'the exam hall', variable: false,
      why: 'It\'s one particular room. (How warm or noisy it is during an exam would be a variable.)' },
    { label: 'the first lecture of the module', variable: false,
      why: 'It\'s one particular lecture. (How long it lasts, or how many notes students take in it, would be a variable.)' },

    // --- not variables: measurable, but only one possible value ---
    { label: 'the number of letters in the English alphabet', variable: false,
      why: 'It\'s always 26. Something that can only ever have one value is a constant, not a variable.' },
    { label: 'the number of minutes in an hour', variable: false,
      why: 'It\'s always 60. It can be measured, but it doesn\'t vary.' },
    { label: 'the answer to 7 × 8', variable: false,
      why: 'It\'s always 56 — only one possible value, so it\'s a constant. (How quickly a pupil gives the answer would be a variable.)' },
  ],

  // -------------------------------------------------------------------------
  // 1b-1d, 2b, 2c. Relations.
  // -------------------------------------------------------------------------
  relations: [
    { id: 'edu-spacing-retention', iv: 'days practice is spread over', dv: 'words remembered',
      ivNP: 'the number of days the practice is spread over', dvNP: 'the number of words remembered a week later',
      hyp: ['spacing', 'words remembered'], ivAxis: 'Days spread over', dvAxis: 'Words recalled', dir: 'up',
      says: ['When the same amount of vocabulary practice is spread over more days, pupils remember more of the words a week later.',
             'The number of words remembered a week later goes up when the same practice is spread over more days.'],
      why: 'How the practice is spread out is decided before the test, and the test comes a week after. Remembering words at the test can\'t go back and change the practice timetable.' },
    { id: 'edu-practiceqs-score', iv: 'practice questions attempted', dv: 'test score',
      ivNP: 'the number of practice questions attempted', dvNP: 'the score on a test of those skills',
      hyp: ['practice questions', 'test score'], ivAxis: 'Practice Qs', dvAxis: 'Test score', dir: 'up',
      says: ['The more practice questions pupils attempt on a skill, the higher they score on a test of that skill.',
             'Test scores on a skill go up with the number of practice questions attempted.'],
      why: 'The practice happens before the test and builds the skill. A high score on the test can\'t add practice questions that were never done.' },
    { id: 'edu-timelimit-attempted', iv: 'time allowed', dv: 'questions attempted',
      ivNP: 'the time allowed for the test', dvNP: 'the number of questions attempted',
      hyp: ['time allowed', 'questions attempted'], ivAxis: 'Time allowed', dvAxis: 'Qs attempted', dir: 'up',
      says: ['The more time pupils are given for a test, the more of its questions they attempt.',
             'The number of questions attempted goes up as the time allowed goes up.'],
      why: 'The time limit is set before the test starts; how far pupils get is the result. Attempting more questions can\'t give anyone extra time.' },
    { id: 'edu-waittime-hands', iv: 'teacher wait time', dv: 'pupils offering answers',
      ivNP: 'the time a teacher waits after asking a question', dvNP: 'the number of pupils who offer an answer',
      hyp: ['wait time', 'pupils answering'], ivAxis: 'Wait time', dvAxis: 'Pupils answering', dir: 'up',
      says: ['When a teacher waits a few seconds after asking a question, more pupils put up their hands to answer.',
             'The number of pupils offering an answer goes up with the time the teacher waits after the question.'],
      why: 'The pause comes first and gives pupils time to think of an answer. Hands going up can\'t go back and lengthen the pause before them.' },
    { id: 'edu-reading-fluency', iv: 'daily reading practice', dv: 'reading fluency',
      ivNP: 'the minutes of reading practice each day', dvNP: 'reading fluency',
      hyp: ['reading practice', 'fluency'], ivAxis: 'Practice (min)', dvAxis: 'Fluency (wpm)', dir: 'up',
      says: ['The more minutes a day pupils spend practising reading aloud, the more words per minute they read correctly by the end of term.',
             'Reading fluency at the end of term goes up with the minutes of daily reading practice.'],
      why: 'The practice happens over the term and fluency is measured at the end. The final reading speed can\'t go back and add practice time.' },
    { id: 'edu-worked-accuracy', iv: 'worked examples studied', dv: 'problems solved',
      ivNP: 'the number of worked examples studied', dvNP: 'the number of similar problems solved correctly',
      hyp: ['worked examples', 'problems solved'], ivAxis: 'Worked examples', dvAxis: 'Problems solved', dir: 'up',
      says: ['Pupils meeting a new type of problem solve more similar problems correctly after studying more worked examples of it.',
             'The number of similar problems solved correctly goes up with the number of worked examples studied.'],
      why: 'The worked examples are studied first and show how the problems are done. Solving problems later can\'t change how many examples were shown.' },
    { id: 'edu-flashcard-vocab', iv: 'flashcard self-tests', dv: 'vocabulary recalled',
      ivNP: 'the number of times students test themselves with flashcards', dvNP: 'the number of vocabulary items recalled',
      hyp: ['self-tests', 'vocabulary recalled'], ivAxis: 'Self-tests', dvAxis: 'Words recalled', dir: 'up',
      says: ['The more times students test themselves on new vocabulary with flashcards, the more of the words they recall in a later test.',
             'Vocabulary recall in the later test goes up with the number of flashcard self-tests.'],
      why: 'The self-testing happens during revision and the test comes later. Recalling words in the test can\'t add self-tests that happened before it.' },
    { id: 'edu-exposure-meaning', iv: 'times a new word is heard', dv: 'knowing its meaning',
      ivNP: 'the number of times a new word is heard in stories', dvNP: 'the chance of knowing what it means',
      hyp: ['times heard', 'knowing the meaning'], ivAxis: 'Times heard', dvAxis: 'Knows meaning', dir: 'up',
      says: ['The more times young pupils hear a new word in stories read to them, the more likely they are to know what it means.',
             'The chance of knowing a new word\'s meaning goes up with the number of times it is heard in stories.'],
      why: 'Hearing the word comes first, and each meeting gives more clues to its meaning. Knowing the word later can\'t change how often it appeared in the stories.' },
    { id: 'edu-tables-speed', iv: 'times-table practice', dv: 'answers per minute',
      ivNP: 'the amount of times-table practice', dvNP: 'the number of answers given per minute',
      hyp: ['tables practice', 'answers per minute'], ivAxis: 'Practice', dvAxis: 'Answers/minute', dir: 'up',
      says: ['The more pupils practise their times tables, the more answers they can give in a minute.',
             'The number of times-table answers given per minute goes up with practice.'],
      why: 'The practice comes first and makes the facts quicker to recall. Answering quickly in the test can\'t add practice that was never done.' },
    { id: 'edu-testlength-reliability', iv: 'number of questions', dv: 'reliability of the score',
      ivNP: 'the number of questions on the test', dvNP: 'the reliability of the score',
      hyp: ['test length', 'score reliability'], ivAxis: 'Questions', dvAxis: 'Reliability', dir: 'up',
      says: ['Tests with more questions on the same topic give more reliable scores: a pupil\'s score changes less from one sitting to the next.',
             'The reliability of a test score goes up as more questions on the same topic are added.'],
      why: 'The setter decides how many questions to include, and luck on any one question matters less when there are many. A reliable score can\'t add questions to the paper.' },
    { id: 'edu-scheme-agreement', iv: 'detail in the marking scheme', dv: 'agreement between markers',
      ivNP: 'the amount of detail in the marking scheme', dvNP: 'the agreement between two markers',
      hyp: ['scheme detail', 'marker agreement'], ivAxis: 'Scheme detail', dvAxis: 'Agreement', dir: 'up',
      says: ['The more precisely a marking scheme says what earns each mark, the more closely two markers agree on the same scripts.',
             'Agreement between two markers goes up as the marking scheme spells out more clearly what earns each mark.'],
      why: 'The marking scheme is written before any marking starts, and it guides both markers. Markers agreeing can\'t go back and rewrite the scheme.' },
    { id: 'edu-boardtext-legible', iv: 'size of writing on the board', dv: 'pupils who can read it',
      ivNP: 'the size of the writing on the board', dvNP: 'the number of pupils at the back who can read it',
      hyp: ['writing size', 'pupils who can read it'], ivAxis: 'Writing size', dvAxis: 'Can read it', dir: 'up',
      says: ['The larger a teacher writes on the board, the more pupils at the back of the room can read it.',
             'The number of pupils at the back who can read the board goes up as the writing gets larger.'],
      why: 'The size of the writing is fixed when it is written; being able to read it depends on that. Pupils reading it can\'t make the letters bigger.' },
    { id: 'edu-readtime-comprehension', iv: 'time to read a passage', dv: 'questions answered correctly',
      ivNP: 'the time allowed to read the passage', dvNP: 'the number of comprehension questions answered correctly',
      hyp: ['reading time', 'questions correct'], ivAxis: 'Reading time', dvAxis: 'Correct answers', dir: 'up',
      says: ['When pupils are given more time to read a passage, they answer more of the questions about it correctly.',
             'The number of comprehension questions answered correctly goes up with the time allowed for reading.'],
      why: 'The reading time is set before the questions are answered. Answering correctly can\'t go back and give more time to read.' },
    { id: 'edu-spelling-rehearsal', iv: 'times a spelling is practised', dv: 'chance of spelling it right',
      ivNP: 'the number of times a spelling is practised', dvNP: 'the chance of spelling it correctly in a test',
      hyp: ['spelling practice', 'correct spelling'], ivAxis: 'Practice', dvAxis: 'Spelt correctly', dir: 'up',
      says: ['The more times pupils practise writing a new spelling, the more likely they are to spell it correctly in the test.',
             'The chance of spelling a word correctly in the test goes up with the number of times it was practised.'],
      why: 'The practice happens during the week and the test at the end. Getting the word right in the test can\'t add practice beforehand.' },
    { id: 'edu-feedback-corrections', iv: 'errors pointed out', dv: 'corrections made',
      ivNP: 'the number of errors pointed out in feedback', dvNP: 'the number of corrections made in the redraft',
      hyp: ['errors pointed out', 'corrections'], ivAxis: 'Errors marked', dvAxis: 'Corrections', dir: 'up',
      says: ['The more errors a teacher points out in a draft, the more corrections pupils make when they redraft it.',
             'The number of corrections in a redraft goes up with the number of errors pointed out in the feedback.'],
      why: 'The feedback comes first and tells pupils what to fix. Making corrections afterwards can\'t change how many errors were pointed out.' },

    { id: 'edu-noise-spelling', iv: 'classroom noise', dv: 'spelling-test score',
      ivNP: 'the level of noise in the classroom', dvNP: 'the spelling-test score',
      hyp: ['noise', 'spelling score'], ivAxis: 'Noise level', dvAxis: 'Spelling score', dir: 'down',
      says: ['The louder the background chatter while pupils take a spelling test, the lower their scores.',
             'Spelling-test scores go down as the classroom gets noisier.'],
      why: 'The noise is there while pupils are working and distracts them. Scoring low on a test can\'t make the room louder.' },
    { id: 'edu-lecture-notes', iv: 'minutes into the lecture', dv: 'notes per minute',
      ivNP: 'how far into a long lecture it is', dvNP: 'the number of notes written per minute',
      hyp: ['time into lecture', 'notes per minute'], ivAxis: 'Minutes in', dvAxis: 'Notes/minute', dir: 'down',
      says: ['The further into a long lecture it gets, the fewer notes students write each minute.',
             'The number of notes written per minute drops as a long lecture goes on.'],
      why: 'Time keeps passing whatever the students do, and a long stretch of listening wears attention down. Writing fewer notes can\'t make time pass.' },
    { id: 'edu-interruptions-completed', iv: 'number of interruptions', dv: 'questions completed',
      ivNP: 'the number of interruptions during the lesson', dvNP: 'the number of worksheet questions completed',
      hyp: ['interruptions', 'questions completed'], ivAxis: 'Interruptions', dvAxis: 'Qs completed', dir: 'down',
      says: ['The more times a lesson is interrupted by announcements, the fewer worksheet questions pupils complete.',
             'The number of worksheet questions completed goes down as the number of interruptions goes up.'],
      why: 'The announcements happen to the class and take time and attention away from the work. Completing fewer questions can\'t cause announcements.' },
    { id: 'edu-unfamiliar-comprehension', iv: 'unfamiliar words', dv: 'comprehension score',
      ivNP: 'the percentage of unfamiliar words in a passage', dvNP: 'the comprehension score',
      hyp: ['unfamiliar words', 'comprehension'], ivAxis: '% unfamiliar', dvAxis: 'Comprehension', dir: 'down',
      says: ['The more words in a passage that a reader doesn\'t know, the fewer questions about it they answer correctly.',
             'Comprehension scores go down as the percentage of unfamiliar words in the passage goes up.'],
      why: 'The words in the passage are fixed before anyone reads it, and each unknown word leaves a gap in the meaning. A low score can\'t change the words on the page.' },
    { id: 'edu-steps-followed', iv: 'steps in an instruction', dv: 'percentage carried out',
      ivNP: 'the number of steps in a spoken instruction', dvNP: 'the percentage of steps carried out correctly',
      hyp: ['steps', '% carried out'], ivAxis: 'Steps', dvAxis: '% carried out', dir: 'down',
      says: ['The more steps a spoken instruction has, the smaller the percentage of them young pupils carry out correctly.',
             'The percentage of steps carried out correctly goes down as spoken instructions get longer.'],
      why: 'The teacher decides how many steps to give, and pupils have to hold them all in mind. Forgetting a step can\'t make the instruction longer.' },
    { id: 'edu-weeks-quiz', iv: 'weeks since the topic was taught', dv: 'quiz score',
      ivNP: 'the number of weeks since the topic was taught', dvNP: 'the score on a quiz about it',
      hyp: ['weeks since taught', 'quiz score'], ivAxis: 'Weeks since', dvAxis: 'Quiz score', dir: 'down',
      says: ['The longer it has been since a topic was taught, without any review, the lower pupils score on a quiz about it.',
             'Quiz scores on a topic go down as more weeks pass since it was taught.'],
      why: 'Time passes after the lesson whatever pupils do, and it is the passing time that lets them forget. A low quiz score can\'t make time pass.' },
    { id: 'edu-faint-reading', iv: 'faintness of the print', dv: 'reading speed',
      ivNP: 'how faint the print is', dvNP: 'the reading speed',
      hyp: ['faint print', 'reading speed'], ivAxis: 'Faintness', dvAxis: 'Reading speed', dir: 'down',
      says: ['The fainter the print on a photocopied worksheet, the more slowly pupils read it.',
             'Reading speed goes down as the print on the page gets fainter.'],
      why: 'The worksheet is printed before anyone reads it, so the print is the changer. Reading slowly can\'t make the ink fainter.' },
    { id: 'edu-questions-finished', iv: 'questions on a timed test', dv: 'percentage finished',
      ivNP: 'the number of questions on a test with a fixed time limit', dvNP: 'the percentage of questions finished',
      hyp: ['questions set', '% finished'], ivAxis: 'Questions set', dvAxis: '% finished', dir: 'down',
      says: ['With the same time limit, the more questions a test has, the smaller the percentage of them pupils finish.',
             'The percentage of questions finished goes down as more questions are put on a timed test.'],
      why: 'The setter decides how many questions go on the paper before anyone sits it. Pupils finishing fewer can\'t add questions to the paper.' },
    { id: 'edu-break-ontask', iv: 'time since the last break', dv: 'pupils on task',
      ivNP: 'the time since the last break', dvNP: 'the number of pupils on task',
      hyp: ['time since break', 'pupils on task'], ivAxis: 'Since break', dvAxis: 'On task', dir: 'down',
      says: ['The longer pupils have been working since their last break, the fewer of them are on task at any moment.',
             'The number of pupils on task goes down as the time since the last break goes up.'],
      why: 'The time since the break keeps growing whatever pupils do, and a long stretch of work wears attention down. Pupils drifting off task can\'t make time pass.' },
  ],

  // -------------------------------------------------------------------------
  // 2a. Validity and reliability.
  // -------------------------------------------------------------------------
  validity: [
    // valid and reliable
    { valid: true, reliable: true,
      text: 'To measure reading fluency, each pupil reads a passage aloud for one minute and the words read correctly are counted from a recording. Two teachers who count the same recordings separately get the same numbers.',
      whyValid: 'words read correctly in a minute is exactly what reading fluency means.',
      whyReliable: 'two teachers counting separately get the same numbers.' },
    { valid: true, reliable: true,
      text: 'To measure spelling, the teacher reads out 20 words and each pupil writes them down; each word is marked right or wrong. A second teacher who marks the same sheets gets identical scores.',
      whyValid: 'writing down words that are read out is a direct test of spelling.',
      whyReliable: 'each word is plainly right or wrong, so a second marker gets identical scores.' },
    { valid: true, reliable: true,
      text: 'To measure how quickly pupils recall times tables, a computer gives 50 questions and records how many are answered correctly in two minutes. Pupils who take it again the next day get very similar scores.',
      whyValid: 'answering times-table questions against the clock is a direct measure of how quickly they are recalled.',
      whyReliable: 'with 50 questions, pupils get very similar scores the next day.' },
    { valid: true, reliable: true,
      text: 'To measure how well students know the content of a module, they take a 60-question multiple-choice test marked by a machine. Two versions of the test, with different questions on the same content, give very similar scores.',
      whyValid: 'many questions covering the module\'s content test what students know about it.',
      whyReliable: 'two versions with different questions give very similar scores.' },

    // reliable, not valid
    { valid: false, reliable: true,
      text: 'To measure how well pupils understand what they read, the teacher counts the pages in the book each pupil chose from the library. Anyone who counts the pages gets the same number.',
      whyValid: 'the length of a book says nothing about how well the pupil understood it.',
      whyReliable: 'counting the pages again gives the same number every time.' },
    { valid: false, reliable: true,
      text: 'To measure how well students understand a history topic, the tutor counts the words in each student\'s essay. Counting again gives the same totals.',
      whyValid: 'a long essay isn\'t necessarily a well-understood one — the count measures length, not understanding.',
      whyReliable: 'a word count gives the same total every time.' },
    { valid: false, reliable: true,
      text: 'To measure how hard pupils worked on a project, the teacher weighs each pupil\'s project folder. The scales give the same weight every time.',
      whyValid: 'the weight of the folder depends on the paper and card used, not on how hard the pupil worked.',
      whyReliable: 'weighing the same folder again gives the same result.' },
    { valid: false, reliable: true,
      text: 'To measure how much students learned in a lecture, researchers record how long the lecture lasted. The timetable gives the same length whoever checks it.',
      whyValid: 'the length of a lecture says nothing about how much any student learned from it.',
      whyReliable: 'the timetable gives the same length every time it is checked.' },

    // valid, not reliable
    { valid: true, reliable: false,
      text: 'To measure whether pupils can add fractions, the teacher sets a single fractions question. The same pupil gets it right on Monday and wrong on Tuesday.',
      whyValid: 'adding fractions is exactly the skill the question asks for.',
      whyReliable: 'one question is too few — a single slip or lucky guess changes the result. Many questions need averaging.' },
    { valid: true, reliable: false,
      text: 'To measure understanding of a history topic, students write an essay that one tutor marks with no marking scheme. A second tutor marking the same essays gives very different marks.',
      whyValid: 'writing an essay on the topic is a sensible way to show understanding of it.',
      whyReliable: 'without a marking scheme, two markers give very different marks to the same essay.' },
    { valid: true, reliable: false,
      text: 'To compare flashcards with rereading for learning vocabulary, a teacher tries each method with 3 pupils and tests them. When she repeats it with 3 different pupils, the result comes out the other way.',
      whyValid: 'testing how many words pupils remember is the right way to compare the methods.',
      whyReliable: 'repeating it with 3 other pupils gives the opposite result. Three pupils per method is far too few.' },
    { valid: true, reliable: false,
      text: 'A study tests pupils\' reading speed before and after "some extra reading practice", but the report doesn\'t say how long the practice was, what was read or how often. Other schools that try to repeat it get quite different results.',
      whyValid: 'timing pupils as they read is a sensible way to measure reading speed.',
      whyReliable: 'without a full "recipe" — how long, how often, what was read — nobody can repeat the study and get the same result.' },

    // neither
    { valid: false, reliable: false,
      text: 'To measure maths ability, the teacher rolls a die for each pupil and records the number. Rolling again gives a different number.',
      whyValid: 'a dice roll has nothing to do with maths ability.',
      whyReliable: 'each roll gives a different number for the same pupil.' },
    { valid: false, reliable: false,
      text: 'To measure how well a class is paying attention, the teacher counts how many birds land on the playground during the lesson. The count is different every lesson.',
      whyValid: 'birds on the playground have nothing to do with the pupils\' attention.',
      whyReliable: 'the count changes from lesson to lesson whatever the class does.' },
    { valid: false, reliable: false,
      text: 'To measure how much students enjoyed a module, researchers note which row of the lecture theatre each student sits in on the last day. The same students sit in different rows on different days.',
      whyValid: 'where someone happens to sit isn\'t a measure of how much they enjoyed the module.',
      whyReliable: 'the same students sit somewhere different each day.' },
    { valid: false, reliable: false,
      text: 'To measure each pupil\'s spelling ability, the teacher writes down the temperature of the classroom on the day of the test. The temperature is different every day.',
      whyValid: 'the room temperature isn\'t a measure of any pupil\'s spelling.',
      whyReliable: 'the reading changes from day to day.' },
  ],

  // -------------------------------------------------------------------------
  // 2d. Continuous or discrete.
  // -------------------------------------------------------------------------
  continuity: [
    { cat: 'cont', label: 'time taken to read a passage', why: EDU_CONT + '95 seconds, 95.4 seconds... time can always be divided further.' },
    { cat: 'cont', label: 'teacher wait time after a question', why: EDU_CONT + '3 seconds, 3.2 seconds, 3.25 seconds...' },
    { cat: 'cont', label: 'time allowed for a test', why: EDU_CONT + '45 minutes, 45.5 minutes... the time limit can be any length.' },
    { cat: 'cont', label: 'time spent revising', why: EDU_CONT + '2 hours, 2.25 hours, 2 hours and 16 minutes...' },
    { cat: 'cont', label: 'classroom noise level in decibels', why: EDU_CONT + '55 dB, 55.5 dB... noise can take any value on the scale.' },
    { cat: 'cont', label: 'height of the letters on the board', why: EDU_CONT + '4 cm, 4.3 cm, 4.35 cm...' },
    { cat: 'cont', label: 'length of a lecture', why: EDU_CONT + '50 minutes, 50.5 minutes... time can always be measured more finely.' },
    { cat: 'cont', label: 'average test score of a class', why: EDU_CONT + 'one pupil can\'t score 14.3 marks, but a class average can be 14.3.' },
    { cat: 'cont', label: 'time taken to finish a worksheet', why: EDU_CONT + '12 minutes, 12 minutes and 20 seconds... time can always be divided further.' },
    { cat: 'cont', label: 'time between two practice sessions', why: EDU_CONT + '24 hours, 24.5 hours... the gap can be any length.' },
    { cat: 'cont', label: 'classroom temperature', why: EDU_CONT + '20°C, 20.4°C, 20.45°C...' },
    { cat: 'cont', label: 'time a pupil takes to answer a question', why: EDU_CONT + '2 seconds, 2.6 seconds... time can always be measured more finely.' },
    { cat: 'cont', label: 'time since a topic was taught', why: EDU_CONT + '3 weeks, 3.5 weeks, 3 weeks and 2 days...' },

    { cat: 'disc', label: 'number of questions attempted', why: EDU_DISC + 'a pupil attempts 17 questions or 18, never 17.5.' },
    { cat: 'disc', label: 'number of spelling errors in an essay', why: EDU_DISC + 'errors are counted in whole numbers.' },
    { cat: 'disc', label: 'number of pupils who put a hand up', why: EDU_DISC + 'pupils are counted: 8 or 9, never 8.5.' },
    { cat: 'disc', label: 'number of worked examples in a lesson', why: EDU_DISC + 'a lesson shows 3 examples or 4, not 3.2.' },
    { cat: 'disc', label: 'number of practice questions done', why: EDU_DISC + 'you do 20 questions or 21, not 20.3.' },
    { cat: 'disc', label: 'number of words on a slide', why: EDU_DISC + 'words are counted: a slide has 30 words or 31.' },
    { cat: 'disc', label: 'number of interruptions in a lesson', why: EDU_DISC + 'each interruption is counted once.' },
    { cat: 'disc', label: 'number of lectures attended', why: EDU_DISC + 'a student attends 9 lectures or 10, nothing in between.' },
    { cat: 'disc', label: 'number of words read correctly in one minute', why: EDU_DISC + 'each word is read correctly or not, so the total is a whole number.' },
    { cat: 'disc', label: 'number of steps in an instruction', why: EDU_DISC + 'an instruction has 3 steps or 4, never 3.5.' },
    { cat: 'disc', label: 'marks on a 20-question quiz (one mark each)', why: EDU_DISC + 'each question is right or wrong, so the mark is 0, 1, 2... 20.' },
    { cat: 'disc', label: 'number of times a new word is met in a story', why: EDU_DISC + 'each time the word appears is counted once.' },
    { cat: 'disc', label: 'confidence rated on a 1–5 scale', why: EDU_DISC + 'students choose 1, 2, 3, 4 or 5, and there\'s no 3.5 on the scale.' },
  ],

  // -------------------------------------------------------------------------
  // 2e. Levels of measurement.
  // -------------------------------------------------------------------------
  measurement: [
    { cat: 'categorical', label: 'subject of the lesson (maths, history or art)', why: EDU_NOM + 'Maths isn\'t more or less than history — they\'re different subjects.' },
    { cat: 'categorical', label: 'question format (multiple choice, short answer or essay)', why: EDU_NOM + 'These are kinds of question, not amounts of one.' },
    { cat: 'categorical', label: 'answer chosen on a multiple-choice question (A, B, C or D)', why: EDU_NOM + 'The letters are labels; B isn\'t more than A.' },
    { cat: 'categorical', label: 'revision method used (flashcards, rereading or summarising)', why: EDU_NOM + 'These are different ways of revising, with no order.' },
    { cat: 'categorical', label: 'which classroom the lesson is in', why: EDU_NOM + 'Room 4 and Room 7 are names, not amounts — Room 7 isn\'t "more room".' },
    { cat: 'categorical', label: 'which module a student is taking', why: EDU_NOM + 'Modules are different courses, not ranked amounts.' },

    { cat: 'ordinal', label: 'degree classification (first, 2:1, 2:2, third)', why: EDU_ORD + 'A first is above a 2:1, but the classes cover different-sized ranges of marks.' },
    { cat: 'ordinal', label: 'agreement from "strongly disagree" to "strongly agree"', why: EDU_ORD + 'The answers are in order, but nothing says the steps are the same size.' },
    { cat: 'ordinal', label: 'position in a class spelling bee (1st, 2nd, 3rd)', why: EDU_ORD + 'The gap between 1st and 2nd could be one word; between 2nd and 3rd, ten words.' },
    { cat: 'ordinal', label: 'teacher\'s rating of effort (low, medium, high)', why: EDU_ORD + 'The labels are ranked, but not equally spaced.' },
    { cat: 'ordinal', label: 'question difficulty (easy, medium, hard)', why: EDU_ORD + 'In order, but the jump from easy to medium needn\'t match the jump from medium to hard.' },
    { cat: 'ordinal', label: 'ranking modules from most to least enjoyed', why: EDU_ORD + 'A ranking gives the order, not how far apart the modules are.' },

    { cat: 'interval', label: 'clarity of a lecture rated on a scale of 1–7', why: EDU_INT + 'The numbered steps are treated as equal, but there\'s no zero, so a 6 isn\'t "twice as clear" as a 3.' },
    { cat: 'interval', label: 'confidence before an exam rated 1–10', why: EDU_INT + 'A numbered scale has constant steps, but no natural zero.' },
    { cat: 'interval', label: 'date of the exam', why: EDU_INT + 'Days are equal steps, but the calendar\'s starting point is arbitrary.' },
    { cat: 'interval', label: 'time of day a lesson starts', why: EDU_INT + 'The minutes are equal, but midnight isn\'t "no time", so 2 o\'clock isn\'t twice 1 o\'clock.' },
    { cat: 'interval', label: 'classroom temperature in °C', why: EDU_INT + '0°C isn\'t "no temperature", so 22°C isn\'t twice as warm as 11°C.' },
    { cat: 'interval', label: 'year a textbook was published', why: EDU_INT + 'Years are equal steps, but year 0 isn\'t the start of time, so 2020 isn\'t "twice" 1010.' },

    { cat: 'ratio', label: 'number of questions answered correctly', why: EDU_RAT + '0 is none at all, and 20 correct is twice 10.' },
    { cat: 'ratio', label: 'reading speed in words per minute', why: EDU_RAT + '0 words per minute is no reading at all, and 120 is twice 60.' },
    { cat: 'ratio', label: 'minutes of reading practice a day', why: EDU_RAT + '0 minutes is no practice, and 30 minutes is twice 15.' },
    { cat: 'ratio', label: 'number of spelling errors', why: EDU_RAT + 'Zero errors means none, and 8 errors is twice 4.' },
    { cat: 'ratio', label: 'teacher wait time in seconds', why: EDU_RAT + '0 seconds is no wait at all, and 6 seconds is twice 3.' },
    { cat: 'ratio', label: 'number of lectures attended', why: EDU_RAT + '0 lectures is none, and 12 is twice 6.' },
  ],

  // -------------------------------------------------------------------------
  // 2g. Confounds. Paired: the same study done badly, then done properly.
  // -------------------------------------------------------------------------
  confounds: [
    { iv: 'wait time', dv: 'number of pupils who answer', confound: 'question difficulty',
      vars: ['wait time', 'number of pupils who answer', 'question difficulty', 'the class'],
      text: 'A teacher tests whether waiting five seconds after a question gets more pupils answering. With the same class, she waits five seconds in a lesson of easy recap questions and one second in a lesson of hard new questions.',
      why: 'The long-wait lesson also had easier questions, which more pupils can answer anyway. The difference could come from the questions, not the wait.' },
    { iv: 'study method', dv: 'vocabulary recalled', confound: 'study time',
      vars: ['study method', 'vocabulary recalled', 'study time', 'the word list'],
      text: 'Researchers test whether self-testing beats rereading for learning vocabulary. Both groups learn the same word list, but the self-testing group studies for 30 minutes and the rereading group for 10.',
      why: 'The self-testing group also studied three times as long. More recall could come from the extra time, not the method.' },
    { iv: 'classroom noise', dv: 'spelling-test score', confound: 'time of day',
      vars: ['classroom noise', 'spelling-test score', 'time of day', 'the spelling list'],
      text: 'To see whether noise affects spelling, a class takes a test on the same spelling list twice: in quiet first thing on Monday morning, and with recorded chatter in the last lesson on Friday afternoon.',
      why: 'The noisy test was also at the end of the week and the day, when pupils are more tired. Lower scores could come from the timing, not the noise.' },
    { iv: 'worked examples', dv: 'problems solved correctly', confound: 'difficulty of the test',
      vars: ['worked examples', 'problems solved correctly', 'difficulty of the test', 'the topic'],
      text: 'Researchers test whether worked examples help pupils solve equations. Both groups study the same topic, but the worked-examples group is then given easier test problems than the other group.',
      why: 'The worked-examples group also got an easier test. More problems solved could come from the easier test, not the examples.' },
    { iv: 'spaced practice', dv: 'words remembered', confound: 'delay before the test',
      vars: ['spaced practice', 'words remembered', 'delay before the test', 'the words learned'],
      text: 'Researchers test whether spacing out practice helps pupils remember new words. Both groups learn the same words; the spaced group is tested a day after its last session, and the all-at-once group a week after its only session.',
      why: 'The spaced group also had a much shorter wait before the test, and memories fade with time. The difference could come from the delay, not the spacing.' },
    { iv: 'size of writing on the board', dv: 'sentences copied correctly', confound: 'glare on the board',
      vars: ['size of writing on the board', 'sentences copied correctly', 'glare on the board', 'the sentences'],
      text: 'A teacher tests whether larger writing helps pupils copy from the board. She writes the same sentences large on a cloudy day and small on a sunny day, when light shines on the board.',
      why: 'The small writing was also on a board with glare, which makes any writing harder to read. The difference could be the glare, not the size.' },
    { iv: 'time allowed', dv: 'questions attempted', confound: 'length of the questions',
      vars: ['time allowed', 'questions attempted', 'length of the questions', 'the topic'],
      text: 'Researchers test whether more time means more questions attempted. The 40-minute group gets short one-line questions on the topic; the 20-minute group gets long questions with paragraphs to read, on the same topic.',
      why: 'The 20-minute group also had longer questions, which take more time to get through. The difference could be the questions, not the time.' },
    { iv: 'daily reading practice', dv: 'reading fluency', confound: 'difficulty of the passage',
      vars: ['daily reading practice', 'reading fluency', 'difficulty of the passage', 'the length of the passage'],
      text: 'Researchers test whether daily reading practice improves fluency. At the end of term both groups read a passage of the same length aloud, but the practice group\'s passage is a simple story and the other group\'s is a science text.',
      why: 'The practice group also had an easier passage, which anyone reads faster. The difference could be the passage, not the practice.' },
    { iv: 'announcements', dv: 'questions completed', confound: 'lesson length',
      vars: ['announcements', 'questions completed', 'lesson length', 'the worksheet'],
      text: 'A teacher tests whether announcements over the speaker stop pupils getting work done. The interrupted lesson is 40 minutes long and the uninterrupted one is 60 minutes; both use the same worksheet.',
      why: 'The interrupted lesson was also 20 minutes shorter. Fewer questions completed could come from the shorter lesson, not the announcements.' },

    { iv: 'wait time', dv: 'number of pupils who answer', confound: null,
      text: 'A teacher tests whether waiting five seconds after a question gets more pupils answering. Across several lessons of the same kind, she randomly decides for each question whether to wait one second or five.',
      why: 'Random choice for each question, in the same kind of lesson, means easy and hard questions end up in both conditions. Only the wait differs.' },
    { iv: 'study method', dv: 'vocabulary recalled', confound: null,
      text: 'Researchers test whether self-testing beats rereading for learning vocabulary. Students are randomly split into two groups, and both study the same word list for 20 minutes.',
      why: 'Same words, same time, random groups — only the study method differs.' },
    { iv: 'classroom noise', dv: 'spelling-test score', confound: null,
      text: 'To see whether noise affects spelling, pupils are randomly split into two groups who take the same test at the same time in two similar rooms, one quiet and one with recorded chatter.',
      why: 'Same test, same time of day, random groups — only the noise differs.' },
    { iv: 'worked examples', dv: 'problems solved correctly', confound: null,
      text: 'Researchers test whether worked examples help pupils solve equations. Pupils are randomly assigned to study with or without worked examples, and everyone takes the same test.',
      why: 'Same test, random groups — only the worked examples differ.' },
    { iv: 'spaced practice', dv: 'words remembered', confound: null,
      text: 'Researchers test whether spacing out practice helps pupils remember new words. Pupils are randomly split; both groups learn the same words and are tested exactly one week after their last session.',
      why: 'Same words, same delay before the test, random groups — only the spacing differs.' },
    { iv: 'size of writing on the board', dv: 'sentences copied correctly', confound: null,
      text: 'A teacher tests whether larger writing helps pupils copy from the board. With the blinds down in both lessons, she writes the same sentences large one day and small the next.',
      why: 'Blinds down both times means the lighting is the same, so only the size of the writing differs.' },
    { iv: 'time allowed', dv: 'questions attempted', confound: null,
      text: 'Researchers test whether more time means more questions attempted. Pupils are randomly given 20 or 40 minutes to work on the same paper of questions.',
      why: 'Same questions, random groups — only the time allowed differs.' },
    { iv: 'daily reading practice', dv: 'reading fluency', confound: null,
      text: 'Researchers test whether daily reading practice improves fluency. Pupils are randomly assigned to practise daily or not, and at the end of term everyone reads the same passage aloud.',
      why: 'Same passage, random groups — only the practice differs.' },
    { iv: 'announcements', dv: 'questions completed', confound: null,
      text: 'A teacher tests whether announcements stop pupils getting work done. Two 60-minute lessons use the same kind of worksheet; which one gets the pre-recorded announcements is decided by a coin toss.',
      why: 'Same lesson length, same kind of worksheet, and a coin toss decides — only the announcements differ.' },
  ],

  // -------------------------------------------------------------------------
  // 2j. Within or between subjects. Pairs: the same study both ways.
  // -------------------------------------------------------------------------
  designs: [
    { cat: 'within',
      label: 'In the same class, the teacher waits 1 second after some questions and 5 seconds after others, and the number of pupils who put up their hands is counted for each kind of question.',
      ivs: [EDU_WAIT], dv: EDU_HANDS,
      others: [{ name: 'the class', aliases: ['class', 'same class', 'classroom', 'children'] }] },
    { cat: 'within',
      label: 'Every student learns one set of facts by testing themselves and another set by rereading. A week later, the number of facts they recall from each set is compared.',
      ivs: [EDU_METHOD], dv: EDU_FACTS,
      others: [EDU_STUDENTS] },
    { cat: 'within',
      label: 'Each pupil takes one spelling test in a quiet room and a similar test with recorded chatter playing. Their scores on the two tests are compared.',
      ivs: [EDU_NOISE], dv: EDU_SPELL,
      others: [EDU_PUPILS] },
    { cat: 'within',
      label: 'Every pupil reads one passage printed in 12-point type and another in 16-point type, and their reading speed in words per minute is compared.',
      ivs: [EDU_FONT], dv: EDU_WPM,
      others: [EDU_PUPILS, { name: 'the passages', aliases: ['passage', 'text', 'story'] }] },
    { cat: 'within',
      label: 'Each pupil studies one type of maths problem with worked examples and another type without. The number of problems of each type they then solve correctly is compared.',
      ivs: [EDU_WORKED], dv: EDU_SOLVED,
      others: [EDU_PUPILS] },
    { cat: 'within',
      label: 'The same students watch one short talk with slides of a few words and another with slides of full paragraphs. The number of points they recall from each talk is compared.',
      ivs: [EDU_SLIDES], dv: EDU_TALK,
      others: [EDU_STUDENTS] },
    { cat: 'within',
      label: 'Each pupil practises one set of French words spread over three days and another set all at once. A week later, the number of words remembered from each set is compared.',
      ivs: [EDU_SPACING], dv: EDU_WORDS_WEEK,
      others: [EDU_PUPILS, { name: 'the French words', aliases: ['french', 'french words', 'set of words', 'word set'] }] },
    { cat: 'within',
      label: 'Every pupil sits one practice paper with 20 minutes and a similar paper with 40 minutes. The number of questions they attempt on each paper is compared.',
      ivs: [EDU_LIMIT], dv: EDU_ATTEMPTED,
      others: [EDU_PUPILS, { name: 'the practice papers', aliases: ['paper', 'papers', 'practice paper', 'exam paper'] }] },
    { cat: 'within',
      label: 'The same class does one worksheet in a lesson with three announcements over the speaker and a similar worksheet in a lesson with none. The number of questions completed in each lesson is compared.',
      ivs: [EDU_INTERRUPT], dv: EDU_COMPLETED,
      others: [EDU_PUPILS] },

    { cat: 'between',
      label: 'Two classes are taught the same lesson; in one the teacher waits 1 second after each question and in the other 5 seconds. The number of pupils who put up their hands is compared between the classes.',
      ivs: [EDU_WAIT], dv: EDU_HANDS,
      others: [{ name: 'the lesson', aliases: ['lesson', 'same lesson', 'topic'] }] },
    { cat: 'between',
      label: 'Students are randomly assigned to learn a set of facts either by testing themselves or by rereading. A week later, the number of facts each group recalls is compared.',
      ivs: [EDU_METHOD], dv: EDU_FACTS,
      others: [EDU_STUDENTS] },
    { cat: 'between',
      label: 'Half the pupils take a spelling test in a quiet room and the other half take the same test with recorded chatter playing. The two groups\' scores are compared.',
      ivs: [EDU_NOISE], dv: EDU_SPELL,
      others: [EDU_PUPILS] },
    { cat: 'between',
      label: 'One group of pupils reads a passage printed in 12-point type and a different group reads the same passage in 16-point type. The two groups\' reading speeds in words per minute are compared.',
      ivs: [EDU_FONT], dv: EDU_WPM,
      others: [{ name: 'the passage', aliases: ['passage', 'text', 'story'] }] },
    { cat: 'between',
      label: 'Pupils are randomly assigned to study a type of maths problem with worked examples or without. The number of problems each group then solves correctly is compared.',
      ivs: [EDU_WORKED], dv: EDU_SOLVED,
      others: [EDU_PUPILS] },
    { cat: 'between',
      label: 'One group of students watches a short talk with slides of a few words, and another group watches the same talk with slides of full paragraphs. The number of points each group recalls is compared.',
      ivs: [EDU_SLIDES], dv: EDU_TALK,
      others: [{ name: 'the groups of students', aliases: ['students', 'groups', 'group', 'people'] }] },
    { cat: 'between',
      label: 'Half the pupils practise a set of French words spread over three days, and the other half practise the same words all at once. A week later, the number of words each group remembers is compared.',
      ivs: [EDU_SPACING], dv: EDU_WORDS_WEEK,
      others: [EDU_PUPILS, { name: 'the French words', aliases: ['french', 'french words', 'set of words', 'word set'] }] },
    { cat: 'between',
      label: 'Pupils are randomly given either 20 or 40 minutes to work on the same practice paper, and the number of questions each group attempts is compared.',
      ivs: [EDU_LIMIT], dv: EDU_ATTEMPTED,
      others: [{ name: 'the practice paper', aliases: ['paper', 'practice paper', 'exam paper'] }] },
    { cat: 'between',
      label: 'One class does a worksheet in a lesson with three announcements over the speaker, and another class does the same worksheet in a lesson with none. The number of questions completed is compared between the classes.',
      ivs: [EDU_INTERRUPT], dv: EDU_COMPLETED,
      others: [{ name: 'the classes', aliases: ['classes', 'class', 'pupils', 'children'] }] },
  ],

  // -------------------------------------------------------------------------
  // 2f-2h. Cross-sectional, longitudinal, or both.
  // -------------------------------------------------------------------------
  crosslong: {
    single: [
      { cat: 'cross',
        label: 'In the same week, pupils in Years 7, 8 and 9 each read the same passage aloud for one minute, and the number of words read correctly is compared between the year groups.',
        ivs: [{ name: 'year group', aliases: ['year group', 'year', 'years 7 8 and 9', 'school year', 'which year', 'group', 'age'] }],
        dv: EDU_FLUENCY,
        others: [{ name: 'the week of testing', aliases: ['week', 'same week', 'the passage'] }] },
      { cat: 'cross',
        label: 'On the same day, a morning maths class and an afternoon maths class take the same 20-question quiz, and the scores of the two classes are compared.',
        ivs: [{ name: 'time of the class (morning or afternoon)', aliases: ['morning or afternoon', 'morning', 'afternoon', 'time of class', 'which class', 'class'] }],
        dv: EDU_QUIZ,
        others: [{ name: 'the same day', aliases: ['day', 'same day', 'one day'] }] },
      { cat: 'cross',
        label: 'In the same term, students taking three different modules each rate the clarity of their lecture slides on a scale of 1–7, and the ratings are compared between the modules.',
        ivs: [{ name: 'module', aliases: ['module', 'modules', 'course', 'which module', 'three modules', 'subject'] }],
        dv: { name: 'clarity rating', aliases: ['clarity', 'clarity rating', 'rating', 'how clear', 'slide rating', 'score'] },
        others: [{ name: 'the term', aliases: ['term', 'same term'] }] },
      { cat: 'cross',
        label: 'In one afternoon, pupils who study French and pupils who study Spanish learn the same 20 words from an invented language, and the number each group recalls is compared.',
        ivs: [{ name: 'language studied (French or Spanish)', aliases: ['language studied', 'french or spanish', 'french', 'spanish', 'which language', 'subject', 'language'] }],
        dv: { name: 'number of invented words recalled', aliases: ['words recalled', 'recall', 'invented words', 'how many words', 'memory', 'score'] },
        others: [{ name: 'the afternoon', aliases: ['afternoon', 'one afternoon'] }] },

      { cat: 'long',
        label: 'A class of pupils read a passage aloud for one minute every half-term for a school year, and the number of words they read correctly is recorded each time.',
        ivs: [{ name: 'time (half-term)', aliases: ['half-term', 'half term', 'every half-term', 'school year', ...EDU_TIME] }],
        dv: EDU_FLUENCY,
        others: [EDU_PUPILS] },
      { cat: 'long',
        label: 'The same pupils take a two-minute times-tables test every week for a term, and the number of correct answers per minute is recorded each week.',
        ivs: [{ name: 'time (week of the term)', aliases: ['week of the term', 'every week', 'weeks of practice', ...EDU_TIME] }],
        dv: EDU_TABLES,
        others: [EDU_PUPILS] },
      { cat: 'long',
        label: 'During one long lecture, the number of notes the same students write is counted in each 10-minute stretch.',
        ivs: [{ name: 'time into the lecture', aliases: ['time into the lecture', '10-minute stretch', 'stretch', 'minutes', 'how far into the lecture', 'duration', ...EDU_TIME] }],
        dv: EDU_NOTES,
        others: [EDU_STUDENTS] },
      { cat: 'long',
        label: 'After a topic is taught, the same class takes a quiz on it one week, one month and three months later, and their scores are compared.',
        ivs: [{ name: 'time since the topic was taught', aliases: ['time since taught', 'time since the topic', 'delay', 'one week', 'one month', 'three months', 'how long ago', ...EDU_TIME] }],
        dv: EDU_QUIZ,
        others: [{ name: 'the topic', aliases: ['topic', 'lesson content'] }] },
    ],

    multi: [
      { cat: 'cross',
        label: 'In the same week, pupils in Years 7, 8 and 9 each read a story passage and an information passage aloud for one minute, and the number of words read correctly is compared.',
        ivs: [
          { name: 'year group', aliases: ['year group', 'year', 'years 7 8 and 9', 'school year', 'which year', 'age'] },
          { name: 'type of passage (story or information)', aliases: ['type of passage', 'passage type', 'story or information', 'story', 'information', 'fiction', 'non-fiction', 'genre'] },
        ],
        dv: EDU_FLUENCY,
        others: [{ name: 'the week', aliases: ['week', 'same week'] }] },
      { cat: 'cross',
        label: 'On the same day, a morning maths class and an afternoon maths class take a quiz with some recall questions and some problem-solving questions, and the scores on each kind are compared.',
        ivs: [
          { name: 'time of the class (morning or afternoon)', aliases: ['morning or afternoon', 'morning', 'afternoon', 'time of class', 'which class'] },
          { name: 'type of question (recall or problem-solving)', aliases: ['type of question', 'question type', 'recall or problem-solving', 'recall questions', 'problem-solving', 'problem solving', 'kind of question'] },
        ],
        dv: EDU_QUIZ,
        others: [{ name: 'the day', aliases: ['day', 'same day'] }] },
      { cat: 'cross',
        label: 'In the same exam week, students on two different modules each answer multiple-choice and short-answer questions, and their marks on each format are compared.',
        ivs: [
          { name: 'module', aliases: ['module', 'modules', 'course', 'which module', 'two modules'] },
          { name: 'question format (multiple choice or short answer)', aliases: ['question format', 'format', 'multiple choice', 'short answer', 'multiple choice or short answer', 'type of question'] },
        ],
        dv: { name: 'marks', aliases: ['marks', 'mark', 'score', 'result', 'grade', 'percentage correct'] },
        others: [{ name: 'the exam week', aliases: ['exam week', 'week'] }] },

      { cat: 'long',
        label: 'A class reads a familiar passage and a new passage aloud every half-term for a school year, and the number of words read correctly per minute is recorded each time.',
        ivs: [
          { name: 'time (half-term)', aliases: ['half-term', 'half term', 'every half-term', 'school year', ...EDU_TIME] },
          { name: 'passage (familiar or new)', aliases: ['familiar or new', 'familiar', 'new passage', 'passage familiarity', 'type of passage', 'unseen', 'seen before'] },
        ],
        dv: EDU_FLUENCY,
        others: [EDU_PUPILS] },
      { cat: 'long',
        label: 'The same pupils take a times-tables test every week for a term, with separate sections for the 2, 5 and 10 times tables and for the 7 and 8 times tables. Correct answers per minute are recorded for each section.',
        ivs: [
          { name: 'time (week of the term)', aliases: ['week of the term', 'every week', 'weeks of practice', ...EDU_TIME] },
          { name: 'which tables (2, 5, 10 or 7, 8)', aliases: ['which tables', 'table', 'section', 'easy or hard tables', '2 5 and 10', '7 and 8', 'difficulty'] },
        ],
        dv: EDU_TABLES,
        others: [EDU_PUPILS] },
      { cat: 'long',
        label: 'Students learn some facts by testing themselves and others by rereading, and the same students are quizzed on all the facts one week, one month and three months later.',
        ivs: [
          { name: 'time since learning', aliases: ['time since learning', 'delay', 'one week', 'one month', 'three months', 'how long ago', 'retention interval', ...EDU_TIME] },
          { name: 'study method (self-testing or rereading)', aliases: ['study method', 'method', 'self-testing', 'self testing', 'rereading', 're-reading', 'testing themselves', 'self-testing or rereading', 'how they study'] },
        ],
        dv: EDU_FACTS,
        others: [EDU_STUDENTS] },
    ],

    panel: [
      { cat: 'both',
        label: 'One class practises its weekly spellings in short daily sessions, and another class in one session a week. Both classes take a spelling test every week for six weeks.',
        ivs: [
          { name: 'practice schedule (daily or weekly)', aliases: ['practice schedule', 'schedule', 'daily or weekly', 'daily', 'weekly', 'spaced', 'massed', 'spacing', 'class', 'group'] },
          { name: 'time (week of testing)', aliases: ['week of testing', 'six weeks', 'every week', ...EDU_TIME] },
        ],
        dv: EDU_SPELL,
        others: [] },
      { cat: 'both',
        label: 'Pupils in Year 7 and Year 8 take a times-tables test at the start of every month for a school year, and their correct answers per minute are recorded.',
        ivs: [
          { name: 'year group (Year 7 or Year 8)', aliases: ['year group', 'year 7 or year 8', 'year 7', 'year 8', 'school year group', 'which year', 'group', 'age'] },
          { name: 'time (month)', aliases: ['every month', 'start of every month', 'month of the year', 'time', 'over time', 'month', 'months', 'when it was measured', 'time point', 'session', 'before and after', 'week', 'weeks', 'day', 'days'] },
        ],
        dv: EDU_TABLES,
        others: [] },
      { cat: 'both',
        label: 'A morning English class and an afternoon English class each take the same short vocabulary quiz every week for a term, and the scores of both classes are recorded.',
        ivs: [
          { name: 'time of the class (morning or afternoon)', aliases: ['morning or afternoon', 'morning', 'afternoon', 'time of class', 'which class', 'class', 'group'] },
          { name: 'time (week of the term)', aliases: ['week of the term', 'every week', ...EDU_TIME] },
        ],
        dv: EDU_QUIZ,
        others: [] },
      { cat: 'both',
        label: 'One group of pupils studies worked examples before solving equations, and another group solves them without examples. Both groups take an equations test at the end of each week for four weeks.',
        ivs: [
          { name: 'worked examples (with or without)', aliases: ['worked examples', 'examples', 'with or without examples', 'worked example', 'solutions shown', 'shown how', 'group'] },
          { name: 'time (week)', aliases: ['each week', 'four weeks', 'end of each week', ...EDU_TIME] },
        ],
        dv: EDU_SOLVED,
        others: [] },
      { cat: 'both',
        label: 'Students on two different modules have the number of notes they write in each 10-minute stretch of a lecture counted, in every lecture for five weeks.',
        ivs: [
          { name: 'module', aliases: ['module', 'modules', 'course', 'which module', 'two modules', 'group'] },
          { name: 'time (week of term)', aliases: ['week of term', 'five weeks', 'every lecture', ...EDU_TIME] },
        ],
        dv: EDU_NOTES,
        others: [] },
    ],
  },

  // -------------------------------------------------------------------------
  // Level 3. Factors for box notation.
  // -------------------------------------------------------------------------
  factors: [
    { name: 'Wait time', levels: { 2: ['1 second', '5 seconds'], 3: ['1 second', '3 seconds', '5 seconds'], 4: ['1 second', '3 seconds', '5 seconds', '7 seconds'] } },
    { name: 'Study method', levels: { 2: ['rereading', 'self-testing'], 3: ['rereading', 'summarising', 'self-testing'] } },
    { name: 'Practice spacing', levels: { 2: ['all at once', 'spaced'], 3: ['same day', '1 day apart', '3 days apart'], 4: ['same day', '1 day apart', '3 days apart', '7 days apart'] } },
    { name: 'Time allowed', levels: { 2: ['20 minutes', '40 minutes'], 3: ['20 minutes', '40 minutes', '60 minutes'], 4: ['15 minutes', '30 minutes', '45 minutes', '60 minutes'] } },
    { name: 'Font size', levels: { 2: ['12 point', '16 point'], 3: ['10 point', '12 point', '14 point'], 4: ['10 point', '12 point', '14 point', '16 point'] } },
    { name: 'Classroom noise', levels: { 2: ['quiet', 'chatter'], 3: ['quiet', 'low chatter', 'loud chatter'] } },
    { name: 'Worked examples', levels: { 2: ['none', '4 examples'], 3: ['none', '2 examples', '4 examples'], 4: ['none', '2 examples', '4 examples', '6 examples'] } },
    { name: 'Test length', levels: { 2: ['10 questions', '40 questions'], 3: ['10 questions', '20 questions', '40 questions'], 4: ['10 questions', '20 questions', '30 questions', '40 questions'] } },
    { name: 'Year group', levels: { 2: ['Year 7', 'Year 8'], 3: ['Year 7', 'Year 8', 'Year 9'], 4: ['Year 7', 'Year 8', 'Year 9', 'Year 10'] } },
    { name: 'Lesson time', levels: { 2: ['morning', 'afternoon'], 3: ['period 1', 'period 3', 'period 5'] } },
    { name: 'Question format', levels: { 2: ['multi-choice', 'short answer'], 3: ['multi-choice', 'short answer', 'essay'] } },
    { name: 'Slide text', levels: { 2: ['few words', 'full paragraph'], 3: ['10 words', '30 words', '60 words'] } },
    { name: 'Feedback', levels: { 2: ['mark only', 'comments'], 3: ['mark only', 'comments', 'both'] } },
    { name: 'Delay before quiz', levels: { 2: ['1 week', '3 months'], 3: ['1 week', '1 month', '3 months'], 4: ['1 day', '1 week', '1 month', '3 months'] } },
  ],
};
