// ---------------------------------------------------------------------------
// Health & exercise pool.
//
// The main pool for nursing, sport & exercise science, nutrition,
// physiotherapy and speech & language therapy; a neighbour pool for
// biomedical science and social work.
//
// Everything here is plainly physiological or about measurement, in healthy
// volunteers: exercise raises heart rate, a cuff that is too small reads
// high, practice improves a skill. Nothing claims that a treatment, diet,
// drug or therapy works for any condition, and nothing compares groups of
// people by who they are.
// ---------------------------------------------------------------------------

const HEALTH_TIME_WORDS = ['time', 'over time', 'when it was measured', 'time point', 'testing time', 'session', 'day', 'days', 'week', 'weeks', 'month', 'months', 'year', 'years', 'how long', 'duration', 'before and after', 'stage'];
const HEALTH_PARTICIPANTS = { name: 'the participants', aliases: ['participants', 'people', 'volunteers', 'subjects', 'person'] };
const HEALTH_HEART_RATE = { name: 'heart rate', aliases: ['heart rate', 'pulse', 'heartbeat', 'beats per minute', 'bpm', 'hr'] };
const HEALTH_GRIP = { name: 'grip strength', aliases: ['grip', 'grip strength', 'hand strength', 'how hard they squeeze', 'squeeze', 'strength', 'force'] };
const HEALTH_REACH = { name: 'sit-and-reach distance', aliases: ['sit and reach', 'reach', 'reach distance', 'flexibility', 'how far they reach', 'distance reached', 'hamstring flexibility'] };
const HEALTH_BP = { name: 'blood pressure reading', aliases: ['blood pressure', 'bp', 'reading', 'readings', 'pressure', 'systolic', 'blood pressure reading'] };
const HEALTH_INTELLIGIBILITY = { name: 'intelligibility (words understood)', aliases: ['intelligibility', 'how intelligible', 'words understood', 'words written down correctly', 'understanding', 'how well they understand', 'how much they understand', 'percentage correct'] };
const HEALTH_NOISE = { name: 'background noise (quiet or noisy)', aliases: ['noise', 'background noise', 'quiet or noisy', 'quiet', 'noisy', 'noise level', 'listening condition', 'loud'] };
const HEALTH_HUNGER = { name: 'hunger rating', aliases: ['hunger', 'how hungry', 'hungry', 'hunger score', 'appetite', 'rating'] };
const HEALTH_REPS = { name: 'number of repetitions completed', aliases: ['repetitions', 'reps', 'number of reps', 'how many repetitions', 'how many they do', 'number completed', 'squats completed'] };
const HEALTH_BALANCE = { name: 'balance time', aliases: ['balance', 'time balanced', 'how long they balance', 'balance score', 'time standing on one leg', 'standing time', 'stability'] };

POOLS.health = {

  // -------------------------------------------------------------------------
  // 1a. Variable or not?
  // -------------------------------------------------------------------------
  sortItems: [
    // --- variables: shared ---
    { label: 'heart rate', variable: true,
      why: 'Heart rate goes up and down — faster during exercise, slower at rest — and it is measured in beats per minute.' },
    { label: 'breathing rate', variable: true,
      why: 'People take more or fewer breaths a minute depending on what they are doing, and the breaths can be counted.' },
    { label: 'body temperature', variable: true,
      why: 'Body temperature changes a little through the day and rises during exercise. It is measured in degrees Celsius.' },
    { label: 'grip strength', variable: true,
      why: 'Some people squeeze harder than others, and the force can be measured with a hand dynamometer.' },
    { label: 'reaction time', variable: true,
      why: 'How quickly someone responds differs from person to person and from one attempt to the next, and it is measured in milliseconds.' },
    { label: 'blood pressure', variable: true,
      why: 'Blood pressure differs between people and changes with activity and position. It is measured in millimetres of mercury (mmHg).' },
    { label: 'time standing on one leg', variable: true,
      why: 'Some people can balance for longer than others, and the time can be measured with a stopwatch.' },
    { label: 'number of steps walked in a day', variable: true,
      why: 'People walk more on some days than others, and a step counter records the number.' },
    { label: 'hours of sleep', variable: true,
      why: 'People sleep for different lengths of time from night to night, and it can be measured in hours.' },
    { label: 'rating of perceived exertion', variable: true,
      why: 'People rate how hard an exercise feels on a numbered scale, and the rating goes up as the exercise gets harder.' },
    { label: 'oxygen saturation', variable: true,
      why: 'The percentage of oxygen carried in the blood can be measured with a finger clip, and it varies — for example, it is lower at high altitude.' },
    { label: 'number of words recalled', variable: true,
      why: 'People remember different numbers of words from a list, and the words they recall can be counted.' },

    // --- variables: sport ---
    { label: 'sprint time', variable: true, for: ['sport'],
      why: 'Some runners cover 20 metres faster than others, and timing gates measure the time.' },
    { label: 'vertical jump height', variable: true, for: ['sport', 'physiotherapy'],
      why: 'People jump to different heights, and the height can be measured in centimetres.' },
    { label: 'time to exhaustion', variable: true, for: ['sport'],
      why: 'How long someone can keep exercising at a set intensity differs between people and between sessions, and it is timed.' },
    { label: 'repetitions completed', variable: true, for: ['sport', 'physiotherapy'],
      why: 'Different people, and the same person on different sets, complete different numbers of repetitions — and they can be counted.' },

    // --- variables: physiotherapy ---
    { label: 'knee range of motion', variable: true, for: ['physiotherapy', 'sport'],
      why: 'How far the knee bends differs between people and changes after a warm-up. It is measured in degrees with a goniometer.' },
    { label: 'sit-and-reach distance', variable: true, for: ['physiotherapy', 'sport'],
      why: 'Some people can reach further past their toes than others, and the distance is measured in centimetres.' },
    { label: 'distance walked in six minutes', variable: true, for: ['physiotherapy', 'nursing'],
      why: 'People walk different distances in the same time, and the distance is measured in metres.' },

    // --- variables: nursing ---
    { label: 'urine output', variable: true, for: ['nursing', 'nutrition'],
      why: 'The volume of urine passed differs from hour to hour and depends on how much someone drinks. It is measured in millilitres.' },
    { label: 'blood glucose level', variable: true, for: ['nursing', 'nutrition'],
      why: 'Blood glucose rises after a meal and falls again over the following hours. It is measured in millimoles per litre.' },
    { label: 'ward noise level', variable: true, for: ['nursing'],
      why: 'Some wards, and some times of night, are louder than others. Noise is measured in decibels.' },
    { label: 'number of times a patient wakes in the night', variable: true, for: ['nursing'],
      why: 'Patients wake more often on some nights than others, and the wakings can be counted.' },

    // --- variables: nutrition ---
    { label: 'hunger rating', variable: true, for: ['nutrition'],
      why: 'People rate how hungry they feel, and the rating changes with how long it has been since they ate.' },
    { label: 'fluid intake', variable: true, for: ['nutrition', 'nursing'],
      why: 'People drink different amounts from day to day, and the volume is measured in millilitres.' },
    { label: 'portion size', variable: true, for: ['nutrition'],
      why: 'Portions can be larger or smaller, and they are weighed in grams.' },

    // --- variables: speech & language therapy ---
    { label: 'speech intelligibility', variable: true, for: ['slt'],
      why: 'Some speech is easier to understand than other speech. It is measured as the percentage of words a listener writes down correctly.' },
    { label: 'speaking rate', variable: true, for: ['slt'],
      why: 'People speak at different speeds, measured in syllables per second.' },
    { label: 'naming accuracy', variable: true, for: ['slt'],
      why: 'People name different numbers of pictures correctly, and the percentage correct can be worked out.' },

    // --- not variables: one particular thing ---
    { label: 'the London Marathon', variable: false,
      why: 'The London Marathon is one particular race — a thing, not a measurement. (Each runner\'s finishing time would be a variable.)' },
    { label: 'Wembley Stadium', variable: false,
      why: 'Wembley Stadium is one particular building. (The number of spectators at a match would be a variable.)' },
    { label: 'Florence Nightingale', variable: false,
      why: 'Florence Nightingale is one particular person. (How many patients a nurse cares for on a shift would be a variable.)' },
    { label: 'the treadmill in the lab', variable: false,
      why: 'It\'s one particular piece of equipment. (The speed it is set to would be a variable.)' },
    { label: 'the stethoscope', variable: false,
      why: 'A stethoscope is a piece of equipment, not a measurement. (The heart rate heard through it would be a variable.)' },
    { label: 'the Borg scale', variable: false,
      why: 'The Borg scale is one particular rating scale — a tool for measuring. (The rating of perceived exertion someone gives on it would be a variable.)' },
    { label: 'the Tour de France', variable: false,
      why: 'The Tour de France is one particular race. (A rider\'s average speed would be a variable.)' },
    { label: 'Ben Nevis', variable: false,
      why: 'Ben Nevis is one particular mountain. (A walker\'s breathing rate on the way up would be a variable.)' },
    { label: 'the apple on the desk', variable: false,
      why: 'It\'s one particular apple. (The mass of an apple would be a variable.)' },
    { label: 'the femur', variable: false,
      why: 'The femur is one particular bone — the thigh bone. (Femur length, which differs between people, would be a variable.)' },
    { label: 'the International Phonetic Alphabet', variable: false,
      why: 'It\'s one particular set of symbols for writing down speech sounds. (The number of sounds a speaker gets right would be a variable.)' },
    { label: 'the blood pressure cuff', variable: false,
      why: 'The cuff is a piece of equipment, not a measurement. (The reading it gives would be a variable — and so would the size of cuff used.)' },
    { label: 'the Olympic Games', variable: false,
      why: 'The Olympic Games is one particular event. (The number of athletes taking part would be a variable.)' },

    // --- not variables: measurable, but only one possible value ---
    { label: 'the length of a marathon', variable: false,
      why: 'A marathon is always 42.195 km. It can be measured, but it only ever has one value — a constant, not a variable.' },
    { label: 'the length of an Olympic swimming pool', variable: false,
      why: 'An Olympic pool is always 50 metres long. Something that can only ever have one value is a constant.' },
    { label: 'the height of a basketball hoop', variable: false,
      why: 'A regulation hoop is always 3.05 metres high. It can be measured, but it doesn\'t vary.' },
    { label: 'the number of minutes in an hour', variable: false,
      why: 'It\'s always 60 — only one possible value, so it\'s a constant, not a variable.' },
  ],

  // -------------------------------------------------------------------------
  // 1b-1d, 2b, 2c. Relations between two variables.
  // -------------------------------------------------------------------------
  relations: [
    // --- shared ---
    { id: 'health-intensity-hr', hyp: ['exercise intensity', 'heart rate'], iv: 'exercise intensity', dv: 'heart rate',
      ivNP: 'exercise intensity', dvNP: 'heart rate', ivAxis: 'Intensity', dvAxis: 'Heart rate', dir: 'up',
      says: ['The harder people exercise, the faster their heart beats.',
             'Heart rate goes up as exercise intensity goes up.'],
      why: 'The intensity is set first — how fast the treadmill runs — and the heart responds to it. A fast heartbeat can\'t make the treadmill go faster.' },
    { id: 'health-intensity-br', hyp: ['exercise intensity', 'breathing rate'], iv: 'exercise intensity', dv: 'breathing rate',
      ivNP: 'exercise intensity', dvNP: 'the breathing rate', ivAxis: 'Intensity', dvAxis: 'Breathing rate', dir: 'up',
      says: ['People breathe faster the harder they exercise.',
             'Breathing rate rises as exercise intensity increases.'],
      why: 'Harder exercise needs more oxygen, so the intensity is what drives the breathing. Breathing faster on purpose doesn\'t make the exercise harder.' },
    { id: 'health-heat-hr', hyp: ['air temperature', 'heart rate'], iv: 'air temperature', dv: 'heart rate during exercise',
      ivNP: 'the air temperature', dvNP: 'heart rate during exercise', ivAxis: 'Air temperature', dvAxis: 'Heart rate', dir: 'up',
      says: ['When people cycle at the same pace in a hotter room, their heart rate is higher.',
             'Heart rate during exercise goes up as the room gets hotter.'],
      why: 'The room temperature is set before the exercise starts, and the body works harder to lose heat. A faster heartbeat can\'t heat up the room.' },
    { id: 'health-duration-temp', hyp: ['exercise time', 'body temperature'], iv: 'time spent exercising', dv: 'body temperature',
      ivNP: 'the time spent exercising', dvNP: 'body temperature', ivAxis: 'Exercise time', dvAxis: 'Body temperature', dir: 'up',
      says: ['In the first half hour of a steady run, body temperature rises the longer people have been running.',
             'Body temperature goes up the longer people have been running, over the first half hour of a steady run.'],
      why: 'Working muscles produce heat, so the time spent exercising is what warms the body. Being warmer can\'t add minutes to the run.' },
    { id: 'health-altitude-spo2', hyp: ['altitude', 'blood oxygen'], iv: 'altitude', dv: 'oxygen saturation',
      ivNP: 'altitude', dvNP: 'oxygen saturation', ivAxis: 'Altitude', dvAxis: 'Blood oxygen', dir: 'down',
      says: ['The higher people climb, the lower the oxygen saturation of their blood.',
             'Oxygen saturation falls as altitude increases.'],
      why: 'There is less oxygen in the air higher up, so altitude is the changer. The amount of oxygen in someone\'s blood can\'t change how high the mountain is.' },
    { id: 'health-awake-rt', hyp: ['hours awake', 'reaction time'], iv: 'hours awake', dv: 'reaction time',
      ivNP: 'the number of hours awake', dvNP: 'reaction time', ivAxis: 'Hours awake', dvAxis: 'Reaction time', dir: 'up',
      says: ['The longer people have been awake without sleep, the slower they react.',
             'Reaction times get longer the more hours people have gone without sleep.'],
      why: 'The hours awake come first and tiredness slows the responses. Careful with the graph: reacting more slowly means the reaction TIME goes up.' },
    { id: 'health-practice-rt', hyp: ['practice trials', 'reaction time'], iv: 'practice trials', dv: 'reaction time',
      ivNP: 'the number of practice trials', dvNP: 'reaction time', ivAxis: 'Practice', dvAxis: 'Reaction time', dir: 'down',
      says: ['The more practice trials people have on a new reaction task, the faster they respond.',
             'Reaction time on a new task gets shorter with more practice trials.'],
      why: 'The practice comes first and makes people quicker. Careful with the graph: quicker means a SHORTER time, so the line goes down.' },
    { id: 'health-squeeze-grip', hyp: ['repeated squeezes', 'grip strength'], iv: 'number of squeezes', dv: 'grip strength',
      ivNP: 'the number of squeezes', dvNP: 'grip strength', ivAxis: 'Squeezes', dvAxis: 'Grip strength', dir: 'down',
      says: ['The more times in a row people squeeze a grip meter as hard as they can, the weaker their grip becomes.',
             'Grip strength drops with each maximum squeeze people have already done.'],
      why: 'Each squeeze tires the hand muscles, so the squeezes are the changer. A weaker grip can\'t go back and add squeezes.' },
    { id: 'health-cold-grip', hyp: ['time in cold water', 'grip strength'], iv: 'time with the hand in cold water', dv: 'grip strength',
      ivNP: 'the time the hand spends in cold water', dvNP: 'grip strength', ivAxis: 'Cooling time', dvAxis: 'Grip strength', dir: 'down',
      says: ['The longer people hold their hand in cold water, the weaker their grip afterwards.',
             'Grip strength goes down the longer the hand has been cooled in cold water.'],
      why: 'Cooling the muscles is what weakens them, and it happens before the grip is tested. A weak grip can\'t change how long the hand was in the water.' },

    // --- sport ---
    { id: 'health-incline-hr', for: ['sport'], hyp: ['treadmill incline', 'heart rate'], iv: 'treadmill incline', dv: 'heart rate',
      ivNP: 'the treadmill incline', dvNP: 'heart rate', ivAxis: 'Incline', dvAxis: 'Heart rate', dir: 'up',
      says: ['Walking at the same speed, people\'s heart rate is higher the steeper the treadmill slope.',
             'Heart rate rises as the incline of the treadmill goes up.'],
      why: 'The researcher sets the slope, and walking uphill is harder work. The heart speeding up can\'t tilt the treadmill.' },
    { id: 'health-training-strength', for: ['sport', 'physiotherapy'], hyp: ['weeks of training', 'leg strength'], iv: 'weeks of strength training', dv: 'leg strength',
      ivNP: 'the number of weeks of strength training', dvNP: 'leg strength', ivAxis: 'Training weeks', dvAxis: 'Leg strength', dir: 'up',
      says: ['The more weeks healthy volunteers spend on a strength-training programme, the stronger their legs become.',
             'Leg strength goes up with each week of strength training.'],
      why: 'The training comes first and builds the muscle. Being stronger at the end can\'t change how many weeks were spent training.' },
    { id: 'health-altitude-br', for: ['sport'], hyp: ['altitude', 'breathing rate'], iv: 'altitude', dv: 'breathing rate',
      ivNP: 'altitude', dvNP: 'the breathing rate', ivAxis: 'Altitude', dvAxis: 'Breathing rate', dir: 'up',
      says: ['People breathe faster at higher altitudes, even at rest.',
             'Resting breathing rate goes up as altitude increases.'],
      why: 'The thinner air higher up is what makes people breathe faster. Breathing faster doesn\'t take anyone higher up the mountain.' },
    { id: 'health-rest-reps', for: ['sport'], hyp: ['rest between sets', 'repetitions'], iv: 'rest time between sets', dv: 'repetitions completed',
      ivNP: 'the rest time between sets', dvNP: 'the number of repetitions completed', ivAxis: 'Rest time', dvAxis: 'Repetitions', dir: 'up',
      says: ['The longer people rest between sets, the more repetitions they complete in the next set.',
             'The number of repetitions completed goes up with longer rests between sets.'],
      why: 'The rest comes before the set and lets the muscles recover. Completing more repetitions can\'t make the rest before it longer.' },
    { id: 'health-load-reps', for: ['sport', 'physiotherapy'], hyp: ['weight lifted', 'repetitions'], iv: 'weight lifted', dv: 'repetitions completed',
      ivNP: 'the weight lifted', dvNP: 'the number of repetitions completed', ivAxis: 'Weight lifted', dvAxis: 'Repetitions', dir: 'down',
      says: ['The heavier the weight, the fewer repetitions people can lift it.',
             'The number of repetitions people complete falls as the weight gets heavier.'],
      why: 'The weight is chosen before the set starts; how many repetitions people manage is the result. Doing fewer repetitions can\'t make the weight heavier.' },
    { id: 'health-warmup-rom', for: ['sport', 'physiotherapy'], hyp: ['warm-up time', 'range of motion'], iv: 'warm-up time', dv: 'range of motion',
      ivNP: 'the length of the warm-up', dvNP: 'range of motion', ivAxis: 'Warm-up time', dvAxis: 'Range of motion', dir: 'up',
      says: ['After a longer warm-up, people can move their hip through a wider range.',
             'Hip range of motion goes up with the length of the warm-up.'],
      why: 'The warm-up comes first and loosens the muscles. Moving the hip further can\'t go back and lengthen the warm-up.' },

    // --- physiotherapy ---
    { id: 'health-stretch-reach', for: ['physiotherapy', 'sport'], hyp: ['stretching time', 'sit-and-reach'], iv: 'time spent stretching', dv: 'sit-and-reach distance',
      ivNP: 'the time spent stretching', dvNP: 'sit-and-reach distance', ivAxis: 'Stretching time', dvAxis: 'Sit-and-reach', dir: 'up',
      says: ['Measured straight afterwards, people who have stretched their hamstrings for longer reach further in the sit-and-reach test.',
             'Sit-and-reach distance, measured straight after stretching, goes up with the time spent stretching.'],
      why: 'The stretching is done first and the reach is measured after it. Reaching further can\'t add time to the stretching already done.' },
    { id: 'health-practice-balance', for: ['physiotherapy'], hyp: ['balance practice', 'balance time'], iv: 'balance practice sessions', dv: 'balance time',
      ivNP: 'the number of practice sessions', dvNP: 'balance time', ivAxis: 'Practice', dvAxis: 'Balance time', dir: 'up',
      says: ['The more sessions healthy volunteers spend practising on a wobble board, the longer they can stay balanced on it.',
             'Time balanced on a wobble board goes up with the number of practice sessions.'],
      why: 'The practice comes first and builds the skill. Balancing for longer can\'t change how many sessions were already done.' },
    { id: 'health-practice-task', for: ['physiotherapy'], hyp: ['practice attempts', 'task time'], iv: 'practice attempts', dv: 'time to complete the task',
      ivNP: 'the number of practice attempts', dvNP: 'the time taken to complete the task', ivAxis: 'Attempts', dvAxis: 'Task time', dir: 'down',
      says: ['The more times people practise a new pegboard task, the less time it takes them.',
             'The time taken to complete a new pegboard task goes down with practice.'],
      why: 'The practice is what makes the movement smoother. Careful with the graph: getting better means taking LESS time, so the line goes down.' },

    // --- nursing ---
    { id: 'health-cuff-bp', for: ['nursing'], hyp: ['cuff size', 'blood pressure reading'], iv: 'cuff size', dv: 'blood pressure reading',
      ivNP: 'the size of the cuff', dvNP: 'the blood pressure reading', ivAxis: 'Cuff size', dvAxis: 'Blood pressure', dir: 'down',
      says: ['On the same arm, a cuff that is too small gives a higher blood pressure reading, and the reading comes down as the cuff gets larger.',
             'Blood pressure readings go down as the cuff used on the same arm gets bigger.'],
      why: 'The nurse chooses the cuff before measuring; the reading is the result. A high reading can\'t change which cuff was picked — which is why the cuff has to fit the arm.' },
    { id: 'health-arm-bp', for: ['nursing'], hyp: ['arm height', 'blood pressure reading'], iv: 'arm height', dv: 'blood pressure reading',
      ivNP: 'the height of the arm', dvNP: 'the blood pressure reading', ivAxis: 'Arm height', dvAxis: 'Blood pressure', dir: 'down',
      says: ['The lower the arm hangs below the level of the heart, the higher the blood pressure reading.',
             'Blood pressure readings go down as the arm is raised towards the level of the heart.'],
      why: 'Where the arm is held is set before the reading is taken, and it changes the pressure in the arm. The reading can\'t move the arm — which is why the arm should be supported at heart level.' },
    { id: 'health-meal-glucose', for: ['nursing', 'nutrition'], hyp: ['time since a meal', 'blood glucose'], iv: 'time since a meal', dv: 'blood glucose',
      ivNP: 'the time since a meal', dvNP: 'blood glucose', ivAxis: 'Time since meal', dvAxis: 'Blood glucose', dir: 'down',
      says: ['In healthy adults, blood glucose falls back from one hour to three hours after a meal.',
             'Between one and three hours after eating, the more time has passed, the lower a healthy adult\'s blood glucose.'],
      why: 'Time passing is what lets the body clear the sugar from the meal. A lower glucose reading can\'t make time pass.' },
    { id: 'health-fluid-urine', for: ['nursing', 'nutrition'], hyp: ['fluid intake', 'urine output'], iv: 'fluid intake', dv: 'urine output',
      ivNP: 'fluid intake', dvNP: 'urine output', ivAxis: 'Fluid intake', dvAxis: 'Urine output', dir: 'up',
      says: ['The more water healthy volunteers drink, the more urine they pass over the next few hours.',
             'Urine output goes up with the amount of fluid people drink.'],
      why: 'The drinking comes first, and the body passes the extra water. Passing more urine can\'t make someone have drunk more.' },
    { id: 'health-noise-sleep', for: ['nursing'], hyp: ['ward noise', 'sleep rating'], iv: 'ward noise', dv: 'sleep rating',
      ivNP: 'the noise level on the ward', dvNP: 'patients\' sleep ratings', ivAxis: 'Ward noise', dvAxis: 'Sleep rating', dir: 'down',
      says: ['The noisier the ward at night, the worse patients rate their sleep.',
             'Patients\' ratings of how well they slept go down on noisier nights.'],
      why: 'The noise happens during the night and disturbs sleep. Rating the night badly the next morning can\'t make the ward noisier.' },

    // --- nutrition ---
    { id: 'health-since-hunger', for: ['nutrition'], hyp: ['time since eating', 'hunger'], iv: 'time since eating', dv: 'hunger rating',
      ivNP: 'the time since eating', dvNP: 'hunger ratings', ivAxis: 'Hours since meal', dvAxis: 'Hunger rating', dir: 'up',
      says: ['The longer it has been since people last ate, the hungrier they say they feel.',
             'Hunger ratings go up as the time since the last meal gets longer.'],
      why: 'Time passing since the meal is what brings the hunger back. Feeling hungry can\'t make more time pass.' },
    { id: 'health-portion-fullness', for: ['nutrition'], hyp: ['portion size', 'fullness'], iv: 'portion size', dv: 'fullness rating',
      ivNP: 'portion size', dvNP: 'fullness ratings', ivAxis: 'Portion size', dvAxis: 'Fullness', dir: 'up',
      says: ['Straight after a meal, people who ate a larger portion rate themselves as fuller.',
             'Fullness ratings just after eating go up with the size of the portion.'],
      why: 'The portion is served and eaten first; the fullness rating comes after. Feeling full can\'t make the portion already eaten bigger.' },

    // --- speech & language therapy ---
    { id: 'health-practice-naming', for: ['slt'], hyp: ['naming practice', 'naming accuracy'], iv: 'naming practice', dv: 'naming accuracy',
      ivNP: 'the amount of naming practice', dvNP: 'naming accuracy', ivAxis: 'Practice', dvAxis: 'Naming accuracy', dir: 'up',
      says: ['The more times healthy adults practise the names of unfamiliar tools, the more of them they name correctly.',
             'Naming accuracy for new object names goes up with practice.'],
      why: 'The practice comes first and builds the memory for the names. Naming more correctly can\'t add practice that already happened.' },
    { id: 'health-noise-intel', for: ['slt'], hyp: ['background noise', 'intelligibility'], iv: 'background noise', dv: 'speech intelligibility',
      ivNP: 'the level of background noise', dvNP: 'speech intelligibility', ivAxis: 'Noise', dvAxis: 'Intelligibility', dir: 'down',
      says: ['The louder the background noise, the fewer of a speaker\'s words listeners understand.',
             'Speech intelligibility drops as background noise gets louder.'],
      why: 'The noise masks the speech the listener is trying to hear. Understanding fewer words can\'t make the room louder.' },
    { id: 'health-rate-intel', for: ['slt'], hyp: ['speaking rate', 'intelligibility'], iv: 'speaking rate', dv: 'speech intelligibility',
      ivNP: 'speaking rate', dvNP: 'speech intelligibility', ivAxis: 'Speaking rate', dvAxis: 'Intelligibility', dir: 'down',
      says: ['When a speaker reads a passage much faster, listeners correctly write down fewer of the words.',
             'Intelligibility goes down as speaking rate goes up.'],
      why: 'How fast the speaker talks is what the listener has to cope with. The listener\'s score can\'t change how fast the passage was already read.' },
    { id: 'health-delay-recall', for: ['slt'], hyp: ['delay', 'words recalled'], iv: 'delay before recall', dv: 'words recalled',
      ivNP: 'the delay before recall', dvNP: 'the number of words recalled', ivAxis: 'Delay', dvAxis: 'Words recalled', dir: 'down',
      says: ['The longer the delay after hearing a word list, the fewer words healthy adults can recall.',
             'The number of words recalled from a list goes down as the delay gets longer.'],
      why: 'Time passing is what does the forgetting. Recalling fewer words can\'t make the delay longer.' },
  ],

  // -------------------------------------------------------------------------
  // 2a. Validity and reliability.
  // -------------------------------------------------------------------------
  validity: [
    // valid and reliable
    { valid: true, reliable: true,
      text: 'To measure heart rate during cycling, researchers use a chest-strap heart rate monitor. When the same people repeat the same ride the next day, the readings are almost identical.',
      whyValid: 'a heart rate monitor records the heartbeat directly.',
      whyReliable: 'the same people give almost the same readings on the same ride the next day.' },
    { valid: true, reliable: true,
      text: 'To measure grip strength, each participant squeezes a hand dynamometer three times in the same seated position, and the best score is recorded. Tested again a few days later, people get very similar scores.',
      whyValid: 'a dynamometer measures the force of the squeeze, which is exactly what grip strength is.',
      whyReliable: 'testing again a few days later gives very similar scores.' },
    { valid: true, reliable: true,
      text: 'To measure knee range of motion, a physiotherapist lines up a goniometer on marked points around the knee. A second physiotherapist measuring the same knees gets the same angles to within a couple of degrees.',
      whyValid: 'a goniometer measures the angle the joint moves through.',
      whyReliable: 'two people measuring separately get nearly the same angles.' },
    { valid: true, reliable: true,
      text: 'To measure speech intelligibility, listeners write down every word of a recorded passage, and the percentage written correctly is worked out. Two researchers who score the same answer sheets get the same percentages.',
      whyValid: 'the percentage of words a listener gets right is a direct measure of how understandable the speech is.',
      whyReliable: 'two people scoring separately get the same results.' },
    { valid: true, reliable: true,
      text: 'To find out whether heart rate goes up when people run up a flight of stairs, researchers test 5 volunteers. When they test another 5, every one of them also has a higher heart rate at the top.',
      whyValid: 'measuring heart rate before and after the stairs is the right way to find out.',
      whyReliable: 'another 5 people give the same result. With an effect this big, 5 people is enough.' },

    // reliable, not valid
    { valid: false, reliable: true,
      text: 'To measure how fit people are, researchers count how many pairs of trainers each person owns. The count is the same every time they ask.',
      whyValid: 'owning trainers isn\'t fitness — someone can own ten pairs and never run.',
      whyReliable: 'people give the same number every time.' },
    { valid: false, reliable: true,
      text: 'To measure how flexible people are, researchers measure their height with a wall-mounted height measure. The same person gets the same height every time.',
      whyValid: 'height says nothing about how far someone can stretch — it measures something else entirely.',
      whyReliable: 'measuring the same person gives the same number. Consistent, but consistently measuring the wrong thing.' },
    { valid: false, reliable: true,
      text: 'To measure how well patients slept, a nurse records how many pillows are on each bed in the morning. The count comes out the same whoever does the counting.',
      whyValid: 'the number of pillows isn\'t how well someone slept.',
      whyReliable: 'anyone who counts gets the same number.' },
    { valid: false, reliable: true,
      text: 'To measure how full people feel after a meal, researchers measure the width of the plate it was served on. The plate measures the same every time.',
      whyValid: 'the size of the plate isn\'t how full someone feels — people should be asked.',
      whyReliable: 'measuring the same plate gives the same number every time.' },
    { valid: false, reliable: true,
      text: 'To measure how intelligible a speaker is, researchers count the number of words in the passage they read aloud. Everyone who counts gets the same total.',
      whyValid: 'the length of the passage has nothing to do with how easy the speaker is to understand.',
      whyReliable: 'counting the passage again gives the same number.' },

    // valid, not reliable
    { valid: true, reliable: false,
      text: 'To measure 20-metre sprint time, one researcher starts and stops a hand-held stopwatch while watching each runner. The same run gets quite different times depending on how quickly the researcher presses the button.',
      whyValid: 'timing the sprint is the right thing to measure.',
      whyReliable: 'the times depend on the researcher\'s thumb, not just the runner.' },
    { valid: true, reliable: false,
      text: 'To measure knee range of motion, a physiotherapist simply estimates the angle by eye. When the same knees are estimated again later, the angles differ by up to 20 degrees.',
      whyValid: 'judging how far the knee bends is aimed at the right thing.',
      whyReliable: 'an estimate by eye changes a lot from one go to the next.' },
    { valid: true, reliable: false,
      text: 'To measure blood pressure, a nurse takes a single hurried reading with a manual cuff straight after each patient sits down. A second reading a few minutes later is often very different.',
      whyValid: 'a blood pressure cuff is the right tool for measuring blood pressure.',
      whyReliable: 'one hurried reading, with no rest first, changes a lot when it is repeated.' },
    { valid: true, reliable: false,
      text: 'To find out whether a 5-minute warm-up changes 20-metre sprint time by a small amount, researchers test 4 runners. When they test another 4, the difference comes out the other way.',
      whyValid: 'timing sprints with and without a warm-up is the right way to answer the question.',
      whyReliable: 'repeating it with another 4 people gives a different result. For a small difference like this, 4 participants is far too few.' },
    { valid: true, reliable: false,
      text: 'Researchers measure grip strength with a proper dynamometer, but their report doesn\'t say which hand was tested, how participants sat, or how many squeezes they were given. Other researchers who try to repeat the study get different results.',
      whyValid: 'a dynamometer is the right tool for measuring grip strength.',
      whyReliable: 'without a full "recipe" — procedure, equipment, participants — nobody can repeat the study and get the same result.' },

    // neither
    { valid: false, reliable: false,
      text: 'To measure how fit people are, researchers ask each person to pick a card from a shuffled pack and record its number. People pick a different card every time.',
      whyValid: 'a random card has nothing to do with fitness.',
      whyReliable: 'the same person gets a different "score" every time.' },
    { valid: false, reliable: false,
      text: 'To measure how hungry people are, researchers note which chair each person chooses in the waiting room. People choose different chairs on different days.',
      whyValid: 'the chair someone picks isn\'t a measure of hunger.',
      whyReliable: 'the same person gets a different result every day.' },
    { valid: false, reliable: false,
      text: 'To measure balance, researchers record which song is playing on the radio when each participant arrives. It is a different song every visit.',
      whyValid: 'the song on the radio has nothing to do with balance.',
      whyReliable: 'the same person gets a different result every visit.' },
    { valid: false, reliable: false,
      text: 'To measure how intelligible a speaker is, researchers count the cars that pass the clinic window while the speaker is recorded. The count is different every time.',
      whyValid: 'passing cars have nothing to do with how easy the speaker is to understand.',
      whyReliable: 'the same speaker gets a different number every recording.' },
  ],

  // -------------------------------------------------------------------------
  // 2d. Continuous or discrete.
  // -------------------------------------------------------------------------
  continuity: [
    { cat: 'cont', label: 'body temperature', why: 'It can take any value on a scale, including every value in between — 36.8°C, 36.85°C, 36.852°C...' },
    { cat: 'cont', label: 'grip strength in kilograms', why: 'It can take any value on a scale, including every value in between — 31 kg, 31.4 kg, 31.42 kg...' },
    { cat: 'cont', label: 'reaction time', why: 'It can take any value on a scale, including every value in between — 250 ms, 250.3 ms... time can always be divided further.' },
    { cat: 'cont', label: '20-metre sprint time', why: 'It can take any value on a scale, including every value in between — 3.41 s, 3.415 s...' },
    { cat: 'cont', label: 'blood pressure', why: 'It can take any value on a scale, including every value in between — the pressure itself changes smoothly, even if the monitor rounds it to whole numbers.' },
    { cat: 'cont', label: 'blood glucose level', why: 'It can take any value on a scale, including every value in between — 5.2, 5.25, 5.253 mmol/L...' },
    { cat: 'cont', label: 'volume of urine passed', why: 'It can take any value on a scale, including every value in between — 250 ml, 250.5 ml...' },
    { cat: 'cont', label: 'volume of water drunk', why: 'It can take any value on a scale, including every value in between — a volume can always be measured more finely.' },
    { cat: 'cont', label: 'vertical jump height', why: 'It can take any value on a scale, including every value in between — 41 cm, 41.3 cm, 41.35 cm...' },
    { cat: 'cont', label: 'knee range of motion in degrees', why: 'It can take any value on a scale, including every value in between — 120°, 120.5°...' },
    { cat: 'cont', label: 'sit-and-reach distance', why: 'It can take any value on a scale, including every value in between — distance can always be measured more finely.' },
    { cat: 'cont', label: 'time standing on one leg', why: 'It can take any value on a scale, including every value in between — 28 s, 28.6 s, 28.61 s...' },
    { cat: 'cont', label: 'time since the last meal', why: 'It can take any value on a scale, including every value in between — 2 hours, 2.5 hours, 2 hours and 31 minutes...' },
    { cat: 'cont', label: 'speaking rate (syllables per second)', why: 'It can take any value on a scale, including every value in between — 4.8, 4.85, 4.9 syllables per second...' },
    { cat: 'cont', label: 'distance walked in six minutes', why: 'It can take any value on a scale, including every value in between — 480 m, 480.5 m...' },

    { cat: 'disc', label: 'number of repetitions completed', why: 'It only comes in separate values, with nothing in between — someone completes 8 or 9 squats, not 8.5.' },
    { cat: 'disc', label: 'number of heartbeats counted in 15 seconds', why: 'It only comes in separate values, with nothing in between — the beats are counted one by one.' },
    { cat: 'disc', label: 'number of breaths counted in a minute', why: 'It only comes in separate values, with nothing in between — breaths are counted in whole numbers.' },
    { cat: 'disc', label: 'number of steps taken in a day', why: 'It only comes in separate values, with nothing in between — steps are counted.' },
    { cat: 'disc', label: 'number of words recalled from a list', why: 'It only comes in separate values, with nothing in between — someone recalls 7 words or 8, never 7.5.' },
    { cat: 'disc', label: 'number of pictures named correctly', why: 'It only comes in separate values, with nothing in between — each picture is either named correctly or not.' },
    { cat: 'disc', label: 'number of times a patient wakes in the night', why: 'It only comes in separate values, with nothing in between — wakings are counted.' },
    { cat: 'disc', label: 'number of patients on a ward', why: 'It only comes in separate values, with nothing in between — patients are counted in whole numbers.' },
    { cat: 'disc', label: 'number of training sessions attended', why: 'It only comes in separate values, with nothing in between — you attend 11 sessions or 12, not 11.5.' },
    { cat: 'disc', label: 'number of lengths swum', why: 'It only comes in separate values, with nothing in between — lengths are counted as whole lengths.' },
    { cat: 'disc', label: 'hunger rating on a 1–7 scale', why: 'It only comes in separate values, with nothing in between — people choose 1, 2, 3... 7, and there\'s no 4.5 on the scale.' },
    { cat: 'disc', label: 'rating of perceived exertion on the 6–20 Borg scale', why: 'It only comes in separate values, with nothing in between — people choose a whole number from 6 to 20.' },
    { cat: 'disc', label: 'number of times someone loses balance in a trial', why: 'It only comes in separate values, with nothing in between — each loss of balance is counted once.' },
    { cat: 'disc', label: 'number of words a listener writes down correctly', why: 'It only comes in separate values, with nothing in between — each word is either right or not, so the total is a whole number.' },
  ],

  // -------------------------------------------------------------------------
  // 2e. Levels of measurement.
  // -------------------------------------------------------------------------
  measurement: [
    { cat: 'categorical', label: 'blood type', why: 'Categorical: distinct outcomes with no order. A, B, AB and O are different outcomes, not ranked ones.' },
    { cat: 'categorical', label: 'type of exercise (running, cycling, rowing)', why: 'Categorical: distinct outcomes with no order. Cycling isn\'t more or less than running, just different.' },
    { cat: 'categorical', label: 'hand tested (left or right)', why: 'Categorical: distinct outcomes with no order. Left isn\'t more than right.' },
    { cat: 'categorical', label: 'position during measurement (lying, sitting or standing)', why: 'Categorical: distinct outcomes with no order. These are different positions, not amounts of anything.' },
    { cat: 'categorical', label: 'which ward a patient is on', why: 'Categorical: distinct outcomes with no order. Ward A and Ward B are labels, not amounts.' },
    { cat: 'categorical', label: 'type of drink given (water, milk or juice)', why: 'Categorical: distinct outcomes with no order. Milk isn\'t more or less than water, just different.' },
    { cat: 'categorical', label: 'sport played', why: 'Categorical: distinct outcomes with no order. Hockey isn\'t more than netball, just different.' },
    { cat: 'categorical', label: 'which group a participant is in (stretching or no stretching)', why: 'Categorical: distinct outcomes with no order. The groups are labels, not amounts.' },

    { cat: 'ordinal', label: 'medal won (gold, silver, bronze)', why: 'Ordinal: the outcomes are ranked, but the difference between steps is arbitrary. Gold beats silver, but the gap could be a hundredth of a second or a whole minute.' },
    { cat: 'ordinal', label: 'finishing position in a race (1st, 2nd, 3rd)', why: 'Ordinal: the outcomes are ranked, but the difference between steps is arbitrary. The gap between 1st and 2nd needn\'t match the gap between 2nd and 3rd.' },
    { cat: 'ordinal', label: 'breathlessness described as none, slight, moderate or severe', why: 'Ordinal: the outcomes are ranked, but the difference between steps is arbitrary. The labels are in order, but nothing says the steps are the same size.' },
    { cat: 'ordinal', label: 'hunger described as "not hungry", "a little hungry" or "very hungry"', why: 'Ordinal: the outcomes are ranked, but the difference between steps is arbitrary. The answers are in order, but not equally spaced.' },
    { cat: 'ordinal', label: 'speech rated as "always", "usually", "sometimes" or "rarely" understood', why: 'Ordinal: the outcomes are ranked, but the difference between steps is arbitrary. The labelled steps are in order, but their size isn\'t fixed.' },
    { cat: 'ordinal', label: 'swimming badge level (bronze, silver, gold)', why: 'Ordinal: the outcomes are ranked, but the difference between steps is arbitrary. The levels are in order, but not equal-sized steps.' },

    { cat: 'interval', label: 'body temperature in °C', why: 'Interval: ranked, with a constant difference between steps, but no natural zero — so values aren\'t "twice as much". 0°C isn\'t "no temperature", so 40°C isn\'t twice as hot as 20°C.' },
    { cat: 'interval', label: 'rating of perceived exertion on the 6–20 Borg scale', why: 'Interval: ranked, with a constant difference between steps, but no natural zero — so values aren\'t "twice as much". A numbered scale has equal steps, but a 16 isn\'t "twice as hard" as an 8.' },
    { cat: 'interval', label: 'fullness rated on a scale of 1–7', why: 'Interval: ranked, with a constant difference between steps, but no natural zero — so values aren\'t "twice as much". There\'s no zero on the scale, so a 6 isn\'t twice as full as a 3.' },
    { cat: 'interval', label: 'date of a training session', why: 'Interval: ranked, with a constant difference between steps, but no natural zero — so values aren\'t "twice as much". Days are equal steps, but the calendar\'s starting point is arbitrary.' },
    { cat: 'interval', label: 'time of day a reading is taken', why: 'Interval: ranked, with a constant difference between steps, but no natural zero — so values aren\'t "twice as much". Midnight isn\'t "no time", so 4 o\'clock isn\'t twice 2 o\'clock.' },
    { cat: 'interval', label: 'calendar year of a study', why: 'Interval: ranked, with a constant difference between steps, but no natural zero — so values aren\'t "twice as much". Year 0 isn\'t the beginning of time, so 2000 isn\'t "twice" 1000.' },

    { cat: 'ratio', label: 'grip strength in kilograms', why: 'Ratio: ranked, constant steps AND a natural zero, so "twice as much" makes sense. 0 kg is no force at all, and 40 kg is twice 20 kg.' },
    { cat: 'ratio', label: 'heart rate in beats per minute', why: 'Ratio: ranked, constant steps AND a natural zero, so "twice as much" makes sense. 0 beats per minute is no beats at all, and 140 is twice 70.' },
    { cat: 'ratio', label: 'urine output in millilitres', why: 'Ratio: ranked, constant steps AND a natural zero, so "twice as much" makes sense. 0 ml is none at all, and 400 ml is twice 200 ml.' },
    { cat: 'ratio', label: 'time to exhaustion in seconds', why: 'Ratio: ranked, constant steps AND a natural zero, so "twice as much" makes sense. 0 seconds is no time, and 600 seconds is twice 300.' },
    { cat: 'ratio', label: 'number of repetitions completed', why: 'Ratio: ranked, constant steps AND a natural zero, so "twice as much" makes sense. Zero repetitions means none, and 12 is twice 6.' },
    { cat: 'ratio', label: 'distance walked in metres', why: 'Ratio: ranked, constant steps AND a natural zero, so "twice as much" makes sense. 0 m is no distance, and 500 m is twice 250 m.' },
    { cat: 'ratio', label: 'number of words recalled', why: 'Ratio: ranked, constant steps AND a natural zero, so "twice as much" makes sense. Zero words is none at all, and 10 words is twice 5.' },
  ],

  // -------------------------------------------------------------------------
  // 2g. Confounds. Mostly pairs: the same study done badly, then properly.
  // -------------------------------------------------------------------------
  confounds: [
    { iv: 'warm-up', dv: 'sprint time', confound: 'track surface',
      vars: ['warm-up', 'sprint time', 'track surface', 'the timing gates'],
      text: 'Researchers want to know whether a warm-up affects 20-metre sprint time, using the same timing gates for everyone. The warm-up group runs on a dry indoor track; the no-warm-up group runs outside on a wet track.',
      why: 'The no-warm-up group also ran on a wet surface, which could slow anyone down. Any difference could come from the track, not the warm-up.' },
    { iv: 'hand cooling', dv: 'grip strength', confound: 'time of testing',
      vars: ['hand cooling', 'grip strength', 'time of testing', 'the dynamometer'],
      text: 'To test whether cooling the hand affects grip strength, one group holds their hand in cold water and another in warm water before using the same dynamometer. The cold-water group is tested at the end of a long training session; the warm-water group before it.',
      why: 'The cold-water group was also tired from training. A weaker grip could come from the tiredness, not the cold.' },
    { iv: 'exercise intensity', dv: 'heart rate', confound: 'room temperature',
      vars: ['exercise intensity', 'heart rate', 'room temperature', 'the exercise bikes'],
      text: 'Researchers test whether exercise intensity affects heart rate on identical exercise bikes. The high-intensity group cycles in a hot room; the low-intensity group cycles in a cool one.',
      why: 'Heat raises heart rate on its own, and the high-intensity group was also in the hot room. The difference could come from the heat, not the intensity.' },
    { iv: 'rest time between sets', dv: 'repetitions completed', confound: 'weight lifted', for: ['sport', 'physiotherapy'],
      vars: ['rest time between sets', 'repetitions completed', 'weight lifted', 'the exercise'],
      text: 'To test whether longer rests between sets lead to more squats in the next set, one group rests for 3 minutes and another for 1 minute. The 3-minute group squats with a lighter bar than the 1-minute group.',
      why: 'The long-rest group also lifted a lighter weight, and anyone can do more repetitions with a lighter weight. The difference could be the weight, not the rest.' },
    { iv: 'stretching', dv: 'sit-and-reach distance', confound: 'sport already played', for: ['physiotherapy', 'sport'],
      vars: ['stretching', 'sit-and-reach distance', 'sport already played', 'the sit-and-reach box'],
      text: 'To test whether stretching straight before the test increases sit-and-reach distance, researchers ask gymnasts to stretch and rugby players not to. Everyone uses the same sit-and-reach box.',
      why: 'The stretching group were also all gymnasts, who train their flexibility every week. Any difference could come from their sport, not the stretching on the day.' },
    { iv: 'balance practice', dv: 'balance time', confound: 'the balance board', for: ['physiotherapy'],
      vars: ['balance practice', 'balance time', 'the balance board', 'the length of the study'],
      text: 'To test whether practice improves balance, over the same three weeks one group practises on a wobble board and another doesn\'t. At the end, the practice group is tested on a firm board and the other group on a wobbly one.',
      why: 'The practice group was also tested on an easier board. Longer balance times could come from the board, not the practice.' },
    { iv: 'cuff size', dv: 'blood pressure reading', confound: 'activity just before the reading', for: ['nursing'],
      vars: ['cuff size', 'blood pressure reading', 'activity just before the reading', 'the blood pressure monitor'],
      text: 'To compare readings from a standard and a large cuff, a nurse uses the same monitor for everyone. Patients measured with the large cuff have rested for five minutes; patients measured with the standard cuff have just walked up two flights of stairs.',
      why: 'Walking up stairs raises blood pressure for a while, and only the standard-cuff patients had done it. The difference could come from the stairs, not the cuff.' },
    { iv: 'ward noise', dv: 'sleep rating', confound: 'lighting', for: ['nursing'],
      vars: ['ward noise', 'sleep rating', 'lighting', 'the sleep questionnaire'],
      text: 'Researchers compare sleep ratings on a noisy ward and a quiet ward, using the same questionnaire. On the noisy ward the lights stay on all night; on the quiet ward they are turned off at 10pm.',
      why: 'The noisy ward was also brightly lit all night, which can disturb sleep too. Worse ratings could come from the light, not the noise.' },
    { iv: 'time since a meal', dv: 'blood glucose', confound: 'size of the meal', for: ['nursing', 'nutrition'],
      vars: ['time since a meal', 'blood glucose', 'size of the meal', 'the glucose meter'],
      text: 'To see how blood glucose changes after eating, researchers use the same glucose meter to test one group of healthy volunteers an hour after a large meal and another group three hours after a small snack.',
      why: 'The one-hour group also ate a much bigger meal. Any difference could come from the meal size, not the time since eating.' },
    { iv: 'portion size', dv: 'fullness rating', confound: 'time since last eating', for: ['nutrition'],
      vars: ['portion size', 'fullness rating', 'time since last eating', 'the rating scale'],
      text: 'To test whether portion size affects how full people feel, one group eats a large bowl of soup and another a small one, then both rate their fullness on the same scale. The large-portion group had lunch an hour before; the small-portion group skipped lunch.',
      why: 'The large-portion group had also eaten recently. Feeling fuller could come from the earlier lunch, not the portion.' },
    { iv: 'background noise', dv: 'speech intelligibility', confound: 'the speaker', for: ['slt'],
      vars: ['background noise', 'speech intelligibility', 'the speaker', 'the listening room'],
      text: 'To test whether background noise affects intelligibility, listeners in the same room hear sentences in quiet or in noise. The quiet sentences were recorded by a slow, clear speaker; the noisy ones by a different speaker who talks very fast.',
      why: 'The noisy sentences also came from a fast speaker, and fast speech is harder to follow anyway. The difference could be the speaker, not the noise.' },
    { iv: 'naming practice', dv: 'naming accuracy', confound: 'familiarity of the objects', for: ['slt'],
      vars: ['naming practice', 'naming accuracy', 'familiarity of the objects', 'the number of pictures'],
      text: 'To test whether practice improves naming accuracy, healthy adults practise naming 20 pictures of everyday objects, then are tested on those and on 20 unpractised pictures of rare tools.',
      why: 'The practised pictures were also familiar objects, which are easier to name anyway. Better accuracy could come from familiarity, not the practice.' },

    { iv: 'warm-up', dv: 'sprint time', confound: null,
      text: 'Researchers want to know whether a warm-up affects 20-metre sprint time. Runners are randomly assigned to warm up or not, and everyone runs on the same dry indoor track through the same timing gates.',
      why: 'Random assignment and the same track and timing gates mean the warm-up is the only thing that systematically differs between the groups.' },
    { iv: 'hand cooling', dv: 'grip strength', confound: null,
      text: 'To test whether cooling the hand affects grip strength, participants are randomly assigned to hold their hand in cold or warm water, and everyone is tested before training with the same dynamometer.',
      why: 'Random groups tested at the same point in the day, on the same equipment — only the water temperature differs.' },
    { iv: 'exercise intensity', dv: 'heart rate', confound: null,
      text: 'Researchers test whether exercise intensity affects heart rate. Participants are randomly assigned to cycle at a low or a high intensity, all in the same room at the same temperature, on identical bikes.',
      why: 'Same room, same temperature, same bikes, random groups — the intensity is the only difference.' },
    { iv: 'rest time between sets', dv: 'repetitions completed', confound: null, for: ['sport', 'physiotherapy'],
      text: 'To test whether longer rests between sets lead to more squats in the next set, participants are randomly assigned to rest for 1 or 3 minutes. Everyone squats with a bar set to the same proportion of their own maximum.',
      why: 'The load is matched and the groups are random, so the rest time is the only systematic difference.' },
    { iv: 'stretching', dv: 'sit-and-reach distance', confound: null, for: ['physiotherapy', 'sport'],
      text: 'To test whether stretching straight before the test increases sit-and-reach distance, members of one sports club are randomly split into a stretching group and a no-stretching group, and everyone uses the same box.',
      why: 'Both groups come from the same club and are split at random, so only the stretching differs.' },
    { iv: 'balance practice', dv: 'balance time', confound: null, for: ['physiotherapy'],
      text: 'To test whether practice improves balance, volunteers are randomly split into a group that practises on a wobble board for three weeks and a group that doesn\'t. At the end, everyone is tested on the same wobble board.',
      why: 'Random groups, the same length of study and the same test board — only the practice differs.' },
    { iv: 'cuff size', dv: 'blood pressure reading', confound: null, for: ['nursing'],
      text: 'To compare readings from a standard and a large cuff, a nurse measures every patient after five minutes\' seated rest, with the arm supported at heart level, using the same monitor.',
      why: 'Every reading is taken in the same way after the same rest, so the cuff is the only thing that differs.' },
    { iv: 'ward noise', dv: 'sleep rating', confound: null, for: ['nursing'],
      text: 'Researchers compare patients\' sleep ratings on noisy and quiet nights on the same ward, with the lights turned off at 10pm every night and the same questionnaire each morning.',
      why: 'Same ward, same lighting, same questionnaire — the noise is what differs between nights.' },
    { iv: 'time since a meal', dv: 'blood glucose', confound: null, for: ['nursing', 'nutrition'],
      text: 'To see how blood glucose changes after eating, healthy volunteers all eat the same meal, and are then randomly assigned to be tested one hour or three hours later with the same glucose meter.',
      why: 'Everyone ate the same meal and the groups were random, so only the time since eating differs.' },
    { iv: 'portion size', dv: 'fullness rating', confound: null, for: ['nutrition'],
      text: 'To test whether portion size affects how full people feel, volunteers who have all eaten nothing since breakfast are randomly given a large or a small bowl of soup, then rate their fullness on the same scale.',
      why: 'Everyone last ate at the same time and the groups are random, so only the portion size differs.' },
    { iv: 'background noise', dv: 'speech intelligibility', confound: null, for: ['slt'],
      text: 'To test whether background noise affects intelligibility, listeners in the same room are randomly assigned to hear the same recorded sentences, by the same speaker, either in quiet or in noise.',
      why: 'Same sentences, same speaker, same room, random groups — the noise is the only difference.' },
    { iv: 'naming practice', dv: 'naming accuracy', confound: null, for: ['slt'],
      text: 'To test whether practice improves naming accuracy, 40 pictures of rare tools are randomly split into two sets. Healthy adults practise naming one set, then are tested on both.',
      why: 'The two sets were split at random from the same kind of pictures, so only the practice differs.' },
  ],

  // -------------------------------------------------------------------------
  // 2j. Within or between subjects. Mostly pairs: the same study both ways.
  // -------------------------------------------------------------------------
  designs: [
    { cat: 'within',
      label: 'Every participant cycles for five minutes at a low intensity and five minutes at a high intensity, and their heart rate in the two conditions is compared.',
      ivs: [{ name: 'exercise intensity (low or high)', aliases: ['intensity', 'exercise intensity', 'low or high', 'how hard they cycle', 'effort', 'workload', 'resistance'] }],
      dv: HEALTH_HEART_RATE,
      others: [HEALTH_PARTICIPANTS, { name: 'the five minutes of cycling', aliases: ['five minutes', 'minutes', 'length of cycling', 'cycling time'] }] },
    { cat: 'within',
      label: 'Each participant squeezes a dynamometer with their dominant hand and with their other hand, and the grip strength of the two hands is compared.',
      ivs: [{ name: 'hand (dominant or non-dominant)', aliases: ['hand', 'which hand', 'dominant', 'non dominant', 'dominant or non dominant', 'left or right', 'handedness'] }],
      dv: HEALTH_GRIP,
      others: [HEALTH_PARTICIPANTS, { name: 'the dynamometer', aliases: ['dynamometer', 'grip meter', 'equipment', 'device'] }] },
    { cat: 'within',
      label: 'Every participant stands on one leg once with their eyes open and once with their eyes closed, and how long they stay balanced is compared.',
      ivs: [{ name: 'eyes (open or closed)', aliases: ['eyes', 'eyes open', 'eyes closed', 'open or closed', 'vision', 'whether they can see', 'sight'] }],
      dv: HEALTH_BALANCE,
      others: [HEALTH_PARTICIPANTS, { name: 'the stopwatch', aliases: ['stopwatch', 'timer', 'watch'] }] },
    { cat: 'within',
      label: 'Participants take a reaction time test once after a full night\'s sleep and again, a week later, after staying awake all night. Their two reaction times are compared.',
      ivs: [{ name: 'sleep (slept or stayed awake)', aliases: ['sleep', 'slept', 'stayed awake', 'awake', 'sleep or no sleep', 'sleep deprivation', 'tiredness', 'rest'] }],
      dv: { name: 'reaction time', aliases: ['reaction time', 'reaction', 'how fast they react', 'response time', 'speed', 'reactions'] },
      others: [HEALTH_PARTICIPANTS, { name: 'the week between sessions', aliases: ['a week later', 'week between', 'gap'] }] },
    { cat: 'within', for: ['sport', 'physiotherapy'],
      label: 'Each participant does sets of squats with 1 minute of rest on one day and 3 minutes of rest on another, and the repetitions they complete are compared.',
      ivs: [{ name: 'rest time (1 or 3 minutes)', aliases: ['rest', 'rest time', 'rest period', 'length of rest', '1 or 3 minutes', 'recovery time', 'rest between sets'] }],
      dv: HEALTH_REPS,
      others: [HEALTH_PARTICIPANTS, { name: 'the days of testing', aliases: ['day', 'days', 'another day', 'testing day'] }] },
    { cat: 'within', for: ['physiotherapy', 'sport'],
      label: 'Each volunteer does the sit-and-reach test, then stretches their hamstrings for five minutes and does the test again. Their two reach distances are compared.',
      ivs: [{ name: 'stretching (before or after)', aliases: ['stretching', 'stretch', 'before or after', 'before and after stretching', 'hamstring stretch', 'whether they stretched'] }],
      dv: HEALTH_REACH,
      others: [{ name: 'the volunteers', aliases: ['volunteers', 'participants', 'people'] }, { name: 'the five minutes', aliases: ['five minutes', 'minutes'] }] },
    { cat: 'within', for: ['nursing'],
      label: 'A nurse measures every patient\'s blood pressure twice, once with a standard cuff and once with a large cuff, and the two readings are compared.',
      ivs: [{ name: 'cuff size (standard or large)', aliases: ['cuff', 'cuff size', 'size of cuff', 'standard or large', 'large cuff', 'standard cuff', 'which cuff'] }],
      dv: HEALTH_BP,
      others: [{ name: 'the patients', aliases: ['patients', 'patient', 'people'] }, { name: 'the nurse', aliases: ['nurse', 'staff'] }] },
    { cat: 'within', for: ['nursing'],
      label: 'Each volunteer has their blood pressure measured lying down and then standing up, and the readings in the two positions are compared.',
      ivs: [{ name: 'position (lying or standing)', aliases: ['position', 'posture', 'lying or standing', 'lying down', 'standing up', 'body position'] }],
      dv: HEALTH_BP,
      others: [{ name: 'the volunteers', aliases: ['volunteers', 'participants', 'people'] }] },
    { cat: 'within', for: ['nutrition'],
      label: 'Every participant eats the same breakfast and rates their hunger one hour later and again four hours later. The two ratings are compared.',
      ivs: [{ name: 'time since breakfast (1 or 4 hours)', aliases: ['time since breakfast', 'time since eating', '1 or 4 hours', 'hours after breakfast', 'hours', 'when they rate it', 'time'] }],
      dv: HEALTH_HUNGER,
      others: [HEALTH_PARTICIPANTS, { name: 'the breakfast', aliases: ['breakfast', 'meal', 'food'] }] },
    { cat: 'within', for: ['nutrition'],
      label: 'On one day each participant eats a small bowl of pasta, and on another day a large bowl. Straight after eating, they rate how full they feel, and the two ratings are compared.',
      ivs: [{ name: 'portion size (small or large)', aliases: ['portion', 'portion size', 'small or large', 'bowl size', 'amount of food', 'how much they eat', 'serving size'] }],
      dv: { name: 'fullness rating', aliases: ['fullness', 'how full', 'full', 'satiety', 'rating', 'fullness score'] },
      others: [HEALTH_PARTICIPANTS, { name: 'the pasta', aliases: ['pasta', 'food', 'meal'] }] },
    { cat: 'within', for: ['slt'],
      label: 'The same listeners hear some sentences in quiet and others with background noise, and write down every word. The percentage of words they get right in each condition is compared.',
      ivs: [HEALTH_NOISE],
      dv: HEALTH_INTELLIGIBILITY,
      others: [{ name: 'the listeners', aliases: ['listeners', 'participants', 'people'] }, { name: 'the sentences', aliases: ['sentences', 'sentence', 'recordings'] }] },
    { cat: 'within', for: ['slt'],
      label: 'Each healthy adult hears word lists and recalls them either straight away or after a 20-minute delay, and the number of words they recall is compared.',
      ivs: [{ name: 'delay (none or 20 minutes)', aliases: ['delay', 'straight away or after a delay', 'straight away', '20 minutes', 'wait', 'time before recall', 'gap before recall'] }],
      dv: { name: 'number of words recalled', aliases: ['recall', 'words recalled', 'how many words', 'memory', 'remember', 'words remembered'] },
      others: [{ name: 'the healthy adults', aliases: ['adults', 'participants', 'people'] }, { name: 'the word lists', aliases: ['word lists', 'lists', 'list'] }] },

    { cat: 'between',
      label: 'Participants are randomly assigned to cycle at either a low or a high intensity, and the two groups\' heart rates are compared.',
      ivs: [{ name: 'exercise intensity (low or high)', aliases: ['intensity', 'exercise intensity', 'low or high', 'how hard they cycle', 'effort', 'workload', 'resistance'] }],
      dv: HEALTH_HEART_RATE,
      others: [{ name: 'the groups of participants', aliases: ['participants', 'people', 'group', 'groups'] }] },
    { cat: 'between',
      label: 'One group holds their hand in cold water and a different group holds it in warm water. Then everyone\'s grip strength is measured and the groups are compared.',
      ivs: [{ name: 'water temperature (cold or warm)', aliases: ['water', 'water temperature', 'cold or warm', 'cold', 'warm', 'cooling', 'temperature'] }],
      dv: HEALTH_GRIP,
      others: [{ name: 'the groups', aliases: ['group', 'groups', 'participants', 'people'] }] },
    { cat: 'between',
      label: 'Half the participants stand on one leg with their eyes open and the other half with their eyes closed. How long each group stays balanced is compared.',
      ivs: [{ name: 'eyes (open or closed)', aliases: ['eyes', 'eyes open', 'eyes closed', 'open or closed', 'vision', 'whether they can see', 'sight'] }],
      dv: HEALTH_BALANCE,
      others: [HEALTH_PARTICIPANTS] },
    { cat: 'between',
      label: 'One group sleeps normally and a different group stays awake all night. The next morning, the two groups\' reaction times are compared.',
      ivs: [{ name: 'sleep (slept or stayed awake)', aliases: ['sleep', 'slept', 'stayed awake', 'awake', 'sleep or no sleep', 'sleep deprivation', 'tiredness', 'rest'] }],
      dv: { name: 'reaction time', aliases: ['reaction time', 'reaction', 'how fast they react', 'response time', 'speed', 'reactions'] },
      others: [{ name: 'the next morning', aliases: ['morning', 'next morning', 'next day'] }] },
    { cat: 'between', for: ['sport', 'physiotherapy'],
      label: 'Participants are randomly assigned to rest for either 1 minute or 3 minutes between sets of squats, and the repetitions each group completes are compared.',
      ivs: [{ name: 'rest time (1 or 3 minutes)', aliases: ['rest', 'rest time', 'rest period', 'length of rest', '1 or 3 minutes', 'recovery time', 'rest between sets'] }],
      dv: HEALTH_REPS,
      others: [HEALTH_PARTICIPANTS] },
    { cat: 'between', for: ['physiotherapy', 'sport'],
      label: 'Volunteers are split into a group that stretches their hamstrings for five minutes and a group that sits quietly. Then everyone does the sit-and-reach test and the groups are compared.',
      ivs: [{ name: 'stretching (stretch or sit quietly)', aliases: ['stretching', 'stretch', 'stretch or not', 'sit quietly', 'no stretching', 'hamstring stretch', 'whether they stretched'] }],
      dv: HEALTH_REACH,
      others: [{ name: 'the volunteers', aliases: ['volunteers', 'participants', 'people', 'groups'] }] },
    { cat: 'between', for: ['sport'],
      label: 'Runners are randomly assigned to do a warm-up or no warm-up before a 20-metre sprint, and the two groups\' sprint times are compared.',
      ivs: [{ name: 'warm-up (or none)', aliases: ['warm up', 'warmup', 'warm up or not', 'no warm up', 'warming up', 'preparation'] }],
      dv: { name: 'sprint time', aliases: ['sprint', 'sprint time', 'time', 'how fast they run', 'speed', 'running time'] },
      others: [{ name: 'the runners', aliases: ['runners', 'participants', 'athletes', 'people'] }] },
    { cat: 'between', for: ['nursing'],
      label: 'One group of patients has blood pressure measured with a standard cuff and a different group with a large cuff, and the two groups\' readings are compared.',
      ivs: [{ name: 'cuff size (standard or large)', aliases: ['cuff', 'cuff size', 'size of cuff', 'standard or large', 'large cuff', 'standard cuff', 'which cuff'] }],
      dv: HEALTH_BP,
      others: [{ name: 'the patients', aliases: ['patients', 'patient', 'people', 'groups'] }] },
    { cat: 'between', for: ['nursing', 'nutrition'],
      label: 'Healthy volunteers are randomly assigned to drink either 250 ml or 750 ml of water, and each group\'s urine output over the next two hours is measured.',
      ivs: [{ name: 'amount of water drunk (250 ml or 750 ml)', aliases: ['water', 'amount of water', 'how much they drink', 'fluid intake', 'fluid', '250 or 750', 'drink'] }],
      dv: { name: 'urine output', aliases: ['urine', 'urine output', 'urine volume', 'how much urine', 'output'] },
      others: [{ name: 'the two hours', aliases: ['two hours', 'hours', 'next two hours'] }] },
    { cat: 'between', for: ['nutrition'],
      label: 'One group of participants is given a small bowl of pasta and another group a large bowl. Straight after eating, both groups rate how full they feel.',
      ivs: [{ name: 'portion size (small or large)', aliases: ['portion', 'portion size', 'small or large', 'bowl size', 'amount of food', 'how much they eat', 'serving size'] }],
      dv: { name: 'fullness rating', aliases: ['fullness', 'how full', 'full', 'satiety', 'rating', 'fullness score'] },
      others: [{ name: 'the groups', aliases: ['group', 'groups', 'participants', 'people'] }, { name: 'the pasta', aliases: ['pasta', 'food', 'meal'] }] },
    { cat: 'between', for: ['slt'],
      label: 'Listeners are split into two groups: one hears sentences in quiet and the other hears them with background noise. The percentage of words each group writes down correctly is compared.',
      ivs: [HEALTH_NOISE],
      dv: HEALTH_INTELLIGIBILITY,
      others: [{ name: 'the listeners', aliases: ['listeners', 'participants', 'people', 'groups'] }, { name: 'the sentences', aliases: ['sentences', 'sentence', 'recordings'] }] },
    { cat: 'between', for: ['slt'],
      label: 'Listeners are randomly assigned to hear a passage read at a normal rate or a fast rate, and each group\'s intelligibility score is compared.',
      ivs: [{ name: 'speaking rate (normal or fast)', aliases: ['speaking rate', 'rate', 'speed of speech', 'normal or fast', 'fast', 'how fast it is read', 'speech rate', 'pace'] }],
      dv: HEALTH_INTELLIGIBILITY,
      others: [{ name: 'the passage', aliases: ['passage', 'text', 'recording'] }] },
  ],

  // -------------------------------------------------------------------------
  // 2f-2h. Cross-sectional, longitudinal, or both.
  // -------------------------------------------------------------------------
  crosslong: {
    single: [
      // cross-sectional: different groups, one point in time
      { cat: 'cross', for: ['sport', 'physiotherapy'],
        label: 'In the same week, researchers measure the grip strength of rowers, runners and swimmers from one university club, and compare the three groups.',
        ivs: [{ name: 'sport (rowing, running or swimming)', aliases: ['sport', 'type of sport', 'rowers runners or swimmers', 'rowing', 'running', 'swimming', 'which sport', 'group'] }],
        dv: HEALTH_GRIP,
        others: [{ name: 'the week of testing', aliases: ['week', 'same week', 'time'] }] },
      { cat: 'cross',
        label: 'In a single session, researchers measure the resting heart rate of people who train for endurance events and people who don\'t, and compare the two groups.',
        ivs: [{ name: 'training status (endurance-trained or not)', aliases: ['training', 'trained or not', 'endurance trained', 'untrained', 'training status', 'whether they train', 'fitness', 'group'] }],
        dv: { name: 'resting heart rate', aliases: ['heart rate', 'resting heart rate', 'pulse', 'heartbeat', 'beats per minute', 'bpm'] },
        others: [{ name: 'the testing session', aliases: ['session', 'single session', 'time'] }] },
      { cat: 'cross', for: ['nursing'],
        label: 'On one night, researchers count how many times patients wake on a quiet ward and on a busy ward, and compare the two wards.',
        ivs: [{ name: 'ward (quiet or busy)', aliases: ['ward', 'quiet or busy', 'busy ward', 'quiet ward', 'which ward', 'type of ward', 'noise', 'group'] }],
        dv: { name: 'number of times patients wake', aliases: ['waking', 'wakings', 'times they wake', 'number of wakings', 'how often they wake', 'sleep', 'waking up'] },
        others: [{ name: 'the night of the study', aliases: ['night', 'one night', 'time'] }] },
      { cat: 'cross', for: ['nutrition'],
        label: 'At one lunchtime, researchers ask volunteers who ate breakfast at 7am and volunteers who ate breakfast at 10am to rate their hunger, and compare the two groups.',
        ivs: [{ name: 'breakfast time (7am or 10am)', aliases: ['breakfast time', 'when they ate breakfast', '7am or 10am', 'breakfast', 'time of breakfast', 'time since eating', 'group'] }],
        dv: HEALTH_HUNGER,
        others: [{ name: 'the lunchtime', aliases: ['lunchtime', 'lunch', 'midday'] }] },
      { cat: 'cross', for: ['slt'],
        label: 'In one week, researchers record radio newsreaders and primary-school teachers reading the same passage, and compare the two groups\' speaking rates.',
        ivs: [{ name: 'job (newsreader or teacher)', aliases: ['job', 'occupation', 'profession', 'newsreader or teacher', 'newsreaders', 'teachers', 'group'] }],
        dv: { name: 'speaking rate', aliases: ['speaking rate', 'rate', 'speech rate', 'how fast they speak', 'speed', 'syllables per second'] },
        others: [{ name: 'the passage', aliases: ['passage', 'text', 'same passage'] }] },

      // longitudinal: one group, followed over time
      { cat: 'long', for: ['sport', 'physiotherapy'],
        label: 'Researchers measure the leg strength of the same 20 volunteers every two weeks during a 12-week strength-training programme.',
        ivs: [{ name: 'time (week of the programme)', aliases: ['week of the programme', 'weeks of training', 'every two weeks', 'training weeks', ...HEALTH_TIME_WORDS] }],
        dv: { name: 'leg strength', aliases: ['leg strength', 'strength', 'how strong', 'leg press', 'force', 'power'] },
        others: [{ name: 'the volunteers', aliases: ['volunteers', 'participants', 'people', 'number of volunteers'] }] },
      { cat: 'long',
        label: 'The body temperature of the same healthy volunteers is measured every two hours from 8am to 8pm on the same day.',
        ivs: [{ name: 'time of day', aliases: ['time of day', 'hour', 'hours', 'every two hours', 'clock time', '8am to 8pm', ...HEALTH_TIME_WORDS] }],
        dv: { name: 'body temperature', aliases: ['temperature', 'body temperature', 'temp', 'how warm', 'degrees'] },
        others: [{ name: 'the volunteers', aliases: ['volunteers', 'participants', 'people'] }] },
      { cat: 'long', for: ['nutrition', 'nursing'],
        label: 'The same group of healthy volunteers rates their hunger every hour from breakfast until lunch.',
        ivs: [{ name: 'time since breakfast', aliases: ['time since breakfast', 'hour', 'hours', 'every hour', 'hours after breakfast', 'time since eating', ...HEALTH_TIME_WORDS] }],
        dv: HEALTH_HUNGER,
        others: [{ name: 'the volunteers', aliases: ['volunteers', 'participants', 'people', 'group'] }] },
      { cat: 'long', for: ['physiotherapy'],
        label: 'A group of volunteers practises on a wobble board, and how long each can stay balanced is tested every week for six weeks.',
        ivs: [{ name: 'time (week of practice)', aliases: ['week of practice', 'weeks of practice', 'every week', 'six weeks', 'practice', ...HEALTH_TIME_WORDS] }],
        dv: HEALTH_BALANCE,
        others: [{ name: 'the volunteers', aliases: ['volunteers', 'participants', 'people', 'group'] }] },
      { cat: 'long', for: ['slt'],
        label: 'Healthy adults learn the names of 20 unfamiliar tools, and the same adults are tested on naming them after one day, one week and one month.',
        ivs: [{ name: 'time since learning', aliases: ['time since learning', 'delay', 'one day one week one month', 'after one day', 'after one week', 'after one month', ...HEALTH_TIME_WORDS] }],
        dv: { name: 'naming accuracy', aliases: ['naming', 'naming accuracy', 'accuracy', 'names remembered', 'how many they name', 'correct', 'recall'] },
        others: [{ name: 'the unfamiliar tools', aliases: ['tools', 'unfamiliar tools', 'objects', 'pictures', 'number of tools'] }] },
    ],

    multi: [
      // cross-sectional, two factors
      { cat: 'cross', for: ['sport', 'physiotherapy'],
        label: 'In the same week, rowers and runners from one club have the grip strength of both their left and right hands measured, and all four results are compared.',
        ivs: [
          { name: 'sport (rowing or running)', aliases: ['sport', 'type of sport', 'rowers or runners', 'rowing', 'running', 'which sport', 'club'] },
          { name: 'hand (left or right)', aliases: ['hand', 'which hand', 'left or right', 'left hand', 'right hand', 'handedness'] },
        ],
        dv: HEALTH_GRIP,
        others: [{ name: 'the week of testing', aliases: ['week', 'same week'] }] },
      { cat: 'cross',
        label: 'In a single session, endurance-trained and untrained volunteers each have their heart rate measured while lying down and while standing.',
        ivs: [
          { name: 'training status (endurance-trained or not)', aliases: ['training', 'trained or not', 'endurance trained', 'untrained', 'training status', 'whether they train', 'fitness'] },
          { name: 'position (lying or standing)', aliases: ['position', 'posture', 'lying or standing', 'lying down', 'standing', 'body position'] },
        ],
        dv: HEALTH_HEART_RATE,
        others: [{ name: 'the session', aliases: ['session', 'single session'] }] },
      { cat: 'cross', for: ['slt'],
        label: 'In one afternoon, speech and language therapy students and students from other courses each listen to sentences in quiet and in noise, and write down the words they hear.',
        ivs: [
          { name: 'course (SLT or other)', aliases: ['course', 'slt students', 'other students', 'slt or other', 'training', 'listening experience', 'degree'] },
          HEALTH_NOISE,
        ],
        dv: HEALTH_INTELLIGIBILITY,
        others: [{ name: 'the sentences', aliases: ['sentences', 'sentence', 'recordings'] }] },
      { cat: 'cross',
        label: 'In one afternoon, volunteers who have just run 5 km and volunteers who have been sitting at a desk each have their body temperature measured under the tongue and in the ear.',
        ivs: [
          { name: 'activity (running or sitting)', aliases: ['activity', 'running or sitting', 'run', 'running', 'sitting', 'desk', 'exercise', 'what they were doing'] },
          { name: 'measurement site (tongue or ear)', aliases: ['site', 'measurement site', 'tongue or ear', 'tongue', 'ear', 'mouth', 'where it is measured', 'thermometer type'] },
        ],
        dv: { name: 'body temperature', aliases: ['temperature', 'body temperature', 'temp', 'how warm', 'degrees'] },
        others: [{ name: 'the afternoon of testing', aliases: ['afternoon', 'one afternoon'] }] },

      // longitudinal, two factors
      { cat: 'long', for: ['sport', 'physiotherapy'],
        label: 'The same 20 volunteers have their squat and bench-press strength measured every four weeks during a 12-week training programme.',
        ivs: [
          { name: 'time (week of the programme)', aliases: ['week of the programme', 'weeks of training', 'every four weeks', 'training weeks', ...HEALTH_TIME_WORDS] },
          { name: 'exercise (squat or bench press)', aliases: ['exercise', 'squat or bench press', 'squat', 'bench press', 'which exercise', 'lift', 'type of lift'] },
        ],
        dv: { name: 'strength', aliases: ['strength', 'how strong', 'weight lifted', 'maximum lift', 'force', 'power'] },
        others: [{ name: 'the volunteers', aliases: ['volunteers', 'participants', 'people'] }] },
      { cat: 'long', for: ['nutrition'],
        label: 'On one day the same volunteers eat a small breakfast, and on another day a large one. Each day, they rate their hunger every hour until lunch.',
        ivs: [
          { name: 'time since breakfast', aliases: ['time since breakfast', 'hour', 'hours', 'every hour', 'hours after breakfast', 'time since eating', ...HEALTH_TIME_WORDS] },
          { name: 'breakfast size (small or large)', aliases: ['breakfast size', 'size of breakfast', 'small or large', 'portion', 'portion size', 'how much they eat'] },
        ],
        dv: HEALTH_HUNGER,
        others: [{ name: 'the volunteers', aliases: ['volunteers', 'participants', 'people'] }] },
      { cat: 'long', for: ['slt'],
        label: 'Healthy adults learn a list of short words and a list of long words, and the same adults are tested on recalling both lists after one hour, one day and one week.',
        ivs: [
          { name: 'time since learning', aliases: ['time since learning', 'delay', 'after one hour', 'after one day', 'after one week', ...HEALTH_TIME_WORDS] },
          { name: 'word length (short or long)', aliases: ['word length', 'length', 'short or long', 'short words', 'long words', 'type of word', 'list'] },
        ],
        dv: { name: 'number of words recalled', aliases: ['recall', 'words recalled', 'how many words', 'memory', 'remember', 'words remembered'] },
        others: [{ name: 'the healthy adults', aliases: ['adults', 'participants', 'people'] }] },
      { cat: 'long', for: ['nursing', 'nutrition'],
        label: 'The same healthy volunteers have their blood glucose measured every 30 minutes for three hours after eating — once after a small meal and, on another day, after a large one.',
        ivs: [
          { name: 'time since the meal', aliases: ['time since the meal', 'time since eating', 'every 30 minutes', 'minutes', 'three hours', 'hours after eating', ...HEALTH_TIME_WORDS] },
          { name: 'meal size (small or large)', aliases: ['meal size', 'size of meal', 'small or large', 'portion', 'portion size', 'how much they eat', 'meal'] },
        ],
        dv: { name: 'blood glucose', aliases: ['glucose', 'blood glucose', 'blood sugar', 'sugar', 'glucose level'] },
        others: [{ name: 'the volunteers', aliases: ['volunteers', 'participants', 'people'] }] },
      { cat: 'long',
        label: 'The same healthy volunteers have their body temperature measured under the tongue and in the ear every two hours across one day.',
        ivs: [
          { name: 'time of day', aliases: ['time of day', 'hour', 'hours', 'every two hours', 'clock time', ...HEALTH_TIME_WORDS] },
          { name: 'measurement site (tongue or ear)', aliases: ['site', 'measurement site', 'tongue or ear', 'tongue', 'ear', 'mouth', 'where it is measured', 'thermometer type'] },
        ],
        dv: { name: 'body temperature', aliases: ['temperature', 'body temperature', 'temp', 'how warm', 'degrees'] },
        others: [{ name: 'the volunteers', aliases: ['volunteers', 'participants', 'people'] }] },
    ],

    panel: [
      { cat: 'both', for: ['physiotherapy', 'sport'],
        label: 'One group of volunteers does a daily hamstring-stretching routine and another group doesn\'t. Both groups do the sit-and-reach test every week for six weeks.',
        ivs: [
          { name: 'stretching group (stretch or no stretch)', aliases: ['stretching', 'stretch', 'stretch or not', 'no stretching', 'routine', 'stretching routine', 'group'] },
          { name: 'time (week of testing)', aliases: ['week of testing', 'every week', 'six weeks', ...HEALTH_TIME_WORDS] },
        ],
        dv: HEALTH_REACH,
        others: [{ name: 'the volunteers', aliases: ['volunteers', 'participants', 'people'] }] },
      { cat: 'both', for: ['sport'],
        label: 'One group trains with 1-minute rests between sets and another with 3-minute rests. Both groups have their squat strength measured every two weeks for 12 weeks.',
        ivs: [
          { name: 'rest between sets (1 or 3 minutes)', aliases: ['rest', 'rest period', 'length of rest', '1 or 3 minutes', 'recovery', 'rest between sets', 'group'] },
          { name: 'time (week of the programme)', aliases: ['week of the programme', 'every two weeks', '12 weeks', 'training weeks', ...HEALTH_TIME_WORDS] },
        ],
        dv: { name: 'squat strength', aliases: ['strength', 'squat strength', 'squat', 'how strong', 'weight lifted', 'force', 'power'] },
        others: [{ name: 'the sets', aliases: ['sets', 'set'] }] },
      { cat: 'both', for: ['nursing'],
        label: 'Patients on a quiet ward and patients on a busy ward rate how well they slept every morning for a week.',
        ivs: [
          { name: 'ward (quiet or busy)', aliases: ['ward', 'quiet or busy', 'busy ward', 'quiet ward', 'which ward', 'type of ward', 'noise', 'group'] },
          { name: 'time (night of the week)', aliases: ['night', 'nights', 'every morning', 'morning', 'a week', ...HEALTH_TIME_WORDS] },
        ],
        dv: { name: 'sleep rating', aliases: ['sleep', 'sleep rating', 'how well they slept', 'sleep quality', 'rating', 'sleep score'] },
        others: [{ name: 'the patients', aliases: ['patients', 'patient', 'people'] }] },
      { cat: 'both', for: ['nutrition'],
        label: 'One group of volunteers is given a small breakfast and another group a large breakfast. Both groups rate their hunger every hour until lunch.',
        ivs: [
          { name: 'breakfast size (small or large)', aliases: ['breakfast size', 'size of breakfast', 'small or large', 'portion', 'portion size', 'how much they eat', 'group'] },
          { name: 'time since breakfast', aliases: ['time since breakfast', 'hour', 'hours', 'every hour', 'hours after breakfast', 'time since eating', ...HEALTH_TIME_WORDS] },
        ],
        dv: HEALTH_HUNGER,
        others: [{ name: 'the volunteers', aliases: ['volunteers', 'participants', 'people'] }] },
      { cat: 'both', for: ['slt'],
        label: 'Two groups of healthy adults learn the names of unfamiliar tools, one practising every day and one once a week. Both groups\' naming accuracy is tested every week for six weeks.',
        ivs: [
          { name: 'practice schedule (daily or weekly)', aliases: ['practice', 'practice schedule', 'daily or weekly', 'daily', 'weekly', 'how often they practise', 'group'] },
          { name: 'time (week of testing)', aliases: ['week of testing', 'every week', 'six weeks', ...HEALTH_TIME_WORDS] },
        ],
        dv: { name: 'naming accuracy', aliases: ['naming', 'naming accuracy', 'accuracy', 'names remembered', 'how many they name', 'correct'] },
        others: [{ name: 'the unfamiliar tools', aliases: ['tools', 'unfamiliar tools', 'objects', 'pictures'] }] },
      { cat: 'both', for: ['physiotherapy'],
        label: 'One group of volunteers practises on a wobble board three times a week and another group doesn\'t. Both groups\' balance time on the board is tested every week for six weeks.',
        ivs: [
          { name: 'practice (wobble board or none)', aliases: ['practice', 'practise or not', 'wobble board practice', 'no practice', 'training', 'group'] },
          { name: 'time (week of testing)', aliases: ['week of testing', 'every week', 'six weeks', ...HEALTH_TIME_WORDS] },
        ],
        dv: HEALTH_BALANCE,
        others: [{ name: 'the volunteers', aliases: ['volunteers', 'participants', 'people'] }] },
      { cat: 'both', for: ['nursing', 'nutrition'],
        label: 'Healthy volunteers are randomly given either 250 ml or 750 ml of water to drink, and each group\'s urine output is measured every hour for four hours.',
        ivs: [
          { name: 'amount of water drunk (250 ml or 750 ml)', aliases: ['water', 'amount of water', 'how much they drink', 'fluid intake', 'fluid', '250 or 750', 'drink', 'group'] },
          { name: 'time (hour after drinking)', aliases: ['hour', 'hours', 'every hour', 'four hours', 'hour after drinking', ...HEALTH_TIME_WORDS] },
        ],
        dv: { name: 'urine output', aliases: ['urine', 'urine output', 'urine volume', 'how much urine', 'output'] },
        others: [{ name: 'the volunteers', aliases: ['volunteers', 'participants', 'people'] }] },
      { cat: 'both',
        label: 'One group of volunteers practises a reaction task every day and another group doesn\'t. Both groups\' reaction times are tested every week for four weeks.',
        ivs: [
          { name: 'practice (daily or none)', aliases: ['practice', 'practise or not', 'daily practice', 'no practice', 'training', 'group'] },
          { name: 'time (week of testing)', aliases: ['week of testing', 'every week', 'four weeks', ...HEALTH_TIME_WORDS] },
        ],
        dv: { name: 'reaction time', aliases: ['reaction time', 'reaction', 'how fast they react', 'response time', 'speed', 'reactions'] },
        others: [{ name: 'the volunteers', aliases: ['volunteers', 'participants', 'people'] }] },
      { cat: 'both',
        label: 'Rowers and runners from one club have their resting heart rate measured at the start of the season and every month for six months.',
        ivs: [
          { name: 'sport (rowing or running)', aliases: ['sport', 'type of sport', 'rowers or runners', 'rowing', 'running', 'which sport', 'group'] },
          { name: 'time (month of the season)', aliases: ['month of the season', 'every month', 'six months', 'season', 'start of the season', ...HEALTH_TIME_WORDS] },
        ],
        dv: { name: 'resting heart rate', aliases: ['heart rate', 'resting heart rate', 'pulse', 'heartbeat', 'beats per minute', 'bpm'] },
        others: [{ name: 'the club', aliases: ['club', 'rowing club', 'members'] }] },
    ],
  },

  // -------------------------------------------------------------------------
  // Level 3. Factors for box notation.
  // -------------------------------------------------------------------------
  factors: [
    { name: 'Exercise intensity', levels: { 2: ['low', 'high'], 3: ['low', 'moderate', 'high'], 4: ['rest', 'low', 'moderate', 'high'] } },
    { name: 'Warm-up', levels: { 2: ['none', '10 minutes'], 3: ['none', '5 minutes', '10 minutes'], 4: ['none', '5 minutes', '10 minutes', '15 minutes'] } },
    { name: 'Rest between sets', levels: { 2: ['1 minute', '3 minutes'], 3: ['30 seconds', '1 minute', '3 minutes'], 4: ['30 seconds', '1 minute', '2 minutes', '3 minutes'] } },
    { name: 'Altitude', levels: { 2: ['sea level', '3000 m'], 3: ['sea level', '2000 m', '4000 m'] } },
    { name: 'Exercise type', levels: { 2: ['running', 'cycling'], 3: ['running', 'cycling', 'rowing'], 4: ['running', 'cycling', 'rowing', 'swimming'] } },
    { name: 'Hand tested', levels: { 2: ['dominant', 'non-dominant'] } },
    { name: 'Eyes', levels: { 2: ['open', 'closed'] } },
    { name: 'Cuff size', levels: { 2: ['standard', 'large'], 3: ['small', 'standard', 'large'] } },
    { name: 'Patient position', levels: { 2: ['lying', 'standing'], 3: ['lying', 'sitting', 'standing'] } },
    { name: 'Time since meal', levels: { 2: ['1 hour', '3 hours'], 3: ['1 hour', '2 hours', '3 hours'], 4: ['1 hour', '2 hours', '3 hours', '4 hours'] } },
    { name: 'Portion size', levels: { 2: ['small', 'large'], 3: ['small', 'medium', 'large'] } },
    { name: 'Water drunk', levels: { 2: ['250 ml', '750 ml'], 3: ['250 ml', '500 ml', '750 ml'], 4: ['250 ml', '500 ml', '750 ml', '1000 ml'] } },
    { name: 'Noise level', levels: { 2: ['quiet', 'noisy'], 3: ['quiet', 'moderate', 'loud'] } },
    { name: 'Speaking rate', levels: { 2: ['normal', 'fast'], 3: ['slow', 'normal', 'fast'] } },
    { name: 'Recall delay', levels: { 2: ['none', '1 day'], 3: ['1 hour', '1 day', '1 week'], 4: ['none', '1 hour', '1 day', '1 week'] } },
    { name: 'Stretching', levels: { 2: ['none', 'stretched'], 3: ['none', 'static', 'dynamic'] } },
  ],
};
