// ---------------------------------------------------------------------------
// Life sciences pool: biology, ecology, biomedical science and agriculture
// (main pool), and a neighbour for neuroscience, sport, nutrition and
// environmental science. Studies are on samples, plants, plots and cultures.
//
// Shared items are textbook biology: enzymes, photosynthesis, osmosis,
// respiration, germination, plant and microbial growth. `for` gives each
// main discipline its own flavour: ecology (quadrats, species richness,
// altitude, trampling), biomedical (lab cultures, cell counts, incubation
// temperature -- nothing about treatments), agriculture (fertiliser, yield,
// stocking density, irrigation, milk yield). Relations with an optimum are
// stated only within the range where they run one way.
// ---------------------------------------------------------------------------

const LIFE_ECO = ['ecology', 'environmental'];
const LIFE_BIOMED = ['biomedical', 'biology'];
const LIFE_AGRI = ['agriculture'];

const LIFE_CONT = 'It can take any value on a scale, including every value in between — ';
const LIFE_DISC = 'It only comes in separate values, with nothing in between — ';

const LIFE_NOM = 'Categorical: distinct outcomes with no order. ';
const LIFE_ORD = 'Ordinal: the outcomes are ranked, but the difference between steps is arbitrary. ';
const LIFE_INT = 'Interval: ranked, with a constant difference between steps, but no natural zero — so values aren\'t "twice as much". ';
const LIFE_RAT = 'Ratio: ranked, constant steps AND a natural zero, so "twice as much" makes sense. ';

const LIFE_TIME_WORDS = ['time', 'over time', 'week', 'weeks', 'month', 'months', 'year', 'years', 'day', 'days', 'when it was measured', 'time point', 'session', 'before and after', 'how long'];

// Aliases reused across design items.
const LIFE_DIST_LAMP = { name: 'distance from the lamp', aliases: ['distance', 'distance from lamp', 'how far from the lamp', 'light intensity', 'light', 'brightness', 'how close', 'position'] };
const LIFE_BUBBLES = { name: 'number of oxygen bubbles', aliases: ['bubbles', 'oxygen', 'oxygen bubbles', 'bubble count', 'rate of photosynthesis', 'photosynthesis', 'gas produced'] };
const LIFE_POND_WEED = { name: 'the pondweed', aliases: ['pondweed', 'plant', 'weed', 'elodea', 'sprig'] };
const LIFE_COVER_FOIL = { name: 'foil covering (covered or uncovered)', aliases: ['foil', 'covered or uncovered', 'covered', 'uncovered', 'light or dark', 'darkness', 'covering', 'shading'] };
const LIFE_STARCH = { name: 'amount of starch', aliases: ['starch', 'starch test', 'iodine', 'iodine test', 'how much starch', 'starch content'] };
const LIFE_DIET = { name: 'feed (ration A or ration B)', aliases: ['feed', 'diet', 'ration', 'ration a or b', 'what they are fed', 'type of feed', 'food'] };
const LIFE_MILK = { name: 'milk yield', aliases: ['milk', 'milk produced', 'how much milk', 'litres of milk', 'yield', 'milk output'] };
const LIFE_IRRIGATION = { name: 'irrigation (watered or not)', aliases: ['irrigation', 'irrigated', 'watering', 'water', 'watered or not', 'irrigated or not'] };
const LIFE_GRAIN_YIELD = { name: 'grain yield', aliases: ['yield', 'crop yield', 'grain', 'how much grain', 'amount of grain', 'mass of grain', 'weight of grain'] };
const LIFE_ANTISEPTIC_CONC = { name: 'antiseptic concentration', aliases: ['antiseptic', 'concentration', 'strength', 'dose', 'antiseptic strength', 'how strong'] };
const LIFE_ZONE = { name: 'diameter of the clear zone', aliases: ['clear zone', 'zone', 'zone of inhibition', 'inhibition zone', 'diameter', 'clear area', 'size of the zone', 'ring'] };
const LIFE_FAN = { name: 'air movement (fan on or off)', aliases: ['fan', 'fan on or off', 'wind', 'air movement', 'air flow', 'moving air', 'breeze'] };
const LIFE_WATER_UPTAKE = { name: 'rate of water uptake', aliases: ['water uptake', 'water loss', 'transpiration', 'transpiration rate', 'bubble movement', 'how fast water is taken up', 'rate'] };
const LIFE_LEAF_POSITION = { name: 'side of the tree (sunny or shaded)', aliases: ['side', 'sunny or shaded', 'sun or shade', 'sunny', 'shaded', 'shade', 'aspect', 'light exposure'] };
const LIFE_LEAF_AREA = { name: 'leaf surface area', aliases: ['leaf area', 'surface area', 'area', 'leaf size', 'size of leaves', 'how big the leaves are'] };
const LIFE_POND_SPECIES = { name: 'number of invertebrate species', aliases: ['species', 'number of species', 'species richness', 'invertebrates', 'biodiversity', 'how many species', 'diversity'] };
const LIFE_GERM = { name: 'percentage of seeds that germinate', aliases: ['germination', 'seeds germinated', 'how many germinate', 'germination rate', 'percentage germinated', 'sprouting'] };
const LIFE_TEMP = { name: 'temperature', aliases: ['temperature', 'temp', 'heat', 'warmth', 'how warm', 'degrees'] };
const LIFE_OD = { name: 'cloudiness of the culture (optical density)', aliases: ['optical density', 'cloudiness', 'turbidity', 'absorbance', 'how cloudy', 'bacterial growth', 'growth', 'number of bacteria'] };
const LIFE_SPECIES_RICH = { name: 'number of plant species', aliases: ['species', 'number of species', 'species richness', 'plant species', 'how many species', 'biodiversity', 'diversity'] };
const LIFE_ALTITUDE = { name: 'altitude', aliases: ['altitude', 'height', 'elevation', 'height above sea level', 'how high', 'metres'] };
const LIFE_PLANT_HEIGHT = { name: 'plant height', aliases: ['height', 'how tall', 'growth', 'plant growth', 'size', 'length'] };
const LIFE_GRAZING = { name: 'grazing (grazed or ungrazed)', aliases: ['grazing', 'grazed', 'ungrazed', 'grazed or ungrazed', 'sheep', 'livestock', 'fenced'] };
const LIFE_FERT = { name: 'fertiliser (with or without)', aliases: ['fertiliser', 'fertilizer', 'with or without fertiliser', 'treatment', 'feed', 'nutrients', 'nitrogen'] };

POOLS.life = {

  // -------------------------------------------------------------------------
  // 1a. Variable or not?
  // -------------------------------------------------------------------------
  sortItems: [
    // --- variables ---
    { label: 'rate of photosynthesis', variable: true,
      why: 'Plants photosynthesise faster or slower depending on conditions, and the rate can be measured — for example as oxygen given off per minute.' },
    { label: 'enzyme activity', variable: true,
      why: 'An enzyme works faster in some conditions than others, and its rate of reaction can be measured.' },
    { label: 'light intensity', variable: true,
      why: 'Light can be brighter or dimmer, and its intensity is measured with a light meter.' },
    { label: 'temperature of a water bath', variable: true,
      why: 'A water bath can be set to different temperatures, measured in degrees.' },
    { label: 'pH', variable: true,
      why: 'Solutions are more or less acidic, and pH puts a number on it.' },
    { label: 'substrate concentration', variable: true,
      why: 'A solution can contain more or less substrate, and the concentration can be measured.' },
    { label: 'number of seeds that germinate', variable: true,
      why: 'Different trays of seeds have different numbers germinating, and they can be counted.' },
    { label: 'plant height', variable: true,
      why: 'Plants are different heights, and height is measured in centimetres.' },
    { label: 'change in mass of a potato cylinder', variable: true,
      why: 'Potato cylinders gain or lose different amounts of mass in different solutions, and it is measured in grams.' },
    { label: 'salt concentration', variable: true,
      why: 'A solution can have more or less salt dissolved in it, and the concentration can be measured.' },
    { label: 'number of bacterial colonies on a plate', variable: true,
      why: 'Different plates grow different numbers of colonies, and they can be counted.' },
    { label: 'diameter of a zone of inhibition', variable: true,
      why: 'The clear zone around a disc on an agar plate is bigger on some plates than others, and it is measured in millimetres.' },
    { label: 'rate of respiration in yeast', variable: true,
      why: 'Yeast respires faster or slower depending on conditions, and the carbon dioxide it gives off can be measured.' },
    { label: 'number of stomata on a leaf', variable: true,
      why: 'Leaves have different numbers of stomata, and they can be counted under a microscope.' },
    { label: 'root length', variable: true,
      why: 'Roots grow to different lengths, measured in millimetres.' },
    { label: 'rate of transpiration', variable: true,
      why: 'Plants lose water faster in some conditions than others, and the rate can be measured with a potometer.' },
    { label: 'leaf surface area', variable: true,
      why: 'Leaves come in different sizes, and their area can be measured in square centimetres.' },
    { label: 'size of a population', variable: true,
      why: 'A population can have more or fewer individuals, and they can be counted or estimated.' },
    { label: 'species richness', variable: true, for: LIFE_ECO,
      why: 'Some habitats have more species than others, and the number of species can be counted.' },
    { label: 'percentage cover of a plant in a quadrat', variable: true, for: LIFE_ECO,
      why: 'A plant covers more of some quadrats than others, and the percentage can be estimated or measured.' },
    { label: 'altitude', variable: true, for: LIFE_ECO,
      why: 'Sampling sites are at different heights above sea level, measured in metres.' },
    { label: 'distance from a river', variable: true, for: LIFE_ECO,
      why: 'Quadrats can be placed nearer to or further from a river, and the distance is measured in metres.' },
    { label: 'soil moisture', variable: true, for: [...LIFE_ECO, 'agriculture'],
      why: 'Some soil is wetter than other soil, and its water content can be measured.' },
    { label: 'crop yield', variable: true, for: LIFE_AGRI,
      why: 'Some fields produce more crop than others, and yield is measured in tonnes per hectare.' },
    { label: 'soil pH', variable: true, for: LIFE_AGRI,
      why: 'Some fields have more acidic soil than others, and the pH can be measured.' },
    { label: 'milk yield', variable: true, for: LIFE_AGRI,
      why: 'Cows give different amounts of milk from day to day and cow to cow, measured in litres.' },
    { label: 'stocking density', variable: true, for: LIFE_AGRI,
      why: 'A field can hold more or fewer animals per hectare, and that number can be counted.' },
    { label: 'fertiliser dose', variable: true, for: LIFE_AGRI,
      why: 'Fields can be given more or less fertiliser, measured in kilograms per hectare.' },
    { label: 'cell count', variable: true, for: LIFE_BIOMED,
      why: 'Different cultures contain different numbers of cells, and they can be counted with a haemocytometer.' },
    { label: 'optical density of a culture', variable: true, for: LIFE_BIOMED,
      why: 'Some cultures are cloudier than others, and a spectrophotometer measures how much light they absorb.' },
    { label: 'incubation temperature', variable: true, for: LIFE_BIOMED,
      why: 'Cultures can be incubated at different temperatures, measured in degrees.' },

    // --- not variables: one particular thing ---
    { label: 'Charles Darwin', variable: false,
      why: 'Charles Darwin is one particular person. (The number of species a naturalist describes would be a variable.)' },
    { label: 'the Galápagos Islands', variable: false,
      why: 'The Galápagos Islands are one particular place. (The beak depth of finches there would be a variable.)' },
    { label: 'Dolly the sheep', variable: false,
      why: 'Dolly was one particular sheep. (The body mass of sheep would be a variable.)' },
    { label: 'the Amazon rainforest', variable: false,
      why: 'The Amazon is one particular forest. (The number of tree species per hectare would be a variable.)' },
    { label: 'Lough Neagh', variable: false,
      why: 'Lough Neagh is one particular lake. (The amount of algae in a lake would be a variable.)' },
    { label: 'the blue whale', variable: false,
      why: 'The blue whale is one particular species. (The body length of individual whales would be a variable.)' },
    { label: 'the Venus flytrap', variable: false,
      why: 'The Venus flytrap is one particular species of plant. (The number of insects a plant traps would be a variable.)' },
    { label: 'the Eden Project', variable: false,
      why: 'The Eden Project is one particular garden. (The temperature inside a greenhouse would be a variable.)' },
    { label: 'the Natural History Museum', variable: false,
      why: 'It\'s one particular museum. (The number of specimens in a collection would be a variable.)' },
    { label: 'the Petri dish on the bench', variable: false,
      why: 'It\'s one particular dish — a piece of equipment, not a measurement. (The number of colonies growing in it would be a variable.)' },
    { label: 'the quadrat in the corner of the meadow', variable: false, for: LIFE_ECO,
      why: 'It\'s one particular quadrat. (The number of plant species inside it would be a variable.)' },
    { label: 'the top field on the college farm', variable: false, for: LIFE_AGRI,
      why: 'It\'s one particular field. (The yield it produces each year would be a variable.)' },
    { label: 'the microscope in lab 3', variable: false, for: LIFE_BIOMED,
      why: 'It\'s one particular microscope. (The number of cells seen in a field of view would be a variable.)' },

    // --- not variables: measurable, but only one possible value ---
    { label: 'the number of carbon atoms in a glucose molecule', variable: false,
      why: 'It\'s always six. It can be counted, but it only ever has one value — a constant, not a variable.' },
    { label: 'the number of different bases in DNA', variable: false,
      why: 'It\'s always four: A, T, C and G. Only one possible value, so it\'s a constant.' },
    { label: 'the number of chambers in a mammal\'s heart', variable: false,
      why: 'A mammal\'s heart always has four chambers. Something with only one possible value is a constant, not a variable.' },
  ],

  // -------------------------------------------------------------------------
  // 1b-1d. Relations.
  // -------------------------------------------------------------------------
  relations: [
    { id: 'life-light-photo', iv: 'light intensity', dv: 'rate of photosynthesis', ivNP: 'the light intensity', dvNP: 'the rate of photosynthesis',
      hyp: ['light intensity', 'photosynthesis rate'], ivAxis: 'Light intensity', dvAxis: 'Photosynthesis', dir: 'up',
      says: ['In dim light, pondweed gives off oxygen faster as the light gets brighter.',
             'The rate of photosynthesis goes up as light intensity increases, until something else limits it.'],
      why: 'Light supplies the energy for photosynthesis, so the light is the changer. A plant photosynthesising faster can\'t make the lamp brighter.' },
    { id: 'life-dist-photo', iv: 'distance from the lamp', dv: 'rate of photosynthesis', ivNP: 'the distance from the lamp', dvNP: 'the rate of photosynthesis',
      hyp: ['lamp distance', 'photosynthesis rate'], ivAxis: 'Distance', dvAxis: 'Photosynthesis', dir: 'down',
      says: ['The further pondweed is from the lamp, the fewer oxygen bubbles it gives off.',
             'The rate of photosynthesis falls as the lamp is moved further away.'],
      why: 'The researcher sets the distance; moving the lamp away means less light reaches the plant. How fast the plant photosynthesises can\'t move the lamp.' },
    { id: 'life-co2-photo', iv: 'carbon dioxide concentration', dv: 'rate of photosynthesis', ivNP: 'the carbon dioxide concentration', dvNP: 'the rate of photosynthesis',
      hyp: ['carbon dioxide', 'photosynthesis rate'], ivAxis: 'CO₂', dvAxis: 'Photosynthesis', dir: 'up',
      says: ['At low carbon dioxide levels, plants photosynthesise faster when more carbon dioxide is added.',
             'The rate of photosynthesis rises with the carbon dioxide concentration, until something else limits it.'],
      why: 'Carbon dioxide is a raw material for photosynthesis, so supplying more of it is the changer. The plant\'s rate can\'t set how much carbon dioxide was supplied.' },
    { id: 'life-temp-enzyme', iv: 'temperature', dv: 'enzyme activity', ivNP: 'the temperature', dvNP: 'enzyme activity',
      hyp: ['temperature', 'enzyme activity'], ivAxis: 'Temperature', dvAxis: 'Enzyme activity', dir: 'up',
      says: ['Below its optimum, an enzyme works faster as the temperature rises.',
             'Enzyme activity goes up with temperature, up to the optimum.'],
      why: 'The temperature is set before the reaction runs, and warmer molecules collide more often. The enzyme working faster can\'t change the temperature of the water bath.' },
    { id: 'life-ph-enzyme', iv: 'pH', dv: 'amylase activity', ivNP: 'the pH', dvNP: 'amylase activity',
      hyp: ['pH', 'amylase activity'], ivAxis: 'pH', dvAxis: 'Amylase activity', dir: 'down',
      says: ['Above its optimum pH, amylase breaks down starch more slowly as the solution becomes more alkaline.',
             'Amylase activity falls as the pH rises above the optimum.'],
      why: 'The pH is set with a buffer before the enzyme is added, and pH away from the optimum changes the shape of the active site. How fast the enzyme works can\'t change the buffer.' },
    { id: 'life-substrate-rate', iv: 'substrate concentration', dv: 'reaction rate', ivNP: 'the substrate concentration', dvNP: 'the reaction rate',
      hyp: ['substrate concentration', 'reaction rate'], ivAxis: 'Substrate', dvAxis: 'Reaction rate', dir: 'up',
      says: ['At low substrate concentrations, an enzyme reaction goes faster when more substrate is added.',
             'The reaction rate goes up with the substrate concentration, until all the enzymes are busy.'],
      why: 'More substrate means more collisions with the enzyme\'s active sites, so the substrate is the changer. A fast reaction can\'t go back and add substrate.' },
    { id: 'life-salt-mass', iv: 'salt concentration', dv: 'final mass of potato', ivNP: 'the salt concentration', dvNP: 'the final mass of potato cylinders',
      hyp: ['salt concentration', 'potato mass'], ivAxis: 'Salt conc.', dvAxis: 'Final mass', dir: 'down',
      says: ['The stronger the salt solution, the more mass a potato cylinder loses.',
             'Potato cylinders end up lighter the more concentrated the salt solution they sit in.'],
      why: 'The solution is made up first, and water leaves the potato by osmosis into stronger solutions. The potato losing water can\'t change how much salt was dissolved.' },
    { id: 'life-temp-germ', iv: 'temperature', dv: 'time to germinate', ivNP: 'the temperature', dvNP: 'the time seeds take to germinate',
      hyp: ['temperature', 'germination time'], ivAxis: 'Temperature', dvAxis: 'Germination time', dir: 'down',
      says: ['Below the optimum, cress seeds germinate sooner at warmer temperatures.',
             'The time seeds take to germinate goes down as the temperature rises towards the optimum.'],
      why: 'The trays are kept at a set temperature, and warmth speeds up the reactions inside the seed. Careful with the graph: germinating faster means fewer days, so the line falls.' },
    { id: 'life-salt-germ', iv: 'salt concentration', dv: 'seeds germinating', ivNP: 'the salt concentration', dvNP: 'the number of seeds that germinate',
      hyp: ['salt concentration', 'germination'], ivAxis: 'Salt conc.', dvAxis: 'Germination', dir: 'down',
      says: ['Fewer cress seeds germinate when they are watered with saltier water.',
             'The number of seeds that germinate drops as the salt concentration goes up.'],
      why: 'The salty water is given to the seeds before they germinate, and it makes it harder for them to take up water. How many seeds germinate can\'t change the water they were given.' },
    { id: 'life-sugar-yeast', iv: 'sugar concentration', dv: 'carbon dioxide produced', ivNP: 'the sugar concentration', dvNP: 'the amount of carbon dioxide produced by yeast',
      hyp: ['sugar concentration', 'carbon dioxide'], ivAxis: 'Sugar conc.', dvAxis: 'CO₂ produced', dir: 'up',
      says: ['At low sugar concentrations, yeast gives off more carbon dioxide when it is given more sugar.',
             'The carbon dioxide produced by yeast goes up with the sugar concentration, until the yeast can\'t use it any faster.'],
      why: 'Sugar is what the yeast respires, so the sugar is the changer. Yeast giving off gas can\'t add sugar to its own solution.' },
    { id: 'life-temp-transp', iv: 'temperature', dv: 'rate of transpiration', ivNP: 'the temperature', dvNP: 'the rate of transpiration',
      hyp: ['temperature', 'transpiration'], ivAxis: 'Temperature', dvAxis: 'Transpiration', dir: 'up',
      says: ['Leafy shoots lose water faster on warmer days.',
             'The rate of transpiration goes up as the temperature rises.'],
      why: 'Warmth makes water evaporate from the leaves faster, so the temperature is the changer. A plant losing water doesn\'t heat the air.' },
    { id: 'life-humid-transp', iv: 'humidity', dv: 'rate of transpiration', ivNP: 'the humidity', dvNP: 'the rate of transpiration',
      hyp: ['humidity', 'transpiration'], ivAxis: 'Humidity', dvAxis: 'Transpiration', dir: 'down',
      says: ['The more humid the air, the more slowly a plant loses water from its leaves.',
             'The rate of transpiration falls as the humidity goes up.'],
      why: 'Damp air slows evaporation from the leaves, so humidity is the changer. One plant losing water can\'t noticeably change the humidity of a whole room.' },
    { id: 'life-water-growth', iv: 'amount of water', dv: 'plant growth', ivNP: 'the amount of water given', dvNP: 'plant growth',
      hyp: ['water', 'plant growth'], ivAxis: 'Water given', dvAxis: 'Growth', dir: 'up',
      says: ['In dry compost, seedlings given more water grow taller, up to the amount they need.',
             'Plant growth goes up with the amount of water given, until the plants have enough.'],
      why: 'The water is given first and the growth follows, so the water is the changer. A plant growing taller can\'t change how much water it was given.' },
    { id: 'life-nitrate-algae', iv: 'nitrate concentration', dv: 'algal growth', ivNP: 'the nitrate concentration', dvNP: 'algal growth',
      hyp: ['nitrate', 'algal growth'], ivAxis: 'Nitrate', dvAxis: 'Algal growth', dir: 'up',
      says: ['Algae grow faster in pond water with more nitrate in it.',
             'Algal growth goes up as the nitrate concentration rises.'],
      why: 'Nitrate is a nutrient the algae need, so the nitrate is the changer. Algae growing can\'t add nitrate to the water — if anything, they use it up.' },
    { id: 'life-density-mass', iv: 'number of seeds per pot', dv: 'mass of each plant', ivNP: 'the number of seeds sown per pot', dvNP: 'the mass of each plant',
      hyp: ['plants per pot', 'mass per plant'], ivAxis: 'Seeds per pot', dvAxis: 'Mass per plant', dir: 'down',
      says: ['The more seeds are sown in a pot, the smaller each plant ends up.',
             'The mass of each plant goes down as more seeds are sown in the same pot.'],
      why: 'The number of seeds is decided at sowing, and more plants share the same light, water and nutrients. A small plant can\'t go back and change how many seeds were sown.' },
    { id: 'life-predator-prey', for: LIFE_ECO, iv: 'number of predators', dv: 'number of prey', ivNP: 'the number of predators', dvNP: 'the number of prey',
      hyp: ['predators', 'prey'], ivAxis: 'Predators', dvAxis: 'Prey', dir: 'down',
      says: ['When there are more ladybirds on a plant, the number of aphids falls.',
             'Aphid numbers go down the more ladybirds there are.'],
      why: 'As stated, the ladybirds are doing the eating, so they are the changer. (The prey numbers also affect the predators over time, but that is a different claim.)' },
    { id: 'life-river-moisture', for: LIFE_ECO, iv: 'distance from the river', dv: 'soil moisture', ivNP: 'the distance from the river', dvNP: 'soil moisture',
      hyp: ['distance from the river', 'soil moisture'], ivAxis: 'Distance', dvAxis: 'Soil moisture', dir: 'down',
      says: ['The further a quadrat is from the river, the drier the soil.',
             'Soil moisture drops as you move away from the river.'],
      why: 'Being close to the river is what keeps the soil wet. Damp soil can\'t move a river closer.' },
    { id: 'life-altitude-richness', for: LIFE_ECO, iv: 'altitude', dv: 'number of plant species', ivNP: 'the altitude', dvNP: 'the number of plant species',
      hyp: ['altitude', 'plant species'], ivAxis: 'Altitude', dvAxis: 'Species', dir: 'down',
      says: ['Above the tree line, fewer plant species are found the higher up the mountain you go.',
             'Above the tree line, the number of plant species falls as the altitude goes up.'],
      why: 'Altitude brings colder, windier conditions that fewer species can survive. The plants growing there can\'t change how high the mountain is.' },
    { id: 'life-trampling-cover', for: LIFE_ECO, iv: 'trampling', dv: 'plant cover', ivNP: 'the amount of trampling', dvNP: 'plant cover',
      hyp: ['trampling', 'plant cover'], ivAxis: 'Trampling', dvAxis: 'Plant cover', dir: 'down',
      says: ['The more a path is walked on, the less of it is covered by plants.',
             'Plant cover goes down as trampling goes up.'],
      why: 'Feet crush plants and pack down the soil, so trampling is the changer. As stated, fewer plants don\'t make people walk there more.' },
    { id: 'life-canopy-ground', for: LIFE_ECO, iv: 'canopy cover', dv: 'grass cover', ivNP: 'the canopy cover', dvNP: 'grass cover on the woodland floor',
      hyp: ['canopy cover', 'grass cover'], ivAxis: 'Canopy cover', dvAxis: 'Grass cover', dir: 'down',
      says: ['Under a denser tree canopy, less grass grows on the woodland floor.',
             'Grass cover falls as the canopy above gets denser.'],
      why: 'The canopy shades out the grass below, so the trees are the changer. Grass on the ground can\'t thin out the trees above it.' },
    { id: 'life-fert-yield', for: LIFE_AGRI, iv: 'fertiliser dose', dv: 'crop yield', ivNP: 'the fertiliser dose', dvNP: 'crop yield',
      hyp: ['fertiliser', 'yield'], ivAxis: 'Fertiliser', dvAxis: 'Yield', dir: 'up',
      says: ['On nitrogen-poor soil, wheat plots given more nitrogen fertiliser produce more grain, up to a point.',
             'Crop yield rises with the fertiliser dose, until the crop has all the nitrogen it can use.'],
      why: 'The fertiliser goes on in spring and the harvest comes in late summer, so fertiliser is the changer. The harvest can\'t change how much fertiliser was spread.' },
    { id: 'life-stocking-grass', for: LIFE_AGRI, iv: 'stocking density', dv: 'grass height', ivNP: 'the stocking density', dvNP: 'grass height',
      hyp: ['stocking density', 'grass height'], ivAxis: 'Stocking density', dvAxis: 'Grass height', dir: 'down',
      says: ['The more sheep there are per hectare, the shorter the grass.',
             'Grass height goes down as the stocking density goes up.'],
      why: 'The farmer decides how many sheep go in the field, and the sheep eat the grass. The grass being short can\'t put more sheep in the field.' },
    { id: 'life-irrigation-yield', for: LIFE_AGRI, iv: 'irrigation', dv: 'crop yield', ivNP: 'the amount of irrigation', dvNP: 'crop yield',
      hyp: ['irrigation', 'yield'], ivAxis: 'Irrigation', dvAxis: 'Yield', dir: 'up',
      says: ['In a dry summer, potato fields given more irrigation produce more potatoes, up to the water the crop needs.',
             'Potato yield goes up with irrigation in a dry season, until the crop has enough water.'],
      why: 'The water is applied during the season and the yield is weighed at harvest, so irrigation is the changer. The harvest can\'t change how much water was applied.' },
    { id: 'life-soilph-growth', for: LIFE_AGRI, iv: 'soil pH', dv: 'barley growth', ivNP: 'the soil pH', dvNP: 'barley growth',
      hyp: ['soil pH', 'barley growth'], ivAxis: 'Soil pH', dvAxis: 'Barley growth', dir: 'up',
      says: ['On acidic soil, barley grows better as lime raises the pH towards neutral.',
             'Barley growth goes up as the pH of an acidic soil is raised towards neutral.'],
      why: 'The soil is limed before sowing, and barley grows poorly in acid soil. The barley growing well can\'t change the pH that the lime set.' },
    { id: 'life-feed-milk', for: LIFE_AGRI, iv: 'amount of feed', dv: 'milk yield', ivNP: 'the amount of feed', dvNP: 'milk yield',
      hyp: ['feed', 'milk yield'], ivAxis: 'Feed', dvAxis: 'Milk yield', dir: 'up',
      says: ['Dairy cows given more feed produce more milk, up to a limit.',
             'Milk yield goes up with the amount of feed a cow is given, until she can\'t use any more.'],
      why: 'Milk is made from the energy and protein in the feed, so the feed is the changer. As stated, the milk yield doesn\'t decide how much feed is put out.' },
    { id: 'life-temp-culture', for: LIFE_BIOMED, iv: 'incubation temperature', dv: 'bacterial growth rate', ivNP: 'the incubation temperature', dvNP: 'the growth rate of the culture',
      hyp: ['incubation temperature', 'growth rate'], ivAxis: 'Incubation temp', dvAxis: 'Growth rate', dir: 'up',
      says: ['Below its optimum temperature, a bacterial culture grows faster the warmer it is incubated.',
             'The growth rate of the culture goes up with the incubation temperature, up to the optimum.'],
      why: 'The incubator is set before the culture goes in, and warmth speeds up the bacteria\'s enzymes. Bacteria growing faster can\'t change the incubator setting.' },
    { id: 'life-antiseptic-colonies', for: LIFE_BIOMED, iv: 'antiseptic concentration', dv: 'number of colonies', ivNP: 'the antiseptic concentration', dvNP: 'the number of colonies',
      hyp: ['antiseptic concentration', 'colonies'], ivAxis: 'Antiseptic', dvAxis: 'Colonies', dir: 'down',
      says: ['The stronger the antiseptic added to the agar, the fewer bacterial colonies grow on the plate.',
             'The number of colonies drops as the antiseptic concentration goes up.'],
      why: 'The antiseptic is in the agar before the bacteria are spread, and it kills or stops them. Fewer colonies can\'t change how much antiseptic went in.' },
    { id: 'life-antibiotic-zone', for: LIFE_BIOMED, iv: 'antibiotic concentration', dv: 'zone of inhibition', ivNP: 'the antibiotic concentration', dvNP: 'the diameter of the zone of inhibition',
      hyp: ['antibiotic concentration', 'clear zone'], ivAxis: 'Antibiotic', dvAxis: 'Clear zone', dir: 'up',
      says: ['On a lawn of bacteria, discs soaked in a stronger antibiotic solution leave a wider clear zone.',
             'The zone of inhibition gets wider as the antibiotic concentration goes up.'],
      why: 'The disc is soaked before it goes on the plate, and a stronger solution stops growth further out as it spreads through the agar. The clear zone can\'t change what the disc was soaked in.' },
    { id: 'life-time-cells', for: LIFE_BIOMED, iv: 'time in culture', dv: 'cell count', ivNP: 'the time in culture', dvNP: 'the cell count',
      hyp: ['time in culture', 'cell count'], ivAxis: 'Time', dvAxis: 'Cell count', dir: 'up',
      says: ['During its growth phase, a yeast culture contains more cells the longer it has been growing.',
             'The cell count goes up with time while the culture is in its growth phase.'],
      why: 'Time passing is what lets the cells divide. More cells can\'t make more time pass.' },
  ],

  // -------------------------------------------------------------------------
  // 2a. Validity and reliability.
  // -------------------------------------------------------------------------
  validity: [
    // valid and reliable
    { valid: true, reliable: true,
      text: 'To measure the rate of photosynthesis, researchers collect the oxygen given off by pondweed in a gas syringe and read the volume after 5 minutes. Repeating it with the same pondweed and lamp gives very similar volumes.',
      whyValid: 'oxygen is a product of photosynthesis, so the volume given off shows how fast it is happening.',
      whyReliable: 'repeating it gives very similar volumes.' },
    { valid: true, reliable: true,
      text: 'To measure osmosis, researchers weigh potato cylinders on a balance before and after an hour in salt solution. Weighing the same cylinder again gives exactly the same reading.',
      whyValid: 'the change in mass shows how much water moved in or out of the potato.',
      whyReliable: 'the balance gives the same reading every time.' },
    { valid: true, reliable: true, for: LIFE_BIOMED,
      text: 'To measure how well an antiseptic stops bacteria, researchers measure the diameter of the clear zone around each disc with a ruler. Two researchers measuring the same plates separately get the same numbers.',
      whyValid: 'the clear zone is where bacteria couldn\'t grow, so its size shows how well the antiseptic stops them.',
      whyReliable: 'two people measuring separately get the same result.' },
    { valid: true, reliable: true, for: LIFE_ECO,
      text: 'To measure plant species richness, a trained surveyor identifies every species in 20 quadrats using a key. A second trained surveyor, working separately, records the same species.',
      whyValid: 'counting the species present is exactly what species richness means.',
      whyReliable: 'a second surveyor working separately gets the same result.' },
    { valid: true, reliable: true, for: LIFE_AGRI,
      text: 'To measure the yield of each wheat plot, researchers harvest all the grain and weigh it on calibrated scales. Weighing the same grain again gives the same mass.',
      whyValid: 'the mass of grain harvested is what yield means.',
      whyReliable: 'weighing it again gives the same mass.' },
    { valid: true, reliable: true,
      text: 'To find out whether boiling stops catalase from working, researchers add boiled and unboiled liver extract to hydrogen peroxide in 3 tubes each. Unboiled extract fizzes hard every time and boiled extract never fizzes; another 3 tubes of each give the same result.',
      whyValid: 'fizzing is oxygen being released, which shows whether the enzyme is working.',
      whyReliable: 'another 3 tubes give the same result. With an effect this big, 3 samples is enough.' },

    // reliable, not valid
    { valid: false, reliable: true,
      text: 'To measure the rate of photosynthesis, researchers measure the length of each sprig of pondweed with a ruler. Measuring the same sprig again gives the same length.',
      whyValid: 'the length of the sprig says nothing about how fast it is photosynthesising right now.',
      whyReliable: 'measuring again gives the same length. Consistent, but consistently measuring the wrong thing.' },
    { valid: false, reliable: true, for: LIFE_ECO,
      text: 'To measure species richness, researchers count every individual plant in each quadrat. Two people counting the same quadrat get the same total.',
      whyValid: 'that counts how many plants there are, not how many species — a quadrat of 200 grass plants may hold only one species.',
      whyReliable: 'two people counting get the same total.' },
    { valid: false, reliable: true, for: LIFE_AGRI,
      text: 'To measure the grain yield of different wheat varieties, researchers measure the height of the plants just before harvest. The heights come out the same whoever measures them.',
      whyValid: 'height isn\'t grain yield — a tall variety can produce less grain than a short one.',
      whyReliable: 'anyone measuring gets the same heights.' },
    { valid: false, reliable: true, for: LIFE_BIOMED,
      text: 'To measure how many bacteria are in a culture, researchers record the volume of the flask it is growing in. The flask volume is the same every time it is checked.',
      whyValid: 'the size of the flask says nothing about how many bacteria are inside it.',
      whyReliable: 'the flask volume never changes.' },
    { valid: false, reliable: true,
      text: 'To measure how active an enzyme is, researchers record the volume of enzyme solution they added to each tube. Checking the pipette gives the same volume every time.',
      whyValid: 'the volume added is what went in, not how fast the enzyme worked once it was there.',
      whyReliable: 'the pipette delivers the same volume every time.' },

    // valid, not reliable
    { valid: true, reliable: false,
      text: 'To measure the rate of photosynthesis, a student counts the oxygen bubbles rising from pondweed for one minute by eye. The bubbles vary in size and come quickly, and counting the same minute of video again gives quite a different number.',
      whyValid: 'the bubbles are oxygen from photosynthesis, so counting them is aimed at the right thing.',
      whyReliable: 'the count changes a lot each time, because bubbles are hard to count by eye.' },
    { valid: true, reliable: false,
      text: 'To measure amylase activity, one student decides by eye when the iodine in each spotting tile stops turning blue-black. The same tile is judged to have finished at quite different times on different attempts.',
      whyValid: 'the time for the starch to disappear does show how fast amylase breaks it down.',
      whyReliable: 'judging the colour change by eye gives a different end point each time.' },
    { valid: true, reliable: false, for: LIFE_ECO,
      text: 'To measure how much of a meadow is covered by clover, one untrained student estimates the percentage cover in each quadrat by eye. Estimating the same quadrats again an hour later gives very different numbers.',
      whyValid: 'percentage cover is the right thing to measure for how much ground the clover covers.',
      whyReliable: 'rough estimates by eye change a lot from one attempt to the next.' },
    { valid: true, reliable: false, for: LIFE_AGRI,
      text: 'To find out whether a new fertiliser increases wheat yield, researchers compare one fertilised plot with one unfertilised plot. When they repeat it on another pair of plots, the unfertilised one yields more.',
      whyValid: 'weighing the grain from fertilised and unfertilised plots is the right comparison.',
      whyReliable: 'repeating it gives the opposite result. For a modest difference, one plot per group is far too few, because plots differ in soil anyway.' },
    { valid: true, reliable: false,
      text: 'To find out whether warmth speeds up germination, researchers put 5 seeds in a warm dish and 5 in a cool dish. When they repeat it with another 5 seeds each, the result comes out the other way.',
      whyValid: 'counting how many seeds germinate is the right way to measure germination.',
      whyReliable: 'with only 5 seeds per dish, one or two odd seeds swing the result. Far too few samples for a small difference.' },
    { valid: true, reliable: false, for: LIFE_BIOMED,
      text: 'Researchers measure the growth of bacterial cultures with a spectrophotometer, but their report doesn\'t say the incubation temperature or how long the cultures were grown. Other labs that try to repeat the study get different results.',
      whyValid: 'optical density is a sensible measure of how much the bacteria have grown.',
      whyReliable: 'without a full "recipe" — temperature, time, medium — nobody can repeat the study and get the same result.' },

    // neither
    { valid: false, reliable: false,
      text: 'To measure the rate of photosynthesis in the lab, researchers record what the weather is like outside. The weather is different every time the experiment is run.',
      whyValid: 'the weather outside isn\'t a measure of how fast the pondweed in the lab is photosynthesising.',
      whyReliable: 'the same set-up gets a different result every day.' },
    { valid: false, reliable: false,
      text: 'To measure how well seedlings grow, researchers note the colour of the plant label that each pot happens to get that day. The labels are handed out at random every morning.',
      whyValid: 'the colour of a label has nothing to do with how well a seedling grows.',
      whyReliable: 'the same seedling gets a different "score" every day.' },
    { valid: false, reliable: false, for: LIFE_ECO,
      text: 'To measure how acidic the soil in a woodland is, researchers record how many birds they hear singing in the first minute of their visit. The count is different every visit.',
      whyValid: 'birdsong has nothing to do with soil pH.',
      whyReliable: 'the same woodland gets a different number every visit.' },
    { valid: false, reliable: false, for: LIFE_BIOMED,
      text: 'To measure how many cells are in a culture, researchers note how long the queue for the microscope is. The queue is different every time.',
      whyValid: 'the queue for the microscope says nothing about the cells in the culture.',
      whyReliable: 'the same culture gets a different result every time.' },
    { valid: false, reliable: false, for: LIFE_AGRI,
      text: 'To measure how much milk each cow gives, a farmer notes how many times she moos during milking. The same cow moos a different number of times every day.',
      whyValid: 'mooing isn\'t milk — it doesn\'t measure how much milk she gives.',
      whyReliable: 'the same cow gets a very different count every day.' },
  ],

  // -------------------------------------------------------------------------
  // 2d. Continuous or discrete.
  // -------------------------------------------------------------------------
  continuity: [
    { cat: 'cont', label: 'mass of a potato cylinder', why: LIFE_CONT + '2.4 g, 2.43 g, 2.431 g...' },
    { cat: 'cont', label: 'length of a root', why: LIFE_CONT + 'a root can be 31 mm, 31.5 mm, 31.52 mm long...' },
    { cat: 'cont', label: 'temperature of a water bath', why: LIFE_CONT + '35°C, 35.5°C, 35.51°C...' },
    { cat: 'cont', label: 'pH of a solution', why: LIFE_CONT + 'pH 6.8, 6.85, 6.852... there\'s always a value in between.' },
    { cat: 'cont', label: 'volume of oxygen produced', why: LIFE_CONT + 'gas volume can always be measured more finely.' },
    { cat: 'cont', label: 'diameter of a zone of inhibition', why: LIFE_CONT + '14 mm, 14.2 mm, 14.25 mm...' },
    { cat: 'cont', label: 'time for starch to disappear', why: LIFE_CONT + 'time can always be divided further.' },
    { cat: 'cont', label: 'leaf surface area', why: LIFE_CONT + 'an area can be 12 cm², 12.3 cm², 12.34 cm²...' },
    { cat: 'cont', label: 'average number of seeds per pod', why: LIFE_CONT + 'a single pod can\'t hold 5.4 seeds, but an average across pods can.' },
    { cat: 'cont', label: 'crop yield in tonnes per hectare', for: LIFE_AGRI, why: LIFE_CONT + '8.1, 8.14, 8.147 tonnes per hectare...' },
    { cat: 'cont', label: 'milk yield in litres', for: LIFE_AGRI, why: LIFE_CONT + 'a cow can give 28 litres, 28.3 litres, 28.35 litres...' },
    { cat: 'cont', label: 'distance of a quadrat from the river', for: LIFE_ECO, why: LIFE_CONT + 'distance can always be measured more finely.' },
    { cat: 'cont', label: 'altitude of a sampling site', for: LIFE_ECO, why: LIFE_CONT + 'a site can be at 412 m, 412.5 m, 412.53 m...' },
    { cat: 'cont', label: 'optical density of a culture', for: LIFE_BIOMED, why: LIFE_CONT + '0.42, 0.425, 0.4253... absorbance can be any value on the scale.' },

    { cat: 'disc', label: 'number of seeds that germinate', why: LIFE_DISC + 'seeds are counted: 17 or 18, never 17.5.' },
    { cat: 'disc', label: 'number of bacterial colonies on a plate', why: LIFE_DISC + 'colonies are counted one by one.' },
    { cat: 'disc', label: 'number of stomata in a field of view', why: LIFE_DISC + 'each stoma is counted once, so the total is a whole number.' },
    { cat: 'disc', label: 'number of leaves on a plant', why: LIFE_DISC + 'a plant has 8 leaves or 9, not 8.6.' },
    { cat: 'disc', label: 'number of oxygen bubbles counted in a minute', why: LIFE_DISC + 'bubbles are counted in whole numbers.' },
    { cat: 'disc', label: 'number of petals on a flower', why: LIFE_DISC + 'a flower has 5 petals or 6, nothing in between.' },
    { cat: 'disc', label: 'number of eggs laid', why: LIFE_DISC + 'eggs are counted: 3 or 4, never 3.5.' },
    { cat: 'disc', label: 'number of samples in an experiment', why: LIFE_DISC + 'samples are counted in whole numbers.' },
    { cat: 'disc', label: 'number of species in a quadrat', for: LIFE_ECO, why: LIFE_DISC + 'each species is either present or not, so they\'re counted.' },
    { cat: 'disc', label: 'number of quadrats sampled', for: LIFE_ECO, why: LIFE_DISC + 'you place 10 quadrats or 11, not 10.5.' },
    { cat: 'disc', label: 'number of cows in a herd', for: LIFE_AGRI, why: LIFE_DISC + 'cows are counted in whole numbers.' },
    { cat: 'disc', label: 'number of lambs born to a ewe', for: LIFE_AGRI, why: LIFE_DISC + 'a ewe has 1 lamb or 2, never 1.5.' },
    { cat: 'disc', label: 'number of cells in a haemocytometer square', for: LIFE_BIOMED, why: LIFE_DISC + 'cells are counted one by one.' },
  ],

  // -------------------------------------------------------------------------
  // 2e. Levels of measurement.
  // -------------------------------------------------------------------------
  measurement: [
    { cat: 'categorical', label: 'species of tree', why: LIFE_NOM + 'An oak isn\'t more or less than an ash, just different.' },
    { cat: 'categorical', label: 'flower colour', why: LIFE_NOM + 'Red, white and purple have no order.' },
    { cat: 'categorical', label: 'soil type (clay, sand, loam)', why: LIFE_NOM + 'These are kinds of soil, not amounts of soil.' },
    { cat: 'categorical', label: 'which treatment group a plant is in', why: LIFE_NOM + 'Group A and group B are labels, not amounts.' },
    { cat: 'categorical', label: 'habitat type (woodland, meadow, pond)', for: LIFE_ECO, why: LIFE_NOM + 'A pond isn\'t more than a meadow, just different.' },
    { cat: 'categorical', label: 'breed of cow', for: LIFE_AGRI, why: LIFE_NOM + 'A Holstein isn\'t more or less than a Jersey, just a different breed.' },
    { cat: 'categorical', label: 'Gram stain result (positive or negative)', for: LIFE_BIOMED, why: LIFE_NOM + 'Positive and negative here are two kinds of cell wall, not more and less of something.' },

    { cat: 'ordinal', label: 'abundance on the DAFOR scale (dominant, abundant, frequent, occasional, rare)', for: LIFE_ECO, why: LIFE_ORD + 'Abundant is above frequent, but the steps aren\'t equal-sized amounts.' },
    { cat: 'ordinal', label: 'leaf damage (none, slight, moderate, severe)', why: LIFE_ORD + 'The categories are in order, but nothing says the steps are the same size.' },
    { cat: 'ordinal', label: 'growth stage (seedling, young plant, mature plant)', why: LIFE_ORD + 'The stages are in order, but they aren\'t equally spaced.' },
    { cat: 'ordinal', label: 'ripeness of fruit (unripe, ripe, overripe)', why: LIFE_ORD + 'In order, but the jump from unripe to ripe needn\'t match the jump from ripe to overripe.' },
    { cat: 'ordinal', label: 'ranking plots from most to least weedy', why: LIFE_ORD + 'A ranking gives the order, not how far apart the plots are.' },
    { cat: 'ordinal', label: 'amount of growth on a plate (none, +, ++, +++)', for: LIFE_BIOMED, why: LIFE_ORD + 'More plus signs means more growth, but "++" isn\'t exactly twice "+".' },

    { cat: 'interval', label: 'temperature in °C', why: LIFE_INT + '0°C isn\'t "no temperature", so 30°C isn\'t twice as hot as 15°C.' },
    { cat: 'interval', label: 'date of first flowering', why: LIFE_INT + 'Days are equal steps, but the calendar\'s starting point is arbitrary.' },
    { cat: 'interval', label: 'calendar year of a survey', why: LIFE_INT + 'The gap between years is equal, but year 0 isn\'t the beginning of time.' },
    { cat: 'interval', label: 'time of day a sample is taken', why: LIFE_INT + 'The minutes are equal, but midnight isn\'t "no time", so 4 o\'clock isn\'t twice 2 o\'clock.' },
    { cat: 'interval', label: 'leaf damage rated on a scale of 1–7', why: LIFE_INT + 'A numbered scale has constant steps, but no natural zero, so a 6 isn\'t "twice as damaged" as a 3.' },
    { cat: 'interval', label: 'sowing date', for: LIFE_AGRI, why: LIFE_INT + 'Days are equal steps, but the date a calendar starts from is arbitrary.' },

    { cat: 'ratio', label: 'mass in grams', why: LIFE_RAT + '0 g is no mass at all, and 4 g is twice 2 g.' },
    { cat: 'ratio', label: 'temperature in kelvin', why: LIFE_RAT + 'Unlike °C, 0 kelvin really is no heat at all — so 300 K is twice 150 K.' },
    { cat: 'ratio', label: 'root length in mm', why: LIFE_RAT + '0 mm is no root, and 40 mm is twice 20 mm.' },
    { cat: 'ratio', label: 'number of bacterial colonies', why: LIFE_RAT + 'Zero colonies means none, and 60 is twice 30.' },
    { cat: 'ratio', label: 'volume of oxygen in cm³', why: LIFE_RAT + '0 cm³ is no gas, and 10 cm³ is twice 5 cm³.' },
    { cat: 'ratio', label: 'days to germinate', why: LIFE_RAT + '0 days is no time at all, and 8 days is twice 4.' },
    { cat: 'ratio', label: 'number of species in a quadrat', for: LIFE_ECO, why: LIFE_RAT + 'Zero species means none, and 12 species is twice 6.' },
    { cat: 'ratio', label: 'crop yield in tonnes per hectare', for: LIFE_AGRI, why: LIFE_RAT + '0 tonnes is no crop, and 8 tonnes is twice 4.' },
  ],

  // -------------------------------------------------------------------------
  // 2g. Confounds -- the same studies done badly, then properly.
  // -------------------------------------------------------------------------
  confounds: [
    { iv: 'light intensity', dv: 'rate of photosynthesis', confound: 'temperature',
      vars: ['light intensity', 'rate of photosynthesis', 'temperature', 'the type of pondweed'],
      text: 'Researchers test whether light intensity affects the rate of photosynthesis in the same type of pondweed. For bright light, the old hot lamp is placed right next to the beaker; for dim light, it is put across the room.',
      why: 'The lamp heats the water nearest to it, so the pondweed in bright light was also warmer. Any difference could come from the temperature, not the light.' },
    { iv: 'temperature', dv: 'enzyme activity', confound: 'pH',
      vars: ['temperature', 'enzyme activity', 'pH', 'the volume of enzyme'],
      text: 'Researchers test whether temperature affects amylase activity, using the same volume of enzyme in every tube. The tubes in the warm water bath are made up with a pH 7 buffer, and the tubes in the cold bath with a pH 5 buffer.',
      why: 'The warm tubes were also at a different pH, and pH changes how well an enzyme works. The difference might be the pH, not the temperature.' },
    { iv: 'salt concentration', dv: 'change in mass', confound: 'the size of the cylinders',
      vars: ['salt concentration', 'change in mass', 'the size of the cylinders', 'the time in solution'],
      text: 'Researchers leave potato cylinders in different salt solutions for the same length of time and record the change in mass. The cylinders for the strong solutions are cut twice as long as the ones for the weak solutions.',
      why: 'A bigger cylinder gains or loses more grams whatever the solution, so the change in mass could come from the size of the cylinders rather than the salt.' },
    { iv: 'amount of water', dv: 'plant growth', confound: 'light',
      vars: ['amount of water', 'plant growth', 'light', 'the type of compost'],
      text: 'Seedlings in the same compost get either plenty of water or very little. The well-watered pots sit on a sunny windowsill and the dry pots in a dim corner of the lab.',
      why: 'The well-watered seedlings also got more light, which makes plants grow. The difference could come from the light, not the water.' },
    { iv: 'temperature', dv: 'germination', confound: 'the age of the seed',
      vars: ['temperature', 'germination', 'the age of the seed', 'the amount of water'],
      text: 'Researchers test whether temperature affects germination, giving every tray the same amount of water. The warm trays are sown with fresh seed, and the cold trays with seed from a packet opened three years ago.',
      why: 'Old seed germinates less well anyway, and the cold trays also got the old seed. The difference might be the seed\'s age, not the temperature.' },
    { iv: 'trampling', dv: 'plant cover', confound: 'shade', for: LIFE_ECO,
      vars: ['trampling', 'plant cover', 'shade', 'the size of the quadrat'],
      text: 'Researchers compare plant cover in trampled and untrampled ground, using the same size of quadrat. All the trampled quadrats are on a path under trees, and all the untrampled ones are in the open meadow.',
      why: 'The trampled quadrats were also in the shade, and shade alone reduces plant cover. The difference could come from the shade, not the trampling.' },
    { iv: 'fertiliser', dv: 'crop yield', confound: 'soil quality', for: LIFE_AGRI,
      vars: ['fertiliser', 'crop yield', 'soil quality', 'the variety of wheat'],
      text: 'Researchers sow the same variety of wheat to test a fertiliser. The fertilised plots are all on the deep soil of the valley floor, and the unfertilised plots on thin soil up the hillside.',
      why: 'The fertilised plots also had better soil, which raises yield on its own. The difference could come from the soil, not the fertiliser.' },
    { iv: 'amount of feed', dv: 'milk yield', confound: 'breed', for: LIFE_AGRI,
      vars: ['amount of feed', 'milk yield', 'breed', 'the milking time'],
      text: 'To test whether extra feed increases milk yield, a farm gives extra feed to its Holstein cows and the normal ration to its Jersey cows. All the cows are milked at the same times each day.',
      why: 'Holsteins generally give a larger volume of milk than Jerseys anyway. The difference could come from the breed, not the feed.' },
    { iv: 'antibiotic concentration', dv: 'zone of inhibition', confound: 'incubation temperature', for: LIFE_BIOMED,
      vars: ['antibiotic concentration', 'zone of inhibition', 'incubation temperature', 'the species of bacteria'],
      text: 'Researchers test whether antibiotic concentration affects the clear zone on plates of the same species of bacteria. Plates with the strong discs are incubated at 25°C, and plates with the weak discs at 37°C.',
      why: 'The bacteria grow differently at the two temperatures, which changes the size of the clear zone. The difference could come from the temperature, not the concentration.' },
    { iv: 'stocking density', dv: 'grass height', confound: 'rainfall', for: LIFE_AGRI,
      vars: ['stocking density', 'grass height', 'rainfall', 'the breed of sheep'],
      text: 'Researchers compare grass height at a low stocking density on a farm in the wet west and at a high stocking density on a farm in the dry east. Both farms keep the same breed of sheep.',
      why: 'The two farms also get very different rainfall, which changes how fast grass grows. The difference could come from the rain, not the number of sheep.' },

    { iv: 'light intensity', dv: 'rate of photosynthesis', confound: null,
      text: 'Researchers test whether light intensity affects the rate of photosynthesis in pondweed. An LED lamp that gives off little heat is used, and the beaker sits in a water bath that keeps it at 25°C at every distance.',
      why: 'The water bath holds the temperature steady, so only the light intensity differs between conditions.' },
    { iv: 'temperature', dv: 'enzyme activity', confound: null,
      text: 'Researchers test whether temperature affects amylase activity. Every tube has the same volume of enzyme, starch and pH 7 buffer, and only the temperature of the water bath changes.',
      why: 'Same enzyme, same starch, same pH — the temperature is the only difference.' },
    { iv: 'salt concentration', dv: 'change in mass', confound: null,
      text: 'Researchers cut potato cylinders of identical size from the same potato and allocate them at random to the salt solutions. All are left for the same time, and the percentage change in mass is recorded.',
      why: 'Same potato, same size, random allocation and percentage change — only the salt concentration differs.' },
    { iv: 'amount of water', dv: 'plant growth', confound: null,
      text: 'Seedlings in the same compost are randomly assigned to get plenty of water or very little. All the pots are kept side by side on the same bench under the same lights.',
      why: 'Random assignment and identical light and compost leave the water as the only difference.' },
    { iv: 'temperature', dv: 'germination', confound: null,
      text: 'Researchers take seeds from one fresh packet and share them at random between warm and cold incubators. Every tray gets the same amount of water.',
      why: 'The seeds all come from the same packet and are shared at random, so only the temperature differs.' },
    { iv: 'trampling', dv: 'plant cover', confound: null, for: LIFE_ECO,
      text: 'In an open meadow, researchers fence off some areas at random and walk a set number of times across the others each day. After a month they compare plant cover in same-sized quadrats.',
      why: 'Every area is in the same open meadow and chosen at random, so only the trampling differs.' },
    { iv: 'fertiliser', dv: 'crop yield', confound: null, for: LIFE_AGRI,
      text: 'A field of even soil is divided into 20 plots of the same wheat variety. Ten plots, chosen at random, are given fertiliser, and all 20 are harvested on the same day.',
      why: 'Same field, same variety, random allocation — the fertiliser is the only systematic difference.' },
    { iv: 'amount of feed', dv: 'milk yield', confound: null, for: LIFE_AGRI,
      text: 'To test whether extra feed increases milk yield, a farm randomly splits its Holstein herd into two groups: one gets extra feed and one the normal ration. All the cows are milked at the same times.',
      why: 'Same breed, same milking routine, random groups — only the feed differs.' },
    { iv: 'antibiotic concentration', dv: 'zone of inhibition', confound: null, for: LIFE_BIOMED,
      text: 'Researchers place discs of every antibiotic concentration on plates spread with the same bacteria. All the plates are incubated together at 25°C for the same time.',
      why: 'Same bacteria, same temperature, same time — only the concentration differs.' },
  ],

  // -------------------------------------------------------------------------
  // 2h. Within or between.
  // -------------------------------------------------------------------------
  designs: [
    { cat: 'within',
      label: 'The same sprig of pondweed is placed 10, 20 and 30 cm from a lamp in turn, and the number of oxygen bubbles it gives off at each distance is counted.',
      ivs: [LIFE_DIST_LAMP], dv: LIFE_BUBBLES,
      others: [LIFE_POND_WEED, { name: 'the beaker of water', aliases: ['beaker', 'water', 'glass', 'container'] }] },
    { cat: 'within',
      label: 'Half of each leaf is covered in foil for two days, then both halves are tested with iodine and the amount of starch in each half is compared.',
      ivs: [LIFE_COVER_FOIL], dv: LIFE_STARCH,
      others: [{ name: 'the leaves', aliases: ['leaves', 'leaf', 'plant'] }] },
    { cat: 'within',
      label: 'Each agar plate has four discs on it, soaked in four different antiseptic concentrations, and the diameter of the clear zone around each disc is measured.',
      ivs: [LIFE_ANTISEPTIC_CONC], dv: LIFE_ZONE,
      others: [{ name: 'the agar plates', aliases: ['plates', 'agar', 'petri dish', 'agar plate'] }] },
    { cat: 'within',
      label: 'A leafy shoot in a potometer has its rate of water uptake measured with a fan switched off, and then with the fan switched on.',
      ivs: [LIFE_FAN], dv: LIFE_WATER_UPTAKE,
      others: [{ name: 'the shoot', aliases: ['shoot', 'plant', 'stem', 'leafy shoot'] }, { name: 'the potometer', aliases: ['potometer', 'apparatus', 'equipment'] }] },
    { cat: 'within',
      label: 'The same pondweed is tested in water with three different amounts of added carbon dioxide, and the number of oxygen bubbles is counted in each.',
      ivs: [{ name: 'carbon dioxide concentration', aliases: ['carbon dioxide', 'co2', 'co2 concentration', 'amount of carbon dioxide', 'hydrogencarbonate', 'bicarbonate'] }],
      dv: LIFE_BUBBLES,
      others: [LIFE_POND_WEED] },
    { cat: 'within', for: LIFE_ECO,
      label: 'Leaves are collected from the sunny side and the shaded side of each of 10 beech trees, and their leaf surface area is measured.',
      ivs: [LIFE_LEAF_POSITION], dv: LIFE_LEAF_AREA,
      others: [{ name: 'the beech trees', aliases: ['trees', 'beech', 'beech trees', 'tree'] }] },
    { cat: 'within', for: LIFE_ECO,
      label: 'In each of 10 ponds, researchers net invertebrates at the edge and in the middle, and count the number of invertebrate species in each spot.',
      ivs: [{ name: 'position in the pond (edge or middle)', aliases: ['position', 'edge or middle', 'edge', 'middle', 'where in the pond', 'location', 'centre'] }],
      dv: LIFE_POND_SPECIES,
      others: [{ name: 'the ponds', aliases: ['ponds', 'pond', '10 ponds'] }, { name: 'the net', aliases: ['net', 'sweep net', 'pond net'] }] },
    { cat: 'within', for: LIFE_AGRI,
      label: 'Each cow in a herd is fed ration A for a month and then ration B for a month, and her milk yield on each ration is compared.',
      ivs: [LIFE_DIET], dv: LIFE_MILK,
      others: [{ name: 'the cows', aliases: ['cows', 'cow', 'herd', 'cattle'] }] },
    { cat: 'within', for: LIFE_AGRI,
      label: 'Every field in the trial is split in half: one half is irrigated and the other isn\'t. The grain yield of the two halves is compared.',
      ivs: [LIFE_IRRIGATION], dv: LIFE_GRAIN_YIELD,
      others: [{ name: 'the fields', aliases: ['fields', 'field', 'plots', 'land'] }] },
    { cat: 'within', for: LIFE_BIOMED,
      label: 'A sample from each yeast culture is counted under the microscope once with a stain and once without, and the two cell counts for each culture are compared.',
      ivs: [{ name: 'staining (stained or unstained)', aliases: ['stain', 'staining', 'stained or unstained', 'stained', 'unstained', 'dye', 'methylene blue'] }],
      dv: { name: 'cell count', aliases: ['cells', 'number of cells', 'count', 'cell number', 'how many cells'] },
      others: [{ name: 'the yeast cultures', aliases: ['cultures', 'yeast', 'culture', 'samples'] }, { name: 'the microscope', aliases: ['microscope'] }] },

    { cat: 'between',
      label: 'Three different sprigs of pondweed are placed 10, 20 and 30 cm from a lamp, one at each distance, and the number of oxygen bubbles from each is counted.',
      ivs: [LIFE_DIST_LAMP], dv: LIFE_BUBBLES,
      others: [{ name: 'the sprigs of pondweed', aliases: ['pondweed', 'sprigs', 'plants', 'elodea'] }] },
    { cat: 'between',
      label: 'Some leaves are covered completely in foil and other leaves are left uncovered. After two days all are tested with iodine, and the amount of starch is compared.',
      ivs: [LIFE_COVER_FOIL], dv: LIFE_STARCH,
      others: [{ name: 'the leaves', aliases: ['leaves', 'leaf', 'plant'] }] },
    { cat: 'between',
      label: 'Each agar plate has one disc on it, soaked in one of four antiseptic concentrations, and the diameter of the clear zone on each plate is measured.',
      ivs: [LIFE_ANTISEPTIC_CONC], dv: LIFE_ZONE,
      others: [{ name: 'the agar plates', aliases: ['plates', 'agar', 'petri dish', 'agar plate'] }] },
    { cat: 'between',
      label: 'Twenty leafy shoots are split at random: ten have their rate of water uptake measured with a fan on, and ten with no fan.',
      ivs: [LIFE_FAN], dv: LIFE_WATER_UPTAKE,
      others: [{ name: 'the shoots', aliases: ['shoots', 'plants', 'stems', 'leafy shoots'] }] },
    { cat: 'between',
      label: 'Cress seeds are sown in three trays, one kept at 10°C, one at 20°C and one at 30°C, and the percentage of seeds that germinate in each tray is recorded.',
      ivs: [LIFE_TEMP], dv: LIFE_GERM,
      others: [{ name: 'the trays', aliases: ['trays', 'tray', 'cress'] }] },
    { cat: 'between', for: LIFE_ECO,
      label: 'Leaves are collected from 10 beech trees growing in open parkland and 10 growing in dense woodland, and their leaf surface area is measured.',
      ivs: [{ name: 'where the tree grows (open or woodland)', aliases: ['open or woodland', 'woodland', 'parkland', 'habitat', 'where they grow', 'location', 'site'] }],
      dv: LIFE_LEAF_AREA,
      others: [{ name: 'the beech trees', aliases: ['trees', 'beech', 'beech trees', 'tree'] }] },
    { cat: 'between', for: LIFE_ECO,
      label: 'Researchers net 10 woodland ponds and 10 farmland ponds, and count the number of invertebrate species in each.',
      ivs: [{ name: 'type of pond (woodland or farmland)', aliases: ['woodland or farmland', 'woodland', 'farmland', 'type of pond', 'pond type', 'surroundings', 'habitat'] }],
      dv: LIFE_POND_SPECIES,
      others: [{ name: 'the net', aliases: ['net', 'sweep net', 'pond net'] }] },
    { cat: 'between', for: LIFE_AGRI,
      label: 'A herd is split at random into two groups: one is fed ration A and the other ration B for a month. The milk yield of the two groups is compared.',
      ivs: [LIFE_DIET], dv: LIFE_MILK,
      others: [{ name: 'the cows', aliases: ['cows', 'cow', 'herd', 'cattle'] }] },
    { cat: 'between', for: LIFE_AGRI,
      label: 'Twenty plots are allocated at random: ten are irrigated and ten aren\'t. The grain yield of the two sets of plots is compared.',
      ivs: [LIFE_IRRIGATION], dv: LIFE_GRAIN_YIELD,
      others: [{ name: 'the plots', aliases: ['plots', 'plot', 'fields', 'land'] }] },
    { cat: 'between', for: LIFE_BIOMED,
      label: 'Ten flasks of the same bacterial culture are incubated at 25°C and ten at 37°C, and the optical density of each flask is measured after a day.',
      ivs: [{ name: 'incubation temperature', aliases: ['temperature', 'incubation temperature', 'temp', '25 or 37', 'heat', 'incubator'] }],
      dv: LIFE_OD,
      others: [{ name: 'the flasks', aliases: ['flasks', 'flask', 'bottles'] }] },
  ],

  // -------------------------------------------------------------------------
  // 2f-2h. Cross-sectional, longitudinal, or both.
  // -------------------------------------------------------------------------
  crosslong: {
    single: [
      { cat: 'cross',
        label: 'On one day, researchers measure the height of oak saplings that are 1, 3 and 5 years old, and compare the three age groups.',
        ivs: [{ name: 'age group of the saplings', aliases: ['age', 'age group', 'how old they are', '1 3 or 5 years', 'years old', 'group'] }],
        dv: { name: 'sapling height', aliases: ['height', 'how tall', 'growth', 'size', 'tallness'] },
        others: [{ name: 'the day of measuring', aliases: ['day', 'one day', 'same day'] }] },
      { cat: 'cross', for: LIFE_ECO,
        label: 'In one week in June, researchers count the plant species in quadrats at 200 m, 400 m and 600 m above sea level, and compare the three altitudes.',
        ivs: [LIFE_ALTITUDE], dv: LIFE_SPECIES_RICH,
        others: [{ name: 'the week of sampling', aliases: ['june', 'week', 'same week'] }, { name: 'the quadrats', aliases: ['quadrats', 'quadrat'] }] },
      { cat: 'cross', for: LIFE_AGRI,
        label: 'At a single harvest, researchers weigh the grain from fields of three different wheat varieties and compare the yields.',
        ivs: [{ name: 'wheat variety', aliases: ['variety', 'wheat variety', 'type of wheat', 'cultivar', 'strain', 'kind of wheat'] }],
        dv: LIFE_GRAIN_YIELD,
        others: [{ name: 'the day of harvest', aliases: ['harvest', 'single harvest', 'harvest day', 'day'] }] },
      { cat: 'cross', for: LIFE_BIOMED,
        label: 'After one 24-hour incubation, researchers measure the optical density of cultures of three different species of bacteria and compare them.',
        ivs: [{ name: 'species of bacteria', aliases: ['species', 'bacteria', 'type of bacteria', 'bacterial species', 'strain', 'organism'] }],
        dv: LIFE_OD,
        others: [{ name: 'the incubation', aliases: ['incubation', '24 hours', 'incubator'] }] },
      { cat: 'cross',
        label: 'On one afternoon, researchers count the stomata on leaves from five different plant species and compare the species.',
        ivs: [{ name: 'plant species', aliases: ['species', 'plant species', 'type of plant', 'kind of plant', 'plant'] }],
        dv: { name: 'number of stomata', aliases: ['stomata', 'number of stomata', 'stomatal count', 'pores', 'how many stomata'] },
        others: [{ name: 'the afternoon', aliases: ['afternoon', 'one afternoon'] }] },

      { cat: 'long',
        label: 'Researchers measure the height of the same 30 bean seedlings every week for eight weeks.',
        ivs: [{ name: 'time (week of measuring)', aliases: ['eight weeks', 'every week', 'age', ...LIFE_TIME_WORDS] }],
        dv: LIFE_PLANT_HEIGHT,
        others: [{ name: 'the seedlings', aliases: ['seedlings', 'beans', 'bean plants', 'plants'] }] },
      { cat: 'long', for: LIFE_ECO,
        label: 'Researchers record the number of plant species in the same meadow every summer for ten years.',
        ivs: [{ name: 'time (year of the survey)', aliases: ['summer', 'every summer', 'ten years', ...LIFE_TIME_WORDS] }],
        dv: LIFE_SPECIES_RICH,
        others: [{ name: 'the meadow', aliases: ['meadow', 'field', 'site'] }] },
      { cat: 'long', for: LIFE_AGRI,
        label: 'A farm records the milk yield of the same 40 cows every month, from calving until the end of lactation.',
        ivs: [{ name: 'time since calving', aliases: ['time since calving', 'calving', 'stage of lactation', 'lactation', 'every month', ...LIFE_TIME_WORDS] }],
        dv: LIFE_MILK,
        others: [{ name: 'the cows', aliases: ['cows', 'cow', 'herd', 'cattle'] }] },
      { cat: 'long', for: LIFE_BIOMED,
        label: 'Researchers measure the optical density of one bacterial culture every hour for twelve hours.',
        ivs: [{ name: 'time (hour of measuring)', aliases: ['hour', 'hours', 'every hour', 'twelve hours', 'incubation time', ...LIFE_TIME_WORDS] }],
        dv: LIFE_OD,
        others: [{ name: 'the culture', aliases: ['culture', 'flask', 'sample'] }] },
      { cat: 'long',
        label: 'The algal cover of one garden pond is estimated on the first day of every month for a year.',
        ivs: [{ name: 'time (month of the year)', aliases: ['month of the year', 'season', 'every month', ...LIFE_TIME_WORDS] }],
        dv: { name: 'algal cover', aliases: ['algae', 'algal cover', 'amount of algae', 'cover', 'how much algae', 'algal growth'] },
        others: [{ name: 'the pond', aliases: ['pond', 'garden pond', 'water'] }] },
    ],

    multi: [
      { cat: 'cross', for: LIFE_ECO,
        label: 'In one week, researchers count plant species in quadrats on grazed and ungrazed land at two altitudes, and compare all four groups.',
        ivs: [LIFE_GRAZING, { name: 'altitude', aliases: ['altitude', 'height above sea level', 'elevation', 'how high', 'two altitudes', 'metres'] }],
        dv: LIFE_SPECIES_RICH,
        others: [{ name: 'the week of sampling', aliases: ['week', 'same week', 'one week'] }] },
      { cat: 'cross', for: LIFE_AGRI,
        label: 'At a single harvest, researchers weigh the grain from fertilised and unfertilised plots of three wheat varieties.',
        ivs: [LIFE_FERT, { name: 'wheat variety', aliases: ['variety', 'wheat variety', 'type of wheat', 'cultivar', 'kind of wheat', 'three varieties'] }],
        dv: LIFE_GRAIN_YIELD,
        others: [{ name: 'the day of harvest', aliases: ['harvest', 'single harvest', 'harvest day', 'day'] }] },
      { cat: 'cross',
        label: 'On one day, researchers measure the surface area of leaves from the sunny and shaded sides of oak and beech trees.',
        ivs: [LIFE_LEAF_POSITION, { name: 'tree species (oak or beech)', aliases: ['species', 'tree species', 'oak or beech', 'oak', 'beech', 'type of tree', 'kind of tree'] }],
        dv: LIFE_LEAF_AREA,
        others: [{ name: 'the day of sampling', aliases: ['day', 'one day', 'same day'] }] },
      { cat: 'cross', for: LIFE_BIOMED,
        label: 'In one incubation run, plates of two species of bacteria are grown with discs of three antiseptic concentrations, and the clear zones are measured.',
        ivs: [{ name: 'species of bacteria', aliases: ['species', 'bacteria', 'type of bacteria', 'bacterial species', 'strain', 'organism'] }, LIFE_ANTISEPTIC_CONC],
        dv: LIFE_ZONE,
        others: [{ name: 'the incubation run', aliases: ['incubation', 'run', 'incubator'] }] },

      { cat: 'long',
        label: 'The same 20 bean plants have the length of one leaf on the sunny side and one on the shaded side measured every week for six weeks.',
        ivs: [{ name: 'time (week of measuring)', aliases: ['six weeks', 'every week', 'age', ...LIFE_TIME_WORDS] }, { name: 'side of the plant (sunny or shaded)', aliases: ['side', 'sunny or shaded', 'sunny', 'shaded', 'sun or shade', 'shade', 'light exposure'] }],
        dv: { name: 'leaf length', aliases: ['length', 'leaf size', 'how long the leaf is', 'leaf growth', 'size', 'growth'] },
        others: [{ name: 'the bean plants', aliases: ['plants', 'beans', 'bean plants', 'plant'] }] },
      { cat: 'long', for: LIFE_AGRI,
        label: 'A farm records the milk yield of the same herd at both the morning and the evening milking, every month for a year.',
        ivs: [{ name: 'time (month of the year)', aliases: ['every month', 'a year', 'season', 'stage of lactation', ...LIFE_TIME_WORDS] }, { name: 'milking (morning or evening)', aliases: ['milking', 'morning or evening', 'morning', 'evening', 'time of day', 'which milking'] }],
        dv: LIFE_MILK,
        others: [{ name: 'the herd', aliases: ['herd', 'cows', 'cattle', 'cow'] }] },
      { cat: 'long', for: LIFE_ECO,
        label: 'The same meadow is surveyed every summer for eight years, in quadrats near the footpath and far from it, and the plant species in each are counted.',
        ivs: [{ name: 'time (year of the survey)', aliases: ['every summer', 'eight years', 'summer', ...LIFE_TIME_WORDS] }, { name: 'distance from the footpath (near or far)', aliases: ['distance', 'distance from footpath', 'near or far', 'near', 'far', 'footpath', 'path', 'trampling'] }],
        dv: LIFE_SPECIES_RICH,
        others: [{ name: 'the meadow', aliases: ['meadow', 'field', 'site'] }] },
      { cat: 'long', for: LIFE_BIOMED,
        label: 'Samples from one yeast culture are counted every two hours for a day, both by hand with a haemocytometer and with an automatic counter, and the counts are compared.',
        ivs: [{ name: 'time (hour of sampling)', aliases: ['hour', 'hours', 'every two hours', 'incubation time', ...LIFE_TIME_WORDS] }, { name: 'counting method (by hand or automatic)', aliases: ['method', 'counting method', 'haemocytometer', 'hemocytometer', 'by hand', 'automatic', 'machine', 'hand or automatic'] }],
        dv: { name: 'cell count', aliases: ['cells', 'number of cells', 'count', 'cell number', 'how many cells'] },
        others: [{ name: 'the yeast culture', aliases: ['culture', 'yeast', 'flask'] }] },
    ],

    panel: [
      { cat: 'both',
        label: 'Bean seedlings are split into a fertilised group and an unfertilised group, and the height of every seedling is measured each week for eight weeks.',
        ivs: [LIFE_FERT, { name: 'time (week of measuring)', aliases: ['eight weeks', 'every week', 'age', ...LIFE_TIME_WORDS] }],
        dv: LIFE_PLANT_HEIGHT,
        others: [] },
      { cat: 'both',
        label: 'Cress seeds are kept at 10°C, 20°C and 30°C, and the number that have germinated in each group is counted every day for ten days.',
        ivs: [LIFE_TEMP, { name: 'time (day of counting)', aliases: ['every day', 'ten days', ...LIFE_TIME_WORDS] }],
        dv: { name: 'number of seeds germinated', aliases: ['germination', 'seeds germinated', 'how many germinate', 'germination rate', 'number germinated', 'sprouting'] },
        others: [] },
      { cat: 'both', for: LIFE_ECO,
        label: 'Researchers follow grazed and ungrazed plots of the same hillside, counting the plant species in each every summer for five years.',
        ivs: [LIFE_GRAZING, { name: 'time (year of the survey)', aliases: ['every summer', 'five years', 'summer', ...LIFE_TIME_WORDS] }],
        dv: LIFE_SPECIES_RICH,
        others: [] },
      { cat: 'both', for: LIFE_AGRI,
        label: 'Two groups of cows, one on ration A and one on ration B, have their milk yield recorded every month for a year.',
        ivs: [LIFE_DIET, { name: 'time (month of recording)', aliases: ['every month', 'a year', 'stage of lactation', ...LIFE_TIME_WORDS] }],
        dv: LIFE_MILK,
        others: [] },
      { cat: 'both', for: LIFE_BIOMED,
        label: 'Flasks of the same bacterial culture are incubated at 25°C and at 37°C, and the optical density of each flask is measured every hour for ten hours.',
        ivs: [{ name: 'incubation temperature', aliases: ['temperature', 'incubation temperature', 'temp', '25 or 37', 'heat', 'incubator'] }, { name: 'time (hour of measuring)', aliases: ['hour', 'hours', 'every hour', 'ten hours', 'incubation time', ...LIFE_TIME_WORDS] }],
        dv: LIFE_OD,
        others: [] },
      { cat: 'both',
        label: 'Tanks of pond water are given low, medium or high amounts of nitrate, and the algal cover in each tank is estimated every week for two months.',
        ivs: [{ name: 'nitrate level', aliases: ['nitrate', 'nitrate level', 'low medium or high', 'nutrients', 'amount of nitrate', 'fertiliser'] }, { name: 'time (week of measuring)', aliases: ['every week', 'two months', ...LIFE_TIME_WORDS] }],
        dv: { name: 'algal cover', aliases: ['algae', 'algal cover', 'amount of algae', 'cover', 'how much algae', 'algal growth'] },
        others: [] },
    ],
  },

  // -------------------------------------------------------------------------
  // Level 3. Factors for the box notation.
  // -------------------------------------------------------------------------
  factors: [
    { name: 'Temperature', levels: { 2: ['15°C', '30°C'], 3: ['10°C', '20°C', '30°C'], 4: ['10°C', '20°C', '30°C', '40°C'] } },
    { name: 'Light intensity', levels: { 2: ['low', 'high'], 3: ['low', 'medium', 'high'] } },
    { name: 'pH', levels: { 2: ['pH 5', 'pH 8'], 3: ['pH 4', 'pH 7', 'pH 10'], 4: ['pH 4', 'pH 6', 'pH 8', 'pH 10'] } },
    { name: 'Salt concentration', levels: { 2: ['0 M', '0.5 M'], 3: ['0 M', '0.4 M', '0.8 M'], 4: ['0 M', '0.2 M', '0.4 M', '0.8 M'] } },
    { name: 'Light colour', levels: { 2: ['red', 'blue'], 3: ['red', 'blue', 'green'] } },
    { name: 'Watering', levels: { 2: ['dry', 'watered'], 3: ['low', 'medium', 'high'] } },
    { name: 'Soil type', levels: { 2: ['clay', 'sand'], 3: ['clay', 'sand', 'loam'] } },
    { name: 'Week', levels: { 3: ['week 1', 'week 2', 'week 3'], 4: ['week 1', 'week 2', 'week 3', 'week 4'] } },
    { name: 'Altitude', for: LIFE_ECO, levels: { 2: ['200 m', '600 m'], 3: ['200 m', '400 m', '600 m'], 4: ['200 m', '400 m', '600 m', '800 m'] } },
    { name: 'Grazing', for: LIFE_ECO, levels: { 2: ['grazed', 'ungrazed'] } },
    { name: 'Fertiliser', for: LIFE_AGRI, levels: { 2: ['none', 'fertiliser'], 3: ['none', 'low dose', 'high dose'] } },
    { name: 'Crop', for: LIFE_AGRI, levels: { 2: ['wheat', 'barley'], 3: ['wheat', 'barley', 'oats'], 4: ['wheat', 'barley', 'oats', 'maize'] } },
    { name: 'Species', for: LIFE_BIOMED, levels: { 2: ['E. coli', 'B. subtilis'], 3: ['E. coli', 'B. subtilis', 'M. luteus'] } },
    { name: 'Antiseptic', for: LIFE_BIOMED, levels: { 2: ['none', 'antiseptic'], 3: ['0%', '1%', '5%'], 4: ['0%', '1%', '2%', '5%'] } },
  ],
};
