// ---------------------------------------------------------------------------
// Mind & behaviour pool: memory, attention, perception, learning and practice,
// motivation in lab tasks, fatigue and vigilance, mood after pleasant tasks.
// The main pool for psychology and neuroscience; a secondary one for
// linguistics, education, business, media and computer science.
// Studies are done on human participants. See pools/README.md for the rules.
// ---------------------------------------------------------------------------

const MIND_CONT = 'It can take any value on a scale, including every value in between — ';
const MIND_DISC = 'It only comes in separate values, with nothing in between — ';

const MIND_NOM = 'Categorical: distinct outcomes with no order. ';
const MIND_ORD = 'Ordinal: the outcomes are ranked, but the difference between steps is arbitrary. ';
const MIND_INT = 'Interval: ranked, with a constant difference between steps, but no natural zero — so values aren\'t "twice as much". ';
const MIND_RAT = 'Ratio: ranked, constant steps AND a natural zero, so "twice as much" makes sense. ';

const MIND_TIME = ['time', 'over time', 'week', 'weeks', 'month', 'months', 'year', 'years', 'day', 'days', 'when it was measured', 'time point', 'session', 'before and after', 'when they are tested', 'testing time'];

const MIND_P = { name: 'the participants', aliases: ['participants', 'people', 'subjects', 'person'] };
const MIND_RT = { name: 'reaction time', aliases: ['reaction time', 'response time', 'rt', 'how fast they respond', 'how quickly they respond', 'speed', 'reaction', 'reactions', 'how fast'] };
const MIND_RECALL = { name: 'number of words recalled', aliases: ['recall', 'words recalled', 'number of words', 'how many words', 'memory', 'remember', 'words remembered', 'score'] };
const MIND_STROOP = { name: 'Stroop condition (matching or clashing)', aliases: ['stroop', 'condition', 'matching or clashing', 'matching', 'clashing', 'congruent', 'incongruent', 'congruency', 'colour word', 'word colour'] };
const MIND_NAMING = { name: 'colour-naming time', aliases: ['naming time', 'naming', 'time to name', 'how long they take', 'how quickly they name', 'speed', 'naming speed', 'response time'] };
const MIND_DUAL = { name: 'task load (one task or two)', aliases: ['dual task', 'single task', 'one task or two', 'second task', 'counting', 'counting backwards', 'load', 'task load', 'multitasking', 'number of tasks'] };
const MIND_TRACK_ERR = { name: 'tracking errors', aliases: ['errors', 'mistakes', 'number of errors', 'tracking', 'tracking errors', 'accuracy', 'performance'] };
const MIND_WORDLEN = { name: 'word length (short or long)', aliases: ['word length', 'length', 'short or long', 'short', 'long', 'short words', 'long words', 'syllables', 'number of syllables'] };
const MIND_CONTRAST = { name: 'contrast (faint or strong)', aliases: ['contrast', 'faint or strong', 'faint', 'strong', 'low contrast', 'high contrast', 'visibility', 'brightness'] };
const MIND_DETECT = { name: 'percentage of dots detected', aliases: ['detection', 'dots detected', 'detected', 'how many they see', 'hits', 'percentage detected', 'accuracy', 'seeing the dots'] };
const MIND_LOUD = { name: 'tone loudness (quiet or loud)', aliases: ['loudness', 'volume', 'quiet or loud', 'quiet', 'loud', 'intensity', 'tone volume', 'sound level'] };
const MIND_CLIP = { name: 'type of clip (amusing or neutral)', aliases: ['clip', 'video', 'amusing or neutral', 'amusing', 'neutral', 'funny', 'type of clip', 'film', 'type of video'] };
const MIND_MOOD = { name: 'mood rating', aliases: ['mood', 'mood rating', 'rating', 'how they feel', 'happiness', 'feelings', 'emotion'] };
const MIND_SLEEP = { name: 'sleep (sleep or stay awake)', aliases: ['sleep', 'sleeping', 'awake', 'sleep or stay awake', 'staying awake', 'night', 'rest', 'sleep or wake'] };
const MIND_PICS = { name: 'number of picture locations recalled', aliases: ['recall', 'memory', 'locations', 'picture locations', 'how many they remember', 'remember', 'locations recalled', 'score'] };
const MIND_REWARD = { name: 'reward (points or no points)', aliases: ['reward', 'points', 'rewarded', 'no reward', 'points or no points', 'incentive', 'motivation', 'prize'] };

POOLS.mind = {
  // -------------------------------------------------------------------------
  // 1a. Variable or not?
  // -------------------------------------------------------------------------
  sortItems: [
    // --- variables ---
    { label: 'reaction time', variable: true,
      why: 'People respond faster on some attempts than others, and the time can be measured in milliseconds.' },
    { label: 'number of words recalled', variable: true,
      why: 'Different people, and different lists, give different numbers of words remembered — and they can be counted.' },
    { label: 'digit span', variable: true,
      why: 'Some people can repeat back longer strings of digits than others. The longest string repeated correctly is measured.' },
    { label: 'Stroop interference', variable: true,
      why: 'The extra time it takes to name an ink colour when the word spells a different colour differs from person to person, and it is measured in milliseconds.' },
    { label: 'detection threshold', variable: true, for: ['neuroscience'],
      why: 'The faintest light or quietest sound a person can detect differs between people and between conditions, and it can be measured.' },
    { label: 'percentage of correct responses', variable: true,
      why: 'Some people, and some tasks, give more correct answers than others. The percentage can be worked out and compared.' },
    { label: 'number of errors', variable: true,
      why: 'Different attempts produce different numbers of errors, and errors can be counted.' },
    { label: 'hours of sleep', variable: true,
      why: 'People sleep for different lengths of time, and it can be measured in hours.' },
    { label: 'time on task', variable: true,
      why: 'Someone can have been doing a task for five minutes or two hours. It is measured in minutes.' },
    { label: 'background noise level', variable: true,
      why: 'Some rooms are louder than others, and noise is measured in decibels.' },
    { label: 'contrast of an image', variable: true, for: ['neuroscience'],
      why: 'An image can be faint or strong against its background, and contrast can be set and measured as a percentage.' },
    { label: 'list length', variable: true,
      why: 'A memory list can have 5 words or 30. The number of items can be counted and changed.' },
    { label: 'mood rating', variable: true,
      why: 'People rate how they feel on a scale, and the rating changes from one moment to the next.' },
    { label: 'alertness rating', variable: true,
      why: 'People feel more or less alert at different times, and can rate it on a scale.' },
    { label: 'pupil size', variable: true, for: ['neuroscience'],
      why: 'The pupil gets wider and narrower, and its diameter can be measured in millimetres.' },
    { label: 'number of practice trials', variable: true,
      why: 'Someone can practise a task 5 times or 500 times, and the trials can be counted.' },
    { label: 'typing speed', variable: true,
      why: 'People type at different speeds, measured in words per minute.' },
    { label: 'reward per correct answer', variable: true,
      why: 'A task can give no points, 1 point or 10 points for each correct answer, so the reward takes different values.' },
    { label: 'confidence rating', variable: true,
      why: 'People are more sure of some answers than others, and can rate their confidence on a scale.' },
    { label: 'number of distractors on screen', variable: true,
      why: 'A search display can have 4 other shapes or 40. They can be counted, and the researcher can change the number.' },
    { label: 'visual search time', variable: true,
      why: 'Finding a target takes longer on some displays than others, and the time is measured in milliseconds.' },
    { label: 'loudness of a tone', variable: true, for: ['neuroscience'],
      why: 'A tone can be played quietly or loudly, and its loudness is measured in decibels.' },
    { label: 'word familiarity', variable: true,
      why: 'Some words are very familiar and some are rarely met. Familiarity can be rated or counted from how often words appear.' },
    { label: 'time since learning', variable: true,
      why: 'A memory test can come 10 minutes after learning or a week after. The delay is measured.' },
    { label: 'number of targets missed', variable: true,
      why: 'In a watch-keeping task some people miss more signals than others, and misses can be counted.' },
    { label: 'size of a brain response (EEG)', variable: true, for: ['neuroscience'],
      why: 'The electrical response recorded from the scalp is bigger on some trials than others. It is measured in microvolts.' },

    // --- not variables: one particular thing ---
    { label: 'the Stroop task', variable: false,
      why: 'The Stroop task is one particular task — a thing, not a measurement. (How long people take to name the colours would be a variable.)' },
    { label: 'the Müller-Lyer illusion', variable: false,
      why: 'It\'s one particular illusion. (How much people misjudge the length of the lines would be a variable.)' },
    { label: 'Pavlov\'s dog', variable: false,
      why: 'It\'s one particular dog. (How much a dog salivates when it hears a bell would be a variable.)' },
    { label: 'Hermann Ebbinghaus', variable: false,
      why: 'Ebbinghaus is one particular person. (How many syllables someone remembers after a delay would be a variable.)' },
    { label: 'the hippocampus', variable: false, for: ['neuroscience'],
      why: 'The hippocampus is one particular part of the brain. (Its size, or how active it is during a task, would be a variable.)' },
    { label: 'the visual cortex', variable: false, for: ['neuroscience'],
      why: 'It\'s one particular brain area. (How strongly it responds to a pattern would be a variable.)' },
    { label: 'the university\'s psychology lab', variable: false,
      why: 'It\'s one particular room. (How noisy the room is, or how many people are tested in it, would be a variable.)' },
    { label: 'the questionnaire', variable: false,
      why: 'A questionnaire is one particular thing. (The score someone gets on it would be a variable.)' },
    { label: 'the word "banana"', variable: false,
      why: 'It\'s one particular word. (Word length, or how quickly people read a word, would be a variable.)' },
    { label: 'the space bar', variable: false,
      why: 'The space bar is one particular key. (How quickly someone presses it would be a variable.)' },
    { label: 'the colour red', variable: false,
      why: 'Red is one particular colour. (How bright a light is, or how quickly people name a colour, would be a variable.)' },
    { label: 'the consent form', variable: false,
      why: 'It\'s one particular document. (How long participants take to read it would be a variable.)' },

    // --- not variables: measurable, but only one possible value ---
    { label: 'the number of milliseconds in a second', variable: false,
      why: 'It\'s always 1,000. Something that can only ever have one value is a constant, not a variable.' },
    { label: 'the number of letters in the word "memory"', variable: false,
      why: 'It\'s always 6 — only one possible value, so it\'s a constant, not a variable.' },
    { label: 'the number of hours in a day', variable: false,
      why: 'It\'s always 24. It can be measured, but it doesn\'t vary.' },
  ],

  // -------------------------------------------------------------------------
  // 1b-1d, 2b, 2c. Relations.
  // -------------------------------------------------------------------------
  relations: [
    { id: 'mind-listlen-recall', iv: 'list length', dv: 'percentage recalled',
      ivNP: 'the length of the list', dvNP: 'the percentage of words recalled',
      hyp: ['list length', 'percentage recalled'], ivAxis: 'List length', dvAxis: '% recalled', dir: 'down',
      says: ['The longer a list of words is, the smaller the percentage of it people can recall.',
             'The percentage of words recalled goes down as the list gets longer.'],
      why: 'The researcher decides how long the list is before anyone learns it; the recall is the result. Remembering less can\'t make a list longer.' },
    { id: 'mind-delay-forget', iv: 'delay before the test', dv: 'items remembered',
      ivNP: 'the delay before the test', dvNP: 'the number of items remembered',
      hyp: ['delay', 'items remembered'], ivAxis: 'Delay', dvAxis: 'Items recalled', dir: 'down',
      says: ['The longer the gap between learning a list and being tested on it, the fewer items people remember.',
             'People remember fewer items the longer the delay before the memory test.'],
      why: 'The delay is set before the test and it is time passing that does the forgetting. Remembering less can\'t make the delay longer.' },
    { id: 'mind-rehearsal-recall', iv: 'number of rehearsals', dv: 'chance of recall',
      ivNP: 'the number of times a word is rehearsed', dvNP: 'the chance of recalling it',
      hyp: ['rehearsals', 'recall'], ivAxis: 'Rehearsals', dvAxis: 'Recall', dir: 'up',
      says: ['The more times people repeat a word to themselves while learning, the more likely they are to recall it.',
             'The chance of recalling a word goes up with the number of times it was rehearsed.'],
      why: 'The rehearsing happens during learning and the test comes later, so rehearsal is the changer. Recalling a word at the test can\'t go back and add rehearsals.' },
    { id: 'mind-practice-rt', iv: 'amount of practice', dv: 'reaction time',
      ivNP: 'the amount of practice', dvNP: 'the reaction time',
      hyp: ['practice', 'reaction time'], ivAxis: 'Practice', dvAxis: 'Reaction time', dir: 'down',
      says: ['The more people practise a reaction task, the faster they respond — their reaction times get shorter.',
             'Reaction times get shorter with more practice.'],
      why: 'The practice comes first and builds the speed. Careful with the graph: responding faster means the reaction TIME goes down.' },
    { id: 'mind-practice-mirror', iv: 'days of practice', dv: 'number of errors',
      ivNP: 'the number of days of practice', dvNP: 'the number of errors',
      hyp: ['practice', 'errors'], ivAxis: 'Days of practice', dvAxis: 'Errors', dir: 'down',
      says: ['The more days people practise tracing a star while watching their hand in a mirror, the fewer errors they make.',
             'Errors in mirror drawing go down with each day of practice.'],
      why: 'The days of practice come first and the errors are counted after. Making fewer errors can\'t add days of practice.' },
    { id: 'mind-dual-errors', iv: 'second-task difficulty', dv: 'number of errors',
      ivNP: 'the difficulty of a second task', dvNP: 'the number of errors on the main task',
      hyp: ['second task', 'errors'], ivAxis: 'Second task', dvAxis: 'Errors', dir: 'up',
      says: ['The harder the second task people must do at the same time, the more errors they make on the main task.',
             'Errors on the main task go up as the second task gets harder.'],
      why: 'The researcher chooses how hard the second task is; the errors are how people cope with it. Making errors can\'t make the other task harder.' },
    { id: 'mind-setsize-search', iv: 'number of distractors', dv: 'search time',
      ivNP: 'the number of distractors', dvNP: 'the search time',
      hyp: ['distractors', 'search time'], ivAxis: 'Distractors', dvAxis: 'Search time', dir: 'up',
      says: ['Finding a target letter takes longer when it is hidden among more other letters.',
             'Search time goes up as the number of distractor letters goes up.'],
      why: 'The display is made before anyone searches it, so the number of distractors is the changer. Searching slowly can\'t put more letters on the screen.' },
    { id: 'mind-contrast-detect', for: ['neuroscience'], iv: 'contrast', dv: 'percentage detected',
      ivNP: 'the contrast of the target', dvNP: 'the percentage of targets detected',
      hyp: ['contrast', 'detection'], ivAxis: 'Contrast', dvAxis: '% detected', dir: 'up',
      says: ['The higher the contrast of a faint pattern, the more often people detect it.',
             'The percentage of targets detected goes up as their contrast goes up.'],
      why: 'The contrast is set on the screen before the person looks; detecting it is the response. Seeing a pattern can\'t change its contrast.' },
    { id: 'mind-loudness-rt', for: ['neuroscience'], iv: 'tone loudness', dv: 'reaction time',
      ivNP: 'the loudness of the tone', dvNP: 'the reaction time',
      hyp: ['loudness', 'reaction time'], ivAxis: 'Loudness', dvAxis: 'Reaction time', dir: 'down',
      says: ['People respond faster to louder tones — their reaction times are shorter.',
             'Reaction time goes down as the tone gets louder.'],
      why: 'The tone is played first and the response comes after, so loudness is the changer. Careful with the graph: a faster response is a SHORTER reaction time.' },
    { id: 'mind-vigilance', iv: 'time on task', dv: 'signals detected',
      ivNP: 'the time spent on the task', dvNP: 'the number of signals detected',
      hyp: ['time on task', 'signals detected'], ivAxis: 'Time on task', dvAxis: 'Signals found', dir: 'down',
      says: ['The longer people spend watching a screen for rare signals, the fewer of the signals they spot.',
             'The number of signals detected drops as time on the task goes on.'],
      why: 'Time on the task keeps passing whatever the person does, and it is the long watch that wears attention down. Missing signals can\'t make time pass.' },
    { id: 'mind-awake-rt', for: ['neuroscience', 'psychology'], iv: 'hours awake', dv: 'reaction time',
      ivNP: 'the number of hours awake', dvNP: 'the reaction time',
      hyp: ['hours awake', 'reaction time'], ivAxis: 'Hours awake', dvAxis: 'Reaction time', dir: 'up',
      says: ['The longer people have been awake without sleep, the slower their reactions.',
             'Reaction times get longer the more hours someone has been awake.'],
      why: 'The hours awake build up before the test; the slow reactions are the result. Reacting slowly can\'t keep someone awake for longer.' },
    { id: 'mind-feedback-acc', iv: 'amount of feedback', dv: 'accuracy after training',
      ivNP: 'the amount of feedback', dvNP: 'accuracy at the end of training',
      hyp: ['feedback', 'accuracy'], ivAxis: 'Feedback', dvAxis: 'Accuracy', dir: 'up',
      says: ['The more often people are told whether their answer was right while learning a new sorting task, the more accurate they are by the end of the session.',
             'Accuracy at the end of training goes up with how often people get feedback.'],
      why: 'The researcher decides how much feedback to give during training, and accuracy is measured at the end. Being accurate at the end can\'t change the feedback already given.' },
    { id: 'mind-reward-rt', iv: 'reward per response', dv: 'reaction time',
      ivNP: 'the reward for each fast response', dvNP: 'the reaction time',
      hyp: ['reward', 'reaction time'], ivAxis: 'Reward', dvAxis: 'Reaction time', dir: 'down',
      says: ['The more points people can win for each fast, correct response, the faster they respond.',
             'Reaction times get shorter as the reward for each response goes up.'],
      why: 'The reward is announced before the trial, so it is the changer. Careful with the graph: responding faster means the reaction TIME goes down.' },
    { id: 'mind-wordlen-span', iv: 'word length', dv: 'words recalled in order',
      ivNP: 'the length of the words', dvNP: 'the number of words recalled in order',
      hyp: ['word length', 'recall'], ivAxis: 'Word length', dvAxis: 'Words recalled', dir: 'down',
      says: ['People can recall fewer words in the right order when the words are long than when they are short.',
             'The number of words recalled in order drops as the words get longer.'],
      why: 'How long the words are is fixed before the list is heard; the recall is the result. Forgetting words can\'t make them longer.' },
    { id: 'mind-familiar-recall', iv: 'word familiarity', dv: 'words recalled',
      ivNP: 'how familiar the words are', dvNP: 'the number of words recalled',
      hyp: ['familiarity', 'words recalled'], ivAxis: 'Familiarity', dvAxis: 'Words recalled', dir: 'up',
      says: ['Lists made of familiar words are recalled better than lists made of unfamiliar words.',
             'The number of words recalled goes up with how familiar the words in the list are.'],
      why: 'How familiar a word is was settled long before the experiment, so familiarity is the changer. Recalling a word once can\'t make it more familiar in the language.' },
    { id: 'mind-studytime-recall', iv: 'study time per word', dv: 'words recalled',
      ivNP: 'the time each word is shown', dvNP: 'the number of words recalled',
      hyp: ['study time', 'words recalled'], ivAxis: 'Study time', dvAxis: 'Words recalled', dir: 'up',
      says: ['The longer each word is shown on screen during learning, the more words people recall.',
             'The number of words recalled goes up with the time each word is shown.'],
      why: 'The researcher sets how long each word stays on screen, and recall is tested afterwards. Remembering a word can\'t change how long it was shown.' },
    { id: 'mind-load-rt', iv: 'memory set size', dv: 'reaction time',
      ivNP: 'the number of items held in memory', dvNP: 'the reaction time',
      hyp: ['memory set size', 'reaction time'], ivAxis: 'Items held', dvAxis: 'Reaction time', dir: 'up',
      says: ['The more digits people are holding in memory, the longer it takes them to say whether a new digit was one of them.',
             'Reaction time goes up as the number of digits held in memory goes up.'],
      why: 'The researcher decides how many digits to give; the reaction time is the result. Answering slowly can\'t change how many digits you were given.' },
    { id: 'mind-load-pupil', for: ['neuroscience'], iv: 'memory load', dv: 'pupil size',
      ivNP: 'the memory load', dvNP: 'the size of the pupil',
      hyp: ['memory load', 'pupil size'], ivAxis: 'Memory load', dvAxis: 'Pupil size', dir: 'up',
      says: ['The more digits people are trying to hold in mind, the wider their pupils get.',
             'Pupil size goes up as the number of digits held in mind goes up.'],
      why: 'The number of digits is set by the task, and the pupil responds to the mental effort. A wider pupil can\'t give someone more digits to remember.' },
    { id: 'mind-light-pupil', for: ['neuroscience'], iv: 'light level', dv: 'pupil size',
      ivNP: 'the brightness of the light', dvNP: 'the size of the pupil',
      hyp: ['brightness', 'pupil size'], ivAxis: 'Brightness', dvAxis: 'Pupil size', dir: 'down',
      says: ['The brighter the light shone into the eye, the smaller the pupil becomes.',
             'Pupil size goes down as the light gets brighter.'],
      why: 'The light is shone first and the pupil reacts to it. A pupil getting smaller can\'t make a lamp brighter.' },
    { id: 'mind-interference', iv: 'lists learned in between', dv: 'first-list recall',
      ivNP: 'the number of lists learned in between', dvNP: 'recall of the first list',
      hyp: ['lists in between', 'first-list recall'], ivAxis: 'Lists between', dvAxis: 'First list', dir: 'down',
      says: ['The more similar lists people learn after the first one, the less of the first list they remember.',
             'Recall of the first list goes down as more lists are learned in between.'],
      why: 'The extra lists are learned before the test and get in the way of the first one. Forgetting the first list can\'t make people learn more lists.' },
    { id: 'mind-testing-effect', iv: 'number of practice tests', dv: 'recall a week later',
      ivNP: 'the number of practice tests', dvNP: 'recall a week later',
      hyp: ['practice tests', 'later recall'], ivAxis: 'Practice tests', dvAxis: 'Later recall', dir: 'up',
      says: ['The more times people test themselves on some facts, the more of them they recall a week later.',
             'Recall a week later goes up with the number of practice tests taken.'],
      why: 'The practice tests happen during learning and the final test a week after, so the practice tests are the changer. The later recall can\'t go back in time.' },
    { id: 'mind-sleep-locations', for: ['neuroscience'], iv: 'hours of sleep', dv: 'locations recalled',
      ivNP: 'the amount of sleep after learning', dvNP: 'the number of picture locations recalled',
      hyp: ['sleep', 'locations recalled'], ivAxis: 'Sleep', dvAxis: 'Locations', dir: 'up',
      says: ['People who sleep longer on the night after learning where pictures were placed recall more of the locations the next day.',
             'The number of picture locations recalled the next day goes up with the hours slept after learning.'],
      why: 'The sleep comes before the memory test, so sleep is the changer. Recalling locations the next morning can\'t change how long you already slept.' },
  ],

  // -------------------------------------------------------------------------
  // 2a. Validity and reliability.
  // -------------------------------------------------------------------------
  validity: [
    // valid and reliable
    { valid: true, reliable: true,
      text: 'To measure reaction time, a computer records the milliseconds between a light appearing and the participant pressing a key, averaged over 50 trials. Running it again with the same people gives very similar averages.',
      whyValid: 'the time between the light and the key press is exactly how long the person took to react.',
      whyReliable: 'the same people get very similar averages when it is run again.' },
    { valid: true, reliable: true,
      text: 'To measure short-term memory, researchers read out strings of digits that get longer and note the longest one each person repeats correctly. Tested again a week later, people get almost the same span.',
      whyValid: 'repeating back digits is a direct test of how much someone can hold in short-term memory.',
      whyReliable: 'the same people get almost the same span a week later.' },
    { valid: true, reliable: true, for: ['neuroscience'],
      text: 'To measure how quiet a tone someone can hear, a computer plays tones at many volumes, many times each, and finds the quietest one the person detects half the time. A second session gives almost the same result.',
      whyValid: 'finding the quietest tone a person can detect is exactly what hearing sensitivity means.',
      whyReliable: 'the second session gives almost the same threshold, because it is based on many trials.' },
    { valid: true, reliable: true,
      text: 'To measure recall, participants write down every word they remember from a list of 20. Two researchers who mark the same answer sheets separately get the same counts.',
      whyValid: 'counting the words written down is a direct measure of how many were recalled.',
      whyReliable: 'two people marking separately get the same counts.' },

    // reliable, not valid
    { valid: false, reliable: true,
      text: 'To measure how quickly people react, researchers measure the length of each participant\'s arm. The tape measure gives the same result every time.',
      whyValid: 'arm length isn\'t reaction time — it measures something else entirely.',
      whyReliable: 'measuring the same arm gives the same number every time. Consistent, but consistently measuring the wrong thing.' },
    { valid: false, reliable: true,
      text: 'To measure how well people remember a list, researchers count how many words were on the list they were given. The count is the same whoever does it.',
      whyValid: 'the length of the list says nothing about how much of it a person remembered.',
      whyReliable: 'anyone who counts the list gets the same number.' },
    { valid: false, reliable: true,
      text: 'To measure how alert participants are, researchers write down the time on the clock when each session was booked to start. Checking the booking sheet again gives the same times.',
      whyValid: 'the booked start time isn\'t alertness — two people starting at the same time can feel very different.',
      whyReliable: 'the booking sheet gives the same times every time it is checked.' },
    { valid: false, reliable: true,
      text: 'To measure how hard a puzzle is for people, researchers count the number of words in its instructions. The count comes out the same every time.',
      whyValid: 'long instructions don\'t make a puzzle hard to solve — the count measures the instructions, not the difficulty.',
      whyReliable: 'counting the words again gives the same number.' },

    // valid, not reliable
    { valid: true, reliable: false,
      text: 'To measure each person\'s reaction time, the computer records just one trial. The same person can be 250 ms on one try and 450 ms on the next.',
      whyValid: 'timing a key press is the right way to measure reaction time.',
      whyReliable: 'a single trial swings a lot from try to try — many trials need averaging.' },
    { valid: true, reliable: false,
      text: 'To measure attention, one observer watches each participant live and counts how often they look away from the screen. When the same session is counted again from a video, the numbers are quite different.',
      whyValid: 'looking away from the screen is a sensible sign that attention has slipped.',
      whyReliable: 'one observer counting live misses glances, so counting the same session again gives a different number.' },
    { valid: true, reliable: false,
      text: 'To find out whether a blue or a green screen background helps people solve anagrams, researchers test 6 people. When they test another 6, the result comes out the other way.',
      whyValid: 'timing how quickly people solve anagrams on each background is the right thing to measure.',
      whyReliable: 'repeating it with another 6 people gives a different result. For a small difference like this, 6 participants is far too few.' },
    { valid: true, reliable: false,
      text: 'Researchers test memory with a sensible word-list task, but their report doesn\'t say how long each word was shown or how long the delay was before the test. Other researchers who try to repeat the study get different results.',
      whyValid: 'recalling a word list is a sensible way to test memory.',
      whyReliable: 'without a full "recipe" — timings, materials, procedure — nobody can repeat the study and get the same result.' },

    // neither
    { valid: false, reliable: false,
      text: 'To measure attention, researchers ask each participant to pick a card from a shuffled deck and record its number. People pick a different card every time.',
      whyValid: 'a randomly picked card has nothing to do with attention.',
      whyReliable: 'people pick a different card every time.' },
    { valid: false, reliable: false,
      text: 'To measure reaction time, researchers count how many cars pass the lab window during each session. The count is different every time the same person is tested.',
      whyValid: 'passing traffic has nothing to do with how quickly the participant reacts.',
      whyReliable: 'the same person gets a different "score" every session.' },
    { valid: false, reliable: false,
      text: 'To measure how tired participants are, researchers note which seat each one chooses in the waiting room. The same person picks a different seat each visit.',
      whyValid: 'the seat someone chooses isn\'t a measure of tiredness.',
      whyReliable: 'the same person gives a different answer each visit.' },
    { valid: false, reliable: false,
      text: 'To measure how well people learned a maze task, researchers count the emails in their own inbox at the start of each session. The number changes every day.',
      whyValid: 'the researcher\'s emails have nothing to do with the participant\'s learning.',
      whyReliable: 'the count is different every time.' },
  ],

  // -------------------------------------------------------------------------
  // 2d. Continuous or discrete.
  // -------------------------------------------------------------------------
  continuity: [
    { cat: 'cont', label: 'time to find a target on screen', why: MIND_CONT + '612 ms, 612.4 ms... time can always be divided further.' },
    { cat: 'cont', label: 'pupil diameter', why: MIND_CONT + '4 mm, 4.2 mm, 4.23 mm...', for: ['neuroscience'] },
    { cat: 'cont', label: 'time spent on a task', why: MIND_CONT + '20 minutes, 20.5 minutes, 20 minutes and 31 seconds...' },
    { cat: 'cont', label: 'hours of sleep', why: MIND_CONT + '7 hours, 7.25 hours, 7 hours and 16 minutes...' },
    { cat: 'cont', label: 'loudness of a tone in decibels', why: MIND_CONT + '60 dB, 60.5 dB... loudness can be set to any value on the scale.' },
    { cat: 'cont', label: 'contrast of a pattern', why: MIND_CONT + '10%, 10.5%, 10.52%... contrast can be set as finely as the screen allows.' },
    { cat: 'cont', label: 'size of a brain response in microvolts', why: MIND_CONT + '5 µV, 5.3 µV, 5.31 µV...', for: ['neuroscience'] },
    { cat: 'cont', label: 'time taken to complete a maze', why: MIND_CONT + 'time can always be measured more finely.' },
    { cat: 'cont', label: 'average number of words recalled across participants', why: MIND_CONT + 'one person can\'t recall 7.4 words, but an average across people can be 7.4.' },
    { cat: 'cont', label: 'delay before a memory test', why: MIND_CONT + '10 minutes, 10.5 minutes... the gap can be any length.' },
    { cat: 'cont', label: 'brightness of a light', why: MIND_CONT + 'brightness can be turned up by any amount, however small.' },
    { cat: 'cont', label: 'how long each word is shown on screen', why: MIND_CONT + '500 ms, 500.5 ms... display time can be any value.' },
    { cat: 'cont', label: 'Stroop interference in milliseconds', why: MIND_CONT + 'the extra naming time can be 84 ms, 84.6 ms...' },

    { cat: 'disc', label: 'number of words recalled', why: MIND_DISC + 'words are counted: 7 or 8, never 7.5.' },
    { cat: 'disc', label: 'number of errors in mirror drawing', why: MIND_DISC + 'errors are counted in whole numbers.' },
    { cat: 'disc', label: 'number of practice trials', why: MIND_DISC + 'you do 20 trials or 21, not 20.3.' },
    { cat: 'disc', label: 'digit span (longest string repeated)', why: MIND_DISC + 'a string has 6 digits or 7, nothing in between.' },
    { cat: 'disc', label: 'number of signals detected', why: MIND_DISC + 'each signal is either spotted or not, so the total is a whole number.' },
    { cat: 'disc', label: 'number of practice sessions', why: MIND_DISC + 'people come to 3 sessions or 4, not 3.5.' },
    { cat: 'disc', label: 'alertness rating on a 1–10 scale', why: MIND_DISC + 'people choose 1, 2, 3... 10, and there\'s no 6.5 on the scale.' },
    { cat: 'disc', label: 'number of times someone looks away from the screen', why: MIND_DISC + 'each glance away is counted once.' },
    { cat: 'disc', label: 'number of distractors in a display', why: MIND_DISC + 'a display has 8 shapes or 9, never 8.2.' },
    { cat: 'disc', label: 'number of anagrams solved', why: MIND_DISC + 'each anagram is solved or not, so the total is a whole number.' },
    { cat: 'disc', label: 'number of words in a memory list', why: MIND_DISC + 'a list has 15 words or 16, nothing in between.' },
    { cat: 'disc', label: 'number of false alarms', why: MIND_DISC + 'each time someone responds when there was no signal is counted once.' },
  ],

  // -------------------------------------------------------------------------
  // 2e. Levels of measurement.
  // -------------------------------------------------------------------------
  measurement: [
    { cat: 'categorical', label: 'Stroop trial type (matching or clashing)', why: MIND_NOM + 'A clashing trial isn\'t more or less than a matching one, just different.' },
    { cat: 'categorical', label: 'which key is pressed (left or right)', why: MIND_NOM + 'Left isn\'t more than right.' },
    { cat: 'categorical', label: 'type of stimulus (word, picture or sound)', why: MIND_NOM + 'A picture isn\'t more than a word — they\'re different kinds of thing.' },
    { cat: 'categorical', label: 'ink colour in the Stroop task', why: MIND_NOM + 'Red, blue and green have no order.' },
    { cat: 'categorical', label: 'sense tested (vision, hearing or touch)', why: MIND_NOM + 'The senses are different, not ranked.' },
    { cat: 'categorical', label: 'memory strategy reported (repeating, imagery or none)', why: MIND_NOM + 'These are kinds of strategy, not amounts of one.' },
    { cat: 'categorical', label: 'which condition someone is in', why: MIND_NOM + 'Condition A and condition B are labels, not amounts.' },

    { cat: 'ordinal', label: 'alertness from "very sleepy" to "very alert"', why: MIND_ORD + 'The answers are in order, but nothing says the steps are the same size.' },
    { cat: 'ordinal', label: 'finishing position in a puzzle race (1st, 2nd, 3rd)', why: MIND_ORD + 'The gap between 1st and 2nd could be a second; between 2nd and 3rd, a minute.' },
    { cat: 'ordinal', label: 'confidence: "guessing", "fairly sure", "certain"', why: MIND_ORD + '"Certain" is above "fairly sure", but the steps aren\'t equal-sized.' },
    { cat: 'ordinal', label: 'task difficulty (easy, medium, hard)', why: MIND_ORD + 'In order, but the jump from easy to medium needn\'t match the jump from medium to hard.' },
    { cat: 'ordinal', label: 'sleep quality (poor, fair, good)', why: MIND_ORD + 'The labels are ranked, but not equally spaced.' },
    { cat: 'ordinal', label: 'ranking tasks from most to least enjoyable', why: MIND_ORD + 'A ranking gives the order, not how far apart the tasks are.' },

    { cat: 'interval', label: 'mood rated on a scale of 1–9', why: MIND_INT + 'The numbered steps are treated as equal, but there\'s no zero, so an 8 isn\'t "twice as happy" as a 4.' },
    { cat: 'interval', label: 'alertness rated on a scale of 1–7', why: MIND_INT + 'A numbered scale has constant steps, but no natural zero.' },
    { cat: 'interval', label: 'time of day of the testing session', why: MIND_INT + 'The minutes are equal, but midnight isn\'t "no time", so 4 o\'clock isn\'t twice 2 o\'clock.' },
    { cat: 'interval', label: 'date of the testing session', why: MIND_INT + 'Days are equal steps, but the calendar\'s starting point is arbitrary.' },
    { cat: 'interval', label: 'lab temperature in °C', why: MIND_INT + '0°C isn\'t "no temperature", so 22°C isn\'t twice as warm as 11°C.' },
    { cat: 'interval', label: 'pleasantness of a task rated 1–7', why: MIND_INT + 'The numbered steps are treated as equal, but there\'s no zero on the scale.' },

    { cat: 'ratio', label: 'reaction time in milliseconds', why: MIND_RAT + '0 ms is no time at all, and 600 ms is twice 300 ms.' },
    { cat: 'ratio', label: 'number of words recalled', why: MIND_RAT + '0 words is none at all, and 10 words is twice 5.' },
    { cat: 'ratio', label: 'hours of sleep', why: MIND_RAT + '0 hours is no sleep, and 8 hours is twice 4.' },
    { cat: 'ratio', label: 'pupil diameter in mm', why: MIND_RAT + '0 mm is no width at all, and 6 mm is twice 3 mm.', for: ['neuroscience'] },
    { cat: 'ratio', label: 'number of errors', why: MIND_RAT + 'Zero errors means none, and 8 errors is twice 4.' },
    { cat: 'ratio', label: 'minutes spent on the task', why: MIND_RAT + '0 minutes is no time on the task, and 40 minutes is twice 20.' },
    { cat: 'ratio', label: 'number of practice trials', why: MIND_RAT + '0 trials is no practice, and 100 trials is twice 50.' },
  ],

  // -------------------------------------------------------------------------
  // 2g. Confounds. Paired: the same study done badly, then done properly.
  // -------------------------------------------------------------------------
  confounds: [
    { iv: 'doing a second task', dv: 'tracking errors', confound: 'tiredness',
      vars: ['doing a second task', 'tracking errors', 'tiredness', 'the tracking task'],
      text: 'Researchers test whether doing two tasks at once causes more errors. One group does the tracking task on its own at the start of a session; another group does it while counting backwards, at the end of a two-hour session.',
      why: 'The two-task group was also tested after two hours of work, when people are tired. Any difference could come from tiredness, not the second task.' },
    { iv: 'rehearsal instructions', dv: 'number of words recalled', confound: 'word familiarity',
      vars: ['rehearsal instructions', 'number of words recalled', 'word familiarity', 'the length of the list'],
      text: 'Researchers test whether telling people to repeat words to themselves improves recall. Both groups get 20-word lists, but the rehearsal group\'s words are everyday words and the other group\'s are rare ones.',
      why: 'The rehearsal group also had more familiar words, which are easier to remember anyway. The difference could be the words, not the rehearsing.' },
    { iv: 'sleep', dv: 'locations recalled', confound: 'type of test',
      vars: ['sleep', 'locations recalled', 'type of test', 'the pictures learned'],
      text: 'Researchers test whether sleep helps people remember where pictures were placed. Both groups learn the same pictures, but the sleep group is tested by picking locations from a list and the stay-awake group has to point to each location from memory.',
      why: 'Picking from a list is easier than recalling from scratch, and only the sleep group got the easier test. The difference could come from the test, not the sleep.' },
    { iv: 'reward', dv: 'reaction time', confound: 'practice',
      vars: ['reward', 'reaction time', 'practice', 'the reaction task'],
      text: 'To see whether points make people respond faster, everyone does the same reaction task twice: first with no points, then with points for fast answers.',
      why: 'The rewarded block always came second, after people had already practised the task. Faster responses could come from practice, not the points.' },
    { iv: 'background noise', dv: 'proofreading errors missed', confound: 'text difficulty',
      vars: ['background noise', 'proofreading errors missed', 'text difficulty', 'the length of the text'],
      text: 'Researchers test whether background noise makes people miss spelling mistakes when proofreading. Both groups read texts of the same length, but the noise group\'s text is a technical manual and the quiet group\'s is a simple story.',
      why: 'The noise group also had a much harder text, and hard texts are harder to check. The difference could come from the text, not the noise.' },
    { iv: 'contrast', dv: 'percentage of dots detected', confound: 'screen size', for: ['neuroscience'],
      vars: ['contrast', 'percentage of dots detected', 'screen size', 'the viewing distance'],
      text: 'Researchers test whether high-contrast dots are easier to detect. Everyone sits the same distance from the screen, but the high-contrast dots are shown on a large screen and the low-contrast dots on a small one.',
      why: 'The high-contrast dots were also shown bigger, on a larger screen, and bigger dots are easier to see. The difference could be size, not contrast.' },
    { iv: 'extra practice', dv: 'typing speed', confound: 'the keyboard',
      vars: ['extra practice', 'typing speed', 'the keyboard', 'the passage typed'],
      text: 'Researchers test whether extra practice sessions improve typing speed. The extra-practice group also switches to a new, easier keyboard; the other group keeps an old stiff one. Both then type the same passage.',
      why: 'The practice group also had the better keyboard, so they might type faster because of the keyboard, not the practice.' },
    { iv: 'watching an amusing clip', dv: 'mood rating', confound: 'the experimenter',
      vars: ['watching an amusing clip', 'mood rating', 'the experimenter', 'the mood scale'],
      text: 'Researchers test whether an amusing video clip raises mood. The amusing-clip group is looked after by a warm, friendly experimenter and the neutral-clip group by a curt one. Everyone rates their mood on the same scale.',
      why: 'The amusing-clip group also had a friendlier experimenter, which could lift anyone\'s mood. The difference could be the experimenter, not the clip.' },
    { iv: 'word length', dv: 'number of words recalled', confound: 'word familiarity',
      vars: ['word length', 'number of words recalled', 'word familiarity', 'the number of words in each list'],
      text: 'To test whether short words are easier to recall than long ones, researchers give everyone lists of the same size. All the short words are everyday words and all the long words are rare.',
      why: 'The long words are also the unfamiliar ones, and unfamiliar words are harder to recall. The difference could be familiarity, not length.' },

    { iv: 'doing a second task', dv: 'tracking errors', confound: null,
      text: 'Researchers test whether doing two tasks at once causes more errors. Participants are randomly assigned to do the tracking task on its own or while counting backwards, both at the start of the session.',
      why: 'Random assignment and the same point in the session mean the second task is the only systematic difference.' },
    { iv: 'rehearsal instructions', dv: 'number of words recalled', confound: null,
      text: 'Researchers test whether telling people to repeat words to themselves improves recall. Participants are randomly split into two groups, and both learn exactly the same list of words.',
      why: 'Same words, random groups — only the instructions differ.' },
    { iv: 'sleep', dv: 'locations recalled', confound: null,
      text: 'To test whether sleep helps memory for picture locations, participants are randomly split into a sleep group and a stay-awake group. Both learn the same pictures and take the same test.',
      why: 'Same pictures, same test, random groups — only the sleep differs.' },
    { iv: 'reward', dv: 'reaction time', confound: null,
      text: 'To see whether points make people respond faster, everyone does rewarded and unrewarded blocks of the same task. Half the participants get the rewarded block first and half get it second.',
      why: 'Swapping the order across participants means practice helps both kinds of block equally, so only the reward differs.' },
    { iv: 'background noise', dv: 'proofreading errors missed', confound: null,
      text: 'Researchers test whether background noise makes people miss spelling mistakes. Participants are randomly assigned to proofread the same text either in quiet or with noise, in the same room.',
      why: 'Same text, same room, random groups — the noise is the only difference.' },
    { iv: 'contrast', dv: 'percentage of dots detected', confound: null, for: ['neuroscience'],
      text: 'Researchers test whether high-contrast dots are easier to detect. High- and low-contrast dots of the same size are mixed in a random order on the same screen.',
      why: 'Same size, same screen, random order — only the contrast differs.' },
    { iv: 'extra practice', dv: 'typing speed', confound: null,
      text: 'Researchers test whether extra practice sessions improve typing speed. Participants are randomly split into two groups who use the same keyboards; only one group gets the extra sessions. Both then type the same passage.',
      why: 'Same keyboards, same passage, random groups — only the practice differs.' },
    { iv: 'watching an amusing clip', dv: 'mood rating', confound: null,
      text: 'Researchers test whether an amusing clip raises mood. Participants are randomly assigned to an amusing or a neutral clip, and the same experimenter follows the same script with everyone.',
      why: 'Same experimenter, same script, random groups — only the clip differs.' },
    { iv: 'word length', dv: 'number of words recalled', confound: null,
      text: 'To test whether short words are easier to recall than long ones, researchers choose short and long words that are all equally familiar.',
      why: 'Matching the words for familiarity removes the obvious other difference between short and long words.' },
  ],

  // -------------------------------------------------------------------------
  // 2j. Within or between subjects. Pairs: the same study both ways.
  // -------------------------------------------------------------------------
  designs: [
    { cat: 'within',
      label: 'Every participant names the ink colours of a list of matching colour words and a list of clashing colour words, and their naming times for the two lists are compared.',
      ivs: [MIND_STROOP], dv: MIND_NAMING,
      others: [MIND_P, { name: 'the ink colours', aliases: ['ink', 'ink colour', 'colours', 'red', 'blue'] }] },
    { cat: 'within',
      label: 'Each participant does a tracking task once on its own and once while counting backwards, and their tracking errors in the two conditions are compared.',
      ivs: [MIND_DUAL], dv: MIND_TRACK_ERR,
      others: [MIND_P] },
    { cat: 'within',
      label: 'Every participant learns one list of short words and one list of long words, and the number of words they recall from each list is compared.',
      ivs: [MIND_WORDLEN], dv: MIND_RECALL,
      others: [MIND_P, { name: 'the lists', aliases: ['list', 'lists', 'word list'] }] },
    { cat: 'within', for: ['neuroscience'],
      label: 'Each participant watches for faint and strong dots mixed together on the same screen, and the percentage of dots they detect at each contrast is compared.',
      ivs: [MIND_CONTRAST], dv: MIND_DETECT,
      others: [MIND_P, { name: 'the screen', aliases: ['screen', 'monitor', 'computer'] }] },
    { cat: 'within', for: ['neuroscience'],
      label: 'Every participant presses a key as soon as they hear a tone. Some tones are quiet and some are loud, and each person\'s reaction times to the two kinds are compared.',
      ivs: [MIND_LOUD], dv: MIND_RT,
      others: [MIND_P, { name: 'the key', aliases: ['key', 'button', 'keyboard'] }] },
    { cat: 'within',
      label: 'Participants watch an amusing clip on one day and a neutral clip on another day, and rate their mood straight after each. Each person\'s two mood ratings are compared.',
      ivs: [MIND_CLIP], dv: MIND_MOOD,
      others: [MIND_P, { name: 'the two days', aliases: ['days', 'another day', 'one day'] }] },
    { cat: 'within', for: ['neuroscience', 'psychology'],
      label: 'Participants learn where pictures are placed on a grid, once before a night\'s sleep and, a week later, before a day awake. How many locations they recall 12 hours later is compared.',
      ivs: [MIND_SLEEP], dv: MIND_PICS,
      others: [MIND_P, { name: 'the grid', aliases: ['grid', 'pictures', 'picture'] }] },
    { cat: 'within',
      label: 'Every participant does blocks of a reaction task with points for fast answers and blocks with no points, and their reaction times in the two kinds of block are compared.',
      ivs: [MIND_REWARD], dv: MIND_RT,
      others: [MIND_P, { name: 'the blocks', aliases: ['blocks', 'block', 'reaction task', 'task'] }] },
    { cat: 'within',
      label: 'The same participants search for a target letter among 5 other letters and among 20 other letters, and their search times are compared.',
      ivs: [{ name: 'number of distractors (5 or 20)', aliases: ['distractors', 'number of distractors', 'number of letters', 'other letters', '5 or 20', 'display size', 'set size', 'clutter'] }],
      dv: { name: 'search time', aliases: ['search time', 'time to find', 'how long it takes', 'how quickly they find', 'speed', 'finding time', 'reaction time'] },
      others: [MIND_P, { name: 'the target letter', aliases: ['target', 'target letter'] }] },

    { cat: 'between',
      label: 'One group of participants names the ink colours of matching colour words, and a different group names the ink colours of clashing colour words. The two groups\' naming times are compared.',
      ivs: [MIND_STROOP], dv: MIND_NAMING,
      others: [{ name: 'the groups of participants', aliases: ['participants', 'people', 'group', 'groups'] }] },
    { cat: 'between',
      label: 'Participants are randomly assigned to do a tracking task either on its own or while counting backwards, and the two groups\' tracking errors are compared.',
      ivs: [MIND_DUAL], dv: MIND_TRACK_ERR,
      others: [MIND_P] },
    { cat: 'between',
      label: 'Half the participants learn a list of short words and the other half learn a list of long words. The number of words each group recalls is compared.',
      ivs: [MIND_WORDLEN], dv: MIND_RECALL,
      others: [MIND_P] },
    { cat: 'between', for: ['neuroscience'],
      label: 'One group watches for faint dots and a different group watches for strong dots, on the same screen. The percentage of dots each group detects is compared.',
      ivs: [MIND_CONTRAST], dv: MIND_DETECT,
      others: [{ name: 'the groups', aliases: ['groups', 'group', 'participants', 'people'] }, { name: 'the screen', aliases: ['screen', 'monitor', 'computer'] }] },
    { cat: 'between', for: ['neuroscience'],
      label: 'One group of participants responds to quiet tones and another group to loud tones, and the two groups\' reaction times are compared.',
      ivs: [MIND_LOUD], dv: MIND_RT,
      others: [{ name: 'the groups', aliases: ['groups', 'group', 'participants', 'people'] }] },
    { cat: 'between',
      label: 'Participants are randomly assigned to watch either an amusing clip or a neutral clip, and then rate their mood. The two groups\' mood ratings are compared.',
      ivs: [MIND_CLIP], dv: MIND_MOOD,
      others: [MIND_P] },
    { cat: 'between', for: ['neuroscience', 'psychology'],
      label: 'Everyone learns where pictures are placed on a grid in the evening. One group then sleeps and a different group stays awake, and the number of locations each group recalls the next morning is compared.',
      ivs: [MIND_SLEEP], dv: MIND_PICS,
      others: [{ name: 'the grid', aliases: ['grid', 'pictures', 'picture'] }] },
    { cat: 'between',
      label: 'One group does a reaction task with points for fast answers, and a different group does the same task with no points. The two groups\' reaction times are compared.',
      ivs: [MIND_REWARD], dv: MIND_RT,
      others: [{ name: 'the reaction task', aliases: ['task', 'reaction task', 'same task'] }] },
    { cat: 'between',
      label: 'Participants are randomly assigned to get feedback after every answer or no feedback while learning to sort shapes. The two groups\' accuracy at the end is compared.',
      ivs: [{ name: 'feedback (or none)', aliases: ['feedback', 'no feedback', 'feedback or none', 'being told if they are right', 'told', 'information'] }],
      dv: { name: 'sorting accuracy', aliases: ['accuracy', 'sorting accuracy', 'how many correct', 'correct', 'score', 'performance', 'learning'] },
      others: [MIND_P, { name: 'the shapes', aliases: ['shapes', 'shape'] }] },
  ],

  // -------------------------------------------------------------------------
  // 2f-2h. Cross-sectional, longitudinal, or both.
  // -------------------------------------------------------------------------
  crosslong: {
    single: [
      { cat: 'cross',
        label: 'In one session each, trained musicians and people with no musical training hear pairs of tones, and the smallest pitch difference each person can detect is compared between the two groups.',
        ivs: [{ name: 'musical training (musician or not)', aliases: ['musician', 'musicians', 'non-musician', 'musical training', 'training', 'music', 'musician or not', 'group'] }],
        dv: { name: 'smallest pitch difference detected', aliases: ['pitch', 'pitch difference', 'pitch discrimination', 'smallest difference', 'threshold', 'hearing', 'detection'] },
        others: [{ name: 'the testing session', aliases: ['session', 'one session', 'time'] }] },
      { cat: 'cross',
        label: 'In a single afternoon, members of a chess club and people who have never played are shown a chess position for 5 seconds, and the number of pieces each person puts back correctly is compared.',
        ivs: [{ name: 'chess experience (club player or never played)', aliases: ['chess experience', 'experience', 'chess player', 'club', 'never played', 'expert', 'novice', 'expertise', 'group'] }],
        dv: { name: 'number of pieces placed correctly', aliases: ['pieces', 'pieces placed', 'pieces correct', 'memory', 'recall', 'how many pieces', 'score'] },
        others: [{ name: 'the afternoon of testing', aliases: ['afternoon', 'single afternoon', 'time', '5 seconds'] }] },
      { cat: 'cross',
        label: 'On one testing day, experienced typists and beginners copy the same passage, and the number of errors in each group is compared.',
        ivs: [{ name: 'typing experience (experienced or beginner)', aliases: ['experience', 'experienced', 'beginner', 'typists', 'experienced or beginner', 'skill', 'expertise', 'group'] }],
        dv: { name: 'number of typing errors', aliases: ['errors', 'typing errors', 'mistakes', 'number of errors', 'how many errors', 'accuracy'] },
        others: [{ name: 'the passage', aliases: ['passage', 'text'] }] },
      { cat: 'cross',
        label: 'In the same week, first-, second- and third-year psychology students each do the Stroop task once, and the size of the Stroop effect is compared between the year groups.',
        ivs: [{ name: 'year group', aliases: ['year group', 'year of study', 'first second or third year', 'which year', 'group', 'students'] }],
        dv: { name: 'size of the Stroop effect', aliases: ['stroop effect', 'stroop', 'interference', 'stroop interference', 'naming time', 'effect', 'score'] },
        others: [{ name: 'the week of testing', aliases: ['week', 'same week', 'time'] }] },

      { cat: 'long',
        label: 'The same 20 participants practise tracing a star while watching their hand in a mirror, and their errors are counted on each of five days.',
        ivs: [{ name: 'time (day of practice)', aliases: ['day of practice', 'practice', 'five days', 'each day', ...MIND_TIME] }],
        dv: { name: 'number of errors', aliases: ['errors', 'mistakes', 'number of errors', 'how many errors', 'accuracy', 'mirror drawing'] },
        others: [MIND_P] },
      { cat: 'long',
        label: 'A group of participants learns a list of words, then the same people are tested on how many they remember after 10 minutes, one day and one week.',
        ivs: [{ name: 'time since learning', aliases: ['time since learning', 'delay', 'retention interval', '10 minutes', 'one day', 'one week', 'how long ago', ...MIND_TIME] }],
        dv: MIND_RECALL,
        others: [{ name: 'the list', aliases: ['list', 'word list'] }] },
      { cat: 'long',
        label: 'The same participants watch a screen for rare signals for two hours, and the number of signals they spot is counted in every 20-minute stretch.',
        ivs: [{ name: 'time on task', aliases: ['time on task', 'time on the task', 'two hours', '20 minutes', 'stretch', 'duration', 'how long they have been watching', 'minutes', ...MIND_TIME] }],
        dv: { name: 'number of signals spotted', aliases: ['signals', 'signals spotted', 'detections', 'hits', 'how many they spot', 'detection', 'vigilance', 'attention'] },
        others: [{ name: 'the screen', aliases: ['screen', 'monitor', 'display'] }] },
      { cat: 'long',
        label: 'A group of new students learning to touch-type have their typing speed measured every week for a term.',
        ivs: [{ name: 'time (week of the term)', aliases: ['week of the term', 'term', 'every week', 'practice', 'weeks of learning', ...MIND_TIME] }],
        dv: { name: 'typing speed', aliases: ['typing speed', 'words per minute', 'wpm', 'how fast they type', 'speed', 'typing'] },
        others: [{ name: 'the students', aliases: ['students', 'learners', 'group'] }] },
    ],

    multi: [
      { cat: 'cross',
        label: 'In one session each, musicians and non-musicians hear pairs of tones in quiet and in background noise, and the smallest pitch difference each can detect is compared.',
        ivs: [
          { name: 'musical training (musician or not)', aliases: ['musician', 'musicians', 'non-musician', 'musical training', 'training', 'music', 'musician or not'] },
          { name: 'background noise (quiet or noise)', aliases: ['noise', 'background noise', 'quiet or noise', 'quiet', 'noisy', 'listening condition'] },
        ],
        dv: { name: 'smallest pitch difference detected', aliases: ['pitch', 'pitch difference', 'pitch discrimination', 'smallest difference', 'threshold', 'detection'] },
        others: [{ name: 'the session', aliases: ['session', 'one session'] }] },
      { cat: 'cross',
        label: 'In a single afternoon, chess club members and people who have never played are shown positions from real games and random positions, and the number of pieces each person puts back correctly is compared.',
        ivs: [
          { name: 'chess experience (club player or never played)', aliases: ['chess experience', 'experience', 'chess player', 'club', 'never played', 'expert', 'novice', 'expertise'] },
          { name: 'type of position (real or random)', aliases: ['position', 'type of position', 'real or random', 'real', 'random', 'real game', 'random position'] },
        ],
        dv: { name: 'number of pieces placed correctly', aliases: ['pieces', 'pieces placed', 'pieces correct', 'memory', 'recall', 'how many pieces', 'score'] },
        others: [{ name: 'the afternoon', aliases: ['afternoon', 'single afternoon'] }] },
      { cat: 'cross',
        label: 'On one testing day, experienced typists and beginners copy a passage of real words and a passage of random letter strings, and their typing speeds are compared.',
        ivs: [
          { name: 'typing experience (experienced or beginner)', aliases: ['experience', 'experienced', 'beginner', 'typists', 'experienced or beginner', 'skill', 'expertise'] },
          { name: 'type of text (words or random letters)', aliases: ['text', 'type of text', 'real words', 'random letters', 'letter strings', 'words or random letters', 'random'] },
        ],
        dv: { name: 'typing speed', aliases: ['typing speed', 'words per minute', 'wpm', 'how fast they type', 'speed', 'typing'] },
        others: [{ name: 'the testing day', aliases: ['day', 'testing day'] }] },

      { cat: 'long',
        label: 'The same participants practise mirror drawing on each of five days, tracing an easy shape and a hard shape each day, and their errors are counted.',
        ivs: [
          { name: 'time (day of practice)', aliases: ['day of practice', 'practice', 'five days', 'each day', ...MIND_TIME] },
          { name: 'shape difficulty (easy or hard)', aliases: ['shape', 'difficulty', 'easy or hard', 'easy', 'hard', 'shape difficulty', 'type of shape'] },
        ],
        dv: { name: 'number of errors', aliases: ['errors', 'mistakes', 'number of errors', 'how many errors', 'accuracy', 'mirror drawing'] },
        others: [MIND_P] },
      { cat: 'long',
        label: 'A group of participants learns lists of short words and lists of long words, and the same people are tested on how many they remember after 10 minutes, one day and one week.',
        ivs: [
          { name: 'time since learning', aliases: ['time since learning', 'delay', 'retention interval', '10 minutes', 'one day', 'one week', 'how long ago', ...MIND_TIME] },
          MIND_WORDLEN,
        ],
        dv: MIND_RECALL,
        others: [{ name: 'the lists', aliases: ['lists', 'list', 'word list'] }] },
      { cat: 'long',
        label: 'The same participants watch a screen for two hours for faint and clear signals, and the number of each kind they spot is counted in every 20-minute stretch.',
        ivs: [
          { name: 'time on task', aliases: ['time on task', 'time on the task', 'two hours', '20 minutes', 'stretch', 'duration', 'how long they have been watching', 'minutes', ...MIND_TIME] },
          { name: 'signal strength (faint or clear)', aliases: ['signal strength', 'faint or clear', 'faint', 'clear', 'strength', 'type of signal', 'visibility', 'contrast'] },
        ],
        dv: { name: 'number of signals spotted', aliases: ['signals spotted', 'detections', 'hits', 'how many they spot', 'detection', 'vigilance', 'attention'] },
        others: [{ name: 'the screen', aliases: ['screen', 'monitor', 'display'] }] },
    ],

    panel: [
      { cat: 'both',
        label: 'One group gets feedback after every answer while learning to sort shapes, and another group gets none. Both groups\' accuracy is measured in each of five blocks of trials.',
        ivs: [
          { name: 'feedback (or none)', aliases: ['feedback', 'no feedback', 'feedback or none', 'being told if they are right', 'told', 'group'] },
          { name: 'time (block of trials)', aliases: ['block', 'blocks', 'block of trials', 'five blocks', 'trials', 'practice', ...MIND_TIME] },
        ],
        dv: { name: 'sorting accuracy', aliases: ['accuracy', 'sorting accuracy', 'how many correct', 'correct', 'score', 'performance', 'learning'] },
        others: [] },
      { cat: 'both',
        label: 'One group learns some facts by testing themselves and another by rereading them. Both groups are tested on the facts after one day, one week and one month.',
        ivs: [
          { name: 'study method (self-testing or rereading)', aliases: ['study method', 'method', 'self-testing', 'testing', 'rereading', 'self-testing or rereading', 'how they study', 'group'] },
          { name: 'time since learning', aliases: ['time since learning', 'delay', 'one day', 'one week', 'one month', 'retention interval', ...MIND_TIME] },
        ],
        dv: { name: 'number of facts recalled', aliases: ['facts recalled', 'recall', 'facts', 'memory', 'how many facts', 'remember', 'score'] },
        others: [] },
      { cat: 'both', for: ['neuroscience', 'psychology'],
        label: 'After learning where pictures are placed on a grid, one group sleeps and another stays awake overnight. Both groups are tested on the locations the next day, three days later and a week later.',
        ivs: [
          MIND_SLEEP,
          { name: 'time since learning', aliases: ['time since learning', 'delay', 'next day', 'three days', 'a week later', 'retention interval', 'time', 'over time', 'week', 'weeks', 'day', 'days', 'when it was measured', 'time point', 'session', 'before and after'] },
        ],
        dv: MIND_PICS,
        others: [] },
      { cat: 'both',
        label: 'One group earns points for fast answers on a reaction task and another group earns none. Both groups\' reaction times are measured on each of four days of practice.',
        ivs: [
          { name: 'reward (points or no points)', aliases: ['reward', 'points', 'rewarded', 'no reward', 'points or no points', 'incentive', 'motivation', 'group'] },
          { name: 'time (day of practice)', aliases: ['day of practice', 'practice', 'four days', 'each day', ...MIND_TIME] },
        ],
        dv: MIND_RT,
        others: [] },
      { cat: 'both',
        label: 'One group learning to touch-type practises for 15 minutes a day, and another practises for one long session a week. Both groups\' typing speed is measured every week for six weeks.',
        ivs: [
          { name: 'practice schedule (daily or weekly)', aliases: ['practice schedule', 'schedule', 'daily or weekly', 'daily', 'weekly', 'spaced', 'massed', 'spacing', 'group'] },
          { name: 'time (week of testing)', aliases: ['week of testing', 'six weeks', 'every week', 'time', 'over time', 'weeks', 'when it was measured', 'time point', 'session', 'before and after', 'month', 'months'] },
        ],
        dv: { name: 'typing speed', aliases: ['typing speed', 'words per minute', 'wpm', 'how fast they type', 'speed', 'typing'] },
        others: [] },
    ],
  },

  // -------------------------------------------------------------------------
  // Level 3. Factors for box notation.
  // -------------------------------------------------------------------------
  factors: [
    { name: 'Stroop condition', levels: { 2: ['matching', 'clashing'], 3: ['matching', 'neutral', 'clashing'] } },
    { name: 'Memory load', levels: { 2: ['2 digits', '6 digits'], 3: ['2 digits', '4 digits', '6 digits'], 4: ['2 digits', '4 digits', '6 digits', '8 digits'] } },
    { name: 'List length', levels: { 2: ['10 words', '20 words'], 3: ['10 words', '20 words', '30 words'], 4: ['5 words', '10 words', '15 words', '20 words'] } },
    { name: 'Delay', levels: { 2: ['10 minutes', '1 week'], 3: ['10 minutes', '1 day', '1 week'], 4: ['10 minutes', '1 hour', '1 day', '1 week'] } },
    { name: 'Contrast', levels: { 2: ['low', 'high'], 3: ['low', 'medium', 'high'], 4: ['5%', '10%', '20%', '40%'] } },
    { name: 'Task load', levels: { 2: ['single task', 'dual task'] } },
    { name: 'Feedback', levels: { 2: ['none', 'every trial'], 3: ['none', 'some trials', 'every trial'] } },
    { name: 'Reward', levels: { 2: ['no points', 'points'], 3: ['none', '1 point', '5 points'] } },
    { name: 'Practice day', levels: { 2: ['day 1', 'day 5'], 3: ['day 1', 'day 3', 'day 5'], 4: ['day 1', 'day 2', 'day 3', 'day 4'] } },
    { name: 'Stimulus type', levels: { 2: ['words', 'pictures'], 3: ['words', 'pictures', 'sounds'] } },
    { name: 'Time on task', levels: { 2: ['first 20 min', 'last 20 min'], 3: ['0–20 min', '20–40 min', '40–60 min'], 4: ['0–20 min', '20–40 min', '40–60 min', '60–80 min'] } },
    { name: 'Sleep', levels: { 2: ['sleep', 'stay awake'] } },
    { name: 'Word length', levels: { 2: ['short', 'long'], 3: ['1 syllable', '3 syllables', '5 syllables'] } },
    { name: 'Tone loudness', levels: { 2: ['quiet', 'loud'], 3: ['quiet', 'medium', 'loud'] } },
  ],
};
