// ---------------------------------------------------------------------------
// The Physical sciences pool: chemistry, physics and engineering (and a
// neighbour pool for earth sciences). See pools/README.md for the format.
//
// Studies here are done on samples, solutions, specimens, components and
// circuits, never on people. Roughly a third of the items are shared; the
// rest carry `for` so that chemistry gets reaction rates and titrations,
// physics gets circuits and pendulums, and engineering gets beams, bolts
// and fatigue. Every mechanism is textbook and undisputed, and each
// relation is stated within the range where it holds.
// ---------------------------------------------------------------------------
const PHYS_CHEM = ['chemistry'];
const PHYS_PHYS = ['physics'];
const PHYS_ENG = ['engineering'];
const PHYS_PE = ['physics', 'engineering'];

const PHYS_CONT = 'It can take any value on a scale, including every value in between — ';
const PHYS_DISC = 'It only comes in separate values, with nothing in between — ';

const PHYS_NOM = 'Categorical: distinct outcomes with no order. ';
const PHYS_ORD = 'Ordinal: the outcomes are ranked, but the difference between steps is arbitrary. ';
const PHYS_INT = 'Interval: ranked, with a constant difference between steps, but no natural zero — so values aren\'t "twice as much". ';
const PHYS_RAT = 'Ratio: ranked, constant steps AND a natural zero, so "twice as much" makes sense. ';

const PHYS_TIME = ['time', 'over time', 'week', 'weeks', 'month', 'months', 'year', 'years', 'day', 'days', 'when it was measured', 'time point', 'session', 'before and after'];

POOLS.physical = {
  // -------------------------------------------------------------------------
  // 1a. Variable or not?
  // -------------------------------------------------------------------------
  sortItems: [
    // --- variables: shared ---
    { label: 'temperature', variable: true,
      why: 'Temperature is measured in degrees, and a sample can be hotter or colder.' },
    { label: 'mass of a sample', variable: true,
      why: 'Samples have different masses, and mass is measured on a balance in grams.' },
    { label: 'density', variable: true,
      why: 'Different materials have different densities, and density can be measured — mass divided by volume.' },
    { label: 'pressure', variable: true,
      why: 'Pressure can be higher or lower, and it is measured with a gauge in pascals.' },
    { label: 'volume of a gas', variable: true,
      why: 'A gas can take up more or less space, and its volume can be read off a gas syringe.' },
    { label: 'time taken', variable: true,
      why: 'Some processes take longer than others, and the time can be measured in seconds.' },
    { label: 'hardness of a mineral', variable: true,
      why: 'Some minerals are harder than others, and hardness can be measured with a scratch test.' },
    { label: 'crystal size', variable: true,
      why: 'Crystals grow to different sizes, and they can be measured under a microscope.' },
    { label: 'boiling point of a liquid', variable: true,
      why: 'Different liquids boil at different temperatures, and the same liquid boils at a lower temperature when the pressure is lower.' },

    // --- variables: chemistry ---
    { label: 'reaction rate', variable: true, for: PHYS_CHEM,
      why: 'Reactions go faster or slower depending on conditions, and the rate can be measured.' },
    { label: 'concentration of a solution', variable: true, for: PHYS_CHEM,
      why: 'A solution can be more or less concentrated, measured in moles per dm³.' },
    { label: 'pH', variable: true, for: PHYS_CHEM,
      why: 'Solutions differ in how acidic or alkaline they are, and pH is measured with a meter or indicator.' },
    { label: 'solubility', variable: true, for: PHYS_CHEM,
      why: 'Different amounts of a solid dissolve in water depending on the solid and the temperature, and the amount can be measured in grams per 100 g of water.' },
    { label: 'percentage yield', variable: true, for: PHYS_CHEM,
      why: 'Some preparations give more product than others, and the yield is measured as a percentage of the maximum possible.' },
    { label: 'titre', variable: true, for: PHYS_CHEM,
      why: 'The volume of solution added from the burette differs from one titration to the next, and it is read in cm³.' },
    { label: 'surface area of a solid reactant', variable: true, for: PHYS_CHEM,
      why: 'Powder has more surface area than lumps of the same mass, and surface area can be measured or calculated.' },

    // --- variables: physics ---
    { label: 'electrical resistance', variable: true, for: PHYS_PHYS,
      why: 'Different wires and components have different resistances, measured in ohms.' },
    { label: 'current', variable: true, for: PHYS_PHYS,
      why: 'More or less current can flow in a circuit, and an ammeter measures it in amps.' },
    { label: 'voltage', variable: true, for: PHYS_PHYS,
      why: 'A power supply can be set to different voltages, and a voltmeter measures them in volts.' },
    { label: 'length of a wire', variable: true, for: PHYS_PHYS,
      why: 'Wires can be cut to different lengths, and length is measured in centimetres.' },
    { label: 'period of a pendulum', variable: true, for: PHYS_PHYS,
      why: 'Some pendulums take longer to swing than others, and the time for one swing can be measured in seconds.' },
    { label: 'light intensity', variable: true, for: PHYS_PHYS,
      why: 'Light can be brighter or dimmer, and a light meter measures it.' },
    { label: 'speed of a falling object', variable: true, for: PHYS_PHYS,
      why: 'A falling object speeds up as it falls, and its speed can be measured with a light gate.' },
    { label: 'cooling rate', variable: true, for: PHYS_PHYS,
      why: 'Some objects cool faster than others, and the rate can be measured in degrees per minute.' },
    { label: 'wavelength of light', variable: true, for: PHYS_PHYS,
      why: 'Different colours of light have different wavelengths, measured in nanometres.' },

    // --- variables: physics and engineering ---
    { label: 'extension of a spring', variable: true, for: PHYS_PE,
      why: 'A spring stretches more or less depending on the load, and the extension is measured in millimetres.' },
    { label: 'expansion of a metal rod', variable: true, for: PHYS_PE,
      why: 'A rod gets longer by different amounts as it is heated, and the change in length can be measured.' },

    // --- variables: engineering ---
    { label: 'beam deflection', variable: true, for: PHYS_ENG,
      why: 'A beam bends more or less depending on its load and span, and the deflection is measured in millimetres.' },
    { label: 'breaking load', variable: true, for: PHYS_ENG,
      why: 'Some specimens take a bigger load than others before they break, and the load is measured in newtons.' },
    { label: 'number of loading cycles', variable: true, for: PHYS_ENG,
      why: 'A component can be loaded and unloaded different numbers of times, and the cycles are counted.' },
    { label: 'bolt tightening torque', variable: true, for: PHYS_ENG,
      why: 'A bolt can be tightened more or less, and a torque wrench measures it in newton metres.' },
    { label: 'fan speed', variable: true, for: PHYS_ENG,
      why: 'A fan can run faster or slower, measured in revolutions per minute.' },
    { label: 'airflow', variable: true, for: PHYS_ENG,
      why: 'More or less air can move through a duct, and airflow is measured in cubic metres per second.' },
    { label: 'fatigue crack length', variable: true, for: PHYS_ENG,
      why: 'Cracks in a loaded component can be longer or shorter, and their length can be measured in millimetres.' },

    // --- not variables: one particular thing (shared) ---
    { label: 'the periodic table', variable: false,
      why: 'The periodic table is one particular thing, not a measurement. (The number of elements in a sample would be a variable.)' },
    { label: 'the Sun', variable: false,
      why: 'The Sun is one particular star. (How bright a star is would be a variable.)' },
    { label: 'Isaac Newton', variable: false,
      why: 'Isaac Newton is one particular person. (The force needed to move an object would be a variable.)' },

    // --- not variables: chemistry ---
    { label: 'sodium chloride', variable: false, for: PHYS_CHEM,
      why: 'Sodium chloride is one particular compound. (How much of it dissolves in 100 g of water would be a variable.)' },
    { label: 'Marie Curie', variable: false, for: PHYS_CHEM,
      why: 'Marie Curie is one particular person. (How radioactive a sample is would be a variable.)' },
    { label: 'Dmitri Mendeleev', variable: false, for: PHYS_CHEM,
      why: 'Mendeleev is one particular person. (The atomic mass of an element would be a variable.)' },
    { label: 'the Bunsen burner', variable: false, for: PHYS_CHEM,
      why: 'A Bunsen burner is a piece of equipment, not a measurement. (The temperature of its flame would be a variable.)' },

    // --- not variables: physics ---
    { label: 'the Large Hadron Collider', variable: false, for: PHYS_PHYS,
      why: 'The Large Hadron Collider is one particular machine. (The energy of the particles in it would be a variable.)' },
    { label: 'Ohm\'s law', variable: false, for: PHYS_PHYS,
      why: 'Ohm\'s law is one particular law — a statement, not a measurement. (The current through a resistor would be a variable.)' },
    { label: 'a multimeter', variable: false, for: PHYS_PHYS,
      why: 'A multimeter is an instrument, not a measurement. (The voltage it reads would be a variable.)' },
    { label: 'the Hubble Space Telescope', variable: false, for: PHYS_PHYS,
      why: 'Hubble is one particular telescope. (The distance to a galaxy would be a variable.)' },
    { label: 'Big Ben', variable: false, for: PHYS_PHYS,
      why: 'Big Ben is one particular bell. (How loud a bell rings would be a variable.)' },

    // --- not variables: engineering ---
    { label: 'the Forth Bridge', variable: false, for: PHYS_ENG,
      why: 'The Forth Bridge is one particular bridge. (How far a bridge bends under load would be a variable.)' },
    { label: 'the tensile testing machine', variable: false, for: PHYS_ENG,
      why: 'It\'s one particular machine, not a measurement. (The load a specimen takes before breaking would be a variable.)' },
    { label: 'steel', variable: false, for: PHYS_ENG,
      why: 'Steel is one particular material. (The stiffness of a material would be a variable.)' },

    // --- not variables: measurable, but only one possible value ---
    { label: 'the speed of light in a vacuum', variable: false,
      why: 'It can be measured, but it only ever has one value. A variable needs different possible values — this is a constant.' },
    { label: 'the charge on an electron', variable: false,
      why: 'Every electron carries exactly the same charge, so it has only one possible value. It\'s a constant, not a variable.' },
    { label: 'absolute zero', variable: false,
      why: 'Absolute zero is always −273.15°C, or 0 K. It has only one value, so it\'s a constant.' },
    { label: 'Avogadro\'s constant', variable: false,
      why: 'It\'s the same number every time — it\'s even called a constant. Something with only one value can\'t be a variable.' },
    { label: 'the number of protons in a carbon atom', variable: false,
      why: 'It\'s always 6 — an atom with a different number wouldn\'t be carbon. Only one possible value, so it\'s a constant.' },
  ],

  // -------------------------------------------------------------------------
  // 1b-1d, 2b, 2c. Relations.
  // -------------------------------------------------------------------------
  relations: [
    // --- shared ---
    { id: 'phys-pressure-gasvol', iv: 'pressure', dv: 'volume of a gas', ivNP: 'the pressure', dvNP: 'the volume of a gas',
      hyp: ['pressure', 'gas volume'], ivAxis: 'Pressure', dvAxis: 'Gas volume', dir: 'down',
      says: ['The more pressure you put on a trapped gas, the smaller its volume at the same temperature.',
             'The volume of a trapped gas goes down as the pressure on it goes up.'],
      why: 'The pressure is applied by pushing on the gas; the volume shrinks in response. The volume reading can\'t push on the plunger.' },
    { id: 'phys-temp-gasvol', iv: 'temperature', dv: 'volume of a gas', ivNP: 'the temperature', dvNP: 'the volume of a gas',
      hyp: ['temperature', 'gas volume'], ivAxis: 'Temperature', dvAxis: 'Gas volume', dir: 'up',
      says: ['A gas kept at constant pressure takes up more space when it is heated.',
             'The volume of a gas at constant pressure goes up as its temperature rises.'],
      why: 'Heating the gas makes its particles move faster and push outwards, so the temperature is the changer. Making the syringe bigger doesn\'t heat the gas.' },
    { id: 'phys-temp-dissolve', iv: 'water temperature', dv: 'time to dissolve', ivNP: 'the water temperature', dvNP: 'the time taken to dissolve',
      hyp: ['water temperature', 'dissolving time'], ivAxis: 'Temperature', dvAxis: 'Dissolving time', dir: 'down',
      says: ['Sugar dissolves more quickly in hotter water.',
             'The time sugar takes to dissolve goes down as the water temperature goes up.'],
      why: 'The water is heated before the sugar goes in, so the temperature is the changer. How long the sugar takes can\'t change how hot the water was. Careful with the graph: dissolving faster means a SHORTER time.' },
    { id: 'phys-insulation-cooling', iv: 'insulation thickness', dv: 'cooling rate', ivNP: 'the thickness of insulation', dvNP: 'the cooling rate',
      hyp: ['insulation', 'cooling rate'], ivAxis: 'Insulation', dvAxis: 'Cooling rate', dir: 'down',
      says: ['The thicker the insulation around a beaker of hot water, the more slowly it cools.',
             'The cooling rate goes down as the insulation gets thicker.'],
      why: 'The insulation is wrapped on before the water cools, and it slows the heat escaping. How fast the water cools can\'t change how thick the wrapping is.' },
    { id: 'phys-temp-expansion', iv: 'temperature', dv: 'length of a metal rod', ivNP: 'the temperature', dvNP: 'the length of a metal rod',
      hyp: ['temperature', 'rod length'], ivAxis: 'Temperature', dvAxis: 'Rod length', dir: 'up',
      says: ['A metal rod gets longer when it is heated.',
             'The length of a metal rod goes up as its temperature rises.'],
      why: 'Heating makes the particles in the metal vibrate more and take up more room, so the temperature is the changer. Cutting a longer rod doesn\'t make it hotter.' },

    // --- chemistry ---
    { id: 'phys-temp-rate', for: PHYS_CHEM, iv: 'temperature', dv: 'reaction rate', ivNP: 'the temperature', dvNP: 'the reaction rate',
      hyp: ['temperature', 'reaction rate'], ivAxis: 'Temperature', dvAxis: 'Reaction rate', dir: 'up',
      says: ['Reactions go faster at higher temperatures.',
             'The reaction rate goes up as the temperature rises.'],
      why: 'The temperature is set before the reaction runs; the rate is the result. A fast reaction can\'t change the temperature it was set at.' },
    { id: 'phys-conc-rate', for: PHYS_CHEM, iv: 'acid concentration', dv: 'reaction rate', ivNP: 'the concentration of the acid', dvNP: 'the reaction rate',
      hyp: ['acid concentration', 'reaction rate'], ivAxis: 'Concentration', dvAxis: 'Reaction rate', dir: 'up',
      says: ['Magnesium reacts faster with more concentrated acid.',
             'The reaction rate goes up as the acid gets more concentrated.'],
      why: 'The acid is made up at its concentration before the magnesium goes in. More acid particles mean more collisions, so the concentration is the changer.' },
    { id: 'phys-sa-rate', for: PHYS_CHEM, iv: 'surface area', dv: 'reaction rate', ivNP: 'the surface area of the marble', dvNP: 'the reaction rate',
      hyp: ['surface area', 'reaction rate'], ivAxis: 'Surface area', dvAxis: 'Reaction rate', dir: 'up',
      says: ['Powdered marble reacts faster with acid than the same mass of marble chips.',
             'The reaction rate goes up as the surface area of the marble goes up.'],
      why: 'Grinding the marble is done before the reaction, and more exposed surface means more collisions with acid. The rate can\'t grind the marble.' },
    { id: 'phys-catalyst-rate', for: PHYS_CHEM, iv: 'mass of catalyst', dv: 'rate of oxygen production', ivNP: 'the mass of catalyst', dvNP: 'the rate of oxygen production',
      hyp: ['catalyst', 'oxygen production'], ivAxis: 'Catalyst mass', dvAxis: 'Oxygen rate', dir: 'up',
      says: ['Adding more manganese(IV) oxide makes hydrogen peroxide give off oxygen faster.',
             'Oxygen is produced faster the more manganese(IV) oxide catalyst is added to hydrogen peroxide.'],
      why: 'The chemist weighs out the catalyst and adds it; the oxygen is the result. Producing oxygen faster can\'t add more catalyst to the flask.' },
    { id: 'phys-temp-solubility', for: PHYS_CHEM, iv: 'water temperature', dv: 'solubility of potassium nitrate', ivNP: 'the water temperature', dvNP: 'the solubility of potassium nitrate',
      hyp: ['temperature', 'solubility'], ivAxis: 'Temperature', dvAxis: 'Solubility', dir: 'up',
      says: ['More potassium nitrate dissolves in hot water than in cold water.',
             'The solubility of potassium nitrate goes up as the water gets hotter.'],
      why: 'The water is heated first, and the hotter water can hold more dissolved solid. Dissolving more solid doesn\'t heat the water.' },
    { id: 'phys-temp-gassol', for: PHYS_CHEM, iv: 'water temperature', dv: 'solubility of carbon dioxide', ivNP: 'the water temperature', dvNP: 'the solubility of carbon dioxide',
      hyp: ['temperature', 'CO₂ solubility'], ivAxis: 'Temperature', dvAxis: 'CO₂ solubility', dir: 'down',
      says: ['Less carbon dioxide dissolves in warm water than in cold water.',
             'The solubility of carbon dioxide goes down as the water gets warmer.'],
      why: 'The water temperature is set first; warmer water holds less dissolved gas. Gas escaping from the water doesn\'t warm it up.' },
    { id: 'phys-conc-cloudy', for: PHYS_CHEM, iv: 'thiosulfate concentration', dv: 'time for the cross to disappear', ivNP: 'the concentration of sodium thiosulfate', dvNP: 'the time for the cross to disappear',
      hyp: ['concentration', 'vanishing time'], ivAxis: 'Concentration', dvAxis: 'Time to cloud', dir: 'down',
      says: ['The more concentrated the sodium thiosulfate, the sooner the cross under the flask disappears.',
             'The time for the cross to disappear goes down as the thiosulfate concentration goes up.'],
      why: 'The solution is made up at its concentration before the acid is added. A faster reaction makes the solution go cloudy sooner — a SHORTER time, so the line falls.' },
    { id: 'phys-conc-ph', for: PHYS_CHEM, iv: 'acid concentration', dv: 'pH', ivNP: 'the concentration of hydrochloric acid', dvNP: 'the pH',
      hyp: ['acid concentration', 'pH'], ivAxis: 'Concentration', dvAxis: 'pH', dir: 'down',
      says: ['More concentrated hydrochloric acid has a lower pH.',
             'The pH goes down as the hydrochloric acid gets more concentrated.'],
      why: 'The concentration is how much acid was put in the water; the pH is measured afterwards. Watch the direction: more acid means a LOWER pH number.' },
    { id: 'phys-conc-titre', for: PHYS_CHEM, iv: 'acid concentration', dv: 'titre', ivNP: 'the concentration of the acid', dvNP: 'the titre',
      hyp: ['acid concentration', 'titre'], ivAxis: 'Concentration', dvAxis: 'Titre', dir: 'up',
      says: ['A more concentrated acid needs more alkali from the burette to neutralise the same 25 cm³.',
             'The titre goes up as the acid in the flask gets more concentrated.'],
      why: 'The acid is in the flask before the titration starts; the titre is how much alkali it takes. Adding alkali can\'t change how concentrated the acid was.' },
    { id: 'phys-transfers-yield', for: PHYS_CHEM, iv: 'number of transfers', dv: 'percentage yield', ivNP: 'the number of transfers between containers', dvNP: 'the percentage yield',
      hyp: ['transfers', 'yield'], ivAxis: 'Transfers', dvAxis: 'Yield', dir: 'down',
      says: ['The more times a product is moved between containers, the lower the percentage yield.',
             'The percentage yield goes down as the number of transfers goes up.'],
      why: 'A little product is left behind in every container, so the transfers are the changer. A low yield can\'t make anyone move the product more times.' },

    // --- physics ---
    { id: 'phys-length-resistance', for: PHYS_PHYS, iv: 'wire length', dv: 'resistance', ivNP: 'the length of the wire', dvNP: 'the resistance',
      hyp: ['wire length', 'resistance'], ivAxis: 'Wire length', dvAxis: 'Resistance', dir: 'up',
      says: ['A longer piece of the same wire has a higher resistance.',
             'The resistance goes up as the wire gets longer.'],
      why: 'The wire is cut to length first; its resistance is measured after. A higher reading on the meter can\'t make the wire longer.' },
    { id: 'phys-area-resistance', for: PHYS_PHYS, iv: 'wire thickness', dv: 'resistance', ivNP: 'the thickness of the wire', dvNP: 'the resistance',
      hyp: ['wire thickness', 'resistance'], ivAxis: 'Wire thickness', dvAxis: 'Resistance', dir: 'down',
      says: ['Thicker wire of the same metal and length has a lower resistance.',
             'The resistance goes down as the wire gets thicker.'],
      why: 'The thickness is fixed when the wire is chosen, and a wider wire gives the current more room. The resistance reading can\'t change how thick the wire is.' },
    { id: 'phys-voltage-current', for: PHYS_PHYS, iv: 'voltage', dv: 'current', ivNP: 'the voltage', dvNP: 'the current',
      hyp: ['voltage', 'current'], ivAxis: 'Voltage', dvAxis: 'Current', dir: 'up',
      says: ['Turning up the voltage across a resistor makes more current flow through it.',
             'The current through a resistor goes up as the voltage across it goes up.'],
      why: 'The voltage is set on the power supply, and the current is what flows as a result. The ammeter reading can\'t turn the supply\'s dial.' },
    { id: 'phys-resistance-current', for: PHYS_PHYS, iv: 'resistance', dv: 'current', ivNP: 'the resistance', dvNP: 'the current',
      hyp: ['resistance', 'current'], ivAxis: 'Resistance', dvAxis: 'Current', dir: 'down',
      says: ['With the same battery, a bigger resistance lets less current flow.',
             'The current in the circuit goes down as the resistance goes up.'],
      why: 'The resistor is chosen and put in the circuit first; the current is the result. Less current flowing can\'t swap in a bigger resistor.' },
    { id: 'phys-pendulum', for: PHYS_PHYS, iv: 'pendulum length', dv: 'period', ivNP: 'the length of the pendulum', dvNP: 'the period',
      hyp: ['pendulum length', 'period'], ivAxis: 'Pendulum length', dvAxis: 'Period', dir: 'up',
      says: ['A longer pendulum takes longer to complete each swing.',
             'The period of a pendulum goes up as its string gets longer.'],
      why: 'The string is set to its length before the pendulum swings; the period is the result. Timing a slow swing can\'t lengthen the string.' },
    { id: 'phys-height-speed', for: PHYS_PHYS, iv: 'drop height', dv: 'speed at the ground', ivNP: 'the drop height', dvNP: 'the speed at the ground',
      hyp: ['drop height', 'impact speed'], ivAxis: 'Drop height', dvAxis: 'Impact speed', dir: 'up',
      says: ['A ball dropped from higher up is moving faster when it reaches the ground.',
             'The speed of a ball at the ground goes up with the height it is dropped from.'],
      why: 'The height is chosen before the ball is let go, and a longer fall gives gravity longer to speed it up. Its landing speed can\'t go back and change where it started.' },
    { id: 'phys-distance-light', for: PHYS_PHYS, iv: 'distance from the lamp', dv: 'light intensity', ivNP: 'the distance from the lamp', dvNP: 'the light intensity',
      hyp: ['distance', 'light intensity'], ivAxis: 'Distance', dvAxis: 'Light intensity', dir: 'down',
      says: ['The further a light meter is from a lamp, the lower the light intensity it reads.',
             'Light intensity goes down as the distance from the lamp goes up.'],
      why: 'The meter is placed at its distance first, and the light spreads out over a bigger area the further it travels. A dim reading can\'t move the meter.' },
    { id: 'phys-starttemp-cooling', for: PHYS_PHYS, iv: 'starting temperature', dv: 'cooling rate', ivNP: 'the starting temperature of the water', dvNP: 'the cooling rate',
      hyp: ['starting temperature', 'cooling rate'], ivAxis: 'Starting temp', dvAxis: 'Cooling rate', dir: 'up',
      says: ['In the same room, hotter water cools faster than warm water at first.',
             'The cooling rate goes up with the starting temperature of the water.'],
      why: 'The water is heated before it is left to cool, and a bigger difference from the room drives heat out faster. How fast it cools can\'t change how hot it started.' },
    { id: 'phys-mass-accel', for: PHYS_PE, iv: 'mass', dv: 'acceleration', ivNP: 'the mass of the trolley', dvNP: 'the acceleration',
      hyp: ['mass', 'acceleration'], ivAxis: 'Mass', dvAxis: 'Acceleration', dir: 'down',
      says: ['Pulled by the same force, a heavier trolley speeds up more slowly.',
             'The acceleration of a trolley goes down as its mass goes up, for the same force.'],
      why: 'Masses are loaded on the trolley before it is pulled; the acceleration is the result. Speeding up slowly can\'t add mass to the trolley.' },
    { id: 'phys-load-extension', for: PHYS_PE, iv: 'load', dv: 'spring extension', ivNP: 'the load', dvNP: 'the extension of the spring',
      hyp: ['load', 'extension'], ivAxis: 'Load', dvAxis: 'Extension', dir: 'up',
      says: ['Up to its elastic limit, a spring stretches further the more weight is hung on it.',
             'The extension of a spring goes up as the load on it goes up.'],
      why: 'The weights are hung on first, and the spring stretches in response. Pulling a spring longer by hand doesn\'t add weights to it.' },

    // --- engineering ---
    { id: 'phys-span-deflection', for: PHYS_ENG, iv: 'beam span', dv: 'deflection', ivNP: 'the span of the beam', dvNP: 'the deflection',
      hyp: ['span', 'deflection'], ivAxis: 'Beam span', dvAxis: 'Deflection', dir: 'up',
      says: ['Under the same load, a beam bends more when its supports are further apart.',
             'The deflection of a beam goes up as its span gets longer.'],
      why: 'The supports are set up first, and a longer span gives the load more leverage. How far the beam bends can\'t move the supports.' },
    { id: 'phys-load-deflection', for: PHYS_ENG, iv: 'load', dv: 'deflection', ivNP: 'the load on the beam', dvNP: 'the deflection',
      hyp: ['load', 'deflection'], ivAxis: 'Load', dvAxis: 'Deflection', dir: 'up',
      says: ['A beam bends further the heavier the load placed on it.',
             'Beam deflection goes up as the load goes up.'],
      why: 'The load is placed on the beam, and the beam bends in response. Bending the beam by hand doesn\'t put more weight on it.' },
    { id: 'phys-depth-deflection', for: PHYS_ENG, iv: 'beam depth', dv: 'deflection', ivNP: 'the depth of the beam', dvNP: 'the deflection',
      hyp: ['beam depth', 'deflection'], ivAxis: 'Beam depth', dvAxis: 'Deflection', dir: 'down',
      says: ['A deeper beam of the same material bends less under the same load.',
             'The deflection goes down as the beam gets deeper.'],
      why: 'The beam\'s depth is fixed when it is made; the bending is how it responds to the load. Bending less can\'t make a beam deeper.' },
    { id: 'phys-area-breakload', for: PHYS_ENG, iv: 'cross-sectional area', dv: 'breaking load', ivNP: 'the cross-sectional area of the rod', dvNP: 'the breaking load',
      hyp: ['cross-sectional area', 'breaking load'], ivAxis: 'Rod thickness', dvAxis: 'Breaking load', dir: 'up',
      says: ['A thicker steel rod takes a bigger pull before it snaps.',
             'The breaking load of a rod goes up as its cross-sectional area goes up.'],
      why: 'The rod is made at its thickness before it is tested, and more material carries more load. The load at which it breaks can\'t change how thick it was.' },
    { id: 'phys-cycles-crack', for: PHYS_ENG, iv: 'number of loading cycles', dv: 'fatigue crack length', ivNP: 'the number of loading cycles', dvNP: 'the length of the fatigue crack',
      hyp: ['loading cycles', 'crack length'], ivAxis: 'Loading cycles', dvAxis: 'Crack length', dir: 'up',
      says: ['A fatigue crack in a metal specimen grows longer the more times it is loaded and unloaded.',
             'Fatigue crack length goes up with the number of loading cycles.'],
      why: 'Each loading cycle pushes the crack a little further, so the cycles are the changer. A longer crack can\'t go back and add cycles.' },
    { id: 'phys-torque-clamp', for: PHYS_ENG, iv: 'tightening torque', dv: 'clamping force', ivNP: 'the tightening torque', dvNP: 'the clamping force',
      hyp: ['torque', 'clamping force'], ivAxis: 'Bolt torque', dvAxis: 'Clamping force', dir: 'up',
      says: ['Tightening a bolt to a higher torque clamps the joint together harder.',
             'The clamping force in a bolted joint goes up as the tightening torque goes up.'],
      why: 'The torque wrench turns the bolt, and the bolt stretches and squeezes the joint as a result. The clamping force can\'t turn the wrench.' },
    { id: 'phys-fan-airflow', for: PHYS_ENG, iv: 'fan speed', dv: 'airflow', ivNP: 'the fan speed', dvNP: 'the airflow',
      hyp: ['fan speed', 'airflow'], ivAxis: 'Fan speed', dvAxis: 'Airflow', dir: 'up',
      says: ['A fan moves more air through a duct when it spins faster.',
             'Airflow through the duct goes up as the fan speed goes up.'],
      why: 'The fan\'s speed is set on its controller, and the moving blades push the air. The air moving through the duct doesn\'t set the controller.' },
    { id: 'phys-pipe-pressuredrop', for: PHYS_ENG, iv: 'pipe diameter', dv: 'pressure drop', ivNP: 'the diameter of the pipe', dvNP: 'the pressure drop along the pipe',
      hyp: ['pipe diameter', 'pressure drop'], ivAxis: 'Pipe diameter', dvAxis: 'Pressure drop', dir: 'down',
      says: ['For the same flow of water, a wider pipe loses less pressure along its length.',
             'The pressure drop along a pipe goes down as the pipe gets wider, for the same flow.'],
      why: 'The pipe is chosen and fitted first, and a wider pipe lets the water move more slowly with less friction. The pressure gauges can\'t change the pipe\'s width.' },
  ],

  // -------------------------------------------------------------------------
  // 2a. Validity and reliability.
  // -------------------------------------------------------------------------
  validity: [
    // valid and reliable
    { valid: true, reliable: true,
      text: 'To measure the mass of a sample, a technician uses a calibrated digital balance. Weighing the same sample again gives the same reading to 0.001 g.',
      whyValid: 'a calibrated balance measures mass directly.',
      whyReliable: 'weighing it again gives the same reading.' },
    { valid: true, reliable: true,
      text: 'To find out whether sodium reacts with water, a chemist drops a small piece into water three times. It fizzes and moves around the surface every time.',
      whyValid: 'dropping sodium in water and watching is the direct way to see whether it reacts.',
      whyReliable: 'every repeat gives the same result. With an effect this obvious, three tests is enough.' },
    { valid: true, reliable: true, for: PHYS_CHEM,
      text: 'To measure the rate of a reaction, a chemist collects the gas it gives off in a gas syringe and reads the volume every 10 seconds. Repeating the reaction with fresh reactants gives almost the same volumes.',
      whyValid: 'the volume of gas given off each second tracks how fast the reaction is going.',
      whyReliable: 'repeating it gives almost the same volumes.' },
    { valid: true, reliable: true, for: PHYS_PHYS,
      text: 'To measure the resistance of a wire, a physicist connects it to a calibrated digital multimeter. Repeated readings of the same wire agree to 0.01 Ω.',
      whyValid: 'a multimeter set to ohms measures resistance directly.',
      whyReliable: 'repeated readings agree closely.' },
    { valid: true, reliable: true, for: PHYS_ENG,
      text: 'To measure how far a beam bends, an engineer fixes a dial gauge under its middle and loads it. Loading the same beam again gives the same reading.',
      whyValid: 'a dial gauge under the beam measures exactly how far it moves down.',
      whyReliable: 'loading it again gives the same reading.' },

    // reliable, not valid
    { valid: false, reliable: true,
      text: 'To measure how well a material insulates, researchers weigh a sheet of it. The balance gives the same mass every time.',
      whyValid: 'how heavy a material is isn\'t how well it keeps heat in — some very light materials insulate very well.',
      whyReliable: 'weighing it again gives the same mass. Consistent, but consistently measuring the wrong thing.' },
    { valid: false, reliable: true, for: PHYS_CHEM,
      text: 'To measure how concentrated a salt solution is, a student reads the volume of solution in the flask. The reading is the same every time.',
      whyValid: 'the volume of solution says nothing about how much salt is dissolved in it.',
      whyReliable: 'reading the flask again gives the same volume.' },
    { valid: false, reliable: true, for: PHYS_PHYS,
      text: 'To measure the temperature of a liquid, a student reads the volume mark on the side of the beaker. Everyone who reads it gets the same number.',
      whyValid: 'the volume of the liquid isn\'t its temperature.',
      whyReliable: 'anyone who reads it gets the same number.' },
    { valid: false, reliable: true, for: PHYS_ENG,
      text: 'To measure how strong a steel rod is, an engineer measures its length with a steel rule. The rule gives the same length every time.',
      whyValid: 'a rod\'s length doesn\'t tell you what load it can take before breaking.',
      whyReliable: 'measuring it again gives the same length.' },

    // valid, not reliable
    { valid: true, reliable: false,
      text: 'Researchers test a crystal-growing method that works well, but their report doesn\'t say what concentration, temperature or cooling time they used. Other labs who try to repeat it get very different crystals.',
      whyValid: 'growing crystals and measuring them is the right way to test a crystal-growing method.',
      whyReliable: 'without a full "recipe" — amounts, temperatures, times — nobody can repeat the study and get the same result.' },
    { valid: true, reliable: false, for: PHYS_CHEM,
      text: 'To find the end point of a titration, one inexperienced student judges the colour change by eye in dim light. Repeat titrations of the same solutions give titres that differ by several cm³.',
      whyValid: 'the indicator\'s colour change does mark the end point.',
      whyReliable: 'the titres vary a lot from one attempt to the next, because the colour change is hard to judge in dim light.' },
    { valid: true, reliable: false, for: PHYS_PHYS,
      text: 'To measure how long a ball takes to fall 1 m, a student uses a hand-held stopwatch. The same drop gets quite different times depending on how quickly the student reacts.',
      whyValid: 'timing the fall is the right thing to measure.',
      whyReliable: 'the times depend on the student\'s thumb, not just on the ball.' },
    { valid: true, reliable: false, for: PHYS_PHYS,
      text: 'To measure the period of a pendulum, a student times a single swing by eye. Timing the same pendulum again gives a noticeably different answer each time.',
      whyValid: 'timing a swing does measure the period.',
      whyReliable: 'one swing is too short to time accurately by hand — timing ten swings and dividing would be far more consistent.' },
    { valid: true, reliable: false, for: PHYS_ENG,
      text: 'To find out whether a new alloy is slightly stronger than the old one, engineers break one bar of each. When they break another bar of each, the result comes out the other way.',
      whyValid: 'breaking bars and recording the load is the right way to measure strength.',
      whyReliable: 'repeating it with another bar gives a different answer. For a small difference like this, one specimen of each is far too few.' },

    // neither
    { valid: false, reliable: false,
      text: 'To measure how hard a metal is, researchers ask a student to guess a number between 1 and 100. The student guesses a different number every time.',
      whyValid: 'a guess has nothing to do with how hard the metal is.',
      whyReliable: 'the student gives a different number every time.' },
    { valid: false, reliable: false, for: PHYS_CHEM,
      text: 'To measure how fast a reaction goes, researchers record the colour of the lab coat worn by whoever runs it. People wear different coats on different days.',
      whyValid: 'a lab coat colour has nothing to do with reaction rate.',
      whyReliable: 'the same reaction gets a different "result" every day.' },
    { valid: false, reliable: false, for: PHYS_PHYS,
      text: 'To measure how stiff a spring is, researchers note the weather outside the lab. The weather is different every time the same spring is tested.',
      whyValid: 'the weather isn\'t a measure of how stiff the spring is.',
      whyReliable: 'the same spring gets a different result every test.' },
    { valid: false, reliable: false, for: PHYS_ENG,
      text: 'To measure how well a bolted joint holds, researchers time how long a technician takes to walk to the store room for the bolts. The time varies a lot from day to day.',
      whyValid: 'walking time has nothing to do with how well the joint holds.',
      whyReliable: 'the same joint gets very different times on different days.' },
  ],

  // -------------------------------------------------------------------------
  // 2d. Continuous or discrete.
  // -------------------------------------------------------------------------
  continuity: [
    // continuous: shared
    { cat: 'cont', label: 'mass of a sample', why: PHYS_CONT + '2.5 g, 2.51 g, 2.513 g...' },
    { cat: 'cont', label: 'temperature of a solution', why: PHYS_CONT + '20°C, 20.5°C, 20.51°C...' },
    { cat: 'cont', label: 'density of a material', why: PHYS_CONT + '2.70 g/cm³, 2.705 g/cm³... there\'s always a value in between.' },
    { cat: 'cont', label: 'volume of gas collected', why: PHYS_CONT + '45 cm³, 45.5 cm³... volume can always be measured more finely.' },
    { cat: 'cont', label: 'time taken for a sample to melt', why: PHYS_CONT + 'time can always be divided further.' },
    { cat: 'cont', label: 'average number of bubbles per minute', why: PHYS_CONT + 'a single minute can\'t have 12.4 bubbles, but an average across several minutes can.' },
    // continuous: chemistry
    { cat: 'cont', label: 'pH of a solution', for: PHYS_CHEM, why: PHYS_CONT + 'pH 4.2, 4.25, 4.253...' },
    { cat: 'cont', label: 'concentration of an acid', for: PHYS_CHEM, why: PHYS_CONT + '0.1, 0.15, 0.152 mol/dm³...' },
    { cat: 'cont', label: 'percentage yield', for: PHYS_CHEM, why: PHYS_CONT + '72%, 72.4%, 72.45%...' },
    { cat: 'cont', label: 'titre', for: PHYS_CHEM, why: PHYS_CONT + '23.40 cm³, 23.45 cm³... the burette is only read to 0.05 cm³, but the volume itself can be anything.' },
    // continuous: physics
    { cat: 'cont', label: 'current in a circuit', for: PHYS_PHYS, why: PHYS_CONT + '0.2 A, 0.25 A, 0.253 A...' },
    { cat: 'cont', label: 'length of a wire', for: PHYS_PHYS, why: PHYS_CONT + 'length can always be measured more finely.' },
    { cat: 'cont', label: 'period of a pendulum', for: PHYS_PHYS, why: PHYS_CONT + '1.4 s, 1.42 s, 1.421 s...' },
    { cat: 'cont', label: 'light intensity', for: PHYS_PHYS, why: PHYS_CONT + 'a light meter can read any value on its scale.' },
    { cat: 'cont', label: 'speed of a falling ball', for: PHYS_PHYS, why: PHYS_CONT + '4.4 m/s, 4.43 m/s...' },
    // continuous: physics and engineering
    { cat: 'cont', label: 'extension of a spring', for: PHYS_PE, why: PHYS_CONT + '12 mm, 12.5 mm, 12.53 mm...' },
    // continuous: engineering
    { cat: 'cont', label: 'beam deflection', for: PHYS_ENG, why: PHYS_CONT + '3.2 mm, 3.25 mm... a beam can bend by any amount.' },
    { cat: 'cont', label: 'fatigue crack length', for: PHYS_ENG, why: PHYS_CONT + 'a crack can be 1.2 mm, 1.25 mm, 1.253 mm long...' },
    { cat: 'cont', label: 'airflow through a duct', for: PHYS_ENG, why: PHYS_CONT + '0.50, 0.505, 0.5053 m³/s...' },

    // discrete: shared
    { cat: 'disc', label: 'number of repeats of an experiment', why: PHYS_DISC + 'you can repeat it 3 times or 4, not 3.5.' },
    { cat: 'disc', label: 'number of protons in an atom', why: PHYS_DISC + 'an atom has 6 protons or 7, never 6.5.' },
    { cat: 'disc', label: 'number of specimens tested', why: PHYS_DISC + 'specimens are counted in whole numbers.' },
    { cat: 'disc', label: 'number of bubbles in one minute', why: PHYS_DISC + 'each bubble is counted once: 12 or 13, never 12.4.' },
    // discrete: chemistry
    { cat: 'disc', label: 'number of drops of indicator added', for: PHYS_CHEM, why: PHYS_DISC + 'drops are counted: 2 or 3, not 2.5.' },
    { cat: 'disc', label: 'number of carbon atoms in a molecule', for: PHYS_CHEM, why: PHYS_DISC + 'a molecule has 3 carbon atoms or 4, nothing in between.' },
    { cat: 'disc', label: 'number of times a precipitate is washed', for: PHYS_CHEM, why: PHYS_DISC + 'each wash is counted once.' },
    // discrete: physics
    { cat: 'disc', label: 'number of turns on a coil', for: PHYS_PHYS, why: PHYS_DISC + 'turns are counted in whole numbers.' },
    { cat: 'disc', label: 'number of cells in a battery', for: PHYS_PHYS, why: PHYS_DISC + 'a battery has 2 cells or 3, not 2.5.' },
    { cat: 'disc', label: 'number of bulbs in a circuit', for: PHYS_PHYS, why: PHYS_DISC + 'bulbs are counted one by one.' },
    { cat: 'disc', label: 'number of complete swings in 30 seconds', for: PHYS_PHYS, why: PHYS_DISC + 'complete swings are counted: 21 or 22.' },
    // discrete: physics and engineering
    { cat: 'disc', label: 'number of charge cycles a battery has had', for: PHYS_PE, why: PHYS_DISC + 'each charge cycle is counted once.' },
    // discrete: engineering
    { cat: 'disc', label: 'number of loading cycles before failure', for: PHYS_ENG, why: PHYS_DISC + 'cycles are counted: 10,000 or 10,001, never 10,000.5.' },
    { cat: 'disc', label: 'number of fatigue cracks in a component', for: PHYS_ENG, why: PHYS_DISC + 'cracks are counted in whole numbers.' },
    { cat: 'disc', label: 'number of bolts in a joint', for: PHYS_ENG, why: PHYS_DISC + 'a joint has 4 bolts or 6, not 4.5.' },
    { cat: 'disc', label: 'number of blades on a fan', for: PHYS_ENG, why: PHYS_DISC + 'a fan has 3 blades or 5, nothing in between.' },
  ],

  // -------------------------------------------------------------------------
  // 2e. Levels of measurement.
  // -------------------------------------------------------------------------
  measurement: [
    // categorical
    { cat: 'categorical', label: 'type of metal (copper, iron, aluminium)', why: PHYS_NOM + 'Copper isn\'t more or less than iron, just different.' },
    { cat: 'categorical', label: 'type of rock (igneous, sedimentary, metamorphic)', why: PHYS_NOM + 'These are kinds of rock, not amounts of rock.' },
    { cat: 'categorical', label: 'which lab bench a sample was tested on', why: PHYS_NOM + 'Bench A and bench B are labels, not amounts.' },
    { cat: 'categorical', label: 'type of chemical bond (ionic, covalent, metallic)', for: PHYS_CHEM, why: PHYS_NOM + 'An ionic bond isn\'t more than a covalent one, just a different kind.' },
    { cat: 'categorical', label: 'which indicator is used', for: PHYS_CHEM, why: PHYS_NOM + 'Methyl orange and phenolphthalein are different indicators, not ranked ones.' },
    { cat: 'categorical', label: 'series or parallel circuit', for: PHYS_PHYS, why: PHYS_NOM + 'Series isn\'t more than parallel, just a different arrangement.' },
    { cat: 'categorical', label: 'type of joint (welded, bolted, glued)', for: PHYS_ENG, why: PHYS_NOM + 'These are ways of joining, with no order between them.' },

    // ordinal
    { cat: 'ordinal', label: 'Mohs hardness (1 to 10)', why: PHYS_ORD + 'The numbers are ranks from a scratch test: diamond (10) is far harder than corundum (9), much more than one step above it.' },
    { cat: 'ordinal', label: 'corrosion rated none, light, moderate or severe', why: PHYS_ORD + 'The ratings are in order, but "light" to "moderate" needn\'t be the same amount of rust as "moderate" to "severe".' },
    { cat: 'ordinal', label: 'how cloudy a solution looks (clear, cloudy, opaque)', why: PHYS_ORD + 'The labels are in order, but the steps aren\'t equal-sized.' },
    { cat: 'ordinal', label: 'ranking metals from most to least reactive', for: PHYS_CHEM, why: PHYS_ORD + 'A ranking gives the order, not how far apart the metals are.' },
    { cat: 'ordinal', label: 'finishing order of three trolleys down a ramp', for: PHYS_PHYS, why: PHYS_ORD + 'The gap between 1st and 2nd could be a tenth of a second; between 2nd and 3rd, a whole second.' },
    { cat: 'ordinal', label: 'surface finish graded rough, medium or smooth', for: PHYS_ENG, why: PHYS_ORD + 'The grades are in order, but nothing says the steps are the same size.' },

    // interval
    { cat: 'interval', label: 'temperature in °C', why: PHYS_INT + '0°C isn\'t "no temperature", so 20°C isn\'t twice as hot as 10°C.' },
    { cat: 'interval', label: 'date a sample was tested', why: PHYS_INT + 'Days are equal steps, but the calendar\'s starting point is arbitrary.' },
    { cat: 'interval', label: 'time of day a reading was taken', why: PHYS_INT + 'The minutes are equal, but midnight isn\'t "no time", so 4 o\'clock isn\'t twice 2 o\'clock.' },
    { cat: 'interval', label: 'temperature in °F', why: PHYS_INT + '0°F isn\'t "no heat", so 80°F isn\'t twice as hot as 40°F.' },
    { cat: 'interval', label: 'surface finish rated on a 1–7 scale', for: PHYS_ENG, why: PHYS_INT + 'A numbered scale has constant steps, but no natural zero, so a 6 isn\'t "twice as smooth" as a 3.' },
    { cat: 'interval', label: 'year a sample was collected', for: PHYS_CHEM, why: PHYS_INT + 'The gap between years is equal, but year 0 isn\'t the beginning of time, so 2000 isn\'t "twice" 1000.' },

    // ratio
    { cat: 'ratio', label: 'temperature in kelvin', why: PHYS_RAT + 'Unlike °C, 0 K really is no heat at all — so 300 K is twice 150 K.' },
    { cat: 'ratio', label: 'mass in grams', why: PHYS_RAT + '0 g is no mass at all, and 10 g is twice 5 g.' },
    { cat: 'ratio', label: 'time in seconds', why: PHYS_RAT + '0 s is no time, and 40 s is twice 20 s.' },
    { cat: 'ratio', label: 'volume of gas in cm³', for: PHYS_CHEM, why: PHYS_RAT + '0 cm³ is no gas, and 60 cm³ is twice 30 cm³.' },
    { cat: 'ratio', label: 'current in amps', for: PHYS_PHYS, why: PHYS_RAT + '0 A is no current, and 2 A is twice 1 A.' },
    { cat: 'ratio', label: 'resistance in ohms', for: PHYS_PHYS, why: PHYS_RAT + '0 Ω is no resistance, and 10 Ω is twice 5 Ω.' },
    { cat: 'ratio', label: 'load in newtons', for: PHYS_ENG, why: PHYS_RAT + '0 N is no load, and 800 N is twice 400 N.' },
    { cat: 'ratio', label: 'beam deflection in mm', for: PHYS_ENG, why: PHYS_RAT + '0 mm is no bending at all, and 6 mm is twice 3 mm.' },
  ],

  // -------------------------------------------------------------------------
  // 2g. Confounds. Pairs: the same study done badly, then properly.
  // -------------------------------------------------------------------------
  confounds: [
    // --- with a confound: shared ---
    { iv: 'water temperature', dv: 'time to dissolve', confound: 'stirring',
      vars: ['water temperature', 'time to dissolve', 'stirring', 'the mass of sugar'],
      text: 'Researchers test whether water temperature affects how quickly sugar dissolves, using 5 g of sugar each time. The beakers of hot water are stirred; the beakers of cold water are left still.',
      why: 'The hot beakers were also stirred, and stirring makes sugar dissolve faster whatever the temperature. The difference could be the stirring, not the temperature.' },
    { iv: 'type of metal', dv: 'time for the wax to melt', confound: 'rod length',
      vars: ['type of metal', 'time for the wax to melt', 'rod length', 'the Bunsen burner'],
      text: 'To compare how well copper and steel conduct heat, researchers heat one end of each rod with the same Bunsen burner and time how long wax at the other end takes to melt. The copper rods are 10 cm long; the steel rods are 30 cm long.',
      why: 'The copper rods were also much shorter, so heat had less far to travel. The wax could melt sooner because of the length, not the metal.' },
    { iv: 'insulation thickness', dv: 'cooling rate', confound: 'starting temperature',
      vars: ['insulation thickness', 'cooling rate', 'starting temperature', 'the volume of water'],
      text: 'Researchers test whether thicker insulation slows cooling, using 200 cm³ of water in each beaker. The thickly wrapped beakers are filled with water at 60°C, and the thinly wrapped ones with water at 90°C.',
      why: 'The thinly wrapped beakers also started much hotter, and hotter water cools faster anyway. The difference could come from the starting temperature, not the insulation.' },
    { iv: 'cooling speed', dv: 'crystal size', confound: 'concentration of the solution',
      vars: ['cooling speed', 'crystal size', 'concentration of the solution', 'the type of salt'],
      text: 'Researchers test whether slow cooling gives bigger crystals of the same salt. The slowly cooled dishes hold a concentrated solution; the quickly cooled dishes hold a dilute one.',
      why: 'The slowly cooled dishes also had more salt in them to form crystals. Bigger crystals could come from the concentration, not the cooling speed.' },

    // --- with a confound: chemistry ---
    { for: PHYS_CHEM, iv: 'temperature', dv: 'reaction rate', confound: 'acid concentration',
      vars: ['temperature', 'reaction rate', 'acid concentration', 'the mass of magnesium'],
      text: 'To test whether temperature affects how fast magnesium reacts with acid, a chemist uses the same mass of magnesium ribbon each time. The warm runs use 2 mol/dm³ acid; the cold runs use 1 mol/dm³ acid.',
      why: 'The warm runs also used more concentrated acid, which speeds the reaction up by itself. The difference could be the concentration, not the temperature.' },
    { for: PHYS_CHEM, iv: 'surface area', dv: 'reaction rate', confound: 'lab temperature',
      vars: ['surface area', 'reaction rate', 'lab temperature', 'the volume of acid'],
      text: 'A chemist compares powdered marble and marble chips reacting with 50 cm³ of acid. The powder runs are done on a hot afternoon at 30°C; the chip runs on a cold morning at 15°C.',
      why: 'The powder was also tested in a warmer lab, and reactions go faster when warm. The difference could be the temperature, not the surface area.' },
    { for: PHYS_CHEM, iv: 'catalyst', dv: 'rate of oxygen production', confound: 'hydrogen peroxide concentration',
      vars: ['catalyst', 'rate of oxygen production', 'hydrogen peroxide concentration', 'the volume of hydrogen peroxide'],
      text: 'To test a catalyst, a chemist adds it to 20 cm³ of fresh hydrogen peroxide and compares the result with 20 cm³ of more dilute hydrogen peroxide with no catalyst.',
      why: 'The catalyst runs also used more concentrated peroxide, which gives off oxygen faster anyway. The difference could be the concentration, not the catalyst.' },

    // --- with a confound: physics ---
    { for: PHYS_PHYS, iv: 'wire length', dv: 'resistance', confound: 'wire thickness',
      vars: ['wire length', 'resistance', 'wire thickness', 'the multimeter'],
      text: 'To test whether longer wires have more resistance, a physicist measures each wire with the same multimeter. All the long wires are thin, and all the short wires are thick.',
      why: 'Thin wires have more resistance whatever their length, so the difference could come from the thickness, not the length.' },
    { for: PHYS_PHYS, iv: 'drop height', dv: 'speed at the ground', confound: 'type of ball',
      vars: ['drop height', 'speed at the ground', 'type of ball', 'the light gate'],
      text: 'To test whether drop height affects landing speed, a physicist times each ball through the same light gate. Steel balls are dropped from 2 m, and table-tennis balls from 1 m.',
      why: 'Air resistance slows a light table-tennis ball much more than a steel ball, so the difference could come from the type of ball, not the height.' },

    // --- with a confound: engineering ---
    { for: PHYS_ENG, iv: 'beam span', dv: 'deflection', confound: 'beam material',
      vars: ['beam span', 'deflection', 'beam material', 'the load'],
      text: 'To test whether span affects deflection, an engineer puts the same load on each beam. The long-span beams are aluminium and the short-span beams are steel.',
      why: 'Aluminium bends more than steel under the same load, so the difference could come from the material, not the span.' },
    { for: PHYS_ENG, iv: 'cross-sectional area', dv: 'breaking load', confound: 'alloy',
      vars: ['cross-sectional area', 'breaking load', 'alloy', 'the testing machine'],
      text: 'Engineers test whether thicker rods take a bigger load before breaking, using the same testing machine. The thick rods are made from a high-strength alloy and the thin rods from ordinary mild steel.',
      why: 'The thick rods were also made of a stronger alloy, so they could hold more because of the material, not the thickness.' },
    { for: PHYS_ENG, iv: 'number of loading cycles', dv: 'fatigue crack length', confound: 'load size',
      vars: ['number of loading cycles', 'fatigue crack length', 'load size', 'the specimen material'],
      text: 'Engineers test whether more loading cycles give longer fatigue cracks in aluminium specimens. The specimens given 100,000 cycles are loaded twice as hard as those given 10,000.',
      why: 'The specimens with more cycles were also loaded harder, and a bigger load grows cracks faster. The difference could come from the load, not the number of cycles.' },

    // --- without a confound ---
    { iv: 'water temperature', dv: 'time to dissolve', confound: null,
      text: 'Researchers test whether water temperature affects how quickly sugar dissolves. Every beaker gets 5 g of the same sugar and is stirred at the same speed; only the water temperature differs.',
      why: 'Same sugar, same amount, same stirring — the temperature is the only thing that differs.' },
    { iv: 'type of metal', dv: 'time for the wax to melt', confound: null,
      text: 'To compare how well copper and steel conduct heat, researchers use rods of exactly the same length and thickness, heated by the same burner, and time how long wax at the far end takes to melt.',
      why: 'The rods are matched for size and heated the same way, so the metal is the only difference.' },
    { iv: 'insulation thickness', dv: 'cooling rate', confound: null,
      text: 'Researchers test whether thicker insulation slows cooling. Every beaker is filled with 200 cm³ of water at 80°C and left in the same room; only the thickness of the wrapping differs.',
      why: 'Same volume, same starting temperature, same room — only the insulation differs.' },
    { iv: 'cooling speed', dv: 'crystal size', confound: null,
      text: 'Researchers split one batch of salt solution between several dishes. Dishes chosen at random are cooled quickly in ice, and the rest slowly on the bench, and the crystals are measured.',
      why: 'Every dish holds the same solution, so the cooling speed is the only thing that differs.' },
    { for: PHYS_CHEM, iv: 'temperature', dv: 'reaction rate', confound: null,
      text: 'To test whether temperature affects how fast magnesium reacts with acid, a chemist uses the same mass of ribbon and the same 1 mol/dm³ acid every time, changing only the temperature of the water bath.',
      why: 'The magnesium and acid are identical in every run, so only the temperature differs.' },
    { for: PHYS_CHEM, iv: 'surface area', dv: 'reaction rate', confound: null,
      text: 'A chemist compares powdered marble and marble chips of the same mass, reacting with the same acid in a water bath held at 25°C, with the order of the runs chosen at random.',
      why: 'Same mass, same acid, same temperature, random order — only the surface area differs.' },
    { for: PHYS_CHEM, iv: 'catalyst', dv: 'rate of oxygen production', confound: null,
      text: 'To test a catalyst, a chemist pours 20 cm³ portions from one bottle of hydrogen peroxide into flasks, and adds the catalyst to half of them, chosen at random.',
      why: 'Every flask gets the same peroxide from the same bottle, so the catalyst is the only difference.' },
    { for: PHYS_PHYS, iv: 'wire length', dv: 'resistance', confound: null,
      text: 'To test whether longer wires have more resistance, a physicist cuts every wire from the same reel, so all are the same metal and thickness, and measures each with the same multimeter.',
      why: 'Cutting everything from one reel keeps the thickness and metal the same, so only the length differs.' },
    { for: PHYS_PHYS, iv: 'drop height', dv: 'speed at the ground', confound: null,
      text: 'To test whether drop height affects landing speed, a physicist drops the same steel ball from each height and times it through the same light gate.',
      why: 'The same ball is used every time, so only the height differs.' },
    { for: PHYS_ENG, iv: 'beam span', dv: 'deflection', confound: null,
      text: 'To test whether span affects deflection, an engineer uses identical steel beams from the same batch, puts the same load on each, and changes only the distance between the supports.',
      why: 'The beams and loads are identical, so the span is the only difference.' },
    { for: PHYS_ENG, iv: 'cross-sectional area', dv: 'breaking load', confound: null,
      text: 'Engineers test whether thicker rods take a bigger load before breaking. All the rods are machined from the same bar of mild steel to different diameters, and tested on the same machine.',
      why: 'Every rod comes from the same bar, so the material is the same and only the thickness differs.' },
    { for: PHYS_ENG, iv: 'number of loading cycles', dv: 'fatigue crack length', confound: null,
      text: 'Engineers test whether more loading cycles give longer fatigue cracks. Identical aluminium specimens are all loaded to the same size of load; only the number of cycles differs.',
      why: 'Same specimens, same load — only the number of cycles differs.' },
  ],

  // -------------------------------------------------------------------------
  // 2j. Within or between. Within: the same sample or component is tested
  // under every condition. Between: different samples in each condition.
  // -------------------------------------------------------------------------
  designs: [
    // --- within ---
    { cat: 'within',
      label: 'One metal block is weighed on three different balances, and the mass each balance shows is compared.',
      ivs: [{ name: 'which balance', aliases: ['balance', 'balances', 'scales', 'three balances', 'type of balance', 'instrument', 'equipment'] }],
      dv: { name: 'mass reading', aliases: ['mass', 'reading', 'weight', 'how heavy', 'measured mass', 'result'] },
      others: [{ name: 'the metal block', aliases: ['block', 'metal block', 'metal', 'sample'] }] },
    { cat: 'within',
      label: 'A sealed gas syringe of air is placed in a water bath at 20°C, 40°C and 60°C in turn, and its volume is read at each temperature.',
      ivs: [{ name: 'temperature of the water bath', aliases: ['temperature', 'heat', 'how hot', '20 40 or 60', 'degrees', 'warmth'] }],
      dv: { name: 'volume of the air', aliases: ['volume', 'gas volume', 'how much space', 'size', 'expansion', 'syringe reading'] },
      others: [{ name: 'the gas syringe', aliases: ['syringe', 'gas syringe', 'air', 'equipment'] }] },
    { cat: 'within', for: PHYS_CHEM,
      label: 'One sample of copper sulfate solution is placed in a colorimeter with a red, a green and a blue filter in turn, and its absorbance is recorded with each filter.',
      ivs: [{ name: 'filter colour', aliases: ['filter', 'colour', 'red green or blue', 'type of filter', 'colour of filter', 'light colour', 'wavelength'] }],
      dv: { name: 'absorbance', aliases: ['absorbance reading', 'how much light is absorbed', 'light absorbed', 'reading', 'absorption'] },
      others: [{ name: 'the copper sulfate solution', aliases: ['solution', 'copper sulfate', 'sample', 'copper sulphate'] }, { name: 'the colorimeter', aliases: ['colorimeter', 'machine', 'instrument'] }] },
    { cat: 'within', for: PHYS_CHEM,
      label: 'One beaker of salt solution is warmed to 20°C, 40°C and 60°C in turn, and its electrical conductivity is measured at each temperature.',
      ivs: [{ name: 'temperature', aliases: ['heat', 'how hot', '20 40 or 60', 'degrees', 'warmth', 'solution temperature'] }],
      dv: { name: 'electrical conductivity', aliases: ['conductivity', 'how well it conducts', 'conductance', 'conduction', 'electrical'] },
      others: [{ name: 'the salt solution', aliases: ['solution', 'salt', 'beaker', 'sample'] }] },
    { cat: 'within', for: PHYS_PHYS,
      label: 'One wire is connected to a power supply set to 2, 4, 6 and 8 V in turn, and the current through it is measured at each voltage.',
      ivs: [{ name: 'voltage', aliases: ['volts', 'power supply setting', 'potential difference', 'pd', '2 4 6 or 8'] }],
      dv: { name: 'current', aliases: ['amps', 'ammeter reading', 'current through it', 'flow of charge', 'amperes'] },
      others: [{ name: 'the wire', aliases: ['wire', 'one wire', 'component'] }] },
    { cat: 'within', for: PHYS_PHYS,
      label: 'One pendulum bob is hung on strings of 20, 40, 60 and 80 cm in turn, and the period of its swing is timed at each length.',
      ivs: [{ name: 'string length', aliases: ['length', 'length of string', 'pendulum length', 'how long the string is', '20 40 60 or 80'] }],
      dv: { name: 'period', aliases: ['time for a swing', 'swing time', 'how long a swing takes', 'time period', 'oscillation time'] },
      others: [{ name: 'the pendulum bob', aliases: ['bob', 'pendulum bob', 'mass', 'weight'] }] },
    { cat: 'within', for: PHYS_PE,
      label: 'One spring has 1, 2, 3 and 4 N hung from it in turn, and its extension is measured with each load.',
      ivs: [{ name: 'load', aliases: ['force', 'weight', 'newtons', 'masses', 'how much is hung on it', '1 2 3 or 4'] }],
      dv: { name: 'extension', aliases: ['stretch', 'how far it stretches', 'length increase', 'how much longer it gets'] },
      others: [{ name: 'the spring', aliases: ['spring', 'one spring'] }] },
    { cat: 'within', for: PHYS_ENG,
      label: 'One steel beam is placed on supports 1 m, 1.5 m and 2 m apart in turn, with the same load in the middle, and its deflection is measured at each span.',
      ivs: [{ name: 'span', aliases: ['beam span', 'distance between supports', 'support spacing', 'how far apart the supports are', 'length'] }],
      dv: { name: 'deflection', aliases: ['bending', 'how far it bends', 'sag', 'displacement', 'deflection of the beam'] },
      others: [{ name: 'the steel beam', aliases: ['beam', 'steel', 'steel beam'] }, { name: 'the load', aliases: ['load', 'weight', 'same load'] }] },
    { cat: 'within', for: PHYS_ENG,
      label: 'One fan is run at low, medium and high speed in turn, and the airflow at the end of the duct is measured at each speed.',
      ivs: [{ name: 'fan speed', aliases: ['speed', 'low medium or high', 'setting', 'rpm', 'how fast the fan spins'] }],
      dv: { name: 'airflow', aliases: ['air flow', 'flow', 'how much air', 'air movement', 'flow rate'] },
      others: [{ name: 'the duct', aliases: ['duct', 'pipe', 'end of the duct'] }] },
    { cat: 'within', for: PHYS_ENG,
      label: 'One bolted joint is tightened to 20, 40 and 60 N m in turn, and the clamping force is measured with a load cell at each torque.',
      ivs: [{ name: 'tightening torque', aliases: ['torque', 'tightness', 'how tight', 'newton metres', '20 40 or 60'] }],
      dv: { name: 'clamping force', aliases: ['clamp force', 'force', 'load cell reading', 'how hard it clamps', 'preload'] },
      others: [{ name: 'the bolted joint', aliases: ['joint', 'bolt', 'bolted joint'] }] },

    // --- between ---
    { cat: 'between',
      label: 'Ten samples of copper and ten samples of aluminium each have their density measured once, and the two metals are compared.',
      ivs: [{ name: 'type of metal', aliases: ['metal', 'copper or aluminium', 'material', 'copper', 'aluminium', 'aluminum'] }],
      dv: { name: 'density', aliases: ['mass per volume', 'how dense', 'densities', 'mass divided by volume'] },
      others: [{ name: 'the samples', aliases: ['samples', 'ten samples', 'number of samples'] }] },
    { cat: 'between',
      label: 'Several dishes of one salt solution are cooled: some quickly in ice, the others slowly on the bench. The size of the crystals in the two groups is compared.',
      ivs: [{ name: 'cooling speed', aliases: ['cooling', 'fast or slow', 'ice or bench', 'how quickly it cools', 'cooling rate', 'rate of cooling'] }],
      dv: { name: 'crystal size', aliases: ['size of the crystals', 'crystals', 'how big the crystals are', 'crystal growth'] },
      others: [{ name: 'the salt solution', aliases: ['solution', 'salt', 'dishes'] }] },
    { cat: 'between', for: PHYS_CHEM,
      label: 'Half the portions of marble are chips and the other half are powder, each reacted with fresh acid. The volume of carbon dioxide given off in the first minute is compared.',
      ivs: [{ name: 'surface area (chips or powder)', aliases: ['surface area', 'chips or powder', 'powder', 'chips', 'particle size', 'size of the pieces'] }],
      dv: { name: 'volume of carbon dioxide', aliases: ['carbon dioxide', 'gas', 'co2', 'volume of gas', 'gas given off'] },
      others: [{ name: 'the acid', aliases: ['acid', 'fresh acid', 'hydrochloric acid'] }] },
    { cat: 'between', for: PHYS_CHEM,
      label: 'Fresh pieces of magnesium ribbon are reacted with acid, some at 20°C and others at 40°C, and the time for each piece to disappear is recorded.',
      ivs: [{ name: 'temperature', aliases: ['heat', 'how hot', '20 or 40', 'degrees', 'warmth'] }],
      dv: { name: 'time for the ribbon to disappear', aliases: ['time', 'reaction time', 'how long it takes', 'time to disappear', 'rate', 'reaction rate'] },
      others: [{ name: 'the magnesium ribbon', aliases: ['magnesium', 'ribbon', 'pieces of magnesium'] }] },
    { cat: 'between', for: PHYS_CHEM,
      label: 'Twenty flasks of hydrogen peroxide are set up; ten chosen at random get a catalyst and ten don\'t. The volume of oxygen each gives off in two minutes is compared.',
      ivs: [{ name: 'catalyst (with or without)', aliases: ['catalyst', 'with or without catalyst', 'manganese oxide', 'no catalyst', 'whether a catalyst is added'] }],
      dv: { name: 'volume of oxygen', aliases: ['oxygen', 'gas', 'volume of gas', 'gas given off', 'o2'] },
      others: [{ name: 'the hydrogen peroxide', aliases: ['hydrogen peroxide', 'peroxide', 'flasks', 'h2o2'] }] },
    { cat: 'between', for: PHYS_PHYS,
      label: 'Five wires of different lengths are cut from the same reel, and each wire\'s resistance is measured once.',
      ivs: [{ name: 'wire length', aliases: ['length', 'how long the wire is', 'length of wire', 'long or short'] }],
      dv: { name: 'resistance', aliases: ['ohms', 'electrical resistance', 'multimeter reading', 'resistances'] },
      others: [{ name: 'the reel', aliases: ['reel', 'same reel', 'spool'] }] },
    { cat: 'between', for: PHYS_PHYS,
      label: 'Beakers of hot water are wrapped in either thin or thick insulation, a different beaker for each, and the drop in temperature after 10 minutes is compared.',
      ivs: [{ name: 'insulation thickness', aliases: ['insulation', 'thin or thick', 'thickness', 'wrapping', 'lagging', 'layers'] }],
      dv: { name: 'drop in temperature', aliases: ['temperature', 'temperature change', 'cooling', 'how much it cools', 'temperature drop', 'heat loss'] },
      others: [{ name: 'the beakers', aliases: ['beakers', 'beaker', 'hot water'] }] },
    { cat: 'between', for: PHYS_PHYS,
      label: 'Twenty identical steel balls are each dropped once: ten from 1 m and ten from 2 m. Each ball\'s speed at the bottom is measured with a light gate.',
      ivs: [{ name: 'drop height', aliases: ['height', '1 or 2 m', 'how high', 'distance fallen', 'drop distance'] }],
      dv: { name: 'speed at the bottom', aliases: ['speed', 'velocity', 'how fast', 'landing speed', 'impact speed'] },
      others: [{ name: 'the steel balls', aliases: ['balls', 'steel balls', 'ball'] }, { name: 'the light gate', aliases: ['light gate', 'gate', 'sensor'] }] },
    { cat: 'between', for: PHYS_ENG,
      label: 'Ten steel beams are tested on supports 1 m apart and ten other beams on supports 2 m apart, with the same load, and their deflections are compared.',
      ivs: [{ name: 'span', aliases: ['beam span', 'distance between supports', 'support spacing', '1 or 2 m', 'how far apart'] }],
      dv: { name: 'deflection', aliases: ['bending', 'how far it bends', 'sag', 'displacement'] },
      others: [{ name: 'the steel beams', aliases: ['beams', 'steel', 'steel beams'] }] },
    { cat: 'between', for: PHYS_ENG,
      label: 'Steel rods of three diameters, five of each, are pulled in a testing machine until they break, and the breaking loads are compared.',
      ivs: [{ name: 'rod diameter', aliases: ['diameter', 'thickness', 'cross-sectional area', 'width', 'how thick', 'size'] }],
      dv: { name: 'breaking load', aliases: ['load', 'strength', 'force to break', 'how much it takes to break', 'failure load'] },
      others: [{ name: 'the testing machine', aliases: ['machine', 'testing machine', 'tensile tester'] }] },
    { cat: 'between', for: PHYS_ENG,
      label: 'Aluminium specimens are each given 10,000, 50,000 or 100,000 loading cycles, a different specimen for each, and then the length of any fatigue crack is measured.',
      ivs: [{ name: 'number of loading cycles', aliases: ['cycles', 'loading cycles', 'how many cycles', 'number of cycles', 'loadings'] }],
      dv: { name: 'fatigue crack length', aliases: ['crack', 'crack length', 'length of the crack', 'how long the crack is', 'cracking'] },
      others: [{ name: 'the aluminium specimens', aliases: ['specimens', 'aluminium', 'samples'] }] },
  ],

  // -------------------------------------------------------------------------
  // 2f-2h. Cross-sectional (many samples measured once) or longitudinal
  // (the same samples measured repeatedly over time).
  // -------------------------------------------------------------------------
  crosslong: {
    single: [
      // cross-sectional
      { cat: 'cross',
        label: 'In one week, a lab measures the hardness of tap water from 20 homes in chalk areas and 20 homes in granite areas, and compares the two groups.',
        ivs: [{ name: 'type of rock (chalk or granite)', aliases: ['rock', 'chalk or granite', 'area', 'geology', 'where the water comes from', 'region', 'group'] }],
        dv: { name: 'water hardness', aliases: ['hardness', 'how hard the water is', 'calcium', 'calcium content', 'hard water'] },
        others: [{ name: 'the week of testing', aliases: ['same week', 'one week', 'week'] }] },
      { cat: 'cross', for: PHYS_CHEM,
        label: 'In one afternoon, a chemist titrates samples of three brands of vinegar and compares how much ethanoic acid each contains.',
        ivs: [{ name: 'brand of vinegar', aliases: ['brand', 'vinegar', 'three brands', 'which brand', 'make', 'group'] }],
        dv: { name: 'ethanoic acid concentration', aliases: ['concentration', 'acid', 'how much acid', 'acid content', 'acetic acid', 'strength'] },
        others: [{ name: 'the afternoon of testing', aliases: ['afternoon', 'one afternoon', 'same afternoon'] }] },
      { cat: 'cross', for: PHYS_PHYS,
        label: 'In one session, a physicist measures the resistance of 30 copper wires and 30 aluminium wires of the same size, and compares the two metals.',
        ivs: [{ name: 'type of metal', aliases: ['metal', 'copper or aluminium', 'material', 'copper', 'aluminium', 'group'] }],
        dv: { name: 'resistance', aliases: ['ohms', 'electrical resistance', 'multimeter reading'] },
        others: [{ name: 'the testing session', aliases: ['one session', 'testing session', 'same session'] }] },
      { cat: 'cross', for: PHYS_PE,
        label: 'On one day, engineers measure the capacity of 20 new batteries and 20 batteries that have been in use for two years, and compare the two groups.',
        ivs: [{ name: 'battery age (new or two years old)', aliases: ['age', 'battery age', 'new or old', 'how old', 'two years', 'use', 'group'] }],
        dv: { name: 'battery capacity', aliases: ['capacity', 'charge', 'how much charge', 'charge it holds', 'mah', 'energy stored'] },
        others: [{ name: 'the day of testing', aliases: ['one day', 'same day', 'testing day'] }] },
      { cat: 'cross', for: PHYS_ENG,
        label: 'In one inspection, engineers measure the depth of rust on steel railings that are 5, 10 and 20 years old, and compare the three age groups.',
        ivs: [{ name: 'age of the railings', aliases: ['age', 'age group', 'how old', 'years old', '5 10 or 20', 'group'] }],
        dv: { name: 'rust depth', aliases: ['rust', 'corrosion', 'depth of rust', 'how much rust', 'corrosion depth'] },
        others: [{ name: 'the inspection', aliases: ['inspection', 'one inspection', 'survey'] }] },

      // longitudinal
      { cat: 'long',
        label: 'A beaker of hot water is left to cool on the bench, and its temperature is recorded every minute for 20 minutes.',
        ivs: [{ name: 'time', aliases: ['minutes', 'minute', 'every minute', 'how long it has cooled', ...PHYS_TIME] }],
        dv: { name: 'temperature of the water', aliases: ['temperature', 'how hot', 'heat', 'degrees', 'water temperature'] },
        others: [{ name: 'the beaker', aliases: ['beaker', 'bench', 'hot water'] }] },
      { cat: 'long', for: PHYS_CHEM,
        label: 'One bottle of hydrogen peroxide is sampled and titrated every week for ten weeks to track how concentrated it is.',
        ivs: [{ name: 'time (weeks of storage)', aliases: ['every week', 'storage time', 'ten weeks', 'how long it was stored', ...PHYS_TIME] }],
        dv: { name: 'concentration of the hydrogen peroxide', aliases: ['concentration', 'how concentrated', 'strength', 'peroxide concentration'] },
        others: [{ name: 'the bottle', aliases: ['bottle', 'one bottle'] }] },
      { cat: 'long', for: PHYS_CHEM,
        label: 'A dish of copper sulfate solution is left on a windowsill and weighed every day for two weeks as the water evaporates.',
        ivs: [{ name: 'time (days on the windowsill)', aliases: ['every day', 'two weeks', 'how long it was left', ...PHYS_TIME] }],
        dv: { name: 'mass of the dish', aliases: ['mass', 'weight', 'how heavy', 'mass of solution'] },
        others: [{ name: 'the windowsill', aliases: ['windowsill', 'window', 'sill'] }] },
      { cat: 'long', for: PHYS_PE,
        label: 'One battery is charged and discharged 500 times, and its capacity is measured every 50 charge cycles.',
        ivs: [{ name: 'number of charge cycles', aliases: ['cycles', 'charge cycles', 'how many times charged', 'usage', 'every 50 cycles', ...PHYS_TIME] }],
        dv: { name: 'capacity', aliases: ['charge capacity', 'charge', 'how much charge', 'charge it holds', 'energy stored', 'mah'] },
        others: [{ name: 'the battery', aliases: ['battery', 'one battery', 'cell'] }] },
      { cat: 'long', for: PHYS_ENG,
        label: 'Ten steel plates are left outdoors, and the same plates have their corrosion depth measured every month for a year.',
        ivs: [{ name: 'time outdoors', aliases: ['every month', 'time outside', 'exposure time', 'age', ...PHYS_TIME] }],
        dv: { name: 'corrosion depth', aliases: ['corrosion', 'rust', 'rust depth', 'how much rust', 'depth of corrosion'] },
        others: [{ name: 'the steel plates', aliases: ['plates', 'steel plates', 'steel', 'ten plates'] }] },
    ],

    multi: [
      // cross-sectional, two factors
      { cat: 'cross',
        label: 'In one week, a lab measures the hardness of water from the hot and cold taps in homes in chalk areas and in granite areas, and compares all four groups.',
        ivs: [
          { name: 'type of rock (chalk or granite)', aliases: ['rock', 'chalk or granite', 'area', 'geology', 'region', 'chalk', 'granite'] },
          { name: 'tap (hot or cold)', aliases: ['tap', 'hot or cold', 'hot tap', 'cold tap', 'which tap'] },
        ],
        dv: { name: 'water hardness', aliases: ['hardness', 'how hard the water is', 'calcium', 'calcium content'] },
        others: [{ name: 'the week of testing', aliases: ['one week', 'same week', 'week'] }] },
      { cat: 'cross', for: PHYS_CHEM,
        label: 'In one afternoon, samples of three brands of vinegar are each titrated using two different indicators, and the acid concentrations are compared.',
        ivs: [
          { name: 'brand of vinegar', aliases: ['brand', 'vinegar', 'three brands', 'which brand', 'make'] },
          { name: 'indicator', aliases: ['indicators', 'which indicator', 'type of indicator', 'two indicators', 'phenolphthalein'] },
        ],
        dv: { name: 'acid concentration', aliases: ['concentration', 'how much acid', 'acid content', 'ethanoic acid', 'acetic acid'] },
        others: [{ name: 'the afternoon', aliases: ['afternoon', 'one afternoon', 'same afternoon'] }] },
      { cat: 'cross', for: PHYS_PHYS,
        label: 'In one session, copper and aluminium wires cut to 50 cm and to 100 cm each have their resistance measured once.',
        ivs: [
          { name: 'type of metal', aliases: ['metal', 'copper or aluminium', 'material', 'copper', 'aluminium'] },
          { name: 'wire length', aliases: ['length', '50 or 100', 'how long', 'length of wire', 'long or short'] },
        ],
        dv: { name: 'resistance', aliases: ['ohms', 'electrical resistance', 'multimeter reading'] },
        others: [{ name: 'the session', aliases: ['one session', 'same session'] }] },
      { cat: 'cross', for: PHYS_PE,
        label: 'On one day, engineers measure the capacity of new and two-year-old batteries from two manufacturers, and compare all four groups.',
        ivs: [
          { name: 'battery age (new or two years old)', aliases: ['age', 'battery age', 'new or old', 'how old', 'two years', 'use'] },
          { name: 'manufacturer', aliases: ['brand', 'maker', 'make', 'company', 'two manufacturers'] },
        ],
        dv: { name: 'battery capacity', aliases: ['capacity', 'charge', 'how much charge', 'charge it holds', 'energy stored'] },
        others: [{ name: 'the day of testing', aliases: ['one day', 'same day', 'testing day'] }] },
      { cat: 'cross', for: PHYS_ENG,
        label: 'In one inspection, engineers measure the rust depth on steel railings aged 5, 10 and 20 years, at coastal and at inland sites.',
        ivs: [
          { name: 'age of the railings', aliases: ['age', 'age group', 'how old', 'years old', '5 10 or 20'] },
          { name: 'site (coastal or inland)', aliases: ['site', 'coastal or inland', 'coast', 'inland', 'location', 'where they are'] },
        ],
        dv: { name: 'rust depth', aliases: ['rust', 'corrosion', 'depth of rust', 'how much rust', 'corrosion depth'] },
        others: [{ name: 'the inspection', aliases: ['inspection', 'one inspection', 'survey'] }] },

      // longitudinal, two factors
      { cat: 'long',
        label: 'A tall beaker of hot water is left to cool, and the temperature near the top and near the bottom is recorded every minute for 20 minutes.',
        ivs: [
          { name: 'time', aliases: ['minutes', 'minute', 'every minute', 'how long it has cooled', ...PHYS_TIME] },
          { name: 'position (top or bottom)', aliases: ['position', 'top or bottom', 'top', 'bottom', 'height in the water', 'depth', 'location'] },
        ],
        dv: { name: 'temperature of the water', aliases: ['temperature', 'how hot', 'heat', 'degrees', 'water temperature'] },
        others: [{ name: 'the beaker', aliases: ['beaker', 'tall beaker', 'hot water'] }] },
      { cat: 'long', for: PHYS_CHEM,
        label: 'One bottle of hydrogen peroxide is sampled every week for ten weeks, and each week its concentration is measured both by titration and by collecting the oxygen it gives off.',
        ivs: [
          { name: 'time (weeks of storage)', aliases: ['every week', 'storage time', 'ten weeks', 'how long it was stored', ...PHYS_TIME] },
          { name: 'method (titration or gas collection)', aliases: ['method', 'titration', 'gas collection', 'titration or gas collection', 'how it is measured', 'technique'] },
        ],
        dv: { name: 'concentration of the hydrogen peroxide', aliases: ['concentration', 'how concentrated', 'strength', 'peroxide concentration'] },
        others: [{ name: 'the bottle', aliases: ['bottle', 'one bottle'] }] },
      { cat: 'long', for: PHYS_PE,
        label: 'One set of batteries is charged and discharged 500 times; every 50 cycles, each battery\'s capacity is measured at both 10°C and 25°C.',
        ivs: [
          { name: 'number of charge cycles', aliases: ['cycles', 'charge cycles', 'how many times charged', 'usage', 'every 50 cycles', ...PHYS_TIME] },
          { name: 'test temperature', aliases: ['temperature', '10 or 25', 'degrees', 'how warm', 'heat'] },
        ],
        dv: { name: 'battery capacity', aliases: ['capacity', 'charge', 'how much charge', 'charge it holds', 'energy stored'] },
        others: [{ name: 'the set of batteries', aliases: ['batteries', 'battery', 'set of batteries'] }] },
      { cat: 'long', for: PHYS_ENG,
        label: 'Ten steel plates are left outdoors, and every month for a year the corrosion depth is measured on both the upper and the lower face of each plate.',
        ivs: [
          { name: 'time outdoors', aliases: ['every month', 'time outside', 'exposure time', 'age', ...PHYS_TIME] },
          { name: 'face (upper or lower)', aliases: ['face', 'upper or lower', 'upper', 'lower', 'side', 'which face', 'top or bottom'] },
        ],
        dv: { name: 'corrosion depth', aliases: ['corrosion', 'rust', 'rust depth', 'how much rust', 'depth of corrosion'] },
        others: [{ name: 'the steel plates', aliases: ['plates', 'steel plates', 'steel', 'ten plates'] }] },
    ],

    panel: [
      { cat: 'both',
        label: 'Beakers of hot water wrapped in thin, medium and thick insulation each have their temperature recorded every minute for 20 minutes.',
        ivs: [
          { name: 'insulation thickness', aliases: ['insulation', 'thin medium or thick', 'thickness', 'wrapping', 'lagging', 'group'] },
          { name: 'time', aliases: ['minutes', 'minute', 'every minute', 'how long it has cooled', ...PHYS_TIME] },
        ],
        dv: { name: 'temperature of the water', aliases: ['temperature', 'how hot', 'heat', 'degrees', 'water temperature'] },
        others: [] },
      { cat: 'both',
        label: 'Pieces of limestone and pieces of granite are left in dilute acid, and each piece is weighed every day for two weeks.',
        ivs: [
          { name: 'type of rock (limestone or granite)', aliases: ['rock', 'limestone or granite', 'limestone', 'granite', 'type of stone', 'group'] },
          { name: 'time', aliases: ['every day', 'two weeks', 'how long in acid', ...PHYS_TIME] },
        ],
        dv: { name: 'mass of each piece', aliases: ['mass', 'weight', 'how heavy', 'mass lost', 'mass loss'] },
        others: [] },
      { cat: 'both', for: PHYS_CHEM,
        label: 'Bottles of hydrogen peroxide are stored either in a fridge or at room temperature, and each is titrated every week for eight weeks to track its concentration.',
        ivs: [
          { name: 'storage (fridge or room temperature)', aliases: ['storage', 'fridge', 'room temperature', 'fridge or room', 'where it is stored', 'storage temperature', 'group'] },
          { name: 'time (weeks of storage)', aliases: ['every week', 'eight weeks', 'how long it was stored', ...PHYS_TIME] },
        ],
        dv: { name: 'concentration of the hydrogen peroxide', aliases: ['concentration', 'how concentrated', 'strength', 'peroxide concentration'] },
        others: [] },
      { cat: 'both', for: PHYS_CHEM,
        label: 'Dishes of copper sulfate solution are left either open or covered, and each dish is weighed every day for a week.',
        ivs: [
          { name: 'dish (open or covered)', aliases: ['open or covered', 'open', 'covered', 'lid', 'cover', 'group'] },
          { name: 'time', aliases: ['every day', 'a week', 'how long it was left', ...PHYS_TIME] },
        ],
        dv: { name: 'mass of the dish', aliases: ['mass', 'weight', 'how heavy', 'mass of solution'] },
        others: [] },
      { cat: 'both', for: PHYS_PHYS,
        label: 'A copper wire and a nichrome wire each carry the same current for 10 minutes, and the resistance of each is measured every minute as it warms up.',
        ivs: [
          { name: 'type of wire (copper or nichrome)', aliases: ['wire', 'metal', 'copper or nichrome', 'copper', 'nichrome', 'material', 'group'] },
          { name: 'time', aliases: ['minutes', 'minute', 'every minute', 'how long the current flows', ...PHYS_TIME] },
        ],
        dv: { name: 'resistance', aliases: ['ohms', 'electrical resistance', 'multimeter reading'] },
        others: [] },
      { cat: 'both', for: PHYS_PE,
        label: 'Batteries stored at 10°C, 25°C and 40°C are charged and discharged, and each battery\'s capacity is measured every 100 charge cycles.',
        ivs: [
          { name: 'storage temperature', aliases: ['temperature', '10 25 or 40', 'degrees', 'how warm', 'heat', 'group'] },
          { name: 'number of charge cycles', aliases: ['cycles', 'charge cycles', 'how many times charged', 'usage', 'every 100 cycles', ...PHYS_TIME] },
        ],
        dv: { name: 'battery capacity', aliases: ['capacity', 'charge', 'how much charge', 'charge it holds', 'energy stored'] },
        others: [] },
      { cat: 'both', for: PHYS_ENG,
        label: 'Painted and unpainted steel plates are left outdoors, and the corrosion depth of each plate is measured every month for a year.',
        ivs: [
          { name: 'paint (painted or unpainted)', aliases: ['paint', 'painted', 'unpainted', 'painted or unpainted', 'coating', 'group'] },
          { name: 'time outdoors', aliases: ['every month', 'time outside', 'exposure time', 'age', ...PHYS_TIME] },
        ],
        dv: { name: 'corrosion depth', aliases: ['corrosion', 'rust', 'rust depth', 'how much rust', 'depth of corrosion'] },
        others: [] },
      { cat: 'both', for: PHYS_ENG,
        label: 'Aluminium and steel specimens are loaded and unloaded repeatedly, and the length of the fatigue crack in each is measured every 10,000 cycles.',
        ivs: [
          { name: 'material (aluminium or steel)', aliases: ['material', 'metal', 'aluminium or steel', 'aluminium', 'steel', 'group'] },
          { name: 'number of loading cycles', aliases: ['cycles', 'loading cycles', 'how many cycles', 'every 10000 cycles', ...PHYS_TIME] },
        ],
        dv: { name: 'fatigue crack length', aliases: ['crack', 'crack length', 'length of the crack', 'how long the crack is', 'cracking'] },
        others: [] },
    ],
  },

  // -------------------------------------------------------------------------
  // Level 3. Factors for the box notation.
  // -------------------------------------------------------------------------
  factors: [
    { name: 'Temperature', levels: { 2: ['20°C', '40°C'], 3: ['20°C', '40°C', '60°C'], 4: ['20°C', '30°C', '40°C', '50°C'] } },
    { name: 'Metal', levels: { 2: ['copper', 'aluminium'], 3: ['copper', 'aluminium', 'iron'], 4: ['copper', 'aluminium', 'iron', 'zinc'] } },
    { name: 'Insulation', levels: { 2: ['none', 'foam'], 3: ['none', 'thin', 'thick'] } },
    { name: 'Acid concentration', for: PHYS_CHEM, levels: { 2: ['0.5 M', '1.0 M'], 3: ['0.5 M', '1.0 M', '1.5 M'], 4: ['0.5 M', '1.0 M', '1.5 M', '2.0 M'] } },
    { name: 'Catalyst', for: PHYS_CHEM, levels: { 2: ['none', 'MnO₂'], 3: ['none', 'MnO₂', 'CuO'] } },
    { name: 'Marble', for: PHYS_CHEM, levels: { 2: ['chips', 'powder'], 3: ['large chips', 'small chips', 'powder'] } },
    { name: 'Voltage', for: PHYS_PHYS, levels: { 2: ['3 V', '6 V'], 3: ['2 V', '4 V', '6 V'], 4: ['2 V', '4 V', '6 V', '8 V'] } },
    { name: 'Wire length', for: PHYS_PHYS, levels: { 2: ['50 cm', '100 cm'], 3: ['25 cm', '50 cm', '75 cm'], 4: ['25 cm', '50 cm', '75 cm', '100 cm'] } },
    { name: 'Circuit', for: PHYS_PHYS, levels: { 2: ['series', 'parallel'] } },
    { name: 'Beam span', for: PHYS_ENG, levels: { 2: ['1 m', '2 m'], 3: ['1 m', '1.5 m', '2 m'], 4: ['1 m', '1.5 m', '2 m', '2.5 m'] } },
    { name: 'Load', for: PHYS_PE, levels: { 2: ['100 N', '200 N'], 3: ['100 N', '200 N', '300 N'], 4: ['100 N', '200 N', '300 N', '400 N'] } },
    { name: 'Beam material', for: PHYS_ENG, levels: { 2: ['steel', 'aluminium'], 3: ['steel', 'aluminium', 'timber'] } },
    { name: 'Loading cycles', for: PHYS_ENG, levels: { 2: ['10,000', '100,000'], 3: ['10,000', '50,000', '100,000'] } },
    { name: 'Bolt torque', for: PHYS_ENG, levels: { 2: ['20 N m', '40 N m'], 3: ['20 N m', '40 N m', '60 N m'] } },
    { name: 'Fan speed', for: PHYS_ENG, levels: { 2: ['low', 'high'], 3: ['low', 'medium', 'high'] } },
  ],
};
